import Mathlib

/-!
# Chapter *"Quantization due to time-evolution: Yang-Mills and Classical Statistical Field Theory"*, §*"Majorana spinors in canonical quantization and antiparticles"*

This file formalizes the self-contained algebraic content of the book section
*"Majorana spinors in canonical quantization and antiparticles"*
(`book.tex` line ~7680).

There the book constructs, from a **real Hilbert space** `V` with inner product
`⟪·,·⟫`, the associated **complex Clifford C\*-algebra** `C(V)`: a unital
associative algebra with an injective linear map `a : V → C(V)` satisfying

* `a(v)² = ⟪v,v⟫·1` (the Clifford relation), and
* `a*(v) = a(v)` (the generators are **self-adjoint** for the canonical
  involution `*`),

generated by the `a(v)`. The book's physical reading is that each `a(v)` is a
**self-adjoint fermionic field operator** — *"a particle which is its own
antiparticle"*, i.e. a Majorana fermion — and that *"it is always possible to do
the canonical fermionic quantization of a real Hilbert space, with the
corresponding operators `a(v)` being self-adjoint"*. The symmetries act as
`a(v) → a(Tv)` for a **real** operator `T`, preserving self-adjointness, i.e. as
**real representations**.

We realize `C(V)` as Mathlib's `CliffordAlgebra Q` for the quadratic form
`Q v = ⟪v,v⟫` induced by the inner product, with the generator map
`a v = CliffordAlgebra.ι Q v` and the canonical involution `*` given by
`CliffordAlgebra.reverse` (the unique anti-automorphism fixing the generators,
`reverse (a v) = a v`). We prove:

* `a_sq` — the **Clifford relation** `a(v)·a(v) = ⟪v,v⟫·1`;
* `car` — the **canonical anticommutation relation**
  `a(v)·a(w) + a(w)·a(v) = 2⟪v,w⟫·1` (the polarization of the Clifford relation,
  i.e. `{a(v),a(w)} = 2⟪v,w⟫`);
* `a_selfAdjoint` — `a(v)` is **self-adjoint**, `reverse (a v) = a v`
  (the book's `a*(v) = a(v)`), the Majorana / *own-antiparticle* property;
* `reverse_star_props` (`reverse_antihom`, `reverse_involutive`) — the involution
  `*` is an **anti-automorphism of order 2** (the defining properties of `C(V)`'s
  unique `*`);
* `a_map_selfAdjoint` — for **any real linear** `T : V → V`, `a(T v)` is again
  self-adjoint, so a real symmetry `a(v) → a(Tv)` **preserves self-adjointness**
  (real representation);
* `car_smul_left` / `a_add` — bilinearity of `a`;
* `a_anticomm_of_orthogonal` — orthogonal directions give **anticommuting** field
  operators, `⟪v,w⟫ = 0 ⇒ a(v)·a(w) + a(w)·a(v) = 0`;
* `a_anticomm_skew` — the **creation/annihilation split**: for a skew-symmetric
  `J` (the complex structure `J² = -1` of the book, `⟪J v, w⟫ = -⟪v, J w⟫`), the
  directions `v` and `J v` are orthogonal, so `a(v)` and `a(J v)`
  **anticommute** — the real shadow of the CAR between the annihilation operator
  `a(v + iJv)` and the creation operator `a(v − iJv)`.

The C\*-completion (the natural norm) and the bosonic symplectic variant
(`[a(v),a(w)] = ⟪v, J w⟫ i`, a CCR/Weyl algebra rather than a Clifford algebra)
are prose in the book and are not formalized here.
-/

open RealInnerProductSpace CliffordAlgebra QuadraticMap

namespace BookProof.MajoranaClifford

variable {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℝ V]

/-- The inner product of the real Hilbert space `V`, packaged as a bilinear form. -/
noncomputable def innerBilin : LinearMap.BilinForm ℝ V :=
  LinearMap.mk₂ ℝ (fun v w => ⟪v, w⟫)
    (fun x y z => inner_add_left x y z)
    (fun c x y => by simp [inner_smul_left])
    (fun x y z => inner_add_right x y z)
    (fun c x y => by simp [inner_smul_right])

/-- The quadratic form `Q v = ⟪v,v⟫` induced by the inner product of `V`.  The
book's complex Clifford C\*-algebra `C(V)` is `CliffordAlgebra Q`. -/
noncomputable def Qform : QuadraticForm ℝ V := (innerBilin (V := V)).toQuadraticMap

@[simp] lemma Qform_apply (v : V) : Qform v = ⟪v, v⟫ := by
  simp [Qform, innerBilin, LinearMap.BilinMap.toQuadraticMap]

lemma polar_Qform (v w : V) : polar (Qform (V := V)) v w = 2 * ⟪v, w⟫ := by
  rw [Qform, LinearMap.BilinMap.polar_toQuadraticMap]
  simp only [innerBilin, LinearMap.mk₂_apply]
  rw [real_inner_comm w v]; ring

/-- The **field operator** `a(v) = ι Q v`: the injective linear generator of the
Clifford algebra `C(V)` associated to `v ∈ V`. -/
noncomputable def a (v : V) : CliffordAlgebra (Qform (V := V)) := ι (Qform) v

@[simp] lemma a_add (v w : V) : a (v + w) = a v + a w := by
  simp [a, map_add]

@[simp] lemma a_smul (c : ℝ) (v : V) : a (c • v) = c • a v := by
  simp [a, map_smul]

@[simp] lemma a_zero : a (0 : V) = 0 := by simp [a]

/-- **The Clifford relation** `a(v)² = ⟪v,v⟫·1`: the defining relation of the
book's `C(V)`. -/
theorem a_sq (v : V) : a v * a v = algebraMap ℝ (CliffordAlgebra (Qform (V := V))) ⟪v, v⟫ := by
  rw [a, ι_sq_scalar]
  simp

/-- **The canonical anticommutation relation (CAR)**
`{a(v), a(w)} = a(v)·a(w) + a(w)·a(v) = 2⟪v,w⟫·1`, the polarization of the
Clifford relation. -/
theorem car (v w : V) :
    a v * a w + a w * a v
      = algebraMap ℝ (CliffordAlgebra (Qform (V := V))) (2 * ⟪v, w⟫) := by
  rw [a, a, ι_mul_ι_add_swap, polar_Qform]

/-- Orthogonal directions produce **anticommuting** field operators. -/
theorem a_anticomm_of_orthogonal {v w : V} (h : ⟪v, w⟫ = (0 : ℝ)) :
    a v * a w + a w * a v = 0 := by
  rw [car, h]; simp

/-- **Self-adjointness of the field operator** (the book's `a*(v) = a(v)`):
`a(v)` is fixed by the canonical involution `*` of `C(V)`, realized as
`CliffordAlgebra.reverse`.  Physically, `a(v)` represents *a particle which is
its own antiparticle* — a Majorana fermion. -/
theorem a_selfAdjoint (v : V) : reverse (a v) = a v := by
  rw [a, reverse_ι]

/-- The canonical involution `*` is an **anti-automorphism**:
`(x·y)* = y*·x*`. -/
theorem reverse_antihom (x y : CliffordAlgebra (Qform (V := V))) :
    reverse (x * y) = reverse y * reverse x :=
  reverse.map_mul x y

/-- The canonical involution `*` is **of order two** (`** = id`), hence a genuine
involution. -/
theorem reverse_involutive :
    Function.Involutive (reverse : CliffordAlgebra (Qform (V := V)) → _) :=
  fun x => reverse_reverse x

/-- **Symmetries act as real representations preserving self-adjointness.**  For
*any* real linear operator `T : V → V`, the transformed field operator `a(T v)`
is again self-adjoint, so the map `a(v) → a(T v)` preserves the
self-adjointness condition (the book's statement that the symmetry group acts by
real representations, `a(v) → a(T v)` with `T` a real operator). -/
theorem a_map_selfAdjoint (T : V →ₗ[ℝ] V) (v : V) : reverse (a (T v)) = a (T v) :=
  a_selfAdjoint (T v)

/-- **Creation/annihilation directions anticommute.**  Given a skew-symmetric
operator `J` (the book's complex structure with `⟪J v, w⟫ = -⟪v, J w⟫`; e.g.
`J² = -1`), each vector `v` is orthogonal to `J v`, hence the corresponding field
operators anticommute: `{a(v), a(J v)} = 0`.  This is the real shadow of the
canonical anticommutation between the annihilation operator `a(v + iJv)` and the
creation operator `a(v − iJv)`. -/
theorem a_anticomm_skew (J : V →ₗ[ℝ] V) (hJ : ∀ v w : V, ⟪J v, w⟫ = -⟪v, J w⟫) (v : V) :
    a v * a (J v) + a (J v) * a v = 0 := by
  have h : ⟪v, J v⟫ = (0 : ℝ) := by
    have h1 : ⟪J v, v⟫ = -⟪v, J v⟫ := hJ v v
    have h2 : ⟪J v, v⟫ = ⟪v, J v⟫ := by rw [real_inner_comm]
    linarith [h1, h2]
  exact a_anticomm_of_orthogonal h

end BookProof.MajoranaClifford
