import Mathlib

/-!
# Chapter "Free field parametrization … Navier-Stokes", §"Mass gap"

Source: `book.tex`, chapter *"Free field parametrization in Classical Statistical
Field Theory and Navier-Stokes equations"*, §*"Mass gap"* (line ~4061).

The book's argument (solving "the hardest part" of the Yang–Mills mass-gap
Millenium problem in its own formalism):

> "the commutative algebra of observables is generated by hermitian operators
> `a†(φ,x) a(φ,x)` … the Hamiltonian commutes with the number operator. Thus,
> the number operator commutes with the algebra of observables which implies that
> the number operator can be added to the Hamiltonian, modifying the mass gap
> without observable consequences."

So a bounded-from-below Hamiltonian with a *null* mass gap (the free
electromagnetic field) can be turned into one with an *arbitrary* mass gap
without any observable consequence.

This file formalizes the two self-contained mathematical facts behind that
claim.

## Observable invariance (the "no observable consequence" part)

Work in an arbitrary complex Banach algebra `𝔸` (the algebra of operators).
`H` is the Hamiltonian, `N` the number operator, `Obs` any observable. The
physical hypotheses are:

* `Commute H N` — the Hamiltonian commutes with the number operator;
* `Commute Obs N` — every observable commutes with the number operator (the
  observable algebra is number-conserving).

Then the Heisenberg-picture time evolution of `Obs` under the *shifted*
Hamiltonian `H + λ N` is **identical** to its evolution under `H`:

`exp(t(H+λN)) · Obs · exp(-t(H+λN)) = exp(tH) · Obs · exp(-tH)`

for every scalar `t` (the physical unitary case is `t = i s`, `s` real) and every
shift `λ`. Hence the number-operator shift is invisible to all observables.

## Spectral shift (the "modify the mass gap at will" part)

For a diagonal Hamiltonian with eigenvalues `E : Fin (n+2) → ℝ`, vacuum index `0`
with `E 0 = 0`, and number operator `numberOp i = if i = 0 then 0 else 1`, the
shifted Hamiltonian has eigenvalues `E i + λ · numberOp i`:

* the vacuum energy is unchanged (`= E 0`);
* every excited energy is shifted by exactly `λ`;
* for the **gapless** free field (`E ≡ 0`) the shifted mass gap equals `λ`, i.e.
  it can be set to any nonnegative value.
-/

namespace BookProof.MassGap

open scoped BigOperators

/-! ### Observable invariance in a complex Banach algebra -/

variable {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℂ 𝔸] [CompleteSpace 𝔸]

/-- Conjugating an observable by `exp Y` is trivial when the observable commutes
with `Y`: `exp Y · Obs · exp(-Y) = Obs`. -/
theorem exp_conj_eq_self {Obs Y : 𝔸} (h : Commute Obs Y) :
    NormedSpace.exp Y * Obs * NormedSpace.exp (-Y) = Obs := by
  haveI : NormedAlgebra ℚ 𝔸 := NormedAlgebra.restrictScalars ℚ ℂ 𝔸
  have hcomm : Commute (NormedSpace.exp Y) Obs := h.symm.exp_left
  have hinv : NormedSpace.exp Y * NormedSpace.exp (-Y) = 1 := by
    rw [← NormedSpace.exp_add_of_commute ((Commute.refl Y).neg_right), add_neg_cancel,
      NormedSpace.exp_zero]
  rw [mul_assoc, ← mul_assoc, hcomm.eq, mul_assoc, hinv, mul_one]

/-- **Headline (observable invariance).** If the Hamiltonian `H` and every
observable `Obs` commute with the number operator `N`, then the Heisenberg
evolution of `Obs` under the number-shifted Hamiltonian `H + λ N` coincides with
its evolution under `H` for every scalar `t` and shift `λ`. The mass-gap shift by
`λ N` has *no observable consequence*. -/
theorem heisenberg_number_shift_invariant (H N Obs : 𝔸) (t lam : ℂ)
    (hHN : Commute H N) (hON : Commute Obs N) :
    NormedSpace.exp (t • (H + lam • N)) * Obs * NormedSpace.exp (-(t • (H + lam • N)))
      = NormedSpace.exp (t • H) * Obs * NormedSpace.exp (-(t • H)) := by
  haveI : NormedAlgebra ℚ 𝔸 := NormedAlgebra.restrictScalars ℚ ℂ 𝔸
  set X := t • H with hX
  set Y := t • (lam • N) with hY
  have hsplit : t • (H + lam • N) = X + Y := by rw [smul_add]
  have hXY : Commute X Y := ((hHN.smul_right lam).smul_left t).smul_right t
  have hObsY : Commute Obs Y := (hON.smul_right lam).smul_right t
  rw [hsplit, NormedSpace.exp_add_of_commute hXY]
  have hneg : -(X + Y) = -Y + -X := by abel
  rw [hneg, NormedSpace.exp_add_of_commute (hXY.symm.neg_left.neg_right)]
  calc NormedSpace.exp X * NormedSpace.exp Y * Obs
          * (NormedSpace.exp (-Y) * NormedSpace.exp (-X))
      = NormedSpace.exp X * (NormedSpace.exp Y * Obs * NormedSpace.exp (-Y))
          * NormedSpace.exp (-X) := by noncomm_ring
    _ = NormedSpace.exp X * Obs * NormedSpace.exp (-X) := by rw [exp_conj_eq_self hObsY]

/-! ### Diagonal spectral shift and the arbitrary mass gap -/

variable {n : ℕ}

/-- The number operator's eigenvalues on `Fin (n+2)`: `0` on the vacuum index and
`1` on every excited index. -/
def numberOp (i : Fin (n + 2)) : ℝ := if i = 0 then 0 else 1

/-- The eigenvalues of the shifted Hamiltonian `H + λ N`. -/
def shiftedSpectrum (E : Fin (n + 2) → ℝ) (lam : ℝ) (i : Fin (n + 2)) : ℝ :=
  E i + lam * numberOp i

/-- The excited states (all indices other than the vacuum `0`). -/
def excited (n : ℕ) : Finset (Fin (n + 2)) := Finset.univ.filter (· ≠ 0)

/-
The excited-state set is nonempty (index `1` is excited).
-/
theorem excited_nonempty : (excited n).Nonempty := by
  exact ⟨ 1, by simp +decide [ excited ] ⟩

/-- The mass gap of a diagonal spectrum: the least excited-state energy. -/
noncomputable def massGap (E : Fin (n + 2) → ℝ) : ℝ :=
  ((excited n).image E).min' (by
    exact (excited_nonempty).image _)

/-
Vacuum energy is unchanged by the number-operator shift.
-/
theorem shiftedSpectrum_vacuum (E : Fin (n + 2) → ℝ) (lam : ℝ) :
    shiftedSpectrum E lam 0 = E 0 := by
  unfold shiftedSpectrum numberOp; norm_num;

/-
Every excited energy is shifted by exactly `λ`.
-/
theorem shiftedSpectrum_excited (E : Fin (n + 2) → ℝ) (lam : ℝ)
    {i : Fin (n + 2)} (hi : i ≠ 0) :
    shiftedSpectrum E lam i = E i + lam := by
  unfold shiftedSpectrum numberOp; aesop;

/-
**Headline (arbitrary mass gap).** For the gapless free field (`E ≡ 0`) the
number-operator shift produces a mass gap equal to `λ`: the mass gap can be set
to any value.
-/
theorem massGap_shifted_gapless (lam : ℝ) :
    massGap (shiftedSpectrum (fun _ : Fin (n + 2) => (0 : ℝ)) lam) = lam := by
  refine' le_antisymm _ _;
  · refine' Finset.min'_le _ _ _;
    simp +decide [ excited, shiftedSpectrum ];
    exact ⟨ 1, by simp +decide, by simp +decide [ numberOp ] ⟩;
  · refine' Finset.le_min' _ _ _ _ ; simp +decide [ shiftedSpectrum, numberOp ];
    exact fun a ha => by rw [ if_neg ( Finset.mem_filter.mp ha |>.2 ) ] ;

end BookProof.MassGap