/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aristotle
-/
import Mathlib

/-!
# The gauge algebra, the Gauss law and the gauge invariance of the Weyl Hamiltonian

Source: `book.tex`, chapter *"Timepiece and the Gribov ambiguity"*,
§*"Pure Yang–Mills theory"* (lines 7290–7400) and the parallel Yang–Mills
chapter (lines 7020–7120).  The manuscript writes the 3D Hamiltonian in the
Weyl gauge

```
H_W = ½ π^i_a π^i_a + ½ B_{i a} B_{i a},
```

states that it *"is invariant under a remnant gauge symmetry generated by
`θ_a (D_i π^i)_a`"* — the **Gauss law** — and that it is *positive definite*.

This file formalizes the algebraic content of those statements, with the
coordinates representing spatial derivatives of the fields kept as **independent
variables** (`dA`, `dX`, `dθ`), exactly as everywhere else in this development.
The gauge algebra is an arbitrary real Lie algebra `L` (so `su(3)`, `su(2)` and
`u(1)` are all instances), and the gauge-invariant inner product `κ` (Killing
form, trace form, …) is an arbitrary invariant symmetric bilinear form.

## Main results

* `adj_closure` — the infinitesimal gauge transformations close on the adjoint
  fields: `[δ_θ, δ_η] = δ_{⁅θ,η⁆}`, i.e. `θ ↦ δ_θ` is a representation of the
  gauge algebra (this is the Jacobi identity).
* `covariantDeriv_covariant` — the covariant derivative `D_i X = ∂_i X + ⁅A_i, X⁆`
  transforms in the adjoint representation, *provided* the derivative
  coordinates obey the Leibniz gauge-fixing rule
  `δ(∂_i X) = ⁅∂_i X, θ⁆ + ⁅X, ∂_i θ⁆`.
* `gaussLaw_covariant`, `gaussLaw_constraint_surface_invariant` — the Gauss-law
  generator transforms in the adjoint, hence the constraint surface `G = 0` is
  preserved by the (remnant) gauge group.
* `magnetic_covariant` — the magnetic field `B_{ij} = ∂_i A_j − ∂_j A_i + ⁅A_i, A_j⁆`
  transforms in the adjoint under a *local* gauge transformation
  `δ A_i = ∂_i θ + ⁅A_i, θ⁆` (the inhomogeneous terms cancel by the symmetry of
  the second-derivative coordinates).
* `weylEnergy_gauge_invariant` — the Weyl-gauge energy `½π² + ½B²` has vanishing
  gauge variation.
* `weylEnergy_nonneg` — and it is non-negative for a positive semidefinite
  invariant form, which is the book's *"positive definite in the Weyl gauge"*.
-/

namespace BookProof.ChapterGaugeAdjointAlgebra

open Finset

variable {L : Type*} [LieRing L]

/-! ## The Jacobi identity in the form used throughout -/

/-- The Jacobi identity, in the "adjoint covariance" form: the adjoint variation
of a bracket is the bracket of the adjoint variations. -/
theorem lie_adj_leibniz (x θ y : L) : ⁅⁅x, θ⁆, y⁆ + ⁅x, ⁅y, θ⁆⁆ = ⁅⁅x, y⁆, θ⁆ := by
  rw [lie_lie x y θ, ← lie_skew ⁅x, θ⁆ y]
  abel

/-! ## The infinitesimal gauge transformation of an adjoint field -/

/-- The infinitesimal gauge variation of a field transforming in the adjoint
representation: `δ_θ X = ⁅X, θ⁆`. -/
def adjVar (θ X : L) : L := ⁅X, θ⁆

@[simp] theorem adjVar_apply (θ X : L) : adjVar θ X = ⁅X, θ⁆ := rfl

/-- **The gauge algebra closes.**  The commutator of two infinitesimal gauge
variations is the gauge variation with parameter `⁅θ, η⁆`; i.e. `θ ↦ δ_θ` is a
representation of the gauge Lie algebra.  This is exactly the Jacobi identity. -/
theorem adj_closure (θ η X : L) :
    adjVar η (adjVar θ X) - adjVar θ (adjVar η X) = adjVar ⁅θ, η⁆ X := by
  simp only [adjVar_apply]
  rw [← lie_adj_leibniz X η θ, ← lie_skew θ η]
  simp

/-- A field commuting with every gauge parameter (a gauge singlet) has zero
gauge variation. -/
theorem adjVar_eq_zero_of_central {X : L} (hX : ∀ θ : L, ⁅X, θ⁆ = 0) (θ : L) :
    adjVar θ X = 0 := hX θ

/-! ## Covariant derivative and the Gauss law -/

/-- The covariant derivative in the independent derivative coordinates:
`D_i X = (∂_i X) + ⁅A_i, X⁆`, where `dX i` is the coordinate representing
`∂_i X`. -/
def covariantDeriv (A dX : Fin 3 → L) (X : L) (i : Fin 3) : L := dX i + ⁅A i, X⁆

/-- The local (inhomogeneous) gauge variation of the gauge field:
`δ A_i = ∂_i θ + ⁅A_i, θ⁆`. -/
def gaugeVarA (A dθ : Fin 3 → L) (θ : L) (i : Fin 3) : L := dθ i + ⁅A i, θ⁆

/-- **Covariance of the covariant derivative.**  If

* the gauge field varies as `δ A_i = ∂_i θ + ⁅A_i, θ⁆` (local transformation),
* the field `X` varies in the adjoint, `δ X = ⁅X, θ⁆`, and
* the derivative coordinates obey the Leibniz rule
  `δ(∂_i X) = ⁅∂_i X, θ⁆ + ⁅X, ∂_i θ⁆` — the gauge fixing of the variables
  representing spatial derivatives —

then `D_i X` transforms in the adjoint representation:
`δ (D_i X) = ⁅D_i X, θ⁆`. -/
theorem covariantDeriv_covariant (A dX dθ : Fin 3 → L) (X θ : L) (i : Fin 3) :
    (⁅dX i, θ⁆ + ⁅X, dθ i⁆) + (⁅gaugeVarA A dθ θ i, X⁆ + ⁅A i, ⁅X, θ⁆⁆)
      = ⁅covariantDeriv A dX X i, θ⁆ := by
  have hc : ⁅X, dθ i⁆ = -⁅dθ i, X⁆ := (lie_skew X (dθ i)).symm
  simp only [covariantDeriv, gaugeVarA, add_lie]
  rw [← lie_adj_leibniz (A i) θ X, hc]
  abel

/-- The Gauss-law generator `G = Σ_i D_i π^i` of the Weyl gauge (book 7364). -/
def gaussLaw (A dπ π : Fin 3 → L) : L := ∑ i, (dπ i + ⁅A i, π i⁆)

/-- **The Gauss law transforms in the adjoint representation** under a *global*
remnant gauge transformation (`∂_i θ = 0`), the electric field and its
derivative coordinates transforming adjointly. -/
theorem gaussLaw_covariant (A dπ π : Fin 3 → L) (θ : L) :
    ∑ i, (⁅dπ i, θ⁆ + (⁅⁅A i, θ⁆, π i⁆ + ⁅A i, ⁅π i, θ⁆⁆))
      = ⁅gaussLaw A dπ π, θ⁆ := by
  simp only [gaussLaw, sum_lie, add_lie]
  exact sum_congr rfl fun i _ => by rw [lie_adj_leibniz (A i) θ (π i)]

/-- **The Gauss-law constraint surface is gauge invariant.**  If the Gauss law
holds, its gauge variation vanishes, so the remnant gauge transformations map
the constraint surface `G = 0` to itself. -/
theorem gaussLaw_constraint_surface_invariant (A dπ π : Fin 3 → L) (θ : L)
    (hG : gaussLaw A dπ π = 0) :
    ∑ i, (⁅dπ i, θ⁆ + (⁅⁅A i, θ⁆, π i⁆ + ⁅A i, ⁅π i, θ⁆⁆)) = 0 := by
  rw [gaussLaw_covariant, hG, zero_lie]

/-! ## The magnetic field and the Weyl Hamiltonian -/

/-- The non-abelian magnetic field in the independent derivative coordinates:
`B_{ij} = ∂_i A_j − ∂_j A_i + ⁅A_i, A_j⁆`. -/
def magnetic (A : Fin 3 → L) (dA : Fin 3 → Fin 3 → L) (i j : Fin 3) : L :=
  dA i j - dA j i + ⁅A i, A j⁆

/-- **Covariance of the magnetic field under a local gauge transformation.**
With `δ A_i = ∂_i θ + ⁅A_i, θ⁆`, the Leibniz rule for the derivative
coordinates, `δ(∂_i A_j) = ∂_i ∂_j θ + ⁅∂_i A_j, θ⁆ + ⁅A_j, ∂_i θ⁆`, and the
symmetry `∂_i ∂_j θ = ∂_j ∂_i θ` of the second-derivative coordinates, the
inhomogeneous terms cancel and `δ B_{ij} = ⁅B_{ij}, θ⁆`. -/
theorem magnetic_covariant (A dθ : Fin 3 → L) (dA : Fin 3 → Fin 3 → L)
    (ddθ : Fin 3 → Fin 3 → L) (θ : L) (i j : Fin 3) (hsym : ddθ i j = ddθ j i) :
    ((ddθ i j + ⁅dA i j, θ⁆ + ⁅A j, dθ i⁆) - (ddθ j i + ⁅dA j i, θ⁆ + ⁅A i, dθ j⁆))
        + (⁅gaugeVarA A dθ θ i, A j⁆ + ⁅A i, gaugeVarA A dθ θ j⁆)
      = ⁅magnetic A dA i j, θ⁆ := by
  have hc1 : ⁅A j, dθ i⁆ = -⁅dθ i, A j⁆ := (lie_skew (A j) (dθ i)).symm
  simp only [magnetic, gaugeVarA, add_lie, lie_add, sub_lie, hsym]
  rw [← lie_adj_leibniz (A i) θ (A j), hc1]
  abel

/-! ## The Weyl-gauge energy -/

/-- The Weyl-gauge energy `½ Σ_i κ(π_i, π_i) + ¼ Σ_{i,j} κ(B_{ij}, B_{ij})`
for an invariant symmetric form `κ` on the gauge algebra. -/
noncomputable def weylEnergy {M : Type*} (κ : M → M → ℝ) (π : Fin 3 → M)
    (B : Fin 3 → Fin 3 → M) : ℝ :=
  (1 / 2) * ∑ i, κ (π i) (π i) + (1 / 4) * ∑ i, ∑ j, κ (B i j) (B i j)

/-- An invariant symmetric form kills the adjoint variation of a vector against
itself: `κ(⁅x, θ⁆, x) = 0`. -/
theorem inner_adjVar_self_eq_zero {κ : L → L → ℝ}
    (hinv : ∀ x y z : L, κ ⁅x, z⁆ y + κ x ⁅y, z⁆ = 0)
    (hsymm : ∀ x y : L, κ x y = κ y x) (x θ : L) : κ ⁅x, θ⁆ x = 0 := by
  have h := hinv x x θ
  rw [hsymm x ⁅x, θ⁆] at h
  linarith

/-- **The Weyl-gauge energy is gauge invariant.**  Its first-order variation
under `δ π_i = ⁅π_i, θ⁆`, `δ B_{ij} = ⁅B_{ij}, θ⁆` vanishes. -/
theorem weylEnergy_gauge_invariant {κ : L → L → ℝ}
    (hinv : ∀ x y z : L, κ ⁅x, z⁆ y + κ x ⁅y, z⁆ = 0)
    (hsymm : ∀ x y : L, κ x y = κ y x)
    (π : Fin 3 → L) (B : Fin 3 → Fin 3 → L) (θ : L) :
    (∑ i, κ ⁅π i, θ⁆ (π i)) + (1 / 2) * ∑ i, ∑ j, κ ⁅B i j, θ⁆ (B i j) = 0 := by
  have h1 : ∀ i, κ ⁅π i, θ⁆ (π i) = 0 := fun i =>
    inner_adjVar_self_eq_zero hinv hsymm _ _
  have h2 : ∀ i j, κ ⁅B i j, θ⁆ (B i j) = 0 := fun i j =>
    inner_adjVar_self_eq_zero hinv hsymm _ _
  simp [h1, h2]

/-- **The Weyl-gauge energy is non-negative** for a positive semidefinite
invariant form: the book's *"the Hamiltonian in the Weyl gauge is positive
definite"*. -/
theorem weylEnergy_nonneg {M : Type*} {κ : M → M → ℝ} (hpos : ∀ x : M, 0 ≤ κ x x)
    (π : Fin 3 → M) (B : Fin 3 → Fin 3 → M) :
    0 ≤ weylEnergy κ π B := by
  have h1 : 0 ≤ ∑ i, κ (π i) (π i) := sum_nonneg fun i _ => hpos _
  have h2 : 0 ≤ ∑ i, ∑ j, κ (B i j) (B i j) :=
    sum_nonneg fun i _ => sum_nonneg fun j _ => hpos _
  unfold weylEnergy
  linarith

end BookProof.ChapterGaugeAdjointAlgebra
