import Mathlib

/-!
# Chapter "Entropy and an irreversible deterministic time-evolution coexist",
§ "Baryon asymmetry" — expansion amplifies the matter/radiation energy ratio

Source: `book.tex`, chapter *"Entropy and an irreversible deterministic
time-evolution coexist"*, § *"Baryon asymmetry"* (`book.tex` line ~9590):

> *"the most relevant ingredient is that the expansion of the Universe increases
> the ratio of the energies in the matter vs. radiation contents, proportional to
> the scale of the Universe. So, in fact the CP asymmetry generated by Particle
> Physics was very small, but it was much amplified by the expansion of the
> Universe."*

The self-contained mathematical content, independent of the surrounding
cosmology, is the classical FRW scaling of perfect-fluid energy densities. For a
homogeneous, isotropic (FRW) universe with dimensionless scale factor `a > 0`, a
perfect-fluid component with equation of state `p = w · ρ` obeys the continuity
equation (rewritten with `d/dt = a · H · d/da`, `H = ȧ/a`)

  `a · ρ'(a) + 3·(1 + w)·ρ(a) = 0`,

whose positive solutions are the power laws `ρ(a) ∝ a^(−3(1+w))`.  Pressureless
**matter** (`w = 0`) therefore dilutes as `ρ_m ∝ a⁻³` while **radiation**
(`w = 1/3`) dilutes faster as `ρ_r ∝ a⁻⁴`.  Consequently the matter-to-radiation
energy ratio

  `ρ_m(a) / ρ_r(a) = (ρ_{m,0} / ρ_{r,0}) · a`

is **proportional to the scale factor** and grows without bound as `a → ∞` — the
"amplification by the expansion of the Universe" the book relies on.

## Deliverables

* `matterDensity`, `radDensity`, `matterRadiationRatio` — the FRW power-law
  densities and their ratio.
* `matter_satisfies_continuity`, `radiation_satisfies_continuity` — the density
  laws satisfy the FRW continuity equation with `w = 0` and `w = 1/3`
  respectively (the physical grounding of the scaling exponents `3` and `4`).
* `matterRadiationRatio_eq` — **the book's "proportional to the scale of the
  Universe"**: the ratio equals `(ρ_{m,0}/ρ_{r,0}) · a`.
* `matterRadiationRatio_strictMonoOn` — the ratio is strictly increasing in `a`.
* `matterRadiationRatio_tendsto_atTop` — **the book's "amplified by the
  expansion"**: the ratio tends to `+∞` as `a → +∞`.

Everything is `sorry`-free and `axiom`-free (only `propext`, `Classical.choice`,
`Quot.sound`).
-/

open Filter Topology

namespace BookProof.ChapterBaryonAsymmetry

/-- FRW matter (pressureless dust, `w = 0`) energy density: dilutes as `a⁻³`.
`ρm0` is the present-day (`a = 1`) matter density. -/
noncomputable def matterDensity (ρm0 a : ℝ) : ℝ := ρm0 / a ^ 3

/-- FRW radiation (`w = 1/3`) energy density: dilutes as `a⁻⁴`.
`ρr0` is the present-day (`a = 1`) radiation density. -/
noncomputable def radDensity (ρr0 a : ℝ) : ℝ := ρr0 / a ^ 4

/-- The matter-to-radiation energy ratio as a function of the scale factor. -/
noncomputable def matterRadiationRatio (ρm0 ρr0 a : ℝ) : ℝ :=
  matterDensity ρm0 a / radDensity ρr0 a

/-- The matter law satisfies the FRW continuity equation with `w = 0`:
`a · ρ_m'(a) + 3·(1 + 0)·ρ_m(a) = 0` for `a > 0`. This fixes the dilution
exponent `3`. -/
theorem matter_satisfies_continuity (ρm0 a : ℝ) (ha : 0 < a) :
    a * deriv (fun x => matterDensity ρm0 x) a + 3 * (1 + 0) * matterDensity ρm0 a = 0 := by
  have h : HasDerivAt (fun x : ℝ => matterDensity ρm0 x)
      (ρm0 * (-(3 * a ^ 2) / (a ^ 3) ^ 2)) a := by
    have hp : HasDerivAt (fun x : ℝ => x ^ 3) (3 * a ^ 2) a := by simpa using hasDerivAt_pow 3 a
    have hinv : HasDerivAt (fun x : ℝ => (x ^ 3)⁻¹) (-(3 * a ^ 2) / (a ^ 3) ^ 2) a :=
      hp.inv (by positivity)
    simpa [matterDensity, div_eq_mul_inv] using hinv.const_mul ρm0
  rw [h.deriv]
  simp only [matterDensity]
  field_simp
  ring

/-- The radiation law satisfies the FRW continuity equation with `w = 1/3`:
`a · ρ_r'(a) + 3·(1 + 1/3)·ρ_r(a) = 0` for `a > 0`. This fixes the dilution
exponent `4`. -/
theorem radiation_satisfies_continuity (ρr0 a : ℝ) (ha : 0 < a) :
    a * deriv (fun x => radDensity ρr0 x) a + 3 * (1 + 1/3) * radDensity ρr0 a = 0 := by
  have h : HasDerivAt (fun x : ℝ => radDensity ρr0 x)
      (ρr0 * (-(4 * a ^ 3) / (a ^ 4) ^ 2)) a := by
    have hp : HasDerivAt (fun x : ℝ => x ^ 4) (4 * a ^ 3) a := by simpa using hasDerivAt_pow 4 a
    have hinv : HasDerivAt (fun x : ℝ => (x ^ 4)⁻¹) (-(4 * a ^ 3) / (a ^ 4) ^ 2) a :=
      hp.inv (by positivity)
    simpa [radDensity, div_eq_mul_inv] using hinv.const_mul ρr0
  rw [h.deriv]
  simp only [radDensity]
  field_simp
  ring

/-- **The book's "proportional to the scale of the Universe".** For a positive
scale factor and nonzero present-day radiation density, the matter-to-radiation
ratio equals `(ρ_{m,0}/ρ_{r,0}) · a`. -/
theorem matterRadiationRatio_eq (ρm0 ρr0 a : ℝ) (ha : 0 < a) (hr : ρr0 ≠ 0) :
    matterRadiationRatio ρm0 ρr0 a = (ρm0 / ρr0) * a := by
  have hane : a ≠ 0 := ne_of_gt ha
  simp only [matterRadiationRatio, matterDensity, radDensity]
  field_simp

/-- The matter-to-radiation ratio is strictly increasing in the scale factor
(for positive present-day densities): expansion monotonically favours matter. -/
theorem matterRadiationRatio_strictMonoOn (ρm0 ρr0 : ℝ) (hm : 0 < ρm0) (hr : 0 < ρr0) :
    StrictMonoOn (fun a => matterRadiationRatio ρm0 ρr0 a) (Set.Ioi (0 : ℝ)) := by
  have hk : 0 < ρm0 / ρr0 := div_pos hm hr
  intro x hx y hy hxy
  dsimp only
  rw [matterRadiationRatio_eq _ _ _ hx (ne_of_gt hr),
    matterRadiationRatio_eq _ _ _ hy (ne_of_gt hr)]
  exact mul_lt_mul_of_pos_left hxy hk

/-- **The book's "amplified by the expansion of the Universe".** As the scale
factor grows, the matter-to-radiation energy ratio tends to `+∞`. -/
theorem matterRadiationRatio_tendsto_atTop (ρm0 ρr0 : ℝ) (hm : 0 < ρm0) (hr : 0 < ρr0) :
    Tendsto (fun a => matterRadiationRatio ρm0 ρr0 a) atTop atTop := by
  have hk : 0 < ρm0 / ρr0 := div_pos hm hr
  have heq : (fun a => matterRadiationRatio ρm0 ρr0 a) =ᶠ[atTop] (fun a => (ρm0 / ρr0) * a) := by
    filter_upwards [eventually_gt_atTop 0] with a ha
    exact matterRadiationRatio_eq _ _ _ ha (ne_of_gt hr)
  rw [tendsto_congr' heq]
  exact Filter.Tendsto.const_mul_atTop hk tendsto_id

end BookProof.ChapterBaryonAsymmetry
