import Mathlib
import BookProof.ChapterQgContinuumModeInstance

/-!
# BRST derivative gauge fixing for the outer-Fock quantum-gravity Hamiltonian

The gauge fixing used throughout this project for Navier–Stokes
(`BookProof.ChapterNavierStokesGaugeY`) introduces an **auxiliary variable that the gauge
condition fixes to a spatial derivative of a field**: the modes `u_{i,j}` are constrained to
be the `y`-derivatives of `u_i(y)`, and the constraint is generated by a first-class
(abelian) generator, so it can be treated by BRST.  This module carries the same device over
to the quantum-gravity Hamiltonian of `BookProof.ChapterQgContinuumModeInstance`.

The extended (pre-gauge-fixed) variables are the vielbein modes `e_ν^i(k)` **together with**
auxiliary derivative modes `D_{μν}^i(k)`, one for every spatial derivative of every vielbein
component (`EMode`).  In these variables the torsion is *linear in the auxiliary variables
alone*,

`T_{μν}^i = D_{μν}^i − D_{νμ}^i`  (`extTorsionCoef`),

with no derivative appearing anywhere; the whole derivative content sits in the gauge
condition

`D_{μν}^i(k) = i k_μ e_ν^i(k)`,

which is exactly "an auxiliary variable is fixed to the spatial derivative of a field".
`gaugeReduce` performs the substitution on linear forms, and the two main identities are

* **`gaugeReduce_extTorsionCoef`** — the gauge-fixed extended torsion form is *exactly* the
  physical torsion form `k_μ e_ν^i − k_ν e_μ^i` of the continuum model;
* **`gaugeReduce_gram`** — hence the gauge-fixed Gram matrix of all extended torsion terms
  is exactly the vielbein self-interaction `contTorsionGram` of the continuum model.

Consequently the gauge-fixed quantum-gravity Hamiltonian is the continuum Hamiltonian, and
it is essentially self-adjoint on the outer Fock space
(**`brstGaugeFixed_esa`**, **`starobinsky_brstGaugeFixed_esa`**).

A second, independent ingredient is the general **restriction principle**
(`restrictModes`): admissible mode data restricted to *any* subset of modes — for
instance the physical modes surviving a gauge condition — is again admissible, so the
Faris–Lavine essential self-adjointness survives gauge fixing
(`restrict_essentiallySelfAdjointOn`).

Everything is `sorry`-free and `axiom`-free.
-/

namespace BookProof.QgBrstDerivativeGauge

open BookProof.ScalaronFiberFL BookProof.ScalaronOuterFockFL
open BookProof.QgVielbeinModeInstance BookProof.QgContinuumModeInstance
open BookProof.FarisLavine BookProof.QgOuterFockCoreFL

noncomputable section

/-! ## 1. The restriction principle: gauge fixing removes modes -/

open Classical in
/-- **Admissible mode data restricted to a subset of the modes.**  Every Faris–Lavine bound
survives, with the same constant `K`, because all the sums are sums of non-negative terms
over a smaller index set.  Gauge fixing — the passage to the modes that survive a gauge
condition — is an instance. -/
def restrictModes {ι : Type*} (Q : QgModeData ι) (s : Set ι) : QgModeData s where
  sig a := Q.sig a
  one_le_sig a := Q.one_le_sig a
  A a b := Q.A a b
  B a b := Q.B a b
  nbr a := (Q.nbr (a : ι)).subtype (· ∈ s)
  mem_nbr_comm a b := by
    simp only [Finset.mem_subtype]
    exact Q.mem_nbr_comm (a : ι) (b : ι)
  A_off a b hb := Q.A_off (a : ι) (b : ι) (fun hmem => hb (Finset.mem_subtype.mpr hmem))
  B_off a b hb := Q.B_off (a : ι) (b : ι) (fun hmem => hb (Finset.mem_subtype.mpr hmem))
  A_herm a b := Q.A_herm (a : ι) (b : ι)
  B_herm a b := Q.B_herm (a : ι) (b : ι)
  K := Q.K
  K_nonneg := Q.K_nonneg
  A_rel_row a := by
    refine le_trans ?_ (Q.A_rel_row (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => ‖Q.A (a : ι) b‖ / Q.sig b)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => div_nonneg (norm_nonneg _) (Q.sig_nonneg b))
  A_rel_col a := by
    refine le_trans ?_ (Q.A_rel_col (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => ‖Q.A (a : ι) b‖)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => norm_nonneg _)
  A_comm a := by
    refine le_trans ?_ (Q.A_comm (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => |Q.sig (a : ι) - Q.sig b| * ‖Q.A (a : ι) b‖)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => mul_nonneg (abs_nonneg _) (norm_nonneg _))
  B_rel a := by
    refine le_trans ?_ (Q.B_rel (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => ‖Q.B (a : ι) b‖)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => norm_nonneg _)
  B_comm a := by
    refine le_trans ?_ (Q.B_comm (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => |Q.sig (a : ι) - Q.sig b| * ‖Q.B (a : ι) b‖)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => mul_nonneg (abs_nonneg _) (norm_nonneg _))

/-- **Essential self-adjointness survives the removal of modes.**  The Hamiltonian of the
mode data restricted to any subset of the modes is essentially self-adjoint on the domain of
the lifted Friedrichs extension of its comparison operator. -/
theorem restrict_essentiallySelfAdjointOn {ι : Type*} (W : WallPot) (Q : QgModeData ι)
    (s : Set ι) :
    EssentiallySelfAdjointOn (secN W (restrictModes Q s)).dom
      (secData W (restrictModes Q s)).ext :=
  secHam_essentiallySelfAdjointOn W _

/-! ## 2. The extended variables and the derivative gauge condition -/

/-- An auxiliary derivative mode `D_{μν}^i(k)`: a momentum together with the derivative
index `μ` and the vielbein indices `(ν, i)`. -/
abbrev DMode := Mom × Fin 3 × Fin 3 × Fin 3

/-- The extended (pre-gauge-fixed) modes: the vielbein modes together with the auxiliary
derivative modes. -/
abbrev EMode := CMode ⊕ DMode

/-- The momentum carried by an extended mode. -/
def emom : EMode → Mom
  | Sum.inl x => x.1
  | Sum.inr d => d.1

/-- **The torsion in the extended variables**: `T_{μν}^i = D_{μν}^i − D_{νμ}^i`, a linear
form in the *auxiliary* variables alone — no derivative appears. -/
def extTorsionCoef (k : Mom) (mu nu i : Fin 3) : EMode → ℂ
  | Sum.inl _ => 0
  | Sum.inr d =>
      if d.1 = k then
        ((if d.2 = (mu, nu, i) then 1 else 0) - (if d.2 = (nu, mu, i) then 1 else 0))
      else 0

/-- **The BRST derivative gauge condition, as a substitution on linear forms**: the
auxiliary variable `D_{μν}^i(k)` is replaced by the spatial derivative `k_μ e_ν^i(k)` of the
vielbein field.  (The factor `i` of the derivative symbol is a phase; it is omitted here
exactly as in the physical torsion form, and cancels in the Gram matrix.) -/
def gaugeReduce (F : EMode → ℂ) (x : CMode) : ℂ :=
  F (Sum.inl x) + ∑ rho : Fin 3, ((x.1 rho : ℤ) : ℂ) * F (Sum.inr (x.1, rho, x.2.1, x.2.2))

private theorem delta_triple (rho mu nu i p1 p2 : Fin 3) :
    (if ((rho, p1, p2) : Fin 3 × Fin 3 × Fin 3) = (mu, nu, i) then (1 : ℂ) else 0)
      = (if rho = mu then (1 : ℂ) else 0) * (if (p1, p2) = (nu, i) then 1 else 0) := by
  by_cases h1 : rho = mu <;> by_cases h2 : (p1, p2) = (nu, i) <;>
    simp [h1, h2, Prod.ext_iff]

private theorem sum_delta (k : Mom) (mu nu i p1 p2 : Fin 3) :
    ∑ rho : Fin 3, ((k rho : ℤ) : ℂ) *
        (if ((rho, p1, p2) : Fin 3 × Fin 3 × Fin 3) = (mu, nu, i) then (1 : ℂ) else 0)
      = if (p1, p2) = (nu, i) then ((k mu : ℤ) : ℂ) else 0 := by
  have hsum : ∑ rho : Fin 3, ((k rho : ℤ) : ℂ) *
      (if ((rho, p1, p2) : Fin 3 × Fin 3 × Fin 3) = (mu, nu, i) then (1 : ℂ) else 0)
      = (if (p1, p2) = (nu, i) then (1 : ℂ) else 0) *
          ∑ rho : Fin 3, (if rho = mu then ((k rho : ℤ) : ℂ) else 0) := by
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun rho _ => ?_
    rw [delta_triple rho mu nu i p1 p2]
    by_cases h1 : rho = mu <;> by_cases h2 : (p1, p2) = (nu, i) <;> simp [h1, h2]
  rw [hsum, Finset.sum_ite_eq' Finset.univ mu (fun rho => ((k rho : ℤ) : ℂ))]
  by_cases h2 : (p1, p2) = (nu, i) <;> simp [h2]

/-- **The gauge-fixed extended torsion form is the physical torsion form.**  Substituting
the gauge condition `D_{μν}^i(k) = k_μ e_ν^i(k)` into the extended torsion
`D_{μν}^i − D_{νμ}^i` returns exactly `k_μ e_ν^i − k_ν e_μ^i`, the exact Fourier torsion of
the continuum model. -/
theorem gaugeReduce_extTorsionCoef (k : Mom) (mu nu i : Fin 3) (x : CMode) :
    gaugeReduce (extTorsionCoef k mu nu i) x
      = if x.1 = k then torsionCoef k mu nu i x else 0 := by
  by_cases hk : x.1 = k
  · subst hk
    simp only [gaugeReduce, extTorsionCoef, if_true, zero_add, mul_sub,
      Finset.sum_sub_distrib]
    rw [sum_delta x.1 mu nu i x.2.1 x.2.2, sum_delta x.1 nu mu i x.2.1 x.2.2]
    simp only [torsionCoef]
  · simp only [gaugeReduce, extTorsionCoef, if_neg hk, mul_zero, Finset.sum_const_zero,
      add_zero]

/-- **The gauge-fixed Gram matrix of the extended torsion terms is the vielbein
self-interaction of the continuum model.**  Gauge fixing the auxiliary derivative variables
to the spatial derivatives of the vielbein turns the extended, derivative-free torsion
potential into the physical torsion potential `½ Σ_m T_m²`. -/
theorem gaugeReduce_gram (x y : CMode) (h : x.1 = y.1) :
    ∑ mu : Fin 3, ∑ nu : Fin 3, ∑ i : Fin 3,
        (starRingEnd ℂ) (gaugeReduce (extTorsionCoef x.1 mu nu i) x)
          * gaugeReduce (extTorsionCoef x.1 mu nu i) y
      = contTorsionGram x y := by
  have hy : y.1 = x.1 := h.symm
  simp only [contTorsionGram, if_pos h]
  refine Finset.sum_congr rfl fun mu _ => Finset.sum_congr rfl fun nu _ =>
    Finset.sum_congr rfl fun i _ => ?_
  rw [gaugeReduce_extTorsionCoef, gaugeReduce_extTorsionCoef, if_pos rfl, if_pos hy]

/-! ## 3. Essential self-adjointness of the gauge-fixed Hamiltonian -/

/-- **The BRST gauge-fixed quantum-gravity Hamiltonian is essentially self-adjoint on the
outer Fock space.**  After the auxiliary derivative variables have been fixed to the spatial
derivatives of the vielbein, the mode matrices are those of the continuum model
(`gaugeReduce_gram`), so the Faris–Lavine theorem applies with no lattice approximation,
no truncation of the mode set, arbitrary coupling constant `g` and an arbitrary smooth
non-negative scalaron wall. -/
theorem brstGaugeFixed_esa (W : WallPot) (g : ℝ) :
    EssentiallySelfAdjointOn (secN W (qgContinuumModes g)).dom
      (secData W (qgContinuumModes g)).ext :=
  qgContinuum_essentiallySelfAdjointOn W g

/-- The gauge-fixed Hamiltonian with the full exponential Einstein-frame Starobinsky wall. -/
theorem starobinsky_brstGaugeFixed_esa (M alpha : ℝ) (halpha : 0 < alpha) (g : ℝ) :
    EssentiallySelfAdjointOn
        (secN (starobinskyWall M alpha halpha) (qgContinuumModes g)).dom
      (secData (starobinskyWall M alpha halpha) (qgContinuumModes g)).ext :=
  starobinsky_qgContinuum_esa M alpha halpha g

/-- Essential self-adjointness of the Hamiltonian on any gauge-fixed subset of the modes of
the continuum model: the restriction principle applied to the physical modes. -/
theorem gaugeFixedSubset_esa (W : WallPot) (g : ℝ) (s : Set CMode) :
    EssentiallySelfAdjointOn (secN W (restrictModes (qgContinuumModes g) s)).dom
      (secData W (restrictModes (qgContinuumModes g) s)).ext :=
  restrict_essentiallySelfAdjointOn W _ s

/-! ## 4. Non-vacuity of the extended description -/

/-- The extended torsion really depends on the auxiliary variables: it is not the zero
form. -/
theorem extTorsionCoef_ne_zero (k : Mom) :
    extTorsionCoef k 0 1 0 (Sum.inr (k, 0, 1, 0)) ≠ 0 := by
  simp only [extTorsionCoef]
  norm_num [Prod.ext_iff]

end

end BookProof.QgBrstDerivativeGauge
