import Mathlib

/-!
# Chapter — Euler's formula for a generic phase-space (density-matrix recursion)

Formalization of the *density-matrix* identity in `book.tex`, chapter
*"Wave-function collapse versus Euler's formula"*, §§*"Euler's formula for a
phase-space with 4 states"* and *"Euler's formula for a generic phase-space"*
(`book.tex` lines ~3478 and ~3565).

The book parametrizes a normalized wave-function recursively as
`vₙ = cₙ·lₙ + sₙ·vₙ₊₁`, with `cₙ = cos θₙ`, `sₙ = sin θₙ`, and `{lₙ}` an
orthonormal basis, and writes the projector `vₙ vₙ†` in *Euler form*:

> `vₙ vₙ† = ½ + ½(lₙ lₙ† − vₙ₊₁ vₙ₊₁†)(cos 2θₙ + Jₙ sin 2θₙ)`,
>   where `Jₙ = lₙ vₙ₊₁† − vₙ₊₁ lₙ†` plays the role of the imaginary unit in the
>   2-dimensional subspace generated by `{lₙ, vₙ₊₁}`,

and describes collapse as *"suppressing the off-diagonal `Jₙ`-proportional
terms"*, leaving the diagonal operator
`diag(vₙ vₙ†) = cₙ² lₙ lₙ† + sₙ² vₙ₊₁ vₙ₊₁†` representing the classical
conditional-probability recursion.

This module formalizes the self-contained algebraic core of that "single
recursion step" for *arbitrary* orthonormal real vectors `l, w` in `Fin d → ℝ`
(any finite dimension `d`), where `w` plays the role of `vₙ₊₁`.  It generalizes
`BookProof.ChapterEulerDensityMatrix` (the concrete 2-state `2×2` case) to the
recursion step over an arbitrary orthonormal pair in any dimension.

All results are `sorry`-free and `axiom`-clean (only `propext`,
`Classical.choice`, `Quot.sound`).

## Definitions

* `eulerVec θ l w` — the wave-function `v = cos θ · l + sin θ · w`.
* `Jgen l w` — the "imaginary unit" `J = l wᵀ − w lᵀ` of the `{l, w}` subspace.

## Results

* `vecMulVec_mul_vecMulVec` — outer-product multiplication
  `(u vᵀ)(x yᵀ) = (v · x)·(u yᵀ)`.
* `eulerVec_unit` — `v` is a unit vector (`v · v = 1`).
* `outer_eulerVec` — the density matrix expanded:
  `v vᵀ = c²·llᵀ + s²·wwᵀ + cs·(lwᵀ + wlᵀ)`.
* `Jgen_sq` — `J² = −(llᵀ + wwᵀ)` (`J` is the imaginary unit of the subspace).
* `Jgen_mul` — `(llᵀ − wwᵀ)·J = lwᵀ + wlᵀ` (the off-diagonal generator).
* **HEADLINE `density_euler_generic`** — the projector in Euler form
  `v vᵀ = ½·(llᵀ + wwᵀ) + (cos 2θ)/2·(llᵀ − wwᵀ) + (sin 2θ)/2·((llᵀ − wwᵀ)·J)`.
* **`density_collapse_generic`** — removing the `J`-proportional part yields the
  diagonal recursion `cos²θ·llᵀ + sin²θ·wwᵀ` (the book's collapse rule).
* `density_trace` (`tr = 1`), `density_symm` (`ρᵀ = ρ`), `density_idempotent`
  (`ρ² = ρ`: a projector / pure state).
-/

open scoped Matrix
open Matrix

namespace BookProof.ChapterEulerGenericDensity

variable {d : ℕ}

/-- Outer-product matrices multiply by contracting the inner factors:
`(u vᵀ)(x yᵀ) = (v · x) • (u yᵀ)`. -/
theorem vecMulVec_mul_vecMulVec (u v x y : Fin d → ℝ) :
    Matrix.vecMulVec u v * Matrix.vecMulVec x y = (v ⬝ᵥ x) • Matrix.vecMulVec u y := by
  ext i k
  simp only [Matrix.mul_apply, Matrix.vecMulVec_apply, Matrix.smul_apply, dotProduct,
    smul_eq_mul, Finset.sum_mul]
  apply Finset.sum_congr rfl; intro j _; ring

/-- The Euler wave-function `v = cos θ · l + sin θ · w` for the recursion step. -/
noncomputable def eulerVec (θ : ℝ) (l w : Fin d → ℝ) : Fin d → ℝ :=
  Real.cos θ • l + Real.sin θ • w

/-- The matrix `J = l wᵀ − w lᵀ` that plays the role of the imaginary unit in the
2-dimensional subspace generated by `{l, w}`. -/
def Jgen (l w : Fin d → ℝ) : Matrix (Fin d) (Fin d) ℝ :=
  Matrix.vecMulVec l w - Matrix.vecMulVec w l

/-- For orthonormal `l, w`, the Euler wave-function is a unit vector:
`v · v = cos²θ + sin²θ = 1`. -/
theorem eulerVec_unit (θ : ℝ) (l w : Fin d → ℝ)
    (hll : l ⬝ᵥ l = 1) (hww : w ⬝ᵥ w = 1) (hlw : l ⬝ᵥ w = 0) :
    eulerVec θ l w ⬝ᵥ eulerVec θ l w = 1 := by
  have hwl : w ⬝ᵥ l = 0 := by rw [dotProduct_comm]; exact hlw
  simp only [eulerVec, dotProduct_add, add_dotProduct, dotProduct_smul, smul_dotProduct,
    smul_eq_mul, hll, hww, hlw, hwl]
  nlinarith [Real.sin_sq_add_cos_sq θ]

/-- The density matrix expanded entrywise:
`v vᵀ = cos²θ·llᵀ + sin²θ·wwᵀ + cos θ sin θ·(lwᵀ + wlᵀ)`. -/
theorem outer_eulerVec (θ : ℝ) (l w : Fin d → ℝ) :
    Matrix.vecMulVec (eulerVec θ l w) (eulerVec θ l w)
      = (Real.cos θ ^ 2) • Matrix.vecMulVec l l
        + (Real.sin θ ^ 2) • Matrix.vecMulVec w w
        + (Real.cos θ * Real.sin θ) •
            (Matrix.vecMulVec l w + Matrix.vecMulVec w l) := by
  ext i j
  simp only [eulerVec, Matrix.vecMulVec_apply, Pi.add_apply, Pi.smul_apply, smul_eq_mul,
    Matrix.add_apply, Matrix.smul_apply]
  ring

/-- `J² = −(llᵀ + wwᵀ)`: on the `{l, w}` subspace, `J` squares to minus the
identity (it is the imaginary unit of the subspace). -/
theorem Jgen_sq (l w : Fin d → ℝ)
    (hll : l ⬝ᵥ l = 1) (hww : w ⬝ᵥ w = 1) (hlw : l ⬝ᵥ w = 0) :
    Jgen l w * Jgen l w = -(Matrix.vecMulVec l l + Matrix.vecMulVec w w) := by
  have hwl : w ⬝ᵥ l = 0 := by rw [dotProduct_comm]; exact hlw
  simp only [Jgen, sub_mul, mul_sub, vecMulVec_mul_vecMulVec, hll, hww, hlw, hwl,
    one_smul, zero_smul]
  abel

/-- `(llᵀ − wwᵀ)·J = lwᵀ + wlᵀ`: multiplying the diagonal generator by `J`
produces the off-diagonal (`J`-proportional) part of the density matrix. -/
theorem Jgen_mul (l w : Fin d → ℝ)
    (hll : l ⬝ᵥ l = 1) (hww : w ⬝ᵥ w = 1) (hlw : l ⬝ᵥ w = 0) :
    (Matrix.vecMulVec l l - Matrix.vecMulVec w w) * Jgen l w
      = Matrix.vecMulVec l w + Matrix.vecMulVec w l := by
  have hwl : w ⬝ᵥ l = 0 := by rw [dotProduct_comm]; exact hlw
  simp only [Jgen, sub_mul, mul_sub, vecMulVec_mul_vecMulVec, hll, hww, hlw, hwl,
    one_smul, zero_smul]
  abel

/-- **Euler's formula for the generic density matrix (single recursion step).**
For orthonormal `l, w`, the projector `v vᵀ` (with `v = cos θ·l + sin θ·w`) is

`v vᵀ = ½·(llᵀ + wwᵀ) + (cos 2θ)/2·(llᵀ − wwᵀ) + (sin 2θ)/2·((llᵀ − wwᵀ)·J)`,

i.e. the "complex number" `cos 2θ + J sin 2θ` scaled by the diagonal generator
`½(llᵀ − wwᵀ)`, plus the subspace-identity offset `½(llᵀ + wwᵀ)`. -/
theorem density_euler_generic (θ : ℝ) (l w : Fin d → ℝ)
    (hll : l ⬝ᵥ l = 1) (hww : w ⬝ᵥ w = 1) (hlw : l ⬝ᵥ w = 0) :
    Matrix.vecMulVec (eulerVec θ l w) (eulerVec θ l w)
      = (1 / 2 : ℝ) • (Matrix.vecMulVec l l + Matrix.vecMulVec w w)
        + (Real.cos (2 * θ) / 2) • (Matrix.vecMulVec l l - Matrix.vecMulVec w w)
        + (Real.sin (2 * θ) / 2) •
            ((Matrix.vecMulVec l l - Matrix.vecMulVec w w) * Jgen l w) := by
  rw [Jgen_mul l w hll hww hlw, outer_eulerVec]
  ext i j
  simp only [Matrix.add_apply, Matrix.smul_apply, Matrix.sub_apply, Matrix.vecMulVec_apply,
    smul_eq_mul]
  rw [Real.cos_two_mul, Real.sin_two_mul]
  linear_combination (w i * w j) * Real.sin_sq_add_cos_sq θ

/-- **Collapse of the wave-function (generic recursion step).**  Removing the
`J`-proportional part `(sin 2θ)/2·((llᵀ − wwᵀ)·J)` from the density matrix yields
exactly the diagonal conditional-probability recursion
`cos²θ·llᵀ + sin²θ·wwᵀ` — the book's `diag(vₙ vₙ†) = cₙ² lₙ lₙ† + sₙ² vₙ₊₁ vₙ₊₁†`. -/
theorem density_collapse_generic (θ : ℝ) (l w : Fin d → ℝ)
    (hll : l ⬝ᵥ l = 1) (hww : w ⬝ᵥ w = 1) (hlw : l ⬝ᵥ w = 0) :
    Matrix.vecMulVec (eulerVec θ l w) (eulerVec θ l w)
        - (Real.sin (2 * θ) / 2) •
            ((Matrix.vecMulVec l l - Matrix.vecMulVec w w) * Jgen l w)
      = (Real.cos θ ^ 2) • Matrix.vecMulVec l l
        + (Real.sin θ ^ 2) • Matrix.vecMulVec w w := by
  rw [Jgen_mul l w hll hww hlw, outer_eulerVec]
  ext i j
  simp only [Matrix.add_apply, Matrix.smul_apply, Matrix.sub_apply, Matrix.vecMulVec_apply,
    smul_eq_mul]
  rw [Real.sin_two_mul]; ring

/-- The density matrix has unit trace (the projector onto a unit vector). -/
theorem density_trace (θ : ℝ) (l w : Fin d → ℝ)
    (hll : l ⬝ᵥ l = 1) (hww : w ⬝ᵥ w = 1) (hlw : l ⬝ᵥ w = 0) :
    Matrix.trace (Matrix.vecMulVec (eulerVec θ l w) (eulerVec θ l w)) = 1 := by
  rw [show (1 : ℝ) = eulerVec θ l w ⬝ᵥ eulerVec θ l w
      from (eulerVec_unit θ l w hll hww hlw).symm]
  simp [Matrix.trace, Matrix.diag, Matrix.vecMulVec_apply, dotProduct]

/-- The density matrix is symmetric (`ρᵀ = ρ`). -/
theorem density_symm (θ : ℝ) (l w : Fin d → ℝ) :
    (Matrix.vecMulVec (eulerVec θ l w) (eulerVec θ l w))ᵀ
      = Matrix.vecMulVec (eulerVec θ l w) (eulerVec θ l w) := by
  ext i j; simp [Matrix.vecMulVec_apply, Matrix.transpose_apply, mul_comm]

/-- The density matrix is idempotent (`ρ² = ρ`): it is a projector, i.e. the
clock state is a *pure* state. -/
theorem density_idempotent (θ : ℝ) (l w : Fin d → ℝ)
    (hll : l ⬝ᵥ l = 1) (hww : w ⬝ᵥ w = 1) (hlw : l ⬝ᵥ w = 0) :
    Matrix.vecMulVec (eulerVec θ l w) (eulerVec θ l w)
        * Matrix.vecMulVec (eulerVec θ l w) (eulerVec θ l w)
      = Matrix.vecMulVec (eulerVec θ l w) (eulerVec θ l w) := by
  rw [vecMulVec_mul_vecMulVec, eulerVec_unit θ l w hll hww hlw, one_smul]

end BookProof.ChapterEulerGenericDensity
