import Mathlib

/-!
# Energy-bounded initial conditions: no finite-time blow-up

This closes goal **A.4** of the book's *Proof Plans* appendix
(`Book/ProofPlans.lean`): *an initial wave-function supported on the part of the
spectrum below `Emax` has a bounded time-derivative, hence cannot blow up in
finite time*.

We work in the spectral representation, where the Hamiltonian is the diagonal
(multiplication) operator `H = diagOp f` with real eigenvalues `f i` — by the
spectral theorem (`BookProof.ChapterDensitySpectral`) every Hermitian matrix is
unitarily equivalent to such an operator, and a unitary change of basis preserves
all the norms below.  The Schrödinger evolution is then the explicit phase flow
`evolve f t v i = e^{-i t f i} · v i`.

Formalized here:

* `norm_diagOp_le` — the **spectral bound**: if every eigenvalue on the support of
  `ψ` satisfies `|f i| ≤ Emax`, then `‖H ψ‖ ≤ Emax ‖ψ‖`;
* `norm_evolve` — the evolution is **unitary**: `‖ψ(t)‖ = ‖ψ(0)‖`;
* `evolve_support` — the evolution preserves the spectral subspace;
* `hasDerivAt_evolve` — the Schrödinger equation `ψ'(t) = -i H ψ(t)`;
* `norm_deriv_evolve_le` — the **energy bound**: `‖ψ'(t)‖ ≤ Emax ‖ψ(0)‖` for all
  `t`, uniformly in time;
* `evolve_lipschitz` — hence `‖ψ(t) − ψ(s)‖ ≤ Emax ‖ψ(0)‖ · |t − s|`: the solution
  is globally Lipschitz, so there is **no finite-time singularity**.

Everything is `sorry`-free and `axiom`-free (only `propext`, `Classical.choice`,
`Quot.sound`).
-/

namespace BookProof.ChapterSpectralEnergyBound

variable {n : Type*} [Fintype n]

/-- The Hamiltonian in its spectral representation: multiplication by the real
eigenvalue function `f`. -/
def diagOp (f : n → ℝ) (v : EuclideanSpace ℂ n) : EuclideanSpace ℂ n :=
  WithLp.toLp 2 (fun i => (f i : ℂ) * v i)

omit [Fintype n] in
@[simp] theorem diagOp_apply (f : n → ℝ) (v : EuclideanSpace ℂ n) (i : n) :
    diagOp f v i = (f i : ℂ) * v i := rfl

/-- The Schrödinger flow generated by `diagOp f`: `ψ(t) i = e^{-i t f i} ψ(0) i`. -/
noncomputable def evolve (f : n → ℝ) (t : ℝ) (v : EuclideanSpace ℂ n) :
    EuclideanSpace ℂ n :=
  WithLp.toLp 2 (fun i => Complex.exp (-Complex.I * (t : ℂ) * (f i : ℂ)) * v i)

omit [Fintype n] in
@[simp] theorem evolve_apply (f : n → ℝ) (t : ℝ) (v : EuclideanSpace ℂ n) (i : n) :
    evolve f t v i = Complex.exp (-Complex.I * (t : ℂ) * (f i : ℂ)) * v i := rfl

omit [Fintype n] in
@[simp] theorem evolve_zero (f : n → ℝ) (v : EuclideanSpace ℂ n) : evolve f 0 v = v := by
  ext i; simp

omit [Fintype n] in
theorem norm_evolve_apply (f : n → ℝ) (t : ℝ) (v : EuclideanSpace ℂ n) (i : n) :
    ‖evolve f t v i‖ = ‖v i‖ := by
  have habs : ‖Complex.exp (-Complex.I * (t : ℂ) * (f i : ℂ))‖ = 1 := by
    rw [Complex.norm_exp]
    simp
  rw [evolve_apply, norm_mul, habs, one_mul]

/-- The evolution is **unitary**: it preserves the norm of the state. -/
theorem norm_evolve (f : n → ℝ) (t : ℝ) (v : EuclideanSpace ℂ n) :
    ‖evolve f t v‖ = ‖v‖ := by
  rw [EuclideanSpace.norm_eq, EuclideanSpace.norm_eq]
  congr 1
  exact Finset.sum_congr rfl fun i _ => by rw [norm_evolve_apply]

omit [Fintype n] in
/-- The evolution preserves the **spectral support**: no new eigenvalues appear. -/
theorem evolve_support (f : n → ℝ) (t : ℝ) (v : EuclideanSpace ℂ n) (i : n)
    (h : evolve f t v i ≠ 0) : v i ≠ 0 := by
  intro hv
  exact h (by simp [hv])

/-- **The spectral bound.**  If every eigenvalue on the support of `ψ` is at most
`E` in absolute value, then `‖H ψ‖ ≤ E ‖ψ‖`. -/
theorem norm_diagOp_le (f : n → ℝ) (E : ℝ) (v : EuclideanSpace ℂ n)
    (h : ∀ i, v i ≠ 0 → |f i| ≤ E) :
    ‖diagOp f v‖ ≤ E * ‖v‖ := by
  classical
  by_cases hv : ∀ i, v i = 0
  · have hz : diagOp f v = 0 := by ext i; simp [hv i]
    have hz' : v = 0 := by ext i; simpa using hv i
    rw [hz, hz']
    simp
  push_neg at hv
  obtain ⟨i₀, hi₀⟩ := hv
  have hE : 0 ≤ E := le_trans (abs_nonneg _) (h i₀ hi₀)
  have hsq : ∀ i, ‖diagOp f v i‖ ^ 2 ≤ E ^ 2 * ‖v i‖ ^ 2 := by
    intro i
    by_cases hvi : v i = 0
    · simp [hvi]
    · have hfi : |f i| ≤ E := h i hvi
      have hnorm : ‖diagOp f v i‖ = |f i| * ‖v i‖ := by
        simp
      rw [hnorm, mul_pow]
      have h1 : |f i| ^ 2 ≤ E ^ 2 := by nlinarith [abs_nonneg (f i)]
      nlinarith [sq_nonneg ‖v i‖, norm_nonneg (v i)]
  have hsum : ∑ i, ‖diagOp f v i‖ ^ 2 ≤ E ^ 2 * ∑ i, ‖v i‖ ^ 2 := by
    rw [Finset.mul_sum]
    exact Finset.sum_le_sum fun i _ => hsq i
  have hnorm : ‖diagOp f v‖ ^ 2 ≤ (E * ‖v‖) ^ 2 := by
    have h1 : ‖diagOp f v‖ ^ 2 = ∑ i, ‖diagOp f v i‖ ^ 2 := by
      rw [EuclideanSpace.norm_eq, Real.sq_sqrt]
      exact Finset.sum_nonneg fun i _ => by positivity
    have h2 : ‖v‖ ^ 2 = ∑ i, ‖v i‖ ^ 2 := by
      rw [EuclideanSpace.norm_eq, Real.sq_sqrt]
      exact Finset.sum_nonneg fun i _ => by positivity
    rw [h1, mul_pow, h2]
    exact hsum
  nlinarith [norm_nonneg (diagOp f v), norm_nonneg v, mul_nonneg hE (norm_nonneg v)]

/-- **The Schrödinger equation** for the phase flow: `ψ'(t) = -i H ψ(t)`. -/
theorem hasDerivAt_evolve (f : n → ℝ) (v : EuclideanSpace ℂ n) (t : ℝ) :
    HasDerivAt (fun s : ℝ => evolve f s v)
      (-Complex.I • diagOp f (evolve f t v)) t := by
  classical
  have hg : HasDerivAt
      (fun s : ℝ => (fun i => Complex.exp (-Complex.I * (s : ℂ) * (f i : ℂ)) * v i : n → ℂ))
      (fun i => (-Complex.I * (f i : ℂ)) *
        (Complex.exp (-Complex.I * (t : ℂ) * (f i : ℂ)) * v i)) t := by
    apply hasDerivAt_pi.2
    intro i
    have h1 : HasDerivAt (fun s : ℝ => (s : ℂ)) 1 t := Complex.ofRealCLM.hasDerivAt
    have hbase : HasDerivAt (fun s : ℝ => -Complex.I * (s : ℂ) * (f i : ℂ))
        (-Complex.I * (f i : ℂ)) t := by
      simpa [mul_comm, mul_left_comm, mul_assoc] using
        ((h1.const_mul (-Complex.I)).mul_const (f i : ℂ))
    have hexp := (hbase.cexp).mul_const (v i)
    convert hexp using 1
    ring
  have hcomp :=
    (((EuclideanSpace.equiv n ℂ).symm : (n → ℂ) →L[ℂ] EuclideanSpace ℂ n).restrictScalars
      ℝ).hasFDerivAt.comp_hasDerivAt t hg
  convert hcomp using 1
  ext i
  simp [mul_comm, mul_left_comm, mul_assoc]

/-- **The energy bound (goal A.4).**  If the initial state is supported on the
part of the spectrum with `|f i| ≤ E`, then the time-derivative of the state is
bounded by `E ‖ψ(0)‖`, uniformly in time. -/
theorem norm_deriv_evolve_le (f : n → ℝ) (E : ℝ) (v : EuclideanSpace ℂ n)
    (h : ∀ i, v i ≠ 0 → |f i| ≤ E) (t : ℝ) :
    ‖-Complex.I • diagOp f (evolve f t v)‖ ≤ E * ‖v‖ := by
  have hsupp : ∀ i, evolve f t v i ≠ 0 → |f i| ≤ E := fun i hi =>
    h i (evolve_support f t v i hi)
  have hbound := norm_diagOp_le f E (evolve f t v) hsupp
  rw [norm_smul]
  simp only [norm_neg, Complex.norm_I, one_mul]
  rw [norm_evolve] at hbound
  exact hbound

/-- **No finite-time singularity.**  An energy-bounded state evolves Lipschitz
continuously in time with constant `E ‖ψ(0)‖`; in particular it stays bounded
(indeed of constant norm) for all times. -/
theorem evolve_lipschitz (f : n → ℝ) (E : ℝ) (v : EuclideanSpace ℂ n)
    (h : ∀ i, v i ≠ 0 → |f i| ≤ E) (s t : ℝ) :
    ‖evolve f t v - evolve f s v‖ ≤ E * ‖v‖ * |t - s| := by
  have hderiv : ∀ x ∈ Set.uIcc s t,
      HasDerivWithinAt (fun r : ℝ => evolve f r v)
        (-Complex.I • diagOp f (evolve f x v)) (Set.uIcc s t) x :=
    fun x _ => (hasDerivAt_evolve f v x).hasDerivWithinAt
  have hbound : ∀ x ∈ Set.uIcc s t, ‖-Complex.I • diagOp f (evolve f x v)‖ ≤ E * ‖v‖ :=
    fun x _ => norm_deriv_evolve_le f E v h x
  have hmain := Convex.norm_image_sub_le_of_norm_hasDerivWithin_le
    hderiv hbound (convex_uIcc s t) Set.left_mem_uIcc Set.right_mem_uIcc
  simpa [Real.norm_eq_abs, abs_sub_comm] using hmain

end BookProof.ChapterSpectralEnergyBound
