import BookProof.ChapterAbelianDirectSum.Part1
import BookProof.ChapterAbelianDirectSum.Part2

/-!
# Abelian algebras without a cyclic vector: the direct-sum model (plan GAP-2)

`ChapterAbelianCyclicModel` models an **arbitrary** abelian algebra — a unital
`*`-representation `π : C(X, ℂ) →⋆ₐ[ℂ] (H →L[ℂ] H)` of the continuous functions on a
compact Hausdorff space — **with a cyclic unit vector**, as multiplication operators
on `L²(μ)`.  This module removes the cyclic-vector hypothesis, exactly as
`ChapterCyclicDecomposition` / `ChapterCyclicDirectSum` / `ChapterSpectralDirectSum`
do for the algebra generated by a single normal operator, but now for a whole
abelian algebra at once.

* `repCyclicSubspace` — the closed subspace generated by `{π(f)ξ}`;
  `RepInvariant`, `repInvariant_repCyclicSubspace`, `repInvariant_orthogonal`
  (the `*`-closedness of the algebra makes the orthogonal complement of an invariant
  subspace invariant), `repCyclicSubspace_le_orthogonal`;
* `exists_rep_cyclic_decomposition` — by Zorn's lemma a family of unit vectors whose
  cyclic subspaces are pairwise orthogonal and jointly dense;
* `orthogonalFamily_repCyclicSubspace`, `isHilbertSum_repCyclicSubspace`,
  `exists_isHilbertSum_repCyclicSubspace` — the space *is* the Hilbert sum of those
  subspaces; `starProjection_commutes_rep` — the projections onto the summands lie in
  the commutant of the algebra;
* `repCyclicUnitary`, `repEmbedding`, `range_repEmbedding`,
  `repEmbedding_intertwines` — the model of a summand, built inside the ambient
  space: an isometric embedding of `L²(μ_ξ)` with range the cyclic subspace of `ξ`,
  carrying multiplication by every continuous symbol `g` into `π(g)`;
* HEADLINE `abelian_multiplication_model_general` — **every** unital
  `*`-representation of `C(X, ℂ)` on a complex Hilbert space is a direct sum of
  multiplication representations: there are Borel probability measures `μₓ` on `X`
  and isometric embeddings `Vₓ : L²(μₓ) → H` exhibiting `H` as their Hilbert sum,
  with `π(g)` acting on each summand as multiplication by `g`.  No cyclic vector, no
  generator and no separability are assumed;
* `abelian_multiplication_model_separable` — on a separable space the family is
  countable;
* `abelian_algebra_multiplication_model_general` — the Gelfand form, for a
  representation of an abstract commutative unital C\*-algebra.

Everything is `sorry`-free and `axiom`-free.
-/
