import Mathlib
import BookProof.ChapterH1

/-!
# Chapter H3 — Hashimoto SIRK: Duhamel identity and rational-Krylov inclusion (roadmap N13, §0 S7)

This file continues the Hashimoto–Nodera *Shift-invert Rational Krylov (SIRK)*
formalization (source `RiemannProof/Hashimoto.md`), begun in `ChapterH1.lean`
and `ChapterH2.lean`.  It lands two more of the N13 deliverables:

* **H1.3 — the exponential-integrator Duhamel identity (scheme (4)), scalar
  core.** The exact solution of `u' = z·u + g` over `[0,δ]` with constant `g`
  is `u δ = e^{δ z} u₀ + δ·φ₁(δ z)·g`; the load-bearing identity is the Duhamel
  integral `∫₀^δ e^{(δ−s) z} ds = δ·φ₁(δ z)` (`duhamel_scalar`), with the
  forcing-term corollary `duhamel_scalar_smul`.  This is exactly the scalar /
  per-spectral-component reduction (§0 S3) of the operator scheme (4); the `φ₁`
  here is the `ChapterH1.phi` of H1.1/H1.2.
* **H1.7 — the rational-Krylov subspace ⊆ rational functions of `Xₘ` (eq. 11).**
  With the SIRK shift identity `X_j = Y_j · Xₘ` of H1.6 (where
  `Y_j = (1 + h(m−j)·Xₘ)⁻¹`), every SIRK Krylov iterate
  `w_j = X_j ⋯ X_1 v` is a *rational function of the single operator `Xₘ`*
  applied to `v`, i.e. lies in `{ r v | r ∈ 𝒜 }` where `𝒜` is the subalgebra
  generated by `Xₘ` and the resolvent factors `Y_j` (`sirk_krylov_mem_adjoin`).
  This is the mathematically load-bearing inclusion behind the SIRK convergence
  theory (the reverse inclusion — surjectivity onto all of `R_SIRK` — is noted
  in the docstring but not needed for the error bound).

Everything is `sorry`-free and `axiom`-free (only `propext`, `Classical.choice`,
`Quot.sound`); **no `EXTERNAL` hypothesis, no `axiom`**.
-/

open scoped BigOperators
open intervalIntegral

namespace BookProof.ChapterH3

noncomputable section

/-! ## H1.3 — the exponential-integrator Duhamel identity (scalar core) -/

/--
**H1.3** (Duhamel identity, scalar core): `∫₀^δ e^{(δ−s) z} ds = δ · φ₁(δ z)`.

This is the exact-solution kernel of the exponential integrator scheme (4):
the contribution of a constant forcing term `g` to `u(δ)` for `u' = z u + g` is
`(∫₀^δ e^{(δ−s)z} ds)·g = δ·φ₁(δ z)·g`.  Substituting `u = δ − s` turns the
left side into `∫₀^δ e^{u z} du`, and rescaling `u = δ t` turns the right side
`δ·φ₁(δ z) = δ·∫₀¹ e^{t δ z} dt` into the same integral.
-/
theorem duhamel_scalar (z : ℂ) (δ : ℝ) :
    (∫ s in (0:ℝ)..δ, Complex.exp ((↑(δ - s)) * z))
      = δ * BookProof.ChapterH1.phi 1 (δ * z) := by
  have hL : (∫ s in (0:ℝ)..δ, Complex.exp ((↑(δ - s)) * z))
      = ∫ u in (0:ℝ)..δ, Complex.exp ((u:ℂ) * z) := by
    have := intervalIntegral.integral_comp_sub_left (a := 0) (b := δ)
      (f := fun u : ℝ => Complex.exp ((u:ℂ) * z)) δ
    simpa using this
  rw [hL]
  unfold BookProof.ChapterH1.phi
  simp only [pow_zero, Nat.factorial_zero, Nat.cast_one, div_one, mul_one]
  by_cases hδ : δ = 0
  · simp [hδ]
  · have hc : ∫ s in (0:ℝ)..1, Complex.exp ((s:ℂ) * ((δ:ℂ) * z))
        = δ⁻¹ • ∫ x in (0:ℝ)..δ, Complex.exp ((x:ℂ) * z) := by
      have := intervalIntegral.integral_comp_mul_left
        (a := 0) (b := 1) (c := δ) (f := fun u : ℝ => Complex.exp ((u:ℂ) * z)) hδ
      simp only [mul_zero, mul_one] at this
      rw [← this]
      apply intervalIntegral.integral_congr
      intro x hx
      simp [Complex.ofReal_mul]
      ring_nf
    rw [hc, Complex.real_smul, ← mul_assoc]
    push_cast
    rw [mul_inv_cancel₀ (by exact_mod_cast hδ), one_mul]

/--
**H1.3** (Duhamel identity with a constant forcing term `g`):
`∫₀^δ e^{(δ−s) z}·g ds = δ · φ₁(δ z) · g`.
-/
theorem duhamel_scalar_smul (z g : ℂ) (δ : ℝ) :
    (∫ s in (0:ℝ)..δ, Complex.exp ((↑(δ - s)) * z) * g)
      = δ * BookProof.ChapterH1.phi 1 (δ * z) * g := by
  rw [intervalIntegral.integral_mul_const, duhamel_scalar]

/-! ## H1.7 — the rational-Krylov subspace ⊆ rational functions of `Xₘ` -/

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]

/-- The SIRK Krylov iterates `w_j = X_j ⋯ X_1 v`, defined over `ℕ` with a family
`X : ℕ → Module.End ℂ E` of shift-invert resolvents (`X (j+1)` is the resolvent
at shift `γ_{j+1}`).  `w 0 = v`, `w (j+1) = X (j+1) (w j)`. -/
def sirkKrylov (X : ℕ → Module.End ℂ E) (v : E) : ℕ → E
  | 0 => v
  | (j + 1) => X (j + 1) (sirkKrylov X v j)

@[simp] theorem sirkKrylov_zero (X : ℕ → Module.End ℂ E) (v : E) :
    sirkKrylov X v 0 = v := rfl

@[simp] theorem sirkKrylov_succ (X : ℕ → Module.End ℂ E) (v : E) (j : ℕ) :
    sirkKrylov X v (j + 1) = X (j + 1) (sirkKrylov X v j) := rfl

/-
**H1.7** (rational-Krylov ⊆ rational functions of `Xₘ`, eq. 11): let `Xm` be the
common shift operator, `Y : ℕ → Module.End ℂ E` the resolvent factors
`Y_j = (1 + h(m−j)·Xₘ)⁻¹`, and suppose every shift-invert resolvent factors as
`X_j = Y_j · Xₘ` (the H1.6 shift identity, `ChapterH1.resolvent_shift_mul`).
Then every SIRK Krylov iterate `w_j` is a *rational function of the single
operator `Xₘ`* applied to `v`: it lies in the image of `v` under the subalgebra
`𝒜 = adjoin ℂ ({Xₘ} ∪ range Y)` of `Module.End ℂ E`.

The reverse inclusion (that the iterates *span* every such rational function of
`Xₘ` applied to `v`) is the surjectivity half of the paper's characterization
and is not needed for the SIRK error bound; only this inclusion is asserted.
-/
theorem sirk_krylov_mem_adjoin
    (Xm : Module.End ℂ E) (Y X : ℕ → Module.End ℂ E)
    (hX : ∀ j, X j = Y j * Xm) (v : E) (j : ℕ) :
    ∃ r ∈ Algebra.adjoin ℂ ({Xm} ∪ Set.range Y),
      sirkKrylov X v j = r v := by
  induction j with
  | zero => exact ⟨1, OneMemClass.one_mem _, by simp [sirkKrylov]⟩
  | succ j ih =>
    obtain ⟨r, hr, hr'⟩ := ih
    refine ⟨X (j + 1) * r, ?_, ?_⟩
    · refine Subalgebra.mul_mem _ ?_ hr
      rw [hX]
      exact Subalgebra.mul_mem _
        (Algebra.subset_adjoin (Set.mem_union_right _ (Set.mem_range_self _)))
        (Algebra.subset_adjoin (Set.mem_union_left _ rfl))
    · simp [sirkKrylov, hr']

end

end BookProof.ChapterH3
