import Mathlib
import BookProof.ChapterStoneTheorem

/-!
# The general Stone theorem on a separable Hilbert space: the capstone

`ChapterStoneResolvent`–`ChapterStoneTheorem` build the two halves of Stone's theorem.
This module states the theorem as a single correspondence, adds the uniqueness statement
that makes "the group generated by `A`" unambiguous, and exhibits a genuinely *unbounded*
instance so that nothing here is vacuous.

* `gen_eq_of_hasDerivAt` — if a weakly measurable unitary group `U` satisfies Schrödinger's
  equation `d/dt|₀ U t x = -i A x` for every `x` in the domain of the self-adjoint operator
  `A`, then the infinitesimal generator of `U` *is* `A`.  (A self-adjoint operator has no
  proper symmetric extension.)
* `eq_stoneU_of_hasDerivAt` — consequently `U t = e^{-itA}`: the group generated by `A` is
  unique.
* `stone_exists_unique_group` / `stone_exists_unique_generator` — the two halves in `∃!`
  form.
* `stoneEquiv` — the resulting bijection `A ↦ (t ↦ e^{-itA})` between unbounded
  self-adjoint operators and weakly measurable one-parameter unitary groups.

The concrete instance is lattice multiplication on `ℓ²(ℤ)`:

* `separableSpace_L2Z` — `ℓ²(ℤ)` is separable;
* `mulSA f` — multiplication by a real field `f` on its natural domain, as an unbounded
  self-adjoint operator (unbounded for the position field, by `position_unbounded`);
* `stoneU_mulSA` — the group it generates through Stone's theorem is exactly the explicit
  phase group `(e^{-itA}ψ)_k = e^{-it f k} ψ_k`.
-/

open scoped InnerProductSpace
open Filter Topology

namespace BookProof.ChapterStoneSeparable

open BookProof.ChapterStoneResolvent BookProof.ChapterStoneMeasurable

/-! ## The abstract correspondence -/

section Abstract

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [TopologicalSpace.SeparableSpace H]

/-- **A self-adjoint operator has no proper symmetric extension.**  If the weakly measurable
unitary group `U` solves `d/dt|₀ U t x = -i A x` on the whole domain of the self-adjoint
operator `A`, then the infinitesimal generator of `U` is `A` itself. -/
theorem gen_eq_of_hasDerivAt (T : UnboundedSelfAdjoint H) (G : WeakMeasurableUnitaryGroup H)
    (h : ∀ x : T.domain, HasDerivAt (fun t : ℝ => G.U t (x : H)) ((-Complex.I) • T.op x) 0) :
    G.gen = T := by
  have hdom : T.domain ≤ G.genDomain := fun x hx => G.mem_genDomain_of_hasDerivAt (h ⟨x, hx⟩)
  have hop : ∀ x : T.domain, G.genOp ⟨(x : H), hdom x.2⟩ = T.op x := fun x =>
    G.genOp_eq_of_hasDerivAt (x := ⟨(x : H), hdom x.2⟩) (h x)
  refine UnboundedSelfAdjoint.ext' (le_antisymm ?_ hdom) ?_
  · intro x hx
    refine T.mem_domain_of_inner (eta := G.genOp ⟨x, hx⟩) ?_
    intro psi
    rw [← hop psi]
    exact G.symmetric ⟨(psi : H), hdom psi.2⟩ ⟨x, hx⟩
  · intro x _ hx'
    exact hop ⟨x, hx'⟩

/-- **Uniqueness of the group generated by `A`.** -/
theorem eq_stoneU_of_hasDerivAt (T : UnboundedSelfAdjoint H) (G : WeakMeasurableUnitaryGroup H)
    (h : ∀ x : T.domain, HasDerivAt (fun t : ℝ => G.U t (x : H)) ((-Complex.I) • T.op x) 0)
    (t : ℝ) : G.U t = T.stoneU t := by
  rw [← G.gen_stoneU_eq t, gen_eq_of_hasDerivAt T G h]

/-- **Stone's theorem, forward direction, in `∃!` form.**  Every unbounded self-adjoint
operator `A` on a separable Hilbert space generates one and only one weakly measurable
one-parameter unitary group, namely `t ↦ e^{-itA}`. -/
theorem stone_exists_unique_group (T : UnboundedSelfAdjoint H) :
    ∃! G : WeakMeasurableUnitaryGroup H,
      ∀ x : T.domain, HasDerivAt (fun t : ℝ => G.U t (x : H)) ((-Complex.I) • T.op x) 0 := by
  refine ⟨T.stoneGroup, fun x => T.hasDerivAt_stoneU_zero x, fun G hG => ?_⟩
  exact WeakMeasurableUnitaryGroup.ext' (fun t => eq_stoneU_of_hasDerivAt T G hG t)

/-- **Stone's theorem, converse direction, in `∃!` form.**  Every weakly measurable
one-parameter unitary group on a separable Hilbert space is `t ↦ e^{-itA}` for a unique
unbounded self-adjoint operator `A`, its infinitesimal generator. -/
theorem stone_exists_unique_generator (G : WeakMeasurableUnitaryGroup H) :
    ∃! T : UnboundedSelfAdjoint H, ∀ t : ℝ, T.stoneU t = G.U t := by
  refine ⟨G.gen, fun t => G.gen_stoneU_eq t, fun T hT => ?_⟩
  have hgroup : T.stoneGroup = G := WeakMeasurableUnitaryGroup.ext' hT
  rw [← T.gen_stoneGroup_eq, hgroup]

/-- **The general Stone theorem on a separable Hilbert space.**  `A ↦ (t ↦ e^{-itA})` is a
bijection from unbounded self-adjoint operators onto weakly measurable one-parameter
unitary groups, with inverse the infinitesimal generator. -/
noncomputable def stoneEquiv :
    UnboundedSelfAdjoint H ≃ WeakMeasurableUnitaryGroup H where
  toFun T := T.stoneGroup
  invFun G := G.gen
  left_inv T := T.gen_stoneGroup_eq
  right_inv G := WeakMeasurableUnitaryGroup.ext' (fun t => G.gen_stoneU_eq t)

@[simp] theorem stoneEquiv_apply_U (T : UnboundedSelfAdjoint H) (t : ℝ) :
    (stoneEquiv T).U t = T.stoneU t := rfl

@[simp] theorem stoneEquiv_symm_apply (G : WeakMeasurableUnitaryGroup H) :
    stoneEquiv.symm G = G.gen := rfl

end Abstract

/-! ## A genuinely unbounded instance: multiplication on `ℓ²(ℤ)` -/

section Concrete

open BookProof.ChapterUnboundedPosition BookProof.ChapterUnitaryTransport
open BookProof.ChapterContinuityUnitaryInfinite (L2Z)

/-- A basis vector rescaled: `δ_k c = c • δ_k 1`. -/
theorem lp_single_eq_smul (k : ℤ) (c : ℂ) :
    (lp.single 2 k c : L2Z) = c • lp.single 2 k (1 : ℂ) := by
  ext j
  by_cases h : j = k <;> simp [lp.single_apply, h]

/-- **`ℓ²(ℤ)` is separable**: the span of the countably many basis vectors is dense. -/
instance separableSpace_L2Z : TopologicalSpace.SeparableSpace L2Z := by
  rw [← TopologicalSpace.isSeparable_univ_iff]
  have hcount : (Set.range (fun k : ℤ => (lp.single 2 k (1 : ℂ) : L2Z))).Countable :=
    Set.countable_range _
  refine (TopologicalSpace.isSeparable_closure.mpr (hcount.isSeparable.span (R := ℂ))).mono ?_
  intro psi _
  refine mem_closure_of_tendsto (lp.hasSum_single (by norm_num) psi) ?_
  filter_upwards with s
  refine Submodule.sum_mem _ fun i _ => ?_
  rw [lp_single_eq_smul]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

/-- Multiplication by a real field `f` on its natural domain, as an unbounded
self-adjoint operator on the separable Hilbert space `ℓ²(ℤ)`. -/
noncomputable def mulSA (f : ℤ → ℝ) : UnboundedSelfAdjoint L2Z where
  domain := mulDomain f
  op := mulOp f
  denseDomain := mulDomain_dense f
  symmetric := mulOp_symmetric f
  selfAdjoint := mulOp_isSelfAdjointOn f

/-- The position operator is a genuinely unbounded self-adjoint operator. -/
theorem mulSA_position_unbounded :
    ¬ ∃ C : ℝ, ∀ x : (mulSA positionField).domain,
      ‖(mulSA positionField).op x‖ ≤ C * ‖(x : L2Z)‖ :=
  position_unbounded

/-- The phase group as a family of bounded operators: `(U t ψ)_k = e^{-i t f k} ψ_k`. -/
noncomputable def phaseCLM (f : ℤ → ℝ) (t : ℝ) : L2Z →L[ℂ] L2Z :=
  (phaseUnitary f (-t)).toLinearIsometry.toContinuousLinearMap

@[simp] theorem phaseCLM_apply (f : ℤ → ℝ) (t : ℝ) (psi : L2Z) :
    phaseCLM f t psi = phaseUnitary f (-t) psi := rfl

/-- The phase group is strongly continuous in `t`, not merely at `0`. -/
theorem continuous_phaseUnitary (f : ℤ → ℝ) (psi : L2Z) :
    Continuous fun t : ℝ => (phaseUnitary f t psi : L2Z) := by
  refine continuous_iff_continuousAt.mpr fun t₀ => ?_
  have hshift : Tendsto (fun s : ℝ => (phaseUnitary f t₀ (phaseUnitary f s psi) : L2Z)) (𝓝 0)
      (𝓝 (phaseUnitary f t₀ psi)) :=
    ((phaseUnitary f t₀).continuous.tendsto psi).comp (tendsto_phaseUnitary f psi)
  have hcomp : Tendsto (fun t : ℝ => t - t₀) (𝓝 t₀) (𝓝 0) := by
    have h : Tendsto (fun t : ℝ => t - t₀) (𝓝 t₀) (𝓝 (t₀ - t₀)) :=
      (continuous_id.sub continuous_const).tendsto t₀
    simpa using h
  refine (hshift.comp hcomp).congr fun t => ?_
  simp only [Function.comp_apply]
  rw [← phaseUnitary_add]
  ring_nf

/-- The phase group, as a weakly measurable one-parameter unitary group. -/
noncomputable def phaseGroup (f : ℤ → ℝ) : WeakMeasurableUnitaryGroup L2Z where
  U := phaseCLM f
  map_zero := by
    refine ContinuousLinearMap.ext fun psi => ?_
    change phaseUnitary f (-0) psi = psi
    rw [neg_zero]
    exact phaseUnitary_zero f psi
  map_add := by
    intro s t
    refine ContinuousLinearMap.ext fun psi => ?_
    change phaseUnitary f (-(s + t)) psi = phaseUnitary f (-s) (phaseUnitary f (-t) psi)
    rw [show -(s + t) = -s + -t by ring]
    exact phaseUnitary_add f (-s) (-t) psi
  norm_map := fun t psi => (phaseUnitary f (-t)).norm_map psi
  weaklyMeasurable := by
    intro x y
    have hc : Continuous fun t : ℝ => ⟪ y, phaseCLM f t x ⟫_ℂ :=
      continuous_const.inner ((continuous_phaseUnitary f x).comp continuous_neg)
    exact hc.measurable

/-- The phase group solves Schrödinger's equation for the multiplication operator. -/
theorem hasDerivAt_phaseGroup (f : ℤ → ℝ) (x : (mulSA f).domain) :
    HasDerivAt (fun t : ℝ => (phaseGroup f).U t (x : L2Z))
      ((-Complex.I) • (mulSA f).op x) 0 := by
  have hd : HasDerivAt (fun t : ℝ => (phaseUnitary f t (x : L2Z) : L2Z))
      (Complex.I • mulOp f x) (-0 : ℝ) := by
    rw [neg_zero, hasDerivAt_iff_tendsto_slope]
    refine (tendsto_slope_phaseUnitary f x).congr fun t => ?_
    simp [slope, phaseLin_zero]
  have hneg : HasDerivAt (fun t : ℝ => -t) (-1 : ℝ) 0 := by
    simpa using hasDerivAt_neg (0 : ℝ)
  simpa [neg_smul] using hd.scomp (0 : ℝ) hneg

/-- **The Stone group of lattice multiplication is the explicit phase group**:
`e^{-it f̂} ψ = (k ↦ e^{-i t f k} ψ_k)`.  In particular Stone's theorem, applied to the
unbounded position operator, returns the expected dynamics. -/
theorem stoneU_mulSA (f : ℤ → ℝ) (t : ℝ) (psi : L2Z) :
    (mulSA f).stoneU t psi = phaseUnitary f (-t) psi := by
  have h := eq_stoneU_of_hasDerivAt (mulSA f) (phaseGroup f) (hasDerivAt_phaseGroup f) t
  exact congrArg (fun L : L2Z →L[ℂ] L2Z => L psi) h.symm

end Concrete

end BookProof.ChapterStoneSeparable

/-! ## Axiom audit -/

section Audit

open BookProof.ChapterStoneTheorem

#print axioms BookProof.ChapterStoneSeparable.stone_exists_unique_group
#print axioms BookProof.ChapterStoneSeparable.stone_exists_unique_generator
#print axioms BookProof.ChapterStoneSeparable.stoneEquiv
#print axioms BookProof.ChapterStoneSeparable.stoneU_mulSA
#print axioms BookProof.ChapterStoneTheorem.stone_bijection

end Audit
