import Mathlib
import BookProof.ChapterA3

/-!
# The commutant of the concrete `4×4` gamma matrices is scalar

`BookProof.ChapterA3b` uses **Pauli's fundamental theorem of the γ-matrices** as
an `EXTERNAL` named hypothesis.  For the *fixed* `4×4` Majorana model built in
`BookProof.ChapterA3` the relevant instance of that theorem — the statement that
the commutant of the four matrices `iγ^μ` consists of scalars only, i.e. the
representation is irreducible — is a finite computation, and this file proves it.

* `gamma_commutant_scalar` — any complex `4×4` matrix commuting with all four
  `iγ^μ` equals `X 0 0 • 1`;
* `gamma_commutant_eq_scalars` — the commutant of the gamma matrices is exactly
  the set of scalar matrices;
* `gamma_intertwiner_unique` — the uniqueness statement in the form used by the
  chapter: two matrices intertwining the same way differ by a scalar factor.

The proof is elementary: `iγ¹` and `iγ⁰ iγ²` are diagonal matrices whose joint
eigenvalue pattern separates all four basis vectors, which forces a commuting
matrix to be diagonal; the off-diagonal gammas `iγ⁰` and `iγ³` then identify all
four diagonal entries.

Everything is `sorry`-free and `axiom`-free (only `propext`, `Classical.choice`,
`Quot.sound`).
-/

open Matrix

namespace BookProof.ChapterGammaCommutant

open BookProof.ChapterA3

private theorem diag_of_int {d : Fin 4 → ℤ} {M : Matrix (Fin 4) (Fin 4) ℤ}
    (h : M = Matrix.diagonal d) :
    (Int.castRingHom ℂ).mapMatrix M = Matrix.diagonal (fun i => ((d i : ℤ) : ℂ)) := by
  subst h
  ext i j
  by_cases hij : i = j <;> simp [RingHom.mapMatrix_apply, Matrix.map_apply, hij]

private theorem offdiag_zero_of_commutes_diagonal (X : Matrix (Fin 4) (Fin 4) ℂ) (d : Fin 4 → ℂ)
    (hcomm : X * Matrix.diagonal d = Matrix.diagonal d * X) {i j : Fin 4} (hij : d i ≠ d j) :
    X i j = 0 := by
  have h := congr_fun₂ hcomm i j
  rw [Matrix.mul_diagonal, Matrix.diagonal_mul] at h
  have hz : X i j * (d j - d i) = 0 := by rw [mul_sub, h]; ring
  rcases mul_eq_zero.1 hz with h1 | h2
  · exact h1
  · exact absurd (sub_eq_zero.1 h2).symm hij

/-- **Pauli's theorem for the fixed `4×4` model (irreducibility).**  Every
complex `4×4` matrix commuting with all four Majorana matrices `iγ^μ` is a
scalar multiple of the identity. -/
theorem gamma_commutant_scalar (X : Matrix (Fin 4) (Fin 4) ℂ)
    (h : ∀ μ, X * mgamma μ = mgamma μ * X) :
    X = X 0 0 • (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
  -- Two diagonal elements of the algebra generated by the gammas.
  have hd1 : mgamma 1 = Matrix.diagonal (fun i => ((![1, -1, -1, 1] i : ℤ) : ℂ)) := by
    rw [mgamma]; exact diag_of_int (by decide)
  have hd2 : mgamma 0 * mgamma 2 = Matrix.diagonal (fun i => ((![1, 1, -1, -1] i : ℤ) : ℂ)) := by
    rw [mgamma, mgamma, ← map_mul]; exact diag_of_int (by decide)
  have hc1 : X * Matrix.diagonal (fun i => ((![1, -1, -1, 1] i : ℤ) : ℂ))
      = Matrix.diagonal (fun i => ((![1, -1, -1, 1] i : ℤ) : ℂ)) * X := by
    rw [← hd1]; exact h 1
  have hc2 : X * Matrix.diagonal (fun i => ((![1, 1, -1, -1] i : ℤ) : ℂ))
      = Matrix.diagonal (fun i => ((![1, 1, -1, -1] i : ℤ) : ℂ)) * X := by
    rw [← hd2, ← Matrix.mul_assoc, h 0, Matrix.mul_assoc, h 2, ← Matrix.mul_assoc]
  -- The joint eigenvalue pattern separates the four basis vectors, so `X` is diagonal.
  have hoff : ∀ i j : Fin 4, i ≠ j → X i j = 0 := by
    intro i j hij
    fin_cases i <;> fin_cases j
    · exact absurd rfl hij
    · exact offdiag_zero_of_commutes_diagonal X _ hc1 (by norm_num)
    · exact offdiag_zero_of_commutes_diagonal X _ hc1 (by norm_num)
    · exact offdiag_zero_of_commutes_diagonal X _ hc2 (by norm_num)
    · exact offdiag_zero_of_commutes_diagonal X _ hc1 (by norm_num)
    · exact absurd rfl hij
    · exact offdiag_zero_of_commutes_diagonal X _ hc2 (by norm_num)
    · exact offdiag_zero_of_commutes_diagonal X _ hc1 (by norm_num)
    · exact offdiag_zero_of_commutes_diagonal X _ hc1 (by norm_num)
    · exact offdiag_zero_of_commutes_diagonal X _ hc2 (by norm_num)
    · exact absurd rfl hij
    · exact offdiag_zero_of_commutes_diagonal X _ hc1 (by norm_num)
    · exact offdiag_zero_of_commutes_diagonal X _ hc2 (by norm_num)
    · exact offdiag_zero_of_commutes_diagonal X _ hc1 (by norm_num)
    · exact offdiag_zero_of_commutes_diagonal X _ hc1 (by norm_num)
    · exact absurd rfl hij
  -- A nonzero entry of a commuting matrix identifies two diagonal entries of `X`.
  have hentry : ∀ M : Matrix (Fin 4) (Fin 4) ℂ, X * M = M * X → ∀ i j : Fin 4, M i j ≠ 0 →
      X i i = X j j := by
    intro M hM i j hMij
    have hsum1 : ∑ k, X i k * M k j = X i i * M i j :=
      Finset.sum_eq_single i (fun k _ hk => by rw [hoff i k (Ne.symm hk), zero_mul]) (by simp)
    have hsum2 : ∑ k, M i k * X k j = M i j * X j j :=
      Finset.sum_eq_single j (fun k _ hk => by rw [hoff k j hk, mul_zero]) (by simp)
    have hij := congr_fun₂ hM i j
    rw [Matrix.mul_apply, Matrix.mul_apply, hsum1, hsum2] at hij
    exact mul_right_cancel₀ hMij (by rw [hij]; ring)
  have e02 : X 0 0 = X 2 2 :=
    hentry _ (h 0) 0 2 (by simp [mgamma, mgammaZ, RingHom.mapMatrix_apply, Matrix.map_apply])
  have e01 : X 0 0 = X 1 1 :=
    hentry _ (h 3) 0 1 (by simp [mgamma, mgammaZ, RingHom.mapMatrix_apply, Matrix.map_apply])
  have e13 : X 1 1 = X 3 3 :=
    hentry _ (h 0) 1 3 (by simp [mgamma, mgammaZ, RingHom.mapMatrix_apply, Matrix.map_apply])
  ext i j
  by_cases hij : i = j
  · subst hij
    fin_cases i <;>
      simp [← e01, ← e02, ← e13]
  · rw [hoff i j hij]
    simp [hij]

/-- The commutant of the four Majorana matrices is exactly the set of scalar
matrices. -/
theorem gamma_commutant_eq_scalars :
    {X : Matrix (Fin 4) (Fin 4) ℂ | ∀ μ, X * mgamma μ = mgamma μ * X}
      = {X | ∃ c : ℂ, X = c • (1 : Matrix (Fin 4) (Fin 4) ℂ)} := by
  ext X
  constructor
  · intro hX
    exact ⟨X 0 0, gamma_commutant_scalar X hX⟩
  · rintro ⟨c, rfl⟩ μ
    rw [Matrix.smul_mul, Matrix.mul_smul, Matrix.one_mul, Matrix.mul_one]

/-- Uniqueness of intertwiners: if `S` and `T` both conjugate the gamma matrices
in the same way and `S` is invertible, then `T` is a scalar multiple of `S`. -/
theorem gamma_intertwiner_unique (S T : Matrix (Fin 4) (Fin 4) ℂ) (hS : IsUnit S.det)
    (hSg : ∀ μ, S * mgamma μ = mgamma μ * S) (hTg : ∀ μ, T * mgamma μ = mgamma μ * T) :
    ∃ c : ℂ, T = c • S := by
  obtain ⟨cS, hcS⟩ : ∃ c : ℂ, S = c • (1 : Matrix (Fin 4) (Fin 4) ℂ) :=
    ⟨S 0 0, gamma_commutant_scalar S hSg⟩
  obtain ⟨cT, hcT⟩ : ∃ c : ℂ, T = c • (1 : Matrix (Fin 4) (Fin 4) ℂ) :=
    ⟨T 0 0, gamma_commutant_scalar T hTg⟩
  have hcS0 : cS ≠ 0 := by
    rintro rfl
    rw [zero_smul] at hcS
    subst hcS
    rw [Matrix.det_zero (⟨0⟩ : Nonempty (Fin 4))] at hS
    exact absurd hS not_isUnit_zero
  refine ⟨cT / cS, ?_⟩
  rw [hcT, hcS, smul_smul, div_mul_cancel₀ _ hcS0]

end BookProof.ChapterGammaCommutant
