import Mathlib
import BookProof.ChapterSirkTrotterKato
import BookProof.ChapterHermiteGalerkinFriedrichs

/-!
# Chapter SirkTrotterKatoGalerkin — the Galerkin flows converge to the selected flow

`ChapterSirkTrotterKato` proves the Trotter–Kato transfer for the unbounded
self-adjoint operators of `ChapterStoneResolvent`, from strong convergence of the
resolvents.  `ChapterHermiteGalerkinFriedrichs` proves exactly such a convergence
for the Galerkin/Rayleigh–Ritz truncations, in the regime where the operator is
bounded on its domain.  This module joins the two, and so closes the last link of
the reliability chain in that regime:

> the unitary flows generated by the Galerkin compressions converge to the flow
> generated by the selected extension, uniformly on bounded time intervals.

* `ofBounded` — a bounded self-adjoint operator as an `UnboundedSelfAdjoint` with
  full domain, with `resCLM_ofBounded` identifying its resolvent at `i` with
  `−(i − A)⁻¹` (the `resolvent` of Mathlib evaluated at `i`).
* `strongResolventConvergence_ofBounded` — strong convergence of bounded
  self-adjoint operators gives the hypothesis of Trotter–Kato.
* `flow_transfer_of_strong_tendsto` — hence their flows converge, uniformly in
  `t` on `[−T₀, T₀]`, and `flow_tendsto_of_strong_tendsto` pointwise in `t`.
* `galerkin_flow_transfer` — the instance for the Galerkin compressions
  `Pₘ A Pₘ` of a bounded self-adjoint `A` in a Hilbert basis, and
  `galerkin_flow_tendsto`.

## Honest boundary

As in `ChapterHermiteGalerkinFriedrichs`, the identification of the Galerkin
limit with the selected (Friedrichs) extension carries a boundedness hypothesis;
the Trotter–Kato theorem of `ChapterSirkTrotterKato` itself does not, and applies
to any family of unbounded self-adjoint operators whose resolvents converge
strongly.

Everything is `sorry`-free and `axiom`-free (only `propext`, `Classical.choice`,
`Quot.sound`).
-/

noncomputable section

open Filter Topology

namespace BookProof.ChapterSirkTrotterKato

open BookProof.ChapterStoneResolvent BookProof.ChapterUnitaryTransport

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-! ## 1. A bounded self-adjoint operator as an unbounded one -/

/-- A bounded self-adjoint operator, viewed as an unbounded self-adjoint operator
with full domain. -/
def ofBounded (A : H →L[ℂ] H) (hA : IsSelfAdjoint A) : UnboundedSelfAdjoint H where
  domain := ⊤
  op := (A : H →ₗ[ℂ] H) ∘ₗ (⊤ : Submodule ℂ H).subtype
  denseDomain := by simp
  symmetric := by
    intro psi phi
    exact (ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric.mp hA) _ _
  selfAdjoint := by
    apply Set.Subset.antisymm
    · intro phi _
      simp
    · intro phi _
      exact ⟨A phi, fun psi => (ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric.mp hA) _ _⟩

@[simp] theorem ofBounded_op (A : H →L[ℂ] H) (hA : IsSelfAdjoint A) (x : H)
    (hx : x ∈ (ofBounded A hA).domain) : (ofBounded A hA).op ⟨x, hx⟩ = A x := rfl

/-- The resolvent of `ofBounded A` at `1` is `−(i − A)⁻¹`: the two sign
conventions (`A − il` here, `z − A` in Mathlib's `resolvent`) differ by a sign. -/
theorem resCLM_ofBounded (A : H →L[ℂ] H) (hA : IsSelfAdjoint A) (y : H) :
    (ofBounded A hA).resCLM 1 y = -(resolvent A Complex.I y) := by
  have hz : (Complex.I).im ≠ 0 := by simp
  have h := BookProof.HermiteGalerkin.sub_resolvent_apply A hA hz y
  rw [Algebra.algebraMap_eq_smul_one] at h
  simp only [ContinuousLinearMap.sub_apply, ContinuousLinearMap.smul_apply,
    ContinuousLinearMap.one_apply] at h
  set r : H := resolvent A Complex.I y with hr
  set x : H := -r with hx
  have hxmem : x ∈ (ofBounded A hA).domain := by simp [ofBounded]
  have hop : (ofBounded A hA).op ⟨x, hxmem⟩ = A x := rfl
  have hshift : (ofBounded A hA).shift 1 ⟨x, hxmem⟩ = y := by
    rw [UnboundedSelfAdjoint.shift_apply, hop]
    calc A x - ((1 : ℂ) * Complex.I) • x = Complex.I • r - A r := by
          rw [hx, map_neg]; module
      _ = y := h
  have hres := (ofBounded A hA).res_shift (l := 1) one_ne_zero ⟨x, hxmem⟩
  rw [hshift] at hres
  simpa using congrArg (fun (u : (ofBounded A hA).domain) => (u : H)) hres

/-! ## 2. Strong convergence of bounded generators feeds Trotter–Kato -/

/-- **Strong convergence of bounded self-adjoint operators gives strong resolvent
convergence** in the sense the Trotter–Kato theorem consumes. -/
theorem strongResolventConvergence_ofBounded {A : ℕ → H →L[ℂ] H} {Alim : H →L[ℂ] H}
    (hA : ∀ n, IsSelfAdjoint (A n)) (hlim : IsSelfAdjoint Alim)
    (hconv : ∀ u : H, Tendsto (fun n => A n u) atTop (𝓝 (Alim u))) :
    StrongResolventConvergence (ofBounded Alim hlim) (fun n => ofBounded (A n) (hA n)) := by
  intro y
  have hz : (Complex.I).im ≠ 0 := by simp
  have h := BookProof.HermiteGalerkin.resolvent_tendsto_of_strong_tendsto A Alim hA hlim hz hconv y
  have h' := h.neg
  simp only [resCLM_ofBounded]
  exact h'

/-- **The flows of strongly convergent bounded self-adjoint generators converge**,
uniformly on every bounded time interval. -/
theorem flow_transfer_of_strong_tendsto {A : ℕ → H →L[ℂ] H} {Alim : H →L[ℂ] H}
    (hA : ∀ n, IsSelfAdjoint (A n)) (hlim : IsSelfAdjoint Alim)
    (hconv : ∀ u : H, Tendsto (fun n => A n u) atTop (𝓝 (Alim u))) (v : H)
    {T₀ : ℝ} (hT₀ : 0 ≤ T₀) :
    TendstoUniformlyOn (fun n t => (ofBounded (A n) (hA n)).stoneU t v)
      (fun t => (ofBounded Alim hlim).stoneU t v) atTop (Set.Icc (-T₀) T₀) :=
  trotterKato_tendstoUniformlyOn _ _ (strongResolventConvergence_ofBounded hA hlim hconv) v hT₀

/-- The same, pointwise in `t`. -/
theorem flow_tendsto_of_strong_tendsto {A : ℕ → H →L[ℂ] H} {Alim : H →L[ℂ] H}
    (hA : ∀ n, IsSelfAdjoint (A n)) (hlim : IsSelfAdjoint Alim)
    (hconv : ∀ u : H, Tendsto (fun n => A n u) atTop (𝓝 (Alim u))) (v : H) (t : ℝ) :
    Tendsto (fun n => (ofBounded (A n) (hA n)).stoneU t v) atTop
      (𝓝 ((ofBounded Alim hlim).stoneU t v)) :=
  trotterKato_tendsto _ _ (strongResolventConvergence_ofBounded hA hlim hconv) v t

/-! ## 3. The Galerkin instance -/

open BookProof.HermiteGalerkin

/-- **The Galerkin flows converge to the flow of the selected generator.**  For a
bounded self-adjoint `A` and a Hilbert basis `b`, the unitary groups generated by
the Galerkin compressions `Pₘ A Pₘ` converge to the unitary group generated by
`A`, uniformly for `t` in a bounded interval. -/
theorem galerkin_flow_transfer {A : H →L[ℂ] H} (hA : IsSelfAdjoint A)
    (b : HilbertBasis ℕ ℂ H) (v : H) {T₀ : ℝ} (hT₀ : 0 ≤ T₀) :
    TendstoUniformlyOn
      (fun m t => (ofBounded (galerkinCompression A b m)
        (isSelfAdjoint_galerkinCompression hA b m)).stoneU t v)
      (fun t => (ofBounded A hA).stoneU t v) atTop (Set.Icc (-T₀) T₀) :=
  flow_transfer_of_strong_tendsto (fun m => isSelfAdjoint_galerkinCompression hA b m) hA
    (galerkinCompression_tendsto A b) v hT₀

/-- The Galerkin flow convergence, pointwise in `t`. -/
theorem galerkin_flow_tendsto {A : H →L[ℂ] H} (hA : IsSelfAdjoint A)
    (b : HilbertBasis ℕ ℂ H) (v : H) (t : ℝ) :
    Tendsto (fun m => (ofBounded (galerkinCompression A b m)
      (isSelfAdjoint_galerkinCompression hA b m)).stoneU t v) atTop
      (𝓝 ((ofBounded A hA).stoneU t v)) :=
  flow_tendsto_of_strong_tendsto (fun m => isSelfAdjoint_galerkinCompression hA b m) hA
    (galerkinCompression_tendsto A b) v t

end BookProof.ChapterSirkTrotterKato
