import Mathlib
import BookProof.ChapterCyclicDecomposition

/-!
# The cyclic decomposition as a Hilbert sum (plan GAP-2, the direct-sum form)

`ChapterCyclicDecomposition` produced, for a normal operator `T` on a complex
Hilbert space, a family `S` of unit vectors whose cyclic subspaces are pairwise
orthogonal and jointly dense.  This module packages that family as an honest
**orthogonal direct sum decomposition** of the space and records the operator-level
consequence: the orthogonal projections onto the summands commute with the whole
functional-calculus algebra, so `T` really is the direct sum of its restrictions.

* `orthogonalFamily_cyclicSubspace` — the cyclic subspaces of an orthogonal cyclic
  family form an `OrthogonalFamily`;
* `isHilbertSum_cyclicSubspace`, `cyclicHilbertEquiv` — when they are moreover
  total, `H` *is* their Hilbert sum: a unitary `H ≃ₗᵢ[ℂ] lp (cyclic summands) 2`;
* HEADLINE `exists_isHilbertSum_cyclicSubspace` — combining with
  `exists_cyclic_decomposition`, for **every** normal `T` such a family exists, so
  every complex Hilbert space is the Hilbert sum of subspaces cyclic for `T`;
* `starProjection_commutes_cfcHom`, `commute_starProjection_cfcHom` — the
  orthogonal projection onto an invariant subspace commutes with `f(T)` for every
  continuous `f` (the `*`-closedness of the algebra makes the complement invariant
  too), hence lies in the commutant of the algebra generated by `T`;
* `starProjection_cyclicSubspace_commutes`, `hasSum_starProjection_cyclicSubspace` —
  the same for the cyclic summands, together with the strong convergence
  `∑ₓ Pₓ v = v` of the projections of the decomposition.

Everything is `sorry`-free and `axiom`-free (only `propext`, `Classical.choice`,
`Quot.sound`).
-/

noncomputable section

open MeasureTheory Complex

namespace BookProof.ChapterCyclicDirectSum

open BookProof.ChapterCyclicDecomposition

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (T : H →L[ℂ] H) (hT : IsStarNormal T)

/-! ## 1. The summands are complete -/

instance instCompleteSpaceCyclicSubspace (xi : H) :
    CompleteSpace (cyclicSubspace T hT xi) :=
  (isClosed_cyclicSubspace T hT xi).completeSpace_coe

/-! ## 2. The Hilbert sum -/

/-- The cyclic subspaces of an orthogonal cyclic family are an orthogonal family of
subspaces in the sense of `OrthogonalFamily`. -/
theorem orthogonalFamily_cyclicSubspace {S : Set H} (hS : OrthogonalCyclicFamily T hT S) :
    OrthogonalFamily ℂ (fun x : S => (cyclicSubspace T hT (x : H)))
      (fun x : S => (cyclicSubspace T hT (x : H)).subtypeₗᵢ) := by
  refine OrthogonalFamily.of_pairwise ?_
  intro x y hxy
  refine Submodule.isOrtho_iff_le.2 ?_
  exact hS.2 (x : H) x.2 (y : H) y.2 (Subtype.coe_injective.ne hxy)

/-- **`H` is the Hilbert sum of the cyclic subspaces** of a total orthogonal cyclic
family. -/
theorem isHilbertSum_cyclicSubspace {S : Set H} (hS : OrthogonalCyclicFamily T hT S)
    (htop : (⨆ x ∈ S, cyclicSubspace T hT x).topologicalClosure = ⊤) :
    IsHilbertSum ℂ (fun x : S => (cyclicSubspace T hT (x : H)))
      (fun x : S => (cyclicSubspace T hT (x : H)).subtypeₗᵢ) := by
  refine IsHilbertSum.mkInternal _ (orthogonalFamily_cyclicSubspace T hT hS) ?_
  have hsup : (⨆ x : S, cyclicSubspace T hT (x : H)) = ⨆ x ∈ S, cyclicSubspace T hT x := by
    rw [iSup_subtype]
  rw [hsup, htop]

/-- The unitary identification of `H` with the `ℓ²`-sum of the cyclic subspaces. -/
def cyclicHilbertEquiv {S : Set H} (hS : OrthogonalCyclicFamily T hT S)
    (htop : (⨆ x ∈ S, cyclicSubspace T hT x).topologicalClosure = ⊤) :
    H ≃ₗᵢ[ℂ] lp (fun x : S => (cyclicSubspace T hT (x : H))) 2 :=
  (isHilbertSum_cyclicSubspace T hT hS htop).linearIsometryEquiv

include hT in
/-- **HEADLINE.**  For every normal operator on a complex Hilbert space the space is
the Hilbert sum of a family of subspaces each of which is cyclic for the operator:
the general case of the spectral model is the direct sum of cyclic cases. -/
theorem exists_isHilbertSum_cyclicSubspace :
    ∃ S : Set H, OrthogonalCyclicFamily T hT S ∧
      IsHilbertSum ℂ (fun x : S => (cyclicSubspace T hT (x : H)))
        (fun x : S => (cyclicSubspace T hT (x : H)).subtypeₗᵢ) := by
  obtain ⟨S, hS, htop⟩ := exists_cyclic_decomposition T hT
  exact ⟨S, hS, isHilbertSum_cyclicSubspace T hT hS htop⟩

/-! ## 3. The projections lie in the commutant -/

/-- **The orthogonal projection onto an invariant subspace commutes with the
functional calculus.**  Invariance of the subspace gives one half; invariance of the
orthogonal complement — which holds because the algebra is `*`-closed — gives the
other. -/
theorem starProjection_commutes_cfcHom {M : Submodule ℂ H} [M.HasOrthogonalProjection]
    (hM : Invariant T hT M) (g : C(spectrum ℂ T, ℂ)) (v : H) :
    M.starProjection (cfcHom hT g v) = cfcHom hT g (M.starProjection v) := by
  refine Submodule.eq_starProjection_of_mem_orthogonal'
    (hM g _ (M.starProjection_apply_mem v))
    (invariant_orthogonal T hT hM g _ (M.sub_starProjection_mem_orthogonal v)) ?_
  rw [← map_add]
  congr 1
  abel

/-- The operator form: the projection onto an invariant subspace lies in the
commutant of the algebra generated by `T`. -/
theorem commute_starProjection_cfcHom {M : Submodule ℂ H} [M.HasOrthogonalProjection]
    (hM : Invariant T hT M) (g : C(spectrum ℂ T, ℂ)) :
    Commute M.starProjection (cfcHom hT g) := by
  ext v
  simpa [ContinuousLinearMap.mul_apply] using starProjection_commutes_cfcHom T hT hM g v

/-- The projections onto the cyclic summands commute with the functional calculus. -/
theorem starProjection_cyclicSubspace_commutes (xi : H) (g : C(spectrum ℂ T, ℂ)) :
    Commute (cyclicSubspace T hT xi).starProjection (cfcHom hT g) :=
  commute_starProjection_cfcHom T hT (invariant_cyclicSubspace T hT xi) g

omit [CompleteSpace H] in
/-- If a vector is the (unconditional) sum of vectors taken from the members of an
orthogonal family of subspaces, then those vectors *are* its orthogonal
projections. -/
theorem starProjection_eq_of_hasSum {ι : Type*} {V : ι → Submodule ℂ H}
    [∀ i, (V i).HasOrthogonalProjection]
    (hV : OrthogonalFamily ℂ (fun i => (V i)) fun i => (V i).subtypeₗᵢ)
    {c : ι → H} (hc : ∀ i, c i ∈ V i) {v : H} (h : HasSum c v) (j : ι) :
    (V j).starProjection v = c j := by
  classical
  have hstep : ∀ i, (V j).starProjection (c i) = if i = j then c j else 0 := by
    intro i
    by_cases hij : i = j
    · subst hij
      simp [Submodule.starProjection_eq_self_iff.2 (hc i)]
    · have hzero : (V j).starProjection (c i) = 0 := by
        have hmem : c i ∈ (V j)ᗮ :=
          Submodule.isOrtho_iff_le.1 (hV.isOrtho hij) (hc i)
        exact Submodule.eq_starProjection_of_mem_orthogonal' (V j).zero_mem hmem (by simp)
      simp [hij, hzero]
  have h1 : HasSum (fun i => (V j).starProjection (c i)) ((V j).starProjection v) :=
    (V j).starProjection.hasSum h
  have h2 : HasSum (fun i => (V j).starProjection (c i)) (c j) := by
    simpa only [hstep] using hasSum_ite_eq j (c j)
  exact h1.unique h2

/-- The resolution of the identity attached to the decomposition: the projections
onto the cyclic summands sum (unconditionally, in norm) to the vector itself. -/
theorem hasSum_starProjection_cyclicSubspace {S : Set H} (hS : OrthogonalCyclicFamily T hT S)
    (htop : (⨆ x ∈ S, cyclicSubspace T hT x).topologicalClosure = ⊤) (v : H) :
    HasSum (fun x : S => (cyclicSubspace T hT (x : H)).starProjection v) v := by
  have hsum := isHilbertSum_cyclicSubspace T hT hS htop
  have hortho := orthogonalFamily_cyclicSubspace T hT hS
  set w := hsum.linearIsometryEquiv v with hw
  have hv : hsum.linearIsometryEquiv.symm w = v := by
    rw [hw, LinearIsometryEquiv.symm_apply_apply]
  have hHas : HasSum (fun x : S => ((w x : H))) v := by
    have := hsum.hasSum_linearIsometryEquiv_symm w
    rwa [hv] at this
  have hmem : ∀ x : S, ((w x : H)) ∈ cyclicSubspace T hT (x : H) := fun x => (w x).2
  have := starProjection_eq_of_hasSum (V := fun x : S => cyclicSubspace T hT (x : H))
    hortho hmem hHas
  simpa only [this] using hHas

end BookProof.ChapterCyclicDirectSum

end
