import Mathlib
import BookProof.ChapterEnergyBandDecomposition

/-!
# An energy bound on the initial condition forbids a divergent time-derivative

Source: `book.tex`, chapter *"Resolution of the singularity of the ODE x'=x² when the
initial x has uncertainties"*, §*Resolution of the singularity using the uncertainties in x*:

> "A singularity at finite-time in the time-evolution of an initial value problem defined by
> an ordinary differential equation implies that the derivative in time of the corresponding
> wave-function diverges. […] Since the derivative in time corresponds to the Hamiltonian
> (whose spectral measure is conserved by the time-evolution) then if the initial condition
> only involves eigenfunctions corresponding to a spectrum up to some maximum absolute value,
> there is no way in which the time-evolution will produce a divergent derivative in time of
> the wave-function."

This file proves that statement.  As in `BookProof.ChapterEnergyBandDecomposition`, the
Hamiltonian is realized as the multiplication operator by a real *energy* function `E` on
`L²(X, μ)`, so that its unitary group is multiplication by `exp(−i t E(x))` (`evol`).  A state
*obeys the energy bound* `Emax` when it vanishes outside the spectral window `|E| ≤ Emax`
(`EnergyLimited`) — the book's "initial condition only involves eigenfunctions corresponding
to a spectrum up to some maximum absolute value".

## Deliverables

* `norm_evol_apply`, `eLpNorm_evol` — the evolution is pointwise and `L²`-isometric, so the
  state stays normalized at all times;
* `energyLimited_evol` — the energy window is conserved by the evolution (the book's
  "spectral measure is conserved by the time-evolution");
* **`eLpNorm_evol_sub_evol_le`** — the trajectory is **Lipschitz in time** with constant
  `Emax ‖ψ‖`: `‖U(t)ψ − U(s)ψ‖₂ ≤ |t − s| · Emax · ‖ψ‖₂`;
* **`eLpNorm_difference_quotient_le`** — equivalently every difference quotient of the
  trajectory is bounded by `Emax ‖ψ‖`, uniformly in the time step: **the derivative in time
  cannot diverge**, which is exactly the chapter's claim;
* `eLpNorm_evol_sub_self_le` — the special case `s = 0`.

No claim is made that the trajectory is differentiable: the point of the chapter is exactly
that *every* difference quotient stays bounded by `Emax ‖ψ‖`, so no divergence of the time
derivative can occur, whatever the initial state inside the energy window.

Everything is `sorry`-free and uses only the standard axioms.
-/

namespace BookProof.ChapterEnergyBoundedEvolution

open MeasureTheory Complex
open scoped ENNReal
open BookProof.EnergyBandDecomposition

variable {X : Type*} [MeasurableSpace X] {μ : Measure X} {E : X → ℝ} {f : X → ℂ}

/-- The time evolution generated by the energy function `E`: multiplication by
`exp(−i t E(x))`. -/
noncomputable def evol (E : X → ℝ) (t : ℝ) (f : X → ℂ) (x : X) : ℂ :=
  Complex.exp (-(Complex.I * (t * E x))) * f x

/-- A state **obeys the energy bound `Emax`** when it vanishes (almost everywhere) outside the
spectral window `|E| ≤ Emax`. -/
def EnergyLimited (E : X → ℝ) (μ : Measure X) (Emax : ℝ) (f : X → ℂ) : Prop :=
  ∀ᵐ x ∂μ, f x ≠ 0 → |E x| ≤ Emax

omit [MeasurableSpace X] in
@[simp] theorem evol_zero (f : X → ℂ) : evol E 0 f = f := by
  funext x
  simp [evol]

omit [MeasurableSpace X] in
/-- The evolution is a pointwise phase, hence norm-preserving at every point. -/
theorem norm_evol_apply (t : ℝ) (f : X → ℂ) (x : X) : ‖evol E t f x‖ = ‖f x‖ := by
  have h : Complex.exp (-(Complex.I * (t * E x)))
      = Complex.exp (Complex.I * ((-(t * E x) : ℝ) : ℂ)) := by
    congr 1
    push_cast
    ring
  rw [evol, h, norm_mul, Complex.norm_exp_I_mul_ofReal, one_mul]

/-- Consequently the evolution is an isometry of `L²`. -/
theorem eLpNorm_evol (t : ℝ) (f : X → ℂ) (p : ℝ≥0∞) :
    eLpNorm (evol E t f) p μ = eLpNorm f p μ := by
  refine eLpNorm_congr_norm_ae ?_
  exact Filter.Eventually.of_forall fun x => norm_evol_apply t f x

/-- **The energy window is conserved by the time-evolution.** -/
theorem energyLimited_evol {Emax : ℝ} (t : ℝ) (h : EnergyLimited E μ Emax f) :
    EnergyLimited E μ Emax (evol E t f) := by
  filter_upwards [h] with x hx hne
  refine hx fun hf => hne ?_
  simp [evol, hf]

/-- Elementary algebra of a phase split. -/
theorem phase_split {A B C z : ℂ} (h : A * B = C) : C * z - A * z = A * (B * z - z) := by
  rw [← h]; ring

/-- Pointwise Lipschitz estimate inside the energy window. -/
theorem norm_evol_sub_evol_le_ae {Emax : ℝ} (h : EnergyLimited E μ Emax f) (s t : ℝ) :
    ∀ᵐ x ∂μ, ‖evol E t f x - evol E s f x‖ ≤ (|t - s| * Emax) * ‖f x‖ := by
  filter_upwards [h] with x hx
  rcases eq_or_ne (f x) 0 with hf | hf
  · simp [evol, hf]
  · have hE : |E x| ≤ Emax := hx hf
    have hsplit : Complex.exp (-(Complex.I * ((s : ℂ) * (E x : ℂ))))
        * Complex.exp (-(Complex.I * (((t - s : ℝ) : ℂ) * (E x : ℂ))))
        = Complex.exp (-(Complex.I * ((t : ℂ) * (E x : ℂ)))) := by
      rw [← Complex.exp_add]
      congr 1
      push_cast
      ring
    have hfac : evol E t f x - evol E s f x
        = Complex.exp (-(Complex.I * ((s : ℂ) * (E x : ℂ))))
          * (Complex.exp (-(Complex.I * (((t - s : ℝ) : ℂ) * (E x : ℂ)))) * f x - f x) :=
      phase_split hsplit
    rw [hfac, norm_mul]
    have hphase : ‖Complex.exp (-(Complex.I * ((s : ℂ) * (E x : ℂ))))‖ = 1 := by
      have h : Complex.exp (-(Complex.I * ((s : ℂ) * (E x : ℂ))))
          = Complex.exp (Complex.I * ((-(s * E x) : ℝ) : ℂ)) := by
        congr 1
        push_cast
        ring
      rw [h, Complex.norm_exp_I_mul_ofReal]
    rw [hphase, one_mul]
    have hbound := norm_evolution_sub_scalar_le' (ε := Emax) (a := E x) (t - s) 0 (f x)
      (by simpa using hE)
    simpa using hbound

/-- **The trajectory of an energy-limited state is Lipschitz in time**, with constant
`Emax ‖ψ‖`. -/
theorem eLpNorm_evol_sub_evol_le {Emax : ℝ} (h : EnergyLimited E μ Emax f) (s t : ℝ) :
    eLpNorm (evol E t f - evol E s f) 2 μ
      ≤ ENNReal.ofReal (|t - s| * Emax) * eLpNorm f 2 μ :=
  eLpNorm_le_mul_eLpNorm_of_ae_le_mul (norm_evol_sub_evol_le_ae h s t) 2

/-- The special case `s = 0`: the state moves at most `|t| · Emax ‖ψ‖` away from itself. -/
theorem eLpNorm_evol_sub_self_le {Emax : ℝ} (h : EnergyLimited E μ Emax f) (t : ℝ) :
    eLpNorm (evol E t f - f) 2 μ ≤ ENNReal.ofReal (|t| * Emax) * eLpNorm f 2 μ := by
  have := eLpNorm_evol_sub_evol_le h 0 t
  simpa using this

/-- **The derivative in time cannot diverge**: every difference quotient of the trajectory of
an energy-limited state is bounded by `Emax ‖ψ‖`, uniformly in the time step `t ≠ 0`. -/
theorem eLpNorm_difference_quotient_le {Emax : ℝ} (h : EnergyLimited E μ Emax f) {t : ℝ}
    (ht : t ≠ 0) :
    eLpNorm (fun x => (evol E t f x - f x) / t) 2 μ ≤ ENNReal.ofReal Emax * eLpNorm f 2 μ := by
  have hae : ∀ᵐ x ∂μ, ‖(evol E t f x - f x) / t‖ ≤ Emax * ‖f x‖ := by
    filter_upwards [norm_evol_sub_evol_le_ae h 0 t] with x hx
    have htpos : (0 : ℝ) < ‖(t : ℂ)‖ := by
      simpa [Complex.norm_real, Real.norm_eq_abs, abs_pos] using ht
    rw [norm_div, div_le_iff₀ htpos]
    calc ‖evol E t f x - f x‖
        = ‖evol E t f x - evol E 0 f x‖ := by rw [evol_zero]
      _ ≤ (|t - 0| * Emax) * ‖f x‖ := hx
      _ = Emax * ‖f x‖ * ‖(t : ℂ)‖ := by
          simp [Complex.norm_real, Real.norm_eq_abs]
          ring
  exact eLpNorm_le_mul_eLpNorm_of_ae_le_mul hae 2

end BookProof.ChapterEnergyBoundedEvolution
