import Mathlib
import BookProof.ChapterA
import BookProof.ChapterA2
import BookProof.ChapterA2b
import BookProof.ChapterSchurIrreducible

/-!
# Lemma 28 and Lemma 34 — Schur's lemma for unitary representations and for systems of
imprimitivity

Source: `book.tex`, chapter *"Real representations, CPT theorem and the relativistic
position operator"*, §*Schur Systems* (**Lemma 28**, "Schur's lemma for unitary
representations") and §*Systems of Imprimitivity* (**Lemma 34**, "Schur's lemma for systems
of imprimitivity").

Both lemmas are quoted in the book from the representation-theory literature, and the
`FORMALIZATION_ROADMAP.md` gap table lists them as `EXTERNAL` (not available in Mathlib).
`BookProof.ChapterSchurIrreducible` proves the underlying operator-theoretic statement —
the commutant of a topologically irreducible **normal** system is `ℂ · 1` — for an
arbitrary complex Hilbert space.  This file records the two named corollaries, by checking
in each case that the system in question *is* normal (closed under the adjoint):

* a **unitary representation**: the adjoint of `U g` is `U g⁻¹`, again in the system
  (`repSystem_isNormal`), so **Lemma 28** (`schur_unitary_representation`) follows;
* a **system of imprimitivity** `(U, π)`: besides the unitaries, the system contains the
  self-adjoint projections `π A`, which are their own adjoints
  (`imprimitivitySystem_isNormal`), so **Lemma 34** (`schur_imprimitivity`) follows.

Note that the book's proof of Lemma 34 goes through Mackey's imprimitivity theorem; the
proof here does not need it — the covariance relation `U g π A U g⁻¹ = π (g • A)` is not
used at all, only the fact that the generators' adjoints stay inside the system.  The
conclusions are also slightly stronger than the book's: *every* bounded operator commuting
with the system is a scalar, not only every normal one.

Everything is `sorry`-free and `axiom`-free.
-/

open scoped ComplexConjugate InnerProductSpace

namespace BookProof.ChapterSchurRepresentation

open BookProof.ChapterA BookProof.ChapterA.System BookProof.ChapterSchurIrreducible

variable {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℂ V] [CompleteSpace V]

/-! ## Unitaries as bounded operators -/

/-- A `ℂ`-linear isometric equivalence, read as a bounded operator. -/
noncomputable def uCLM (f : V ≃ₗᵢ[ℂ] V) : V →L[ℂ] V :=
  f.toContinuousLinearEquiv.toContinuousLinearMap

omit [CompleteSpace V] in
@[simp] theorem uCLM_apply (f : V ≃ₗᵢ[ℂ] V) (x : V) : uCLM f x = f x := rfl

/-- The adjoint of a unitary is its inverse. -/
theorem adjoint_uCLM (f : V ≃ₗᵢ[ℂ] V) :
    ContinuousLinearMap.adjoint (uCLM f) = uCLM f.symm := by
  refine ((ContinuousLinearMap.eq_adjoint_iff _ _).mpr ?_).symm
  intro x y
  change ⟪f.symm x, y⟫_ℂ = ⟪x, f y⟫_ℂ
  rw [← f.inner_map_map (f.symm x) y, f.apply_symm_apply]

/-! ## Lemma 28 — unitary representations -/

/-- The system of operators of a unitary representation `U : G →* (V ≃ₗᵢ[ℂ] V)`. -/
noncomputable def repSystem {G : Type*} [Group G] (U : G →* (V ≃ₗᵢ[ℂ] V)) : System ℂ V :=
  ⟨{T : V →L[ℂ] V | ∃ g : G, T = uCLM (U g)}⟩

/-- A unitary representation is a **normal** system: the adjoint of `U g` is `U g⁻¹`. -/
theorem repSystem_isNormal {G : Type*} [Group G] (U : G →* (V ≃ₗᵢ[ℂ] V)) :
    (repSystem U).IsNormal := by
  rintro m ⟨g, rfl⟩
  refine ⟨g⁻¹, ?_⟩
  rw [adjoint_uCLM]
  congr 1
  rw [map_inv]
  rfl

/-- **Lemma 28 (Schur's lemma for unitary representations).**  If a unitary representation
of a group on a complex Hilbert space is topologically irreducible, then every bounded
operator commuting with it is a scalar.  (No separability, no finite-dimensionality and no
Lie-group structure are needed.) -/
theorem schur_unitary_representation {G : Type*} [Group G] (U : G →* (V ≃ₗᵢ[ℂ] V))
    (hirr : (repSystem U).IsIrreducible) {S : V →L[ℂ] V}
    (hcomm : ∀ g : G, S * uCLM (U g) = uCLM (U g) * S) :
    ∃ c : ℂ, S = c • (1 : V →L[ℂ] V) :=
  commutant_scalar_of_irreducible (repSystem U) (repSystem_isNormal U) hirr
    (by rintro m ⟨g, rfl⟩; exact hcomm g)

/-- The same statement in the pointwise form used in the book: an operator commuting with
every `U g` (as a map) is multiplication by a complex number. -/
theorem schur_unitary_representation_apply {G : Type*} [Group G] (U : G →* (V ≃ₗᵢ[ℂ] V))
    (hirr : (repSystem U).IsIrreducible) {S : V →L[ℂ] V}
    (hcomm : ∀ (g : G) (x : V), S (U g x) = U g (S x)) :
    ∃ c : ℂ, ∀ x, S x = c • x := by
  obtain ⟨c, hc⟩ := schur_unitary_representation U hirr (S := S) (by
    intro g
    ext x
    simpa [ContinuousLinearMap.mul_apply] using hcomm g x)
  exact ⟨c, fun x => by simpa using congrArg (fun T : V →L[ℂ] V => T x) hc⟩

/-! ## Lemma 34 — systems of imprimitivity -/

/-- The system of operators generated by a pair `(U, π)`: the unitaries `U g` of the
representation together with the self-adjoint projections `π A` of the
projection-valued measure (Def 31/32).  Only the operators matter here; the covariance
relation of Def 32 plays no role in Schur's lemma. -/
noncomputable def imprimitivitySystem {G : Type*} [Group G] {X : Type*}
    (U : G →* (V ≃ₗᵢ[ℂ] V)) (pvm : Set X → (V →L[ℂ] V)) : System ℂ V :=
  ⟨{T : V →L[ℂ] V | (∃ g : G, T = uCLM (U g)) ∨ ∃ A : Set X, T = pvm A}⟩

/-- A system of imprimitivity is a **normal** system: the unitaries have their inverses in
the system and the projections are self-adjoint. -/
theorem imprimitivitySystem_isNormal {G : Type*} [Group G] {X : Type*}
    (U : G →* (V ≃ₗᵢ[ℂ] V)) (pvm : Set X → (V →L[ℂ] V))
    (hpvm : ∀ A : Set X, IsSelfAdjoint (pvm A)) :
    (imprimitivitySystem U pvm).IsNormal := by
  rintro m (⟨g, rfl⟩ | ⟨A, rfl⟩)
  · refine Or.inl ⟨g⁻¹, ?_⟩
    rw [adjoint_uCLM]
    congr 1
    rw [map_inv]
    rfl
  · refine Or.inr ⟨A, ?_⟩
    have := hpvm A
    rw [ContinuousLinearMap.isSelfAdjoint_iff'] at this
    exact this

/-- **Lemma 34 (Schur's lemma for systems of imprimitivity).**  If a system of
imprimitivity `(U, π)` on a complex Hilbert space is topologically irreducible, then every
bounded operator commuting with all the `U g` and all the projections `π A` is a scalar.

The book derives this from Mackey's imprimitivity theorem; here it is a direct consequence
of Schur's lemma for irreducible normal systems, since the generators' adjoints — `U g⁻¹`
and `π A` itself — stay inside the system. -/
theorem schur_imprimitivity {G : Type*} [Group G] {X : Type*}
    (U : G →* (V ≃ₗᵢ[ℂ] V)) (pvm : Set X → (V →L[ℂ] V))
    (hpvm : ∀ A : Set X, IsSelfAdjoint (pvm A))
    (hirr : (imprimitivitySystem U pvm).IsIrreducible) {S : V →L[ℂ] V}
    (hU : ∀ g : G, S * uCLM (U g) = uCLM (U g) * S)
    (hP : ∀ A : Set X, S * pvm A = pvm A * S) :
    ∃ c : ℂ, S = c • (1 : V →L[ℂ] V) :=
  commutant_scalar_of_irreducible (imprimitivitySystem U pvm)
    (imprimitivitySystem_isNormal U pvm hpvm) hirr
    (by
      rintro m (⟨g, rfl⟩ | ⟨A, rfl⟩)
      · exact hU g
      · exact hP A)

end BookProof.ChapterSchurRepresentation
