import Mathlib
import BookProof.ChapterSpectralMultiplication

/-!
# Decomposition into cyclic subspaces (plan GAP-2, the reduction to the cyclic case)

`ChapterSpectralMultiplication` and `ChapterSpectralCommutant` model a normal
operator **with a cyclic vector** — as multiplication by `z` on `L²(μ)`, with
commutant and bicommutant `L∞(μ)`.  The step that reduces the general case to that
one is the classical *cyclic decomposition*: for any normal `T` the space splits as
an orthogonal family of subspaces, each of which is generated by a single vector
under the continuous functional calculus of `T`.

This module proves that decomposition:

* `cyclicSubspace` — the closed subspace generated by `{f(T)ξ : f ∈ C(σ(T))}`;
* `Invariant`, `invariant_cyclicSubspace` — the cyclic subspaces are invariant under
  the whole functional calculus algebra;
* `invariant_orthogonal` — because the algebra is `*`-closed, the orthogonal
  complement of an invariant subspace is invariant, and
  `cyclicSubspace_le_orthogonal` — the cyclic subspace of a vector orthogonal to an
  invariant subspace stays orthogonal to it;
* HEADLINE `exists_cyclic_decomposition` — by Zorn's lemma there is a family of unit
  vectors whose cyclic subspaces are pairwise orthogonal and together span a dense
  subspace of `H`.

Everything is `sorry`-free and `axiom`-free.  What is still not claimed is the
assembly step: transporting the multiplication model of each summand (which requires
identifying the functional calculus of the restriction of `T` to an invariant
subspace with the restriction of the functional calculus) into a single model on a
direct sum of `L²` spaces.
-/

noncomputable section

open MeasureTheory Complex

namespace BookProof.ChapterCyclicDecomposition

open BookProof.ChapterSpectralMultiplication

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (T : H →L[ℂ] H) (hT : IsStarNormal T)

/-! ## 1. Cyclic subspaces -/

/-- **The cyclic subspace generated by a vector**: the closed linear span of the
vectors `f(T)ξ`, `f` continuous on the spectrum. -/
def cyclicSubspace (xi : H) : Submodule ℂ H :=
  (Submodule.span ℂ (Set.range fun g : C(spectrum ℂ T, ℂ) => cfcHom hT g xi)).topologicalClosure

theorem isClosed_cyclicSubspace (xi : H) : IsClosed (cyclicSubspace T hT xi : Set H) :=
  Submodule.isClosed_topologicalClosure _

theorem cfcHom_apply_mem_cyclicSubspace (xi : H) (g : C(spectrum ℂ T, ℂ)) :
    cfcHom hT g xi ∈ cyclicSubspace T hT xi :=
  Submodule.le_topologicalClosure _ (Submodule.subset_span ⟨g, rfl⟩)

theorem self_mem_cyclicSubspace (xi : H) : xi ∈ cyclicSubspace T hT xi := by
  have h := cfcHom_apply_mem_cyclicSubspace T hT xi 1
  rwa [map_one] at h
  
/-! ## 2. Invariance -/

/-- A subspace invariant under the whole continuous functional calculus algebra. -/
def Invariant (M : Submodule ℂ H) : Prop :=
  ∀ (g : C(spectrum ℂ T, ℂ)) (v : H), v ∈ M → cfcHom hT g v ∈ M

theorem invariant_cyclicSubspace (xi : H) : Invariant T hT (cyclicSubspace T hT xi) := by
  intro g v hv
  have hle : Submodule.span ℂ (Set.range fun f : C(spectrum ℂ T, ℂ) => cfcHom hT f xi)
      ≤ (cyclicSubspace T hT xi).comap (cfcHom hT g).toLinearMap := by
    refine Submodule.span_le.mpr ?_
    rintro _ ⟨f, rfl⟩
    have hgf : cfcHom hT g (cfcHom hT f xi) = cfcHom hT (g * f) xi := by
      rw [map_mul]
      rfl
    simp only [SetLike.mem_coe, Submodule.mem_comap, ContinuousLinearMap.coe_coe, hgf]
    exact cfcHom_apply_mem_cyclicSubspace T hT xi (g * f)
  have hclosed : IsClosed
      ((cyclicSubspace T hT xi).comap (cfcHom hT g).toLinearMap : Set H) :=
    (isClosed_cyclicSubspace T hT xi).preimage (cfcHom hT g).continuous
  exact Submodule.topologicalClosure_minimal _ hle hclosed hv

/-- **The orthogonal complement of an invariant subspace is invariant** — this is
where `*`-closedness of the functional calculus algebra enters. -/
theorem invariant_orthogonal {M : Submodule ℂ H} (hM : Invariant T hT M) :
    Invariant T hT Mᗮ := by
  intro g v hv
  rw [Submodule.mem_orthogonal]
  intro u hu
  have hadj : (ContinuousLinearMap.adjoint (cfcHom hT g)) u = cfcHom hT (star g) u := by
    have h : star (cfcHom hT g) = cfcHom hT (star g) := (map_star (cfcHom hT) g).symm
    rw [← ContinuousLinearMap.star_eq_adjoint, h]
  have h0 : (inner ℂ (cfcHom hT (star g) u) v : ℂ) = 0 :=
    (Submodule.mem_orthogonal M v).1 hv _ (hM (star g) u hu)
  rw [← ContinuousLinearMap.adjoint_inner_left, hadj, h0]

/-- The cyclic subspace of a vector orthogonal to an invariant subspace is again
orthogonal to it. -/
theorem cyclicSubspace_le_orthogonal {M : Submodule ℂ H} (hM : Invariant T hT M) {v : H}
    (hv : v ∈ Mᗮ) : cyclicSubspace T hT v ≤ Mᗮ := by
  refine Submodule.topologicalClosure_minimal _ (Submodule.span_le.mpr ?_)
    (Submodule.isClosed_orthogonal M)
  rintro _ ⟨g, rfl⟩
  exact invariant_orthogonal T hT hM g v hv

/-! ## 3. The decomposition -/

/-- The property defining the family we maximize over: a set of unit vectors with
pairwise orthogonal cyclic subspaces. -/
def OrthogonalCyclicFamily (S : Set H) : Prop :=
  (∀ x ∈ S, ‖x‖ = 1) ∧
    ∀ x ∈ S, ∀ y ∈ S, x ≠ y → cyclicSubspace T hT x ≤ (cyclicSubspace T hT y)ᗮ

theorem invariant_iSup_cyclicSubspace (S : Set H) :
    Invariant T hT (⨆ x ∈ S, cyclicSubspace T hT x).topologicalClosure := by
  intro g v hv
  have hle : (⨆ x ∈ S, cyclicSubspace T hT x)
      ≤ ((⨆ x ∈ S, cyclicSubspace T hT x).topologicalClosure).comap
          (cfcHom hT g).toLinearMap := by
    refine iSup_le fun x => iSup_le fun hx => ?_
    intro w hw
    simp only [Submodule.mem_comap, ContinuousLinearMap.coe_coe]
    refine Submodule.le_topologicalClosure _ ?_
    have : cfcHom hT g w ∈ cyclicSubspace T hT x :=
      invariant_cyclicSubspace T hT x g w hw
    exact le_iSup₂ (f := fun x (_ : x ∈ S) => cyclicSubspace T hT x) x hx this
  have hclosed : IsClosed
      (((⨆ x ∈ S, cyclicSubspace T hT x).topologicalClosure).comap
        (cfcHom hT g).toLinearMap : Set H) :=
    (Submodule.isClosed_topologicalClosure _).preimage (cfcHom hT g).continuous
  exact Submodule.topologicalClosure_minimal _ hle hclosed hv

include hT in
/-- **HEADLINE (cyclic decomposition).**  For a normal operator on a complex Hilbert
space there is a family of unit vectors whose cyclic subspaces are pairwise
orthogonal and whose span is dense: the space is the orthogonal direct sum of
cyclic subspaces for `T`. -/
theorem exists_cyclic_decomposition :
    ∃ S : Set H, OrthogonalCyclicFamily T hT S ∧
      (⨆ x ∈ S, cyclicSubspace T hT x).topologicalClosure = ⊤ := by
  obtain ⟨S, hS⟩ :=
    zorn_subset {S : Set H | OrthogonalCyclicFamily T hT S} (fun c hc hchain => by
      refine ⟨⋃₀ c, ⟨?_, ?_⟩, fun s hs => Set.subset_sUnion_of_mem hs⟩
      · rintro x ⟨s, hs, hx⟩
        exact ((hc hs).1) x hx
      · rintro x ⟨s, hs, hx⟩ y ⟨t, ht, hy⟩ hxy
        rcases hchain.total hs ht with h | h
        · exact ((hc ht).2) x (h hx) y hy hxy
        · exact ((hc hs).2) x hx y (h hy) hxy)
  refine ⟨S, hS.1, ?_⟩
  set N : Submodule ℂ H := ⨆ x ∈ S, cyclicSubspace T hT x with hN
  haveI : CompleteSpace N.topologicalClosure :=
    (Submodule.isClosed_topologicalClosure N).completeSpace_coe
  by_contra hne
  have hbot : N.topologicalClosureᗮ ≠ ⊥ := by
    intro h
    exact hne (Submodule.orthogonal_eq_bot_iff.1 h)
  obtain ⟨v, hv, hv0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hbot
  set u : H := ‖v‖⁻¹ • v with hu
  have hnv : ‖v‖ ≠ 0 := norm_ne_zero_iff.2 hv0
  have hunorm : ‖u‖ = 1 := by
    rw [hu, norm_smul]
    simp [hnv]
  have humem : u ∈ N.topologicalClosureᗮ := Submodule.smul_mem _ _ hv
  -- the cyclic subspace of `u` is orthogonal to everything already collected
  have hcyc : cyclicSubspace T hT u ≤ N.topologicalClosureᗮ :=
    cyclicSubspace_le_orthogonal T hT (invariant_iSup_cyclicSubspace T hT S) humem
  have hle : ∀ x ∈ S, cyclicSubspace T hT x ≤ N.topologicalClosure := fun x hx =>
    le_trans (le_iSup₂ (f := fun x (_ : x ∈ S) => cyclicSubspace T hT x) x hx)
      (Submodule.le_topologicalClosure N)
  have hnew : (insert u S) ∈ {S : Set H | OrthogonalCyclicFamily T hT S} := by
    constructor
    · rintro x (rfl | hx)
      · exact hunorm
      · exact hS.1.1 x hx
    · have key : ∀ x ∈ S, cyclicSubspace T hT u ≤ (cyclicSubspace T hT x)ᗮ := fun x hx =>
        le_trans hcyc (Submodule.orthogonal_le (hle x hx))
      have key' : ∀ x ∈ S, cyclicSubspace T hT x ≤ (cyclicSubspace T hT u)ᗮ := fun x hx =>
        le_trans (le_trans (hle x hx) (Submodule.le_orthogonal_orthogonal _))
          (Submodule.orthogonal_le hcyc)
      rintro x (rfl | hx) y (rfl | hy) hxy
      · exact absurd rfl hxy
      · exact key y hy
      · exact key' x hx
      · exact hS.1.2 x hx y hy hxy
  have hnotmem : u ∉ S := by
    intro hmem
    have h1 : u ∈ N.topologicalClosure := hle u hmem (self_mem_cyclicSubspace T hT u)
    have : u = 0 := inner_self_eq_zero.1 ((Submodule.mem_orthogonal _ _).1 humem u h1)
    rw [this] at hunorm
    simp at hunorm
  exact hnotmem (hS.2 hnew (Set.subset_insert u S) (Set.mem_insert u S))

end BookProof.ChapterCyclicDecomposition

end
