import BookProof.ChapterQgBrstCompleted.Part1
import BookProof.ChapterQgBrstCompleted.Part2

/-!
# The bounded BRST charge on the *completed* graded Hilbert space, and its reduced transfer

`CONSOLIDATED_PLAN.md` §10.6.2 item 4 is closed except for one join: the BRST charge of
`ChapterQuantumGravityBrstCharge` is built on the *algebraic* graded space
`ℂ[x₀,…,x₈₃] ⊗ Λ(ℂ¹⁹)`, whereas the reduced-transfer theorems of
`ChapterBrstReducedTransfer` need a **bounded** nilpotent charge on a *complete* space.
This module supplies exactly that missing object and performs the join.

## What is proved

* **A bounded weighted shift calculus on `ℓ²`** (`wshift`).  For a weight `w` with
  `‖w i‖ ≤ 1` and a reindexing `e` that is injective on the support of `w`, the map
  `f ↦ (i ↦ w i * f (e i))` is a bounded operator of norm `≤ 1` on `ℓ²(ι)`
  (`memlp_weighted`, `wshiftL_norm_le`).  This is the analytic content: the pullback of a
  square-summable family along a partially injective reindexing stays square-summable.
* **The ghost creation operators on the completed graded space.**  On
  `QGH = ℓ²(GradedIdx)` — the completion of the graded Fock space of
  `ChapterQuantumGravityFock`, `GradedIdx = BoseConf × FermConf` — the operator
  `brstTerm sym a` is `Ψ†_a` dressed with a bounded boson-sector constraint symbol
  `sym a : BoseConf → ℂ`.  It is bounded by `1` and satisfies the Jordan–Wigner
  anticommutation relations `brstTerm_comp_self` (`(Ψ†_a)² = 0`) and `brstTerm_anticomm`
  (`Ψ†_aΨ†_b + Ψ†_bΨ†_a = 0`).
* **The bounded nilpotent BRST charge** `qgBrstCharge sym = ∑_{a<19} sym_a Ψ†_a` over the
  book's `19` diffeomorphism ghosts: `qgBrstCharge_nilpotent` (`Ω² = 0`) and
  `qgBrstCharge_ne_zero` (it is not the zero operator, so the statement is not vacuous).
* **An explicit unitary group commuting with it**: `qgPhase omega t`, multiplication by
  `e^{-it·(boson energy)}`, with `qgPhase_zero`, `qgPhase_group`, `qgPhase_isometry` and
  `qgPhase_comm_brst`.  `qgPhase_single` identifies it on the occupation basis as the
  evolution generated by the graded Fock symbol `qgGradedSymbol omega 0` of
  `ChapterQuantumGravityFock` — the ghost-energy-free case, which is precisely the case in
  which the evolution commutes with the ghost ladder.
* **The join** (§10.6.2 item 4): `qgBrstTransfer` is the induced one-parameter group on the
  BRST cohomology `Cohomology (qgBrstCharge sym)` of the completed space, with
  `qgBrstTransfer_zero`, `qgBrstTransfer_comp`, `qgBrstTransfer_bijective`,
  `qgPhase_mem_physicalStates` (the §10.3 caveat: the evolution preserves the physical
  subspace) and `qgBrstTransfer_infDist` (the BRST quotient norm is preserved).

## Honest boundary

The charge is `Ω = ∑_a C_a Ψ†_a` with the constraint symbols `C_a` *diagonal* in the boson
occupation basis and bounded by one; the full gauge-fixed constraint algebra (whose
generators are unbounded) is not represented, and no claim is made that this `Ω` is the
BRST charge of the `R + αR²` theory.  What is claimed, and proved, is that the reduced
transfer of §10.6.2 item 4 now has a concrete bounded nilpotent charge on a complete
Hilbert space, together with a nontrivial commuting unitary group.  The Hamiltonian whose
group is used here has no ghost energy: a nonzero ghost energy does *not* commute with the
ghost ladder, so its evolution does not descend — that obstruction is recorded, not hidden.
-/
