import Mathlib

/-!
# Chapter "Wave-function parametrization of a probability measure", §8 —
# Conservative transformations

This file formalizes the self-contained finite-dimensional core of the book's
section *"8. Conservative transformations"* (`book.tex` line ~1917), of the
main-conclusion chapter *"Wave-function parametrization of a probability
measure"*.

The book states that a conservative (canonical) transformation preserving the
measure is realized by a **unitary time-evolution** `U(t) = e^{iHt}` for a
self-adjoint Hamiltonian `H`, and remarks that *"any unitary automorphism can be
defined as a time-evolution, for some Hamiltonian and time"* and that a
conservative transformation *preserves the measure* (total probability).

We model this over a finite index set `n` and complex matrices. For a Hermitian
matrix `H : Matrix n n ℂ` we define the time-evolution
`timeEvo H t = exp((t : ℂ) • (I • H))` (the book's `e^{iHt}`) and prove:

* `timeEvo_zero` — `U(0) = 1`;
* `timeEvo_add` — the one-parameter group law `U(s) · U(t) = U(s + t)`;
* `timeEvo_unitary` / `timeEvo_unitary'` — `U(t)` is unitary (`U(t)ᴴ U(t) = 1`
  and `U(t) U(t)ᴴ = 1`);
* `timeEvo_mem_unitaryGroup` — hence `U(t) ∈ unitaryGroup n ℂ`;
* `timeEvo_inv` — the inverse of the time-evolution is the time-reversed
  evolution, `U(t)⁻¹ = U(-t)`;
* `timeEvo_conj_trace` — the conservative property: conjugating a density
  operator `ρ` by `U(t)` preserves its trace, `tr(U(t) ρ U(t)ᴴ) = tr ρ`
  (so total probability `tr ρ = 1` is preserved).

Everything is `sorry`-free and `axiom`-free (only `propext`, `Classical.choice`,
`Quot.sound`).
-/

open scoped Matrix

namespace BookProof.ChapterConservative

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The book's unitary time-evolution `U(t) = e^{iHt}` generated by the
self-adjoint Hamiltonian `H`. -/
noncomputable def timeEvo (H : Matrix n n ℂ) (t : ℝ) : Matrix n n ℂ :=
  NormedSpace.exp ((t : ℂ) • (Complex.I • H))

/-- `U(0) = 1`. -/
theorem timeEvo_zero (H : Matrix n n ℂ) : timeEvo H 0 = 1 := by
  unfold timeEvo; aesop

/-- The exponents at two times commute (both are scalar multiples of `I • H`). -/
theorem timeEvo_commute (H : Matrix n n ℂ) (s t : ℝ) :
    Commute ((s : ℂ) • (Complex.I • H)) ((t : ℂ) • (Complex.I • H)) := by
  ext i j; simp +decide [ mul_assoc, mul_comm, mul_left_comm ]

/-- One-parameter group law: `U(s) · U(t) = U(s + t)`. -/
theorem timeEvo_add (H : Matrix n n ℂ) (s t : ℝ) :
    timeEvo H s * timeEvo H t = timeEvo H (s + t) := by
  unfold timeEvo
  rw [← Matrix.exp_add_of_commute]
  · simp +decide [add_smul]
  · exact timeEvo_commute H s t

/-- The time-evolution is unitary: `U(t)ᴴ · U(t) = 1` for Hermitian `H`. -/
theorem timeEvo_unitary (H : Matrix n n ℂ) (hH : H.IsHermitian) (t : ℝ) :
    (timeEvo H t)ᴴ * (timeEvo H t) = 1 := by
  have hU : timeEvo H t = NormedSpace.exp ((t : ℂ) • (Complex.I • H)) := rfl
  -- Since `H` is Hermitian, `((t:ℂ) • (I • H))ᴴ = -(t:ℂ) • (I • H)`.
  have h_conj : ((t : ℂ) • (Complex.I • H))ᴴ = -(t : ℂ) • (Complex.I • H) := by
    simp +decide [Matrix.IsHermitian, Complex.ext_iff] at hH ⊢
    rw [hH]
  rw [hU, ← Matrix.exp_conjTranspose]
  rw [h_conj, ← Matrix.exp_add_of_commute]
  · simp +decide [NormedSpace.exp_zero]
  · simp +decide [mul_smul_comm, smul_smul]

/-- The time-evolution is unitary: `U(t) · U(t)ᴴ = 1` for Hermitian `H`. -/
theorem timeEvo_unitary' (H : Matrix n n ℂ) (hH : H.IsHermitian) (t : ℝ) :
    (timeEvo H t) * (timeEvo H t)ᴴ = 1 := by
  rw [← mul_eq_one_comm, timeEvo_unitary]
  exact hH

/-- The time-evolution belongs to the unitary group. -/
theorem timeEvo_mem_unitaryGroup (H : Matrix n n ℂ) (hH : H.IsHermitian) (t : ℝ) :
    timeEvo H t ∈ Matrix.unitaryGroup n ℂ := by
  constructor
  · convert timeEvo_unitary H hH t using 1
  · convert timeEvo_unitary' H hH t using 1

/-- The inverse of the time-evolution is the time-reversed evolution:
`U(t)⁻¹ = U(-t)`. -/
theorem timeEvo_inv (H : Matrix n n ℂ) (t : ℝ) :
    timeEvo H t * timeEvo H (-t) = 1 := by
  convert timeEvo_add H t (-t) using 1
  simp +decide [timeEvo_zero]

/-- **Conservative property.** Conjugating a density operator `ρ` by the unitary
time-evolution preserves its trace, so total probability `tr ρ = 1` is
conserved. -/
theorem timeEvo_conj_trace (H : Matrix n n ℂ) (hH : H.IsHermitian) (t : ℝ)
    (ρ : Matrix n n ℂ) :
    (timeEvo H t * ρ * (timeEvo H t)ᴴ).trace = ρ.trace := by
  rw [Matrix.trace_mul_comm]
  rw [← Matrix.mul_assoc, timeEvo_unitary H hH t, Matrix.one_mul]

end BookProof.ChapterConservative
