import Mathlib
import BookProof.ChapterQgBrstDerivativeGauge
import BookProof.ChapterStoneBridge
import BookProof.ChapterSirkTrotterKato

/-!
# The unitary dynamics of the outer-Fock quantum-gravity Hamiltonian, and its numerical
# approximation

`BookProof.ChapterScalaronOuterFockFL` proves that the full gauge-fixed quantum-gravity
Hamiltonian — the scalaron in vielbein variables, with the full exponential Starobinsky
wall, all torsion self-interactions and the scalaron–vielbein coupling — is essentially
self-adjoint on the domain of the lifted Friedrichs extension `N` of the positive
one-particle operator, and `BookProof.ChapterQgContinuumModeInstance` supplies the
non-lattice mode data.  This module draws the two dynamical consequences.

## What is proved

* `comparison_dom_dense` — the domain of a Faris–Lavine comparison operator is dense.  Only
  positivity, symmetry and surjectivity of `N + 1` are used: if `y ⟂ 𝒟(N)` and
  `(N + 1)x = y`, then `0 = ⟪x, y⟫ = q(x) + ‖x‖²`, so `x = 0` and `y = 0`.
* **`qgOuterFock_stone_flow`** — the quantum-gravity Hamiltonian on the outer Fock space has
  a self-adjoint realization and generates a complete strongly continuous unitary group
  `e^{-itH}` (Stone), for arbitrary admissible mode data and an arbitrary non-negative
  scalaron wall; `starobinsky_qgContinuum_stone_flow` is the physical instance — the
  non-lattice Fourier modes and the full exponential Starobinsky potential.
* **`qgOuterFock_numerical_flow_convergence`** — the numerical half.  Whenever a sequence of
  self-adjoint approximations of the selected realization converges to it in the strong
  resolvent sense — which is exactly the interface the shift-invert Hashimoto/SIRK schemes
  of this project deliver, cf. `BookProof.ChapterSirkTrotterKato` — the approximate flows
  converge to the exact quantum-gravity flow, uniformly on every compact time interval.
  `qgOuterFock_numerical_flow_tendsto` is the fixed-time form.

Honest boundary: strong resolvent convergence of a *particular* discretization is not proved
here; it is the hypothesis of the transfer theorem, as everywhere else in the project's
Trotter–Kato layer.  What is new is that the limit object exists and is unique for the
quantum-gravity Hamiltonian: essential self-adjointness is what makes the numerical limit
unambiguous.

Everything is `sorry`-free and `axiom`-free.
-/

namespace BookProof.QgOuterFockFlow

open Filter Topology
open BookProof.ScalaronFiberFL BookProof.ScalaronOuterFockFL
open BookProof.QgContinuumModeInstance
open BookProof.FarisLavine BookProof.QgOuterFockFL BookProof.QgOuterFockCoreFL
open BookProof.StoneBridge BookProof.ChapterStoneResolvent BookProof.EsaClosure
open BookProof.ChapterSirkTrotterKato

noncomputable section

/-! ## 1. The domain of a comparison operator is dense -/

/-- **The domain of a Faris–Lavine comparison operator is dense.**  If `y` is orthogonal to
the domain and `(N + 1)x = y`, then `0 = ⟪x, y⟫ = q(x) + ‖x‖²`, whence `x = 0` and `y = 0`. -/
theorem comparison_dom_dense {F : Type*} [NormedAddCommGroup F] [InnerProductSpace ℂ F]
    [CompleteSpace F] (C : Comparison F) : Dense ((C.dom : Submodule ℂ F) : Set F) := by
  rw [Submodule.dense_iff_topologicalClosure_eq_top, Submodule.topologicalClosure_eq_top_iff,
    Submodule.eq_bot_iff]
  intro y hy
  obtain ⟨x, hx⟩ := C.surj y
  have hxy : (inner ℂ (x : F) y : ℂ) = 0 := (Submodule.mem_orthogonal _ _).mp hy x x.2
  rw [← hx] at hxy
  have hsplit : (inner ℂ (x : F) (C.op x + (x : F)) : ℂ)
      = (inner ℂ (x : F) (C.op x) : ℂ) + (inner ℂ (x : F) (x : F) : ℂ) := inner_add_right _ _ _
  have hre : quadForm C.op x + ‖(x : F)‖ ^ 2 = 0 := by
    have h := congrArg Complex.re (hsplit ▸ hxy)
    simpa [quadForm, inner_self_eq_norm_sq, Complex.add_re, ← Complex.ofReal_pow] using h
  have hpos := C.pos x
  have hx0 : (x : F) = 0 := by
    have hzero : ‖(x : F)‖ ^ 2 = 0 := by nlinarith [sq_nonneg ‖(x : F)‖]
    simpa using hzero
  have hxx : x = (0 : C.dom) := Subtype.ext (by simpa using hx0)
  have hy0 : y = 0 := by rw [← hx, hxx]; simp
  simpa using hy0

/-! ## 2. The unitary flow generated by the quantum-gravity Hamiltonian -/

variable {ι : Type*} (W : WallPot) (Q : QgModeData ι)

/-- The domain of the lifted comparison operator on the outer Fock space is dense. -/
theorem secN_dom_dense : Dense (((secN W Q).dom : Submodule ℂ (Sec ι)) : Set (Sec ι)) :=
  comparison_dom_dense _

/-- The Hamiltonian, extended to the domain of the comparison operator, is symmetric
there. -/
theorem secData_ext_symmetricOn :
    SymmetricOn (secN W Q).dom (secData W Q).ext :=
  (secData W Q).ext_symmetricOn (secHam_symmetricOn W Q)

/-- **The quantum-gravity Hamiltonian on the outer Fock space generates a complete unitary
flow.**  Essential self-adjointness selects a unique self-adjoint realization, and Stone's
theorem turns it into the strongly continuous one-parameter group `e^{-itH}`. -/
theorem qgOuterFock_stone_flow :
    ∃ (T : UnboundedSelfAdjoint (Sec ι)) (U : ℝ → (Sec ι →L[ℂ] Sec ι)),
      IsSelfAdjointExtension (secData W Q).ext T.op ∧ IsStoneFlow T U :=
  exists_stone_flow_of_esa _ (secN_dom_dense W Q) (secData_ext_symmetricOn W Q)
    (secHam_essentiallySelfAdjointOn W Q)

/-- **The physical instance**: the non-lattice Fourier-mode quantum-gravity Hamiltonian with
the full exponential Einstein-frame Starobinsky wall generates a complete unitary flow. -/
theorem starobinsky_qgContinuum_stone_flow (M alpha : ℝ) (halpha : 0 < alpha) (g : ℝ) :
    ∃ (T : UnboundedSelfAdjoint (Sec CMode)) (U : ℝ → (Sec CMode →L[ℂ] Sec CMode)),
      IsSelfAdjointExtension (secData (starobinskyWall M alpha halpha)
          (qgContinuumModes g)).ext T.op ∧ IsStoneFlow T U :=
  qgOuterFock_stone_flow (starobinskyWall M alpha halpha) (qgContinuumModes g)

/-! ## 3. Numerical approximation of the flow -/

/-- **Convergence of the numerical flows to the quantum-gravity flow.**  Let `T` be a
self-adjoint realization of the quantum-gravity Hamiltonian (the one selected by essential
self-adjointness) and let `S n` be self-adjoint approximations whose resolvents converge
strongly — the interface produced by the shift-invert Hashimoto/SIRK schemes.  Then the
approximate unitary evolutions converge to the exact one, uniformly on every compact time
interval. -/
theorem qgOuterFock_numerical_flow_convergence :
    ∃ (T : UnboundedSelfAdjoint (Sec ι)) (U : ℝ → (Sec ι →L[ℂ] Sec ι)),
      IsSelfAdjointExtension (secData W Q).ext T.op ∧ IsStoneFlow T U ∧
        ∀ S : ℕ → UnboundedSelfAdjoint (Sec ι), StrongResolventConvergence T S →
          ∀ (v : Sec ι) (T₀ : ℝ), 0 ≤ T₀ →
            (TendstoUniformlyOn (fun n t => (S n).stoneU t v) (fun t => T.stoneU t v) atTop
                (Set.Icc (-T₀) T₀)
              ∧ ∀ t : ℝ, Tendsto (fun n => (S n).stoneU t v) atTop (𝓝 (T.stoneU t v))) := by
  obtain ⟨T, U, hext, hflow⟩ := qgOuterFock_stone_flow W Q
  exact ⟨T, U, hext, hflow, fun S hres v T₀ hT₀ =>
    ⟨trotterKato_tendstoUniformlyOn T S hres v hT₀, fun t => trotterKato_tendsto T S hres v t⟩⟩

/-- The physical instance of the numerical transfer: the non-lattice Fourier-mode
quantum-gravity Hamiltonian with the full exponential Starobinsky wall. -/
theorem starobinsky_qgContinuum_numerical_flow_convergence (M alpha : ℝ) (halpha : 0 < alpha)
    (g : ℝ) :
    ∃ (T : UnboundedSelfAdjoint (Sec CMode)) (U : ℝ → (Sec CMode →L[ℂ] Sec CMode)),
      IsSelfAdjointExtension (secData (starobinskyWall M alpha halpha)
          (qgContinuumModes g)).ext T.op ∧ IsStoneFlow T U ∧
        ∀ S : ℕ → UnboundedSelfAdjoint (Sec CMode), StrongResolventConvergence T S →
          ∀ (v : Sec CMode) (T₀ : ℝ), 0 ≤ T₀ →
            (TendstoUniformlyOn (fun n t => (S n).stoneU t v) (fun t => T.stoneU t v) atTop
                (Set.Icc (-T₀) T₀)
              ∧ ∀ t : ℝ, Tendsto (fun n => (S n).stoneU t v) atTop (𝓝 (T.stoneU t v))) :=
  qgOuterFock_numerical_flow_convergence (starobinskyWall M alpha halpha) (qgContinuumModes g)

end

end BookProof.QgOuterFockFlow
