import Mathlib
import BookProof.ChapterNavierStokesFlow

/-!
# The truncated Navier–Stokes Cauchy problem: global existence and uniqueness

Companion to `BookProof.ChapterNavierStokesFlow`.  That module builds the
truncated Navier–Stokes Hamiltonian `H_N` and its flow `U(t) = e^{i t H_N}` and
proves that the flow is a one-parameter unitary group (so it is *complete*: it
exists for every real time) which preserves the `ℓ²` mass.

This module supplies the missing *differential* half of `book.tex` ~4210–4216
("the solution … exists and it is unique"): on the finite truncation the curve
`t ↦ U(t) ψ` is differentiable and

* **solves** the evolution equation `ψ̇(t) = i H_N ψ(t)` with `ψ(0) = ψ`
  (`nsFlow_solves_schrodinger`), and
* is the **only** solution — any differentiable curve satisfying the same
  equation and the same initial value coincides with it at every time
  (`nsFlow_unique_solution`), so the Cauchy problem is uniquely solvable for all
  time (`nsCauchy_existsUnique`).

Together with `nsFlow_noBlowup` of the companion module this is the honest,
finite-dimensional shadow of global regularity: *on the truncation* the initial
value problem has one and only one solution, defined for all `t ∈ ℝ`, whose
coefficients never exceed the conserved initial mass.

## Scope

Exactly as in the companion module, **nothing is claimed about the continuum
Navier–Stokes equations**.  The statements below are theorems about a fixed
finite-dimensional truncation, where the generator is a finite Hermitian matrix;
the passage to the untruncated operator (essential self-adjointness, and with it
global existence and uniqueness for Navier–Stokes) is the research target
recorded in `BookProof.ChapterNavierStokesFlow`, not a result of this file.

The general lemmas about `matrixFlow` are stated for an arbitrary complex square
matrix, since neither differentiability nor uniqueness uses Hermiticity; only
the *unitarity* of the Navier–Stokes flow does.
-/

open scoped BigOperators Matrix Matrix.Norms.Operator

namespace BookProof.NavierStokesFlow

/-! ## The flow of an arbitrary finite generator -/

section MatrixFlow

variable {n : ℕ}

/-- Multiplication of a vector by a fixed matrix, as a continuous `ℝ`-linear
map.  (Everything in sight is finite-dimensional, so linearity is enough.) -/
noncomputable def mulVecCLM (A : Matrix (Fin n) (Fin n) ℂ) : (Fin n → ℂ) →L[ℝ] (Fin n → ℂ) :=
  LinearMap.toContinuousLinearMap ((Matrix.mulVecLin A).restrictScalars ℝ)

@[simp] theorem mulVecCLM_apply (A : Matrix (Fin n) (Fin n) ℂ) (x : Fin n → ℂ) :
    mulVecCLM A x = A *ᵥ x := rfl

/-- The assignment `A ↦ (x ↦ A x)` itself, as a continuous `ℝ`-linear map from
matrices to operators.  This is what turns the product rule for `t ↦ U(t) y(t)`
into an application of `HasDerivAt.clm_apply`. -/
noncomputable def mulVecCLM' :
    Matrix (Fin n) (Fin n) ℂ →L[ℝ] ((Fin n → ℂ) →L[ℝ] (Fin n → ℂ)) :=
  LinearMap.toContinuousLinearMap
    { toFun := mulVecCLM
      map_add' := by intro A B; ext x i; simp [mulVecCLM]
      map_smul' := by intro c A; ext x i; simp [mulVecCLM, Matrix.mulVec] }

@[simp] theorem mulVecCLM'_apply (A : Matrix (Fin n) (Fin n) ℂ) (x : Fin n → ℂ) :
    mulVecCLM' A x = A *ᵥ x := rfl

/-- Application of a fixed vector to a varying matrix, as a continuous
`ℝ`-linear map `A ↦ A x`. -/
noncomputable def applyVecCLM (x : Fin n → ℂ) : Matrix (Fin n) (Fin n) ℂ →L[ℝ] (Fin n → ℂ) :=
  LinearMap.toContinuousLinearMap
    { toFun := fun A => A *ᵥ x
      map_add' := by intro A B; ext i; simp [Matrix.add_mulVec]
      map_smul' := by
        intro c A; ext i
        simp [Matrix.mulVec, dotProduct, Finset.mul_sum, mul_assoc] }

@[simp] theorem applyVecCLM_apply (A : Matrix (Fin n) (Fin n) ℂ) (x : Fin n → ℂ) :
    applyVecCLM x A = A *ᵥ x := rfl

/-- The flow `t ↦ e^{t A}` generated by a finite matrix `A`. -/
noncomputable def matrixFlow (A : Matrix (Fin n) (Fin n) ℂ) (t : ℝ) :
    Matrix (Fin n) (Fin n) ℂ :=
  NormedSpace.exp (t • A)

/-- The flow is differentiable in time, with derivative `e^{tA} A`. -/
theorem matrixFlow_hasDerivAt (A : Matrix (Fin n) (Fin n) ℂ) (t : ℝ) :
    HasDerivAt (matrixFlow A) (matrixFlow A t * A) t :=
  hasDerivAt_exp_smul_const (𝕂 := ℝ) A t

/-- The generator commutes with its own flow. -/
theorem matrixFlow_comm (A : Matrix (Fin n) (Fin n) ℂ) (t : ℝ) :
    matrixFlow A t * A = A * matrixFlow A t :=
  (((Commute.refl A).smul_left t).exp_left).eq

/-- The time-reversed flow is differentiable, with derivative `−e^{−tA} A`. -/
theorem matrixFlow_neg_hasDerivAt (A : Matrix (Fin n) (Fin n) ℂ) (t : ℝ) :
    HasDerivAt (fun s : ℝ => matrixFlow A (-s)) (-(matrixFlow A (-t) * A)) t := by
  have h : HasDerivAt (fun s : ℝ => -s) (-1 : ℝ) t := (hasDerivAt_id t).neg
  simpa using HasDerivAt.scomp t (matrixFlow_hasDerivAt A (-t)) h

/-- `e^{tA} e^{−tA} = 1`: the flow is invertible at every time, its inverse
being the flow run backwards. -/
theorem matrixFlow_mul_neg (A : Matrix (Fin n) (Fin n) ℂ) (t : ℝ) :
    matrixFlow A t * matrixFlow A (-t) = 1 := by
  have h : matrixFlow A t * matrixFlow A (-t) = NormedSpace.exp ((t • A) + ((-t) • A)) := by
    rw [Matrix.exp_add_of_commute _ _ (((Commute.refl A).smul_left t).smul_right (-t))]
    rfl
  rw [h]
  simp [NormedSpace.exp_zero]

/-- The orbit `t ↦ e^{tA} x` solves the linear evolution equation `ẏ = A y`. -/
theorem matrixFlow_vec_hasDerivAt (A : Matrix (Fin n) (Fin n) ℂ) (x : Fin n → ℂ) (t : ℝ) :
    HasDerivAt (fun s : ℝ => matrixFlow A s *ᵥ x) (A *ᵥ (matrixFlow A t *ᵥ x)) t := by
  have h := (applyVecCLM x).hasFDerivAt.comp_hasDerivAt t (matrixFlow_hasDerivAt A t)
  simpa [matrixFlow_comm, Matrix.mulVec_mulVec] using h

/-- **Uniqueness for the linear Cauchy problem.**  Any differentiable curve with
`ẏ(t) = A y(t)` for every `t` and `y(0) = x` is the orbit of the flow.  The
proof is the classical one: `t ↦ e^{−tA} y(t)` has vanishing derivative, hence is
constant. -/
theorem matrixFlow_unique (A : Matrix (Fin n) (Fin n) ℂ) (x : Fin n → ℂ) (y : ℝ → Fin n → ℂ)
    (hy : ∀ t, HasDerivAt y (A *ᵥ y t) t) (hy0 : y 0 = x) (t : ℝ) :
    y t = matrixFlow A t *ᵥ x := by
  have hzd : ∀ s : ℝ, HasDerivAt (fun s : ℝ => matrixFlow A (-s) *ᵥ y s) 0 s := by
    intro s
    have hV : HasDerivAt (fun s : ℝ => mulVecCLM' (matrixFlow A (-s)))
        (mulVecCLM' (-(matrixFlow A (-s) * A))) s :=
      mulVecCLM'.hasFDerivAt.comp_hasDerivAt s (matrixFlow_neg_hasDerivAt A s)
    have h := hV.clm_apply (hy s)
    have hrw : (mulVecCLM' (-(matrixFlow A (-s) * A))) (y s)
        + (mulVecCLM' (matrixFlow A (-s))) (A *ᵥ y s) = 0 := by
      change (-(matrixFlow A (-s) * A)) *ᵥ (y s) + (matrixFlow A (-s)) *ᵥ (A *ᵥ y s) = 0
      rw [Matrix.mulVec_mulVec]
      simp [Matrix.neg_mulVec]
    rw [hrw] at h
    exact h
  have hconst : matrixFlow A (-t) *ᵥ y t = matrixFlow A (-0) *ᵥ y 0 :=
    is_const_of_deriv_eq_zero (fun s => (hzd s).differentiableAt) (fun s => (hzd s).deriv) t 0
  have h0 : matrixFlow A (-t) *ᵥ y t = x := by
    rw [hconst, hy0]
    simp [matrixFlow, NormedSpace.exp_zero]
  calc y t = (matrixFlow A t * matrixFlow A (-t)) *ᵥ y t := by rw [matrixFlow_mul_neg]; simp
    _ = matrixFlow A t *ᵥ (matrixFlow A (-t) *ᵥ y t) := by rw [Matrix.mulVec_mulVec]
    _ = matrixFlow A t *ᵥ x := by rw [h0]

/-- **Global existence and uniqueness for a linear finite-dimensional Cauchy
problem.**  For every initial value there is exactly one curve, defined at every
real time, solving `ẏ = A y` — the flow orbit. -/
theorem matrixFlow_cauchy_existsUnique (A : Matrix (Fin n) (Fin n) ℂ) (x : Fin n → ℂ) :
    ∃! y : ℝ → Fin n → ℂ, y 0 = x ∧ ∀ t, HasDerivAt y (A *ᵥ y t) t := by
  refine ⟨fun t => matrixFlow A t *ᵥ x, ⟨?_, fun t => matrixFlow_vec_hasDerivAt A x t⟩, ?_⟩
  · simp [matrixFlow, NormedSpace.exp_zero]
  · rintro y ⟨hy0, hy⟩
    exact funext fun t => matrixFlow_unique A x y hy hy0 t

end MatrixFlow

/-! ## The Navier–Stokes Cauchy problem on the truncation -/

variable {n : ℕ} (d : NSTruncation n)

/-- The Navier–Stokes flow is the flow of the generator `i H_N`. -/
theorem nsFlowUnitary_eq_matrixFlow (t : ℝ) :
    nsFlowUnitary d t = matrixFlow (Complex.I • nsHamiltonian d) t := by
  rw [nsFlowUnitary, matrixFlow, ← smul_assoc, Complex.real_smul]

/-- The function-level form of `nsFlowUnitary_eq_matrixFlow`. -/
theorem nsFlowUnitary_eq_matrixFlow' :
    nsFlowUnitary d = matrixFlow (Complex.I • nsHamiltonian d) :=
  funext (nsFlowUnitary_eq_matrixFlow d)

/-- **D.8** The Navier–Stokes flow is differentiable in time:
`d/dt U(t) = U(t) · i H_N`. -/
theorem nsFlow_hasDerivAt (t : ℝ) :
    HasDerivAt (nsFlowUnitary d) (nsFlowUnitary d t * (Complex.I • nsHamiltonian d)) t := by
  rw [nsFlowUnitary_eq_matrixFlow']
  exact matrixFlow_hasDerivAt (Complex.I • nsHamiltonian d) t

/-- **D.9 (headline)** *The evolved state solves the Navier–Stokes evolution
equation on the truncation*: `ψ(t) = U(t) ψ` is differentiable with
`ψ̇(t) = i H_N ψ(t)`, for every real time — the differential form of
`book.tex` ~4210–4216, on the truncation. -/
theorem nsFlow_solves_schrodinger (psi : Fin n → ℂ) (t : ℝ) :
    HasDerivAt (fun s : ℝ => nsFlowUnitary d s *ᵥ psi)
      ((Complex.I • nsHamiltonian d) *ᵥ (nsFlowUnitary d t *ᵥ psi)) t := by
  rw [nsFlowUnitary_eq_matrixFlow']
  exact matrixFlow_vec_hasDerivAt (Complex.I • nsHamiltonian d) psi t

/-- **D.10 (headline)** *The solution is unique*: any differentiable curve
solving `ẏ(t) = i H_N y(t)` with `y(0) = ψ` is the flow orbit `t ↦ U(t) ψ`. -/
theorem nsFlow_unique_solution (psi : Fin n → ℂ) (y : ℝ → Fin n → ℂ)
    (hy : ∀ t, HasDerivAt y ((Complex.I • nsHamiltonian d) *ᵥ y t) t) (hy0 : y 0 = psi)
    (t : ℝ) : y t = nsFlowUnitary d t *ᵥ psi := by
  rw [nsFlowUnitary_eq_matrixFlow]
  exact matrixFlow_unique (Complex.I • nsHamiltonian d) psi y hy hy0 t

/-- **D.11 (headline)** *Global existence and uniqueness for the truncated
Navier–Stokes Cauchy problem* (`book.tex` ~4210–4216, truncation only): for
every initial state `ψ` there is **exactly one** curve `y : ℝ → ℂ^n` with
`y(0) = ψ` which solves `ẏ(t) = i H_N y(t)` at every real time, namely the
unitary orbit `t ↦ U(t) ψ`.  Existence for *all* `t` is the completeness of the
flow; by `nsFlow_noBlowup` the solution never leaves the sphere of radius
`‖ψ‖`, so there is no finite-time singularity on the truncation. -/
theorem nsCauchy_existsUnique (psi : Fin n → ℂ) :
    ∃! y : ℝ → Fin n → ℂ,
      y 0 = psi ∧ ∀ t, HasDerivAt y ((Complex.I • nsHamiltonian d) *ᵥ y t) t :=
  matrixFlow_cauchy_existsUnique (Complex.I • nsHamiltonian d) psi

/-- The flow of `A` commutes with everything `A` commutes with. -/
theorem matrixFlow_commute_of_commute (A B : Matrix (Fin n) (Fin n) ℂ) (h : Commute A B)
    (t : ℝ) : Commute (matrixFlow A t) B :=
  (h.smul_left t).exp_left

/-- The flow commutes with its own generator: `U(t) H_N = H_N U(t)`. -/
theorem nsFlow_comm_hamiltonian (t : ℝ) :
    nsFlowUnitary d t * nsHamiltonian d = nsHamiltonian d * nsFlowUnitary d t := by
  rw [nsFlowUnitary_eq_matrixFlow]
  exact (matrixFlow_commute_of_commute (Complex.I • nsHamiltonian d) (nsHamiltonian d)
    (by simp [Commute, SemiconjBy]) t).eq

/-- **D.12** *Conservation of energy along the truncated flow*: the expectation
`⟨ψ(t), H_N ψ(t)⟩` of the Navier–Stokes Hamiltonian is the same at every time.
With `nsFlow_norm_preserving` this is the second conserved quantity of the
truncated evolution. -/
theorem nsFlow_energy_conserved (t : ℝ) (psi : Fin n → ℂ) :
    star (nsFlowUnitary d t *ᵥ psi) ⬝ᵥ (nsHamiltonian d *ᵥ (nsFlowUnitary d t *ᵥ psi))
      = star psi ⬝ᵥ (nsHamiltonian d *ᵥ psi) := by
  have hstep : star (nsFlowUnitary d t *ᵥ psi) ⬝ᵥ (nsHamiltonian d *ᵥ (nsFlowUnitary d t *ᵥ psi))
      = star psi ⬝ᵥ (((nsFlowUnitary d t)ᴴ * nsHamiltonian d * nsFlowUnitary d t) *ᵥ psi) := by
    rw [Matrix.star_mulVec, Matrix.mulVec_mulVec, Matrix.dotProduct_mulVec,
      Matrix.vecMul_vecMul, ← Matrix.dotProduct_mulVec, mul_assoc]
  rw [hstep, mul_assoc, ← nsFlow_comm_hamiltonian, ← mul_assoc, nsFlow_unitary, Matrix.one_mul]

/-- The flow is continuous in time (in particular the orbit of every state is a
continuous curve): a one-parameter unitary group with no jumps. -/
theorem nsFlow_continuous : Continuous (nsFlowUnitary d) :=
  continuous_iff_continuousAt.2 fun t => (nsFlow_hasDerivAt d t).continuousAt

/-! ## The Lagrangian (parcel) operator generates a complete flow too

The four-term operator `ĥ_full` of Part B — positive advective Laplacian,
positive viscous term, force drift and the 0-order volume-preservation
constraint — is Hermitian on the truncation
(`LagrangianNS.transformed_hamiltonian_hermitian`), so the same argument applies
to it verbatim: its flow is a one-parameter unitary group and its Cauchy problem
is uniquely solvable for all time.  This is the truncated form of the route
recorded in Part B; the *continuum* statement remains unclaimed. -/

namespace LagrangianNS

variable (L : LagrangianNS n)

/-- The flow of the transformed (Lagrangian) operator, `e^{i t ĥ_full}`. -/
noncomputable def flowUnitary (t : ℝ) : Matrix (Fin n) (Fin n) ℂ :=
  matrixFlow (Complex.I • L.hFull) t

/-- Every `e^{i t ĥ_full}` is unitary, because `ĥ_full` is Hermitian. -/
theorem flowUnitary_unitary (t : ℝ) : (L.flowUnitary t)ᴴ * L.flowUnitary t = 1 := by
  have h := BookProof.ChapterContinuityUnitary.exp_smul_I_unitary L.hFull
    L.transformed_hamiltonian_hermitian t
  rwa [flowUnitary, matrixFlow, ← smul_assoc, Complex.real_smul]

/-- The transformed flow is a one-parameter group: it is **complete**. -/
theorem flowUnitary_group (s t : ℝ) :
    L.flowUnitary (s + t) = L.flowUnitary s * L.flowUnitary t := by
  have hcomm : Commute ((s : ℝ) • (Complex.I • L.hFull)) ((t : ℝ) • (Complex.I • L.hFull)) :=
    ((Commute.refl (Complex.I • L.hFull)).smul_left s).smul_right t
  rw [flowUnitary, flowUnitary, flowUnitary, matrixFlow, matrixFlow, matrixFlow, add_smul,
    Matrix.exp_add_of_commute _ _ hcomm]

/-- **B (truncated completeness)** *The Cauchy problem of the transformed
Lagrangian operator has exactly one global solution*, for every initial state
and every real time. -/
theorem cauchy_existsUnique (psi : Fin n → ℂ) :
    ∃! y : ℝ → Fin n → ℂ,
      y 0 = psi ∧ ∀ t, HasDerivAt y ((Complex.I • L.hFull) *ᵥ y t) t :=
  matrixFlow_cauchy_existsUnique (Complex.I • L.hFull) psi

end LagrangianNS

end BookProof.NavierStokesFlow
