import Mathlib
import BookProof.ChapterNavierStokesGaugeY2
import BookProof.ChapterQuantumGravityBrstCharge

/-!
# The BRST charge of the Navier–Stokes derivative gauge, and its commutator with the Hamiltonian

`BookProof.ChapterNavierStokesGaugeY` and `BookProof.ChapterNavierStokesGaugeY2` build the
gauge fixing of the Navier–Stokes variables **that represent the derivatives in space of the
velocity field**: the modes `u_{i,j}` (and, at second order, `u_{i,jj}`) are constrained to be
the `y`-derivatives of the field `u_i(y)`, and the constraint is generated by

* `G_j = ∂/∂y_j − u_{i,j} ∂/∂u_i`  (`genY`, first order), respectively
* `G²_j = ∂/∂y_j − u_{i,j} ∂/∂u_i − u_{i,jj} ∂/∂u_{i,j}`  (`genY2`, second order).

Both families are abelian, hence first class, so they are exactly the situation BRST was made
for.  This module builds the BRST charge of that gauge fixing and proves the property the
whole construction rests on: **the charge commutes with the Navier–Stokes Hamiltonian.**

## What is proved

* **The ghost sector.**  `nsGhostSpace = Λ(ℂ³)` carries one ghost per gauge generator, with
  creation `nsGhostCre` (exterior multiplication) and annihilation `nsGhostAnn`
  (contraction); `nsGhost_car` is the canonical anticommutation relations.
* **The graded state space** `NSGraded = ℂ[x, y, u, u_{·,·}, u_{·,··}] ⊗ Λ(ℂ³)`, with the
  bosonic and ghost embeddings `nsBos`, `nsGh` (`nsBos_nsGh_comm`) and the ghosts
  `nsChi`, `nsBeta` (`nsGradedGhostCar`).
* **The Hamiltonian.**  `nsHamAlg nu = ∑_i (π^i A_i + A_i π^i)` with
  **`π^i = ∂/∂u_i` the momentum conjugate to the velocity field** (`genU`) and
  `A_i = u_j(y) u_{i,j} − ν u_{i,jj}` the Navier–Stokes symbol built from the *fields*
  (`BookProof.NavierStokesGaugeY.nsSymbol`); `nsHamAlg2` is the second-order version built
  from `nsSymbol2`.  `nsHamiltonian`, `nsHamiltonian2` are their images on `NSGraded`.

  The momentum is conjugate to `u`, not to the space coordinate `x`: `genU_ccr_u` is the
  canonical commutation relation `[π^i, u_k · ] = δ^i_k`.  The choice is not cosmetic.  With
  `π^i = ∂/∂u_i` the momentum does **not** commute with the symbol, `[∂/∂u_m, A_i] = u_{i,m}`
  (`genU_nsSymbol`, `genU_nsSymbol_ne_zero`), so the symmetrized ordering `π^i A_i + A_i π^i`
  carries real content; the superseded operator built with `∂/∂x_i` is kept as `nsHamAlgX`,
  and `nsHamAlg_ne_nsHamAlgX` shows that the two differ — already on the constant state
  (`nsHamAlg_one`, `nsHamAlgX_one`).
* **The BRST charges** `nsDerivBrstCharge = ∑_j G_j χ_j` and
  `nsDerivBrstCharge2 = ∑_j G²_j χ_j` (abelian constraints, so no cubic ghost term is
  needed), with `nsDerivBrstCharge_nilpotent`, `nsDerivBrstCharge2_nilpotent` (`Ω² = 0`) and
  `nsDerivBrstCharge_ne_zero`, `nsDerivBrstCharge2_ne_zero` (the charges are not the zero
  operator, so the statements below are not vacuous).
* **The headline** — `nsDerivBrstCharge_comm_hamiltonian`,
  `nsDerivBrstCharge2_comm_hamiltonian2`:

  `⁅Ω, H⁆ = 0`.

  The charge is odd and the Hamiltonian even, so the *correct* relation is the commutator,
  and it vanishes.  The mechanism is the gauge invariance of the Hamiltonian symbol
  (`genY_nsSymbol`, `genY2_nsSymbol2`) together with `genY_comm_genU`, `genY2_comm_genU`:
  the generator is a derivation that kills the symbol, so it commutes with multiplication by
  it, and it commutes with the velocity momenta `π^i = ∂/∂u_i` — the coefficients `u_{i,j}`,
  `u_{i,jj}` of the generator are independent canonical variables, so `∂/∂u_m` passes
  through them.  The correction of the momentum therefore changes the Hamiltonian but leaves
  the BRST commutator intact.
* **Consequences** — `nsHamiltonian_mapsTo_ker`, `nsHamiltonian_mapsTo_range` (the dynamics
  preserves the BRST-closed and the BRST-exact states) and hence
  `nsBrstCohomologyMap`: the Hamiltonian descends to the BRST cohomology of the derivative
  gauge; the same statements hold at second order.

That the order of the generator matters — the first-order generator is *not* a symmetry of
the second-order field — is recorded in
`BookProof.NavierStokesGaugeY2.genY_uField2_ne_zero`.

Everything is `sorry`-free and `axiom`-free.
-/

namespace BookProof.NsBrstDerivativeGauge

open MvPolynomial BookProof.BRSTNilpotent BookProof.QuantumGravityBrstCharge
open BookProof.NavierStokesGaugeY BookProof.NavierStokesGaugeY2

noncomputable section

/-! ## 1. The ghost sector: one ghost per gauge generator -/

/-- The ghost Fock space of the derivative gauge: one fermionic mode for each of the three
gauge generators `G_j`, realized as the exterior algebra `Λ(ℂ³)`. -/
abbrev nsGhostSpace : Type := ExteriorAlgebra ℂ (Fin 3 → ℂ)

/-- The ghost **creation** operator `χ_a`: exterior multiplication by the `a`-th basis
vector. -/
def nsGhostCre (a : Fin 3) : Module.End ℂ nsGhostSpace :=
  LinearMap.mulLeft ℂ (ExteriorAlgebra.ι ℂ (Pi.single a 1))

/-- The ghost **annihilation** operator `β_a`: contraction against the `a`-th coordinate. -/
def nsGhostAnn (a : Fin 3) : Module.End ℂ nsGhostSpace :=
  CliffordAlgebra.contractLeft (LinearMap.proj a)

/-- **The ghosts obey the canonical anticommutation relations.** -/
theorem nsGhost_car : GhostCAR nsGhostCre nsGhostAnn := by
  constructor
  · intro a b
    refine LinearMap.ext fun x => ?_
    simp only [nsGhostCre, LinearMap.add_apply, Module.End.mul_apply, LinearMap.mulLeft_apply,
      LinearMap.zero_apply, ← mul_assoc]
    rw [← add_mul, CliffordAlgebra.ι_mul_ι_add_swap]
    simp [QuadraticMap.polar]
  · intro a b
    refine LinearMap.ext fun x => ?_
    simp only [nsGhostAnn, LinearMap.add_apply, Module.End.mul_apply, LinearMap.zero_apply]
    rw [CliffordAlgebra.contractLeft_comm, neg_add_cancel]
  · intro a b
    refine LinearMap.ext fun x => ?_
    simp only [nsGhostCre, nsGhostAnn, LinearMap.add_apply, Module.End.mul_apply,
      LinearMap.mulLeft_apply, CliffordAlgebra.contractLeft_ι_mul]
    by_cases h : a = b
    · subst h; simp
    · simp [h]

/-! ## 2. The graded state space -/

/-- The **graded state space** of the derivative gauge: the polynomial algebra in the
canonical variables `x, y, u, u_{i,j}, u_{i,jj}` tensored with the ghost sector. -/
abbrev NSGraded : Type := TensorProduct ℂ NSAlg nsGhostSpace

/-- A bosonic operator, acting as `T ⊗ 1` on the graded space. -/
def nsBos (T : Module.End ℂ NSAlg) : Module.End ℂ NSGraded :=
  LinearMap.rTensor nsGhostSpace T

/-- A ghost operator, acting as `1 ⊗ T` on the graded space. -/
def nsGh (T : Module.End ℂ nsGhostSpace) : Module.End ℂ NSGraded :=
  LinearMap.lTensor NSAlg T

theorem nsBos_mul (S T : Module.End ℂ NSAlg) : nsBos (S * T) = nsBos S * nsBos T := by
  simp [nsBos, Module.End.mul_eq_comp, LinearMap.rTensor_comp]

theorem nsBos_zero : nsBos 0 = 0 := by simp [nsBos]

theorem nsGh_mul (S T : Module.End ℂ nsGhostSpace) : nsGh (S * T) = nsGh S * nsGh T := by
  simp [nsGh, Module.End.mul_eq_comp, LinearMap.lTensor_comp]

theorem nsGh_add (S T : Module.End ℂ nsGhostSpace) : nsGh (S + T) = nsGh S + nsGh T := by
  simp [nsGh]

theorem nsGh_one : nsGh 1 = 1 := by
  simp [nsGh, Module.End.one_eq_id, LinearMap.lTensor_id]

theorem nsGh_zero : nsGh 0 = 0 := by simp [nsGh]

/-- **Bosonic and ghost operators commute** on the graded space. -/
theorem nsBos_nsGh_comm (S : Module.End ℂ NSAlg) (T : Module.End ℂ nsGhostSpace) :
    nsBos S * nsGh T = nsGh T * nsBos S := by
  simp [nsBos, nsGh, Module.End.mul_eq_comp, LinearMap.lTensor_comp_rTensor,
    LinearMap.rTensor_comp_lTensor]

/-- The ghost creation operators on the graded space. -/
def nsChi (a : Fin 3) : Module.End ℂ NSGraded := nsGh (nsGhostCre a)

/-- The ghost annihilation operators on the graded space. -/
def nsBeta (a : Fin 3) : Module.End ℂ NSGraded := nsGh (nsGhostAnn a)

/-- **The CAR hold on the graded state space.** -/
theorem nsGradedGhostCar : GhostCAR nsChi nsBeta := by
  classical
  constructor
  · intro a b
    rw [nsChi, nsChi, ← nsGh_mul, ← nsGh_mul, ← nsGh_add, nsGhost_car.chichi a b, nsGh_zero]
  · intro a b
    rw [nsBeta, nsBeta, ← nsGh_mul, ← nsGh_mul, ← nsGh_add, nsGhost_car.betabeta a b, nsGh_zero]
  · intro a b
    rw [nsBeta, nsChi, ← nsGh_mul, ← nsGh_mul, ← nsGh_add, nsGhost_car.betachi a b]
    by_cases h : a = b
    · simp [h, nsGh_one]
    · simp [h, nsGh_zero]

/-! ## 3. The Navier–Stokes Hamiltonian in the gauge-fixed variables -/

/-- Multiplication by a polynomial, as an operator on the canonical algebra. -/
def mulOp (a : NSAlg) : Module.End ℂ NSAlg := LinearMap.mulLeft ℂ a

/-- **The momentum conjugate to the velocity field**, `π^i = ∂/∂u_i`.

This is the momentum that appears in the Navier–Stokes Hamiltonian
`H = ∑_i (π^i A_i + A_i π^i)`: the canonical pair of the theory is the velocity mode `u_i`
and its conjugate momentum, *not* the space coordinate `x_i`.  (An earlier version of this
module used `π^i = ∂/∂x_i`; that is corrected here, and the correction is not cosmetic — see
`genU_nsSymbol_ne_zero` and `nsHamAlg_one_ne_zero`, which exhibit contributions of the
Hamiltonian that are invisible for `∂/∂x_i`, because the symbol `A_i` does not depend on
`x`.) -/
def genU (i : Fin 3) : Module.End ℂ NSAlg := (pderiv (NSVar.u i)).toLinearMap

theorem genU_apply (i : Fin 3) (p : NSAlg) : genU i p = pderiv (NSVar.u i) p := rfl

/-- The momentum conjugate to the velocity is a derivation. -/
theorem genU_leibniz (i : Fin 3) (p q : NSAlg) :
    genU i (p * q) = genU i p * q + p * genU i q := by
  rw [genU_apply, genU_apply, genU_apply, pderiv_mul]

/-- **`π^i = ∂/∂u_i` is the momentum conjugate to the velocity mode `u_i`**:
`[π^i, u_k · ] = δ^i_k`. -/
theorem genU_ccr_u (i k : Fin 3) (p : NSAlg) :
    genU i (X (NSVar.u k) * p) - X (NSVar.u k) * genU i p = if i = k then p else 0 := by
  rw [genU_apply, genU_apply, pderiv_mul, pderiv_X, Pi.single_apply]
  simp only [NSVar.u.injEq]
  by_cases h : i = k
  · subst h; simp
  · rw [if_neg (fun hh : k = i => h hh.symm), if_neg h]; ring

/-- The velocity momentum ignores the space coordinate: `[π^i, x_k · ] = 0`. -/
theorem genU_ccr_x (i k : Fin 3) (p : NSAlg) :
    genU i (X (NSVar.x k) * p) - X (NSVar.x k) * genU i p = 0 := by
  rw [genU_apply, genU_apply, pderiv_mul, pderiv_X_of_ne (by simp)]; ring

/-- The Laplacian modes are constants for the momentum conjugate to `u`. -/
theorem pderiv_u_mul_uL (m i : Fin 3) (q : NSAlg) :
    pderiv (NSVar.u m) (X (NSVar.uL i) * q) = X (NSVar.uL i) * pderiv (NSVar.u m) q := by
  rw [pderiv_mul, pderiv_X_of_ne (by simp)]; ring

/-! ### How the velocity momentum sees the Hamiltonian symbol -/

/-- The velocity momentum picks the coefficient of `u_m` out of the field:
`∂ u_j(y)/∂u_m = δ_{mj}`. -/
theorem genU_uField (m j : Fin 3) : genU m (uField j) = if m = j then 1 else 0 := by
  simp only [genU_apply, uField, map_add, map_sum, pderiv_mul, pderiv_X, Pi.single_apply,
    NSVar.u.injEq]
  simp [eq_comm]

/-- **The velocity momentum does not commute with the Navier–Stokes symbol**:
`[∂/∂u_m, A_i] = u_{i,m}`.  This is the content of the correction `π^i = ∂/∂u_i`: the
momentum conjugate to the velocity really acts inside the advection term, whereas `∂/∂x_i`
would annihilate the symbol (`genX_nsSymbol`). -/
theorem genU_nsSymbol (nu : ℂ) (i m : Fin 3) :
    genU m (nsSymbol nu i) = X (NSVar.uD i m) := by
  have hC : genU m (C nu * X (NSVar.uL i)) = 0 := by
    simp [genU_apply, pderiv_X_of_ne (show NSVar.uL i ≠ NSVar.u m by simp)]
  have huD : ∀ j : Fin 3, genU m (X (NSVar.uD i j)) = 0 := by
    intro j
    simp [genU_apply, pderiv_X_of_ne (show NSVar.uD i j ≠ NSVar.u m by simp)]
  simp only [nsSymbol, map_sub, map_sum, hC, sub_zero, genU_leibniz, huD, mul_zero, add_zero,
    genU_uField]
  simp [ite_mul, Finset.sum_ite_eq]

/-- The commutator above is non-zero, so the Hamiltonian genuinely differs from the one
built with the space momentum `∂/∂x_i`. -/
theorem genU_nsSymbol_ne_zero (nu : ℂ) (i m : Fin 3) : genU m (nsSymbol nu i) ≠ 0 := by
  rw [genU_nsSymbol]
  exact X_ne_zero _

/-- **A derivation that kills a polynomial commutes with multiplication by it.**  This is the
one algebraic mechanism behind the vanishing commutator of the BRST charge with the
Hamiltonian. -/
theorem comm_mulOp_of_apply_eq_zero (D : Module.End ℂ NSAlg)
    (hL : ∀ p q, D (p * q) = D p * q + p * D q) {a : NSAlg} (ha : D a = 0) :
    D * mulOp a = mulOp a * D := by
  refine LinearMap.ext fun p => ?_
  simp [Module.End.mul_apply, mulOp, LinearMap.mulLeft_apply, hL a p, ha]

/-- **The Navier–Stokes Hamiltonian** `H = ∑_i (π^i A_i + A_i π^i)` on the canonical algebra,
with `π^i = ∂/∂u_i` the momentum **conjugate to the velocity field** and
`A_i = ∑_j u_j(y) u_{i,j} − ν u_{i,jj}` the symbol built from the *fields* expanded in the
auxiliary coordinate — the first-order gauge-fixed form.  The symmetrized ordering
`π^i A_i + A_i π^i` is now essential, since `π^i` no longer commutes with `A_i`
(`genU_nsSymbol`). -/
def nsHamAlg (nu : ℂ) : Module.End ℂ NSAlg :=
  ∑ i : Fin 3, (genU i * mulOp (nsSymbol nu i) + mulOp (nsSymbol nu i) * genU i)

/-- The **second-order** Navier–Stokes Hamiltonian, built from the symbol
`A_i = ∑_j u_j(y) u_{i,j}(y) − ν u_{i,jj}` of `BookProof.NavierStokesGaugeY2` and the same
velocity momenta `π^i = ∂/∂u_i`. -/
def nsHamAlg2 (nu : ℂ) : Module.End ℂ NSAlg :=
  ∑ i : Fin 3, (genU i * mulOp (nsSymbol2 nu i) + mulOp (nsSymbol2 nu i) * genU i)

/-- **The velocity momenta commute with the first-order derivative-gauge generator.**  The
coefficients `u_{i,j}` of the generator are independent canonical variables, so `∂/∂u_m`
passes through them; this is what replaces the (trivial) commutation of the gauge generator
with the space momenta. -/
theorem genY_comm_genU (i j : Fin 3) : genY j * genU i = genU i * genY j := by
  refine LinearMap.ext fun p => ?_
  have h : ∀ k : Fin 3, pderiv (NSVar.u i) (X (NSVar.uD k j) * pderiv (NSVar.u k) p)
      = X (NSVar.uD k j) * pderiv (NSVar.u k) (pderiv (NSVar.u i) p) := fun k => by
    rw [pderiv_u_mul_uD, pderiv_swap (NSVar.u i) (NSVar.u k)]
  simp only [Module.End.mul_apply, genU_apply, genY_apply, map_sub, map_sum,
    pderiv_swap (NSVar.u i) (NSVar.y j), h]

/-- **The velocity momenta commute with the second-order derivative-gauge generator** as
well: its extra coefficients `u_{i,jj}` are independent canonical variables too. -/
theorem genY2_comm_genU (i j : Fin 3) : genY2 j * genU i = genU i * genY2 j := by
  refine LinearMap.ext fun p => ?_
  have h : ∀ k : Fin 3, pderiv (NSVar.u i) (X (NSVar.uD k j) * pderiv (NSVar.u k) p)
      = X (NSVar.uD k j) * pderiv (NSVar.u k) (pderiv (NSVar.u i) p) := fun k => by
    rw [pderiv_u_mul_uD, pderiv_swap (NSVar.u i) (NSVar.u k)]
  have h2 : ∀ k : Fin 3, pderiv (NSVar.u i) (X (NSVar.uL k) * pderiv (NSVar.uD k j) p)
      = X (NSVar.uL k) * pderiv (NSVar.uD k j) (pderiv (NSVar.u i) p) := fun k => by
    rw [pderiv_u_mul_uL, pderiv_swap (NSVar.u i) (NSVar.uD k j)]
  simp only [Module.End.mul_apply, genU_apply, genY2_apply, map_sub, map_sum,
    pderiv_swap (NSVar.u i) (NSVar.y j), h, h2]

/-- **The first-order gauge generator commutes with the Navier–Stokes Hamiltonian**: it is a
derivation annihilating the symbol, and it commutes with the momenta. -/
theorem genY_comm_nsHamAlg (nu : ℂ) (j : Fin 3) :
    genY j * nsHamAlg nu = nsHamAlg nu * genY j := by
  rw [nsHamAlg, Finset.mul_sum, Finset.sum_mul]
  refine Finset.sum_congr rfl fun i _ => ?_
  have hM : genY j * mulOp (nsSymbol nu i) = mulOp (nsSymbol nu i) * genY j :=
    comm_mulOp_of_apply_eq_zero (genY j) (genY_leibniz j) (genY_nsSymbol nu i j)
  have hX : genY j * genU i = genU i * genY j := genY_comm_genU i j
  have h1 : genY j * (genU i * mulOp (nsSymbol nu i))
      = (genU i * mulOp (nsSymbol nu i)) * genY j := by
    rw [← mul_assoc, hX, mul_assoc, hM, ← mul_assoc]
  have h2 : genY j * (mulOp (nsSymbol nu i) * genU i)
      = (mulOp (nsSymbol nu i) * genU i) * genY j := by
    rw [← mul_assoc, hM, mul_assoc, hX, ← mul_assoc]
  rw [mul_add, add_mul, h1, h2]

/-- **The second-order gauge generator commutes with the second-order Navier–Stokes
Hamiltonian.** -/
theorem genY2_comm_nsHamAlg2 (nu : ℂ) (j : Fin 3) :
    genY2 j * nsHamAlg2 nu = nsHamAlg2 nu * genY2 j := by
  rw [nsHamAlg2, Finset.mul_sum, Finset.sum_mul]
  refine Finset.sum_congr rfl fun i _ => ?_
  have hM : genY2 j * mulOp (nsSymbol2 nu i) = mulOp (nsSymbol2 nu i) * genY2 j :=
    comm_mulOp_of_apply_eq_zero (genY2 j) (genY2_leibniz j) (genY2_nsSymbol2 nu i j)
  have hX : genY2 j * genU i = genU i * genY2 j := genY2_comm_genU i j
  have h1 : genY2 j * (genU i * mulOp (nsSymbol2 nu i))
      = (genU i * mulOp (nsSymbol2 nu i)) * genY2 j := by
    rw [← mul_assoc, hX, mul_assoc, hM, ← mul_assoc]
  have h2 : genY2 j * (mulOp (nsSymbol2 nu i) * genU i)
      = (mulOp (nsSymbol2 nu i) * genU i) * genY2 j := by
    rw [← mul_assoc, hM, mul_assoc, hX, ← mul_assoc]
  rw [mul_add, add_mul, h1, h2]

/-! ### The correction `π^i = ∂/∂u_i` changes the Hamiltonian

The superseded form of the Hamiltonian, built with the space momentum `π^i = ∂/∂x_i`, is
kept below only in order to record *why* it had to be corrected: the Navier–Stokes symbol
carries no `x`-dependence, so with that momentum the two orderings coincide and the
Hamiltonian annihilates the constant state, whereas the correct velocity momentum produces
the divergence `∑_i u_{i,i}` there. -/

/-- The **superseded** Hamiltonian built with the space momentum `∂/∂x_i` instead of the
momentum `∂/∂u_i` conjugate to the velocity.  It is retained only for the comparison
`nsHamAlg_ne_nsHamAlgX`. -/
def nsHamAlgX (nu : ℂ) : Module.End ℂ NSAlg :=
  ∑ i : Fin 3, (genX i * mulOp (nsSymbol nu i) + mulOp (nsSymbol nu i) * genX i)

/-- With the velocity momentum the Hamiltonian does not annihilate the constant state: it
returns the divergence `∑_i u_{i,i}` of the velocity field. -/
theorem nsHamAlg_one (nu : ℂ) : nsHamAlg nu 1 = ∑ i : Fin 3, X (NSVar.uD i i) := by
  rw [nsHamAlg, LinearMap.sum_apply]
  refine Finset.sum_congr rfl fun i _ => ?_
  have h1 : (genU i * mulOp (nsSymbol nu i)) 1 = X (NSVar.uD i i) := by
    rw [Module.End.mul_apply, mulOp, LinearMap.mulLeft_apply, mul_one, genU_nsSymbol]
  have h2 : (mulOp (nsSymbol nu i) * genU i) 1 = 0 := by
    rw [Module.End.mul_apply, genU_apply]
    simp [mulOp]
  rw [LinearMap.add_apply, h1, h2, add_zero]

/-- With the space momentum it does annihilate the constant state, because the symbol has no
`x`-dependence. -/
theorem nsHamAlgX_one (nu : ℂ) : nsHamAlgX nu 1 = 0 := by
  rw [nsHamAlgX, LinearMap.sum_apply]
  refine Finset.sum_eq_zero fun i _ => ?_
  have h1 : (genX i * mulOp (nsSymbol nu i)) 1 = 0 := by
    rw [Module.End.mul_apply, mulOp, LinearMap.mulLeft_apply, mul_one, genX_nsSymbol]
  have h2 : (mulOp (nsSymbol nu i) * genX i) 1 = 0 := by
    rw [Module.End.mul_apply, genX_apply]
    simp [mulOp]
  rw [LinearMap.add_apply, h1, h2, add_zero]

/-- The Hamiltonian built with the velocity momentum does not annihilate the constant
state. -/
theorem nsHamAlg_one_ne_zero (nu : ℂ) : nsHamAlg nu 1 ≠ 0 := by
  rw [nsHamAlg_one]
  intro h
  have hc := congrArg (MvPolynomial.coeff (Finsupp.single (NSVar.uD 0 0) 1)) h
  rw [MvPolynomial.coeff_sum] at hc
  rw [Finset.sum_eq_single (0 : Fin 3), MvPolynomial.coeff_X] at hc
  · exact one_ne_zero hc
  · intro b _ hb
    rw [MvPolynomial.coeff_X']
    exact if_neg fun hh => hb (by
      have := (Finsupp.single_left_injective (by norm_num) hh)
      simpa using this)
  · intro h0
    exact absurd (Finset.mem_univ (0 : Fin 3)) h0

/-- **The correction matters**: the Navier–Stokes Hamiltonian built with the momentum
`π^i = ∂/∂u_i` conjugate to the velocity is *not* the operator obtained with the space
momentum `∂/∂x_i`. -/
theorem nsHamAlg_ne_nsHamAlgX (nu : ℂ) : nsHamAlg nu ≠ nsHamAlgX nu := by
  intro h
  refine nsHamAlg_one_ne_zero nu ?_
  rw [h, nsHamAlgX_one]

/-! ## 4. The BRST charge of the derivative gauge -/

/-- The **constraint operators** on the graded space: the first-order derivative-gauge
generators `G_j = ∂/∂y_j − u_{i,j} ∂/∂u_i`, acting on the bosonic factor. -/
def nsGaugeConstraint (j : Fin 3) : Module.End ℂ NSGraded := nsBos (genY j)

/-- The **constraint operators** of the second-order gauge, `G²_j`. -/
def nsGaugeConstraint2 (j : Fin 3) : Module.End ℂ NSGraded := nsBos (genY2 j)

/-- **The BRST charge of the derivative gauge fixing**, `Ω = ∑_j G_j χ_j`.  The constraints
are abelian, so the cubic ghost term of the general charge is absent. -/
def nsDerivBrstCharge : Module.End ℂ NSGraded := glin nsGaugeConstraint nsChi

/-- **The BRST charge of the second-order derivative gauge fixing**, `Ω = ∑_j G²_j χ_j`. -/
def nsDerivBrstCharge2 : Module.End ℂ NSGraded := glin nsGaugeConstraint2 nsChi

/-- The **Hamiltonian on the graded space**: the Navier–Stokes Hamiltonian acting on the
bosonic factor, the ghosts carrying no energy. -/
def nsHamiltonian (nu : ℂ) : Module.End ℂ NSGraded := nsBos (nsHamAlg nu)

/-- The second-order Hamiltonian on the graded space. -/
def nsHamiltonian2 (nu : ℂ) : Module.End ℂ NSGraded := nsBos (nsHamAlg2 nu)

/-- The constraints commute with each other on the graded space (the derivative gauge algebra
is abelian, hence first class). -/
theorem nsGaugeConstraint_comm (j k : Fin 3) :
    nsGaugeConstraint j * nsGaugeConstraint k = nsGaugeConstraint k * nsGaugeConstraint j := by
  have h := genY_genY_commute j k
  rw [Ring.lie_def, sub_eq_zero] at h
  rw [nsGaugeConstraint, nsGaugeConstraint, ← nsBos_mul, ← nsBos_mul, h]

theorem nsGaugeConstraint2_comm (j k : Fin 3) :
    nsGaugeConstraint2 j * nsGaugeConstraint2 k
      = nsGaugeConstraint2 k * nsGaugeConstraint2 j := by
  have h := genY2_genY2_commute j k
  rw [Ring.lie_def, sub_eq_zero] at h
  rw [nsGaugeConstraint2, nsGaugeConstraint2, ← nsBos_mul, ← nsBos_mul, h]

/-- **The BRST charge of the derivative gauge is nilpotent**, `Ω² = 0`. -/
theorem nsDerivBrstCharge_nilpotent : nsDerivBrstCharge * nsDerivBrstCharge = 0 :=
  brst_abelian_nilpotent nsGradedGhostCar
    (fun _ _ => nsBos_nsGh_comm _ _) (fun _ _ => nsBos_nsGh_comm _ _)
    nsGaugeConstraint_comm

/-- **The second-order BRST charge is nilpotent**, `Ω² = 0`. -/
theorem nsDerivBrstCharge2_nilpotent : nsDerivBrstCharge2 * nsDerivBrstCharge2 = 0 :=
  brst_abelian_nilpotent nsGradedGhostCar
    (fun _ _ => nsBos_nsGh_comm _ _) (fun _ _ => nsBos_nsGh_comm _ _)
    nsGaugeConstraint2_comm

/-! ## 5. The headline: the charge commutes with the Hamiltonian -/

/-- A general commutation lemma: a bosonic operator commuting with every constraint commutes
with the whole abelian BRST charge, because bosonic and ghost operators commute. -/
theorem glin_comm_bos (G : Fin 3 → Module.End ℂ NSAlg) (B : Module.End ℂ NSAlg)
    (hcomm : ∀ j, G j * B = B * G j) :
    ⁅glin (fun j => nsBos (G j)) nsChi, nsBos B⁆ = 0 := by
  rw [Ring.lie_def, sub_eq_zero, glin, Finset.sum_mul, Finset.mul_sum]
  refine Finset.sum_congr rfl fun j _ => ?_
  have hc : nsChi j * nsBos B = nsBos B * nsChi j := (nsBos_nsGh_comm B (nsGhostCre j)).symm
  calc nsBos (G j) * nsChi j * nsBos B
      = nsBos (G j) * (nsChi j * nsBos B) := by rw [mul_assoc]
    _ = nsBos (G j) * (nsBos B * nsChi j) := by rw [hc]
    _ = nsBos (G j * B) * nsChi j := by rw [nsBos_mul, mul_assoc]
    _ = nsBos (B * G j) * nsChi j := by rw [hcomm j]
    _ = nsBos B * (nsBos (G j) * nsChi j) := by rw [nsBos_mul, mul_assoc]

/-- **Headline.**  *The BRST charge of the gauge fixing of the variables representing the
spatial derivatives of the velocity field has the correct commutator with the Navier–Stokes
Hamiltonian*: the charge is odd, the Hamiltonian even, and

`⁅Ω, H⁆ = 0`.

Equivalently the gauge symmetry is a symmetry of the dynamics, so the BRST charge is
conserved and the physical (BRST-closed) states evolve among themselves. -/
theorem nsDerivBrstCharge_comm_hamiltonian (nu : ℂ) :
    ⁅nsDerivBrstCharge, nsHamiltonian nu⁆ = 0 :=
  glin_comm_bos genY (nsHamAlg nu) (fun j => genY_comm_nsHamAlg nu j)

/-- **Headline (second order).**  The same for the second-order gauge fixing, in which the
Laplacian modes `u_{i,jj}` are also tied to the expansion of the field:
`⁅Ω, H⁆ = 0`. -/
theorem nsDerivBrstCharge2_comm_hamiltonian2 (nu : ℂ) :
    ⁅nsDerivBrstCharge2, nsHamiltonian2 nu⁆ = 0 :=
  glin_comm_bos genY2 (nsHamAlg2 nu) (fun j => genY2_comm_nsHamAlg2 nu j)

/-- The commutator in the explicit form `Ω H = H Ω`. -/
theorem nsDerivBrstCharge_hamiltonian_comm (nu : ℂ) :
    nsDerivBrstCharge * nsHamiltonian nu = nsHamiltonian nu * nsDerivBrstCharge := by
  have h := nsDerivBrstCharge_comm_hamiltonian nu
  rwa [Ring.lie_def, sub_eq_zero] at h

/-- The second-order commutator in the explicit form `Ω H = H Ω`. -/
theorem nsDerivBrstCharge2_hamiltonian2_comm (nu : ℂ) :
    nsDerivBrstCharge2 * nsHamiltonian2 nu = nsHamiltonian2 nu * nsDerivBrstCharge2 := by
  have h := nsDerivBrstCharge2_comm_hamiltonian2 nu
  rwa [Ring.lie_def, sub_eq_zero] at h

/-! ## 6. Consequences: the dynamics descends to the BRST cohomology -/

/-- **The Hamiltonian preserves the BRST-closed (physical) states.** -/
theorem nsHamiltonian_mapsTo_ker (nu : ℂ) {v : NSGraded} (hv : nsDerivBrstCharge v = 0) :
    nsDerivBrstCharge (nsHamiltonian nu v) = 0 := by
  have h := congrArg (fun L : Module.End ℂ NSGraded => L v)
    (nsDerivBrstCharge_hamiltonian_comm nu)
  simpa [Module.End.mul_apply, hv] using h

/-- **The Hamiltonian preserves the BRST-exact states.** -/
theorem nsHamiltonian_mapsTo_range (nu : ℂ) (w : NSGraded) :
    nsHamiltonian nu (nsDerivBrstCharge w) = nsDerivBrstCharge (nsHamiltonian nu w) := by
  have h := congrArg (fun L : Module.End ℂ NSGraded => L w)
    (nsDerivBrstCharge_hamiltonian_comm nu)
  simpa [Module.End.mul_apply] using h.symm

/-- The same at second order: the physical states are preserved. -/
theorem nsHamiltonian2_mapsTo_ker (nu : ℂ) {v : NSGraded} (hv : nsDerivBrstCharge2 v = 0) :
    nsDerivBrstCharge2 (nsHamiltonian2 nu v) = 0 := by
  have h := congrArg (fun L : Module.End ℂ NSGraded => L v)
    (nsDerivBrstCharge2_hamiltonian2_comm nu)
  simpa [Module.End.mul_apply, hv] using h

/-- The BRST cohomology of the derivative gauge: closed states modulo exact states. -/
abbrev nsBrstCohomology : Type :=
  (LinearMap.ker nsDerivBrstCharge) ⧸
    (LinearMap.range nsDerivBrstCharge).comap (LinearMap.ker nsDerivBrstCharge).subtype

/-- **The Hamiltonian descends to the BRST cohomology of the derivative gauge.**  This is the
operational content of `⁅Ω, H⁆ = 0`: the dynamics is well defined on gauge classes. -/
def nsBrstCohomologyMap (nu : ℂ) : nsBrstCohomology →ₗ[ℂ] nsBrstCohomology := by
  refine Submodule.mapQ _ _
    ((nsHamiltonian nu).restrict (p := LinearMap.ker nsDerivBrstCharge)
      (q := LinearMap.ker nsDerivBrstCharge)
      (fun v hv => nsHamiltonian_mapsTo_ker nu hv)) ?_
  rintro ⟨v, hv⟩ hmem
  obtain ⟨w, hw⟩ : ∃ w, nsDerivBrstCharge w = v := by
    simpa using hmem
  refine Submodule.mem_comap.2 ?_
  refine ⟨nsHamiltonian nu w, ?_⟩
  simpa [hw] using (nsHamiltonian_mapsTo_range nu w).symm

/-! ## 7. The charge is not zero -/

/-- A bosonic operator followed by a ghost operator acts factorwise on a simple tensor. -/
theorem nsBos_nsGh_apply_tmul (S : Module.End ℂ NSAlg) (T : Module.End ℂ nsGhostSpace)
    (p : NSAlg) (w : nsGhostSpace) :
    (nsBos S * nsGh T) (p ⊗ₜ[ℂ] w) = S p ⊗ₜ[ℂ] T w := by
  simp [nsBos, nsGh, Module.End.mul_apply]

/-- An abelian BRST charge on a simple tensor: `Ω (p ⊗ w) = ∑_j (G_j p) ⊗ (χ_j w)`. -/
theorem glin_bos_apply_tmul (G : Fin 3 → Module.End ℂ NSAlg) (p : NSAlg) (w : nsGhostSpace) :
    glin (fun j => nsBos (G j)) nsChi (p ⊗ₜ[ℂ] w)
      = ∑ j : Fin 3, G j p ⊗ₜ[ℂ] nsGhostCre j w := by
  rw [glin, LinearMap.sum_apply]
  exact Finset.sum_congr rfl fun j _ => nsBos_nsGh_apply_tmul (G j) (nsGhostCre j) p w

/-- The first-order BRST charge on a simple tensor. -/
theorem nsDerivBrstCharge_apply_tmul (p : NSAlg) (w : nsGhostSpace) :
    nsDerivBrstCharge (p ⊗ₜ[ℂ] w) = ∑ j : Fin 3, genY j p ⊗ₜ[ℂ] nsGhostCre j w :=
  glin_bos_apply_tmul genY p w

/-- The second-order BRST charge on a simple tensor. -/
theorem nsDerivBrstCharge2_apply_tmul (p : NSAlg) (w : nsGhostSpace) :
    nsDerivBrstCharge2 (p ⊗ₜ[ℂ] w) = ∑ j : Fin 3, genY2 j p ⊗ₜ[ℂ] nsGhostCre j w :=
  glin_bos_apply_tmul genY2 p w

/-- Evaluation of the bosonic factor at the origin, keeping the ghost factor: a linear
functional used only to see that a simple tensor is non-zero. -/
def ghostComponent : NSGraded →ₗ[ℂ] nsGhostSpace :=
  (TensorProduct.lid ℂ nsGhostSpace).toLinearMap ∘ₗ
    LinearMap.rTensor nsGhostSpace (MvPolynomial.aeval (fun _ => (0 : ℂ))).toLinearMap

theorem ghostComponent_tmul (p : NSAlg) (w : nsGhostSpace) :
    ghostComponent (p ⊗ₜ[ℂ] w) = (MvPolynomial.aeval (fun _ => (0 : ℂ)) p) • w := by
  simp [ghostComponent]

/-- **The BRST charge of the derivative gauge is not the zero operator**, so the commutation
relation above is not vacuous: on `y_0 ⊗ 1` it produces the one-ghost state `1 ⊗ χ_0`. -/
theorem nsDerivBrstCharge_ne_zero : nsDerivBrstCharge ≠ 0 := by
  intro h
  have happ : nsDerivBrstCharge (X (NSVar.y 0) ⊗ₜ[ℂ] (1 : nsGhostSpace)) = 0 := by
    rw [h]; simp
  rw [nsDerivBrstCharge_apply_tmul] at happ
  have hterm : ∀ j : Fin 3, j ≠ 0 →
      genY j (X (NSVar.y 0)) ⊗ₜ[ℂ] nsGhostCre j (1 : nsGhostSpace) = 0 := by
    intro j hj
    have hzero : genY j (X (NSVar.y 0)) = 0 := by
      simp [genY_apply, pderiv_X, Ne.symm hj]
    rw [hzero, TensorProduct.zero_tmul]
  rw [Finset.sum_eq_single (0 : Fin 3) (fun j _ hj => hterm j hj) (by simp)] at happ
  have h0 : genY (0 : Fin 3) (X (NSVar.y 0)) = 1 := by
    simp [genY_apply, pderiv_X]
  rw [h0] at happ
  have hgh := congrArg ghostComponent happ
  rw [ghostComponent_tmul] at hgh
  simp [nsGhostCre] at hgh

/-- **The second-order BRST charge is not the zero operator** either. -/
theorem nsDerivBrstCharge2_ne_zero : nsDerivBrstCharge2 ≠ 0 := by
  intro h
  have happ : nsDerivBrstCharge2 (X (NSVar.y 0) ⊗ₜ[ℂ] (1 : nsGhostSpace)) = 0 := by
    rw [h]; simp
  rw [nsDerivBrstCharge2_apply_tmul] at happ
  have hterm : ∀ j : Fin 3, j ≠ 0 →
      genY2 j (X (NSVar.y 0)) ⊗ₜ[ℂ] nsGhostCre j (1 : nsGhostSpace) = 0 := by
    intro j hj
    have hzero : genY2 j (X (NSVar.y 0)) = 0 := by
      simp [genY2_apply, pderiv_X, Ne.symm hj]
    rw [hzero, TensorProduct.zero_tmul]
  rw [Finset.sum_eq_single (0 : Fin 3) (fun j _ hj => hterm j hj) (by simp)] at happ
  have h0 : genY2 (0 : Fin 3) (X (NSVar.y 0)) = 1 := by
    simp [genY2_apply, pderiv_X]
  rw [h0] at happ
  have hgh := congrArg ghostComponent happ
  rw [ghostComponent_tmul] at hgh
  simp [nsGhostCre] at hgh

end

end BookProof.NsBrstDerivativeGauge
