import Mathlib
import BookProof.ChapterQg3DGaugeEsa
import BookProof.ChapterFarisLavineOnly

/-!
# The 3D gauge-fixed gravity Hamiltonian in the jet coordinates, **through Faris–Lavine**

`BookProof.ChapterQg3DGaugeEsa` proves essential self-adjointness of the `84`-coordinate
3D gauge-fixed gravity Hamiltonian — the densitized, Weyl-ordered Hamiltonian whose
coordinates are the four spacetime coordinates, the sixteen tetrad components `e_μ^a` and
the sixty-four **independent coordinates `E_{μν}^a` representing the spatial derivatives of
the tetrad** — by the Carleman flux criterion.  That criterion does not lift to the outer
Fock space.  This module re-proves the same statement, and strengthens it, using **only**
the commutator criterion of Faris–Lavine with the Friedrichs extension of
`N₁ = −Δ + ‖x‖²/4` as comparison operator, which does lift.

## What is proved

* `qgSigned_eq_sqSumOp` — the identification: for every real signature `κ` the operator
  `½ Σ_j κ_j π_j² + ½ Σ_m T_m²` is the kinetic-plus-squares operator `sqSumOp κ torsionVec`.
* **`qgSigned_esa_fl`**, **`qg3D_esa_fl`** — essential self-adjointness on the
  Gauss–polynomial core of `L²(ℝ⁸⁴)`, by Faris–Lavine, for every real signature and in
  particular for the physical hyperbolic signature `qgKappa`.
* `div3Vec`, `timeDerivVec`, `qgGaugeVec` — the two gauge-fixing families, written as linear
  forms in the `84` coordinates: the **3D gauge condition** `Σ_j E_{jj}^a = 0` (the spatial
  divergence of the tetrad, expressed in the coordinates that represent its spatial
  derivatives) and the **gauge fixing of the derivative coordinates** `E_{0ν}^a = 0` (the
  coordinates representing time derivatives are fixed to zero, which is what makes the
  formulation three-dimensional).
* **`qg3DGaugeFixed_esa_fl`** — the gauge-fixed Hamiltonian, torsion *and* both gauge-fixing
  families together, is essentially self-adjoint on the core, by Faris–Lavine.
* **`qgGaugeOuterHam`, `qgGauge_sector_esa_fl`, `qgGauge_outerHam_esa_fl`** — the same
  Hamiltonian on the nested Fock space `⊕ₙ L²(ℝ^{84n})`, one copy of the one-particle
  Hamiltonian per particle, essentially self-adjoint on the finite-particle core.
* **`qg3DGaugeFixed_stone_flow`, `qgGauge_stone_flow`** — the unitary time evolution
  generated by the unique self-adjoint realization, on the one-particle space and on the
  nested Fock space (Stone).
* **`dsOp_number_conserving`, `qgGauge_number_conserving`** — the outer Hamiltonian
  **conserves the particle number**: it is block diagonal in the particle-number sectors, and
  its restriction to the `n`-particle sector is the `n`-particle Hamiltonian
  (`qgGaugeOuterHam_sector`).  This is what makes a spatial lattice regularization
  unnecessary: the sectors, not a lattice, cut the problem into pieces.

## Scope — this model carries **no scalaron**

The identification `qgSigned_eq_sqSumOp` of the Hamiltonian as a *kinetic-plus-squares*
operator is a statement about the pure tetrad/jet sector: kinetic term plus squares of
**linear** forms in the `84` coordinates.  It does **not** extend to the gravity Hamiltonian
this development delivers, which also carries the scalaron with the **full exponential**
Einstein-frame potential and no Taylor expansion: that potential is not a polynomial of
degree `≤ 2`, hence not a half-sum of squares of linear forms
(`BookProof.ScalaronNotQuadratic.starobinskyV_not_quadratic`,
`starobinskyPot_not_sum_of_squares`), so no kinetic-plus-squares identification of it is
possible or claimed.  The Hamiltonian with the vielbein, the scalaron, the 3D gauge fixing
and the gauge fixing of the derivative variables is
`BookProof.QgVielbeinScalaronGaugeFL.secHam _ (qgFullModes g)`, whose essential
self-adjointness on the outer Fock space is proved by Faris–Lavine against a comparison
operator whose fibre carries the exponential wall itself.

No spectral information and no mass gap is claimed.

Everything is `sorry`-free and `axiom`-free.
-/

namespace BookProof.Qg3DGaugeFL

open BookProof.QuantumGravity3DGauge BookProof.Qg3DGaugeEsa
open BookProof.QgOuterFock BookProof.FarisLavineOnly
open BookProof.HermiteProductCore BookProof.FarisLavine BookProof.DirectSumEsa
open BookProof.YangMillsHermite
open BookProof.StoneBridge BookProof.EsaClosure BookProof.ChapterStoneResolvent

noncomputable section

/-! ## 1. The one-particle Hamiltonian as a kinetic-plus-squares operator -/

theorem qgFqP_eq_diagP (kappa : Fin 84 → ℝ) : qgFqP kappa = diagP kappa := rfl

theorem qgFqQ_eq_gramQ : qgFqQ = gramQ torsionVec := rfl

/-- **The gravity Hamiltonian is a kinetic-plus-squares operator**: for every real signature
`κ`, `½ Σ_j κ_j π_j² + ½ Σ_m T_m²` is `sqSumOp κ torsionVec`, the operator whose family of
linear forms is the sixty-four torsion forms. -/
theorem qgSigned_eq_sqSumOp (kappa : Fin 84 → ℝ) :
    signedOp kappa (qgMom (coreRepPoly 84)) (torsionOps (coreRepPoly 84))
      = sqSumOp kappa torsionVec := by
  rw [qgSigned_eq_fqOp, sqSumOp_eq_fqOp, qgFqP_eq_diagP, qgFqQ_eq_gramQ]

/-- **Essential self-adjointness of the gravity Hamiltonian on the Gauss–polynomial core, by
Faris–Lavine**, for every real signature — in particular with no positivity, ellipticity or
definiteness assumption on the kinetic term.  Unlike
`BookProof.Qg3DGaugeEsa.qgSigned_essentiallySelfAdjointOn_core`, whose proof is the Carleman
flux criterion, this proof is Theorem 1 of Faris–Lavine against the Friedrichs extension of
`N₁ = −Δ + ‖x‖²/4`: the certificate that lifts to the outer Fock space. -/
theorem qgSigned_esa_fl (kappa : Fin 84 → ℝ) :
    EssentiallySelfAdjointOn (polyGaussCore (d := 84))
      (signedOp kappa (qgMom (coreRepPoly 84)) (torsionOps (coreRepPoly 84))) := by
  rw [qgSigned_eq_sqSumOp kappa]
  exact sqSumOp_esa_farisLavine kappa torsionVec

/-- The physical, *hyperbolic* instance: the densitized, Weyl-ordered 3D gauge-fixed gravity
Hamiltonian is essentially self-adjoint on the Gauss–polynomial core of `L²(ℝ⁸⁴)`, by
Faris–Lavine. -/
theorem qg3D_esa_fl :
    EssentiallySelfAdjointOn (polyGaussCore (d := 84)) (qg3DHamiltonian (coreRepPoly 84)) :=
  qgSigned_esa_fl qgKappa

/-! ## 2. The gauge-fixing forms -/

/-- The spatial directions among the four spacetime directions. -/
def spatial (j : Fin 3) : Fin 4 := j.succ

/-- **The 3D gauge condition** `Σ_j E_{jj}^a = 0`: the spatial divergence of the tetrad,
written in the coordinates that represent its spatial derivatives. -/
def div3Vec (a : Fin 4) (i : Fin 84) : ℝ :=
  ∑ j : Fin 3, (if i = idxDE (spatial j) (spatial j) a then 1 else 0)

/-- **The gauge fixing of the derivative coordinates** `E_{0ν}^a = 0`: the coordinates that
represent time derivatives of the tetrad are fixed to zero, which is what makes the
formulation three-dimensional. -/
def timeDerivVec (q : Fin 4 × Fin 4) (i : Fin 84) : ℝ :=
  if i = idxDE 0 q.1 q.2 then 1 else 0

/-- The complete gauge-fixing family: the four 3D gauge conditions and the sixteen
conditions on the derivative coordinates. -/
def qgGaugeVec : (Fin 4) ⊕ (Fin 4 × Fin 4) → Fin 84 → ℝ := Sum.elim div3Vec timeDerivVec

/-- The linear forms of the gauge-fixed Hamiltonian: the torsion forms together with the two
gauge-fixing families. -/
def qgFullVec : (Fin 64) ⊕ ((Fin 4) ⊕ (Fin 4 × Fin 4)) → Fin 84 → ℝ :=
  Sum.elim torsionVec qgGaugeVec

@[simp] theorem qgFullVec_torsion (m : Fin 64) : qgFullVec (Sum.inl m) = torsionVec m := rfl

@[simp] theorem qgFullVec_div3 (a : Fin 4) : qgFullVec (Sum.inr (Sum.inl a)) = div3Vec a := rfl

@[simp] theorem qgFullVec_timeDeriv (q : Fin 4 × Fin 4) :
    qgFullVec (Sum.inr (Sum.inr q)) = timeDerivVec q := rfl

/-- The gauge-fixing forms are not vacuous: the 3D gauge condition really involves the
derivative coordinates. -/
theorem div3Vec_ne_zero (a : Fin 4) : div3Vec a (idxDE (spatial 0) (spatial 0) a) = 1 := by
  rw [div3Vec, Fin.sum_univ_three]
  have h1 : idxDE (spatial 0) (spatial 0) a ≠ idxDE (spatial 1) (spatial 1) a := by
    simp [idxDE, spatial, Fin.ext_iff]
  have h2 : idxDE (spatial 0) (spatial 0) a ≠ idxDE (spatial 2) (spatial 2) a := by
    simp [idxDE, spatial, Fin.ext_iff]
  simp [h1, h2]

/-- The gauge fixing of a derivative coordinate really involves that coordinate. -/
theorem timeDerivVec_ne_zero (q : Fin 4 × Fin 4) : timeDerivVec q (idxDE 0 q.1 q.2) = 1 := by
  simp [timeDerivVec]

/-- **The complete 3D gauge-fixed gravity Hamiltonian on the one-particle space**:
`½ Σ_j κ_j π_j² + ½ Σ_m T_m² + ½ Σ (gauge-fixing forms)²`, with the independent coordinates
for the spatial derivatives of the tetrad, the 3D gauge condition and the gauge fixing of
the derivative coordinates. -/
def qg3DGaugeFixedHam : (polyGaussCore (d := 84)) →ₗ[ℂ] L2d 84 := sqSumOp qgKappa qgFullVec

/-- **Essential self-adjointness of the complete gauge-fixed gravity Hamiltonian on the
Gauss–polynomial core, by Faris–Lavine.** -/
theorem qg3DGaugeFixed_esa_fl :
    EssentiallySelfAdjointOn (polyGaussCore (d := 84)) qg3DGaugeFixedHam :=
  sqSumOp_esa_farisLavine qgKappa qgFullVec

/-! ## 3. The nested Fock space -/

/-- The `n`-particle lift of a one-particle family of linear forms: one copy of every form
in every particle's coordinate block. -/
def liftVecN {R : Type} [Fintype R] (v : R → Fin 84 → ℝ) (n : ℕ) (r : Fin n × R)
    (I : Fin (n * 84)) : ℝ :=
  if partOf I = r.1 then v r.2 (modeOf I) else 0

/-- **The `n`-particle gauge-fixed gravity Hamiltonian** `Σ_p h^{(p)}` on the
Gauss–polynomial core of `L²(ℝ^{84n})`. -/
def qgGaugeSectorHam (n : ℕ) : (polyGaussCore (d := n * 84)) →ₗ[ℂ] L2d (n * 84) :=
  sqSumOp (qgKappaN n) (liftVecN qgFullVec n)

/-- **The gauge-fixed gravity Hamiltonian on the nested Fock space.** -/
def qgGaugeOuterHam : qgOuterCore →ₗ[ℂ] qgOuterFock := dsOp (fun n : ℕ => qgGaugeSectorHam n)

/-- Each sector is essentially self-adjoint on its Gauss–polynomial core, by
Faris–Lavine. -/
theorem qgGauge_sector_esa_fl (n : ℕ) :
    EssentiallySelfAdjointOn (polyGaussCore (d := n * 84)) (qgGaugeSectorHam n) :=
  sqSumOp_esa_farisLavine _ _

theorem qgGaugeSectorHam_symmetricOn (n : ℕ) :
    SymmetricOn (polyGaussCore (d := n * 84)) (qgGaugeSectorHam n) :=
  sqSumOp_symmetricOn _ _

/-- **The gauge-fixed gravity Hamiltonian is essentially self-adjoint on the
finite-particle core of the nested Fock space, by Faris–Lavine.** -/
theorem qgGauge_outerHam_esa_fl : EssentiallySelfAdjointOn qgOuterCore qgGaugeOuterHam :=
  dsOp_essentiallySelfAdjointOn _ fun n => qgGauge_sector_esa_fl n

theorem qgGaugeOuterHam_symmetricOn : SymmetricOn qgOuterCore qgGaugeOuterHam :=
  dsOp_symmetricOn _ fun n => qgGaugeSectorHam_symmetricOn n

/-- **The unitary flow of the gauge-fixed gravity Hamiltonian on the nested Fock space.**
Essential self-adjointness on the dense finite-particle core gives a unique self-adjoint
realization, and Stone's theorem gives the time evolution it generates. -/
theorem qgGauge_stone_flow :
    ∃ (T : UnboundedSelfAdjoint qgOuterFock) (U : ℝ → (qgOuterFock →L[ℂ] qgOuterFock)),
      IsSelfAdjointExtension qgGaugeOuterHam T.op ∧ IsStoneFlow T U :=
  exists_stone_flow_of_esa _ qgOuterCore_dense qgGaugeOuterHam_symmetricOn
    qgGauge_outerHam_esa_fl

/-- The unitary flow of the one-particle gauge-fixed gravity Hamiltonian. -/
theorem qg3DGaugeFixed_stone_flow :
    ∃ (T : UnboundedSelfAdjoint (L2d 84)) (U : ℝ → (L2d 84 →L[ℂ] L2d 84)),
      IsSelfAdjointExtension qg3DGaugeFixedHam T.op ∧ IsStoneFlow T U :=
  exists_stone_flow_of_esa _ polyGaussCore_dense (sqSumOp_symmetricOn _ _)
    qg3DGaugeFixed_esa_fl

/-! ## 4. Particle-number conservation -/

section Number

variable {ι : Type*} {G : ι → Type*} [∀ i, NormedAddCommGroup (G i)]
  [∀ i, InnerProductSpace ℂ (G i)] {D : ∀ i, Submodule ℂ (G i)}

/-- The direct-sum operator acts sector by sector. -/
theorem dsOp_sector (H : ∀ i, D i →ₗ[ℂ] G i) (x : dsCore D) (i : ι) :
    ((dsOp H x : lp G 2) : ∀ i, G i) i = H i ⟨((x : lp G 2) : ∀ i, G i) i, x.2.2 i⟩ := rfl

/-- **The outer Hamiltonian conserves the particle number.**  A direct-sum operator is block
diagonal: a core vector living in the `n`-particle sector is mapped to a vector living in the
same sector.  Nothing is truncated and no lattice is involved — the particle-number sectors
are what decompose the problem. -/
theorem dsOp_number_conserving (H : ∀ i, D i →ₗ[ℂ] G i) (x : dsCore D) {n : ι}
    (hx : ∀ i, i ≠ n → ((x : lp G 2) : ∀ i, G i) i = 0) (i : ι) (hi : i ≠ n) :
    ((dsOp H x : lp G 2) : ∀ i, G i) i = 0 := by
  rw [dsOp_sector]
  have hz : (⟨((x : lp G 2) : ∀ i, G i) i, x.2.2 i⟩ : D i) = 0 := Subtype.ext (hx i hi)
  rw [hz, map_zero]

end Number

/-- The restriction of the outer Hamiltonian to the `n`-particle sector is the `n`-particle
Hamiltonian. -/
theorem qgGaugeOuterHam_sector (x : qgOuterCore) (n : ℕ) :
    ((qgGaugeOuterHam x : qgOuterFock) : ∀ n : ℕ, L2d (n * 84)) n
      = qgGaugeSectorHam n ⟨((x : qgOuterFock) : ∀ n : ℕ, L2d (n * 84)) n, x.2.2 n⟩ := rfl

/-- **The gauge-fixed gravity Hamiltonian conserves the particle number.** -/
theorem qgGauge_number_conserving (x : qgOuterCore) {n : ℕ}
    (hx : ∀ m, m ≠ n → ((x : qgOuterFock) : ∀ m : ℕ, L2d (m * 84)) m = 0) (m : ℕ) (hm : m ≠ n) :
    ((qgGaugeOuterHam x : qgOuterFock) : ∀ m : ℕ, L2d (m * 84)) m = 0 :=
  dsOp_number_conserving _ x hx m hm

end

end BookProof.Qg3DGaugeFL
