import Mathlib
import BookProof.ChapterWallEsaBddBelow
import BookProof.ChapterSchrodingerCutoffEsa
import BookProof.ChapterWallEsaSemibounded

/-!
# `−d²/dx² + (eˣ + e⁻ˣ)` is essentially self-adjoint

This module records, as an explicit theorem, the motivating example of the
Simader–Faris–Lavine programme: the Schrödinger operator with the
**non-polynomial, exponentially growing** potential

  `V(x) = eˣ + e⁻ˣ = 2 cosh x`

is essentially self-adjoint on the compactly supported smooth core of `L²(ℝ)`.

No new analysis is needed: `V` is smooth and bounded below (by `2`), and
`BookProof/ChapterWallEsaBddBelow.lean` already proves essential
self-adjointness of `−d²/dx² + V` for *every* smooth potential bounded below,
with no growth restriction from above.  What this module supplies is the
verification that `Vexp` meets those hypotheses and the resulting named
statements.

## Contents

* `contDiff_Vexp` — smoothness of `x ↦ eˣ + e⁻ˣ`.
* **`expPotential_esa`** — `−d²/dx² + (eˣ + e⁻ˣ)` is essentially self-adjoint
  on the compactly supported smooth core.
* `expPotential_stone_flow` — the resulting unitary group `e^{−itH}`.
* `coshPotential_esa` — the same statement written with `2 cosh x`.
* `expPotential_semibounded` — its quadratic form is non-negative on the core.

The elementary cutoff/commutator route to the same physics, at the level of
classical square-integrable solutions of `H u = ± i u`, is in
`BookProof/ChapterSchrodingerCutoffEsa.lean`
(`schrodinger_exp_deficiency_trivial_I` / `..._negI`); it is independent of the
machinery used here.
-/

namespace BookProof.ExpPotentialEsa

open MeasureTheory
open BookProof.FarisLavine BookProof.ScalaronEsa BookProof.ScalaronWallEsa
open BookProof.WallEsaBddBelow BookProof.EsaClosure BookProof.ChapterStoneResolvent
open BookProof.WallEsaSemibounded
open BookProof.SchrodingerCutoff (Vexp two_le_Vexp)

noncomputable section

/-- The exponential wall `x ↦ eˣ + e⁻ˣ` is smooth. -/
theorem contDiff_Vexp : ContDiff ℝ ((⊤ : ℕ∞) : WithTop ℕ∞) Vexp :=
  Real.contDiff_exp.add (Real.contDiff_exp.comp contDiff_neg)

/-- **`−d²/dx² + (eˣ + e⁻ˣ)` is essentially self-adjoint on the compactly
supported smooth core of `L²(ℝ)`.**  This is the motivating example of the
Simader–Faris–Lavine method: the potential grows faster than any polynomial, so
no relative-boundedness (Kato–Rellich) criterion applies to it. -/
theorem expPotential_esa :
    EssentiallySelfAdjointOn (ccDomain ℝ) (wallHam Vexp contDiff_Vexp) :=
  wallHam_essentiallySelfAdjoint_of_bddBelow Vexp contDiff_Vexp (c := 0)
    fun x => by linarith [two_le_Vexp x]

/-- **The unitary flow generated by `−d²/dx² + (eˣ + e⁻ˣ)`.** -/
theorem expPotential_stone_flow :
    ∃ (T : UnboundedSelfAdjoint (Lp ℂ 2 (volume : Measure ℝ)))
      (U : ℝ → (Lp ℂ 2 (volume : Measure ℝ) →L[ℂ] Lp ℂ 2 (volume : Measure ℝ))),
      IsSelfAdjointExtension (wallHam Vexp contDiff_Vexp) T.op ∧
        BookProof.StoneBridge.IsStoneFlow T U :=
  wallHam_stone_flow_of_bddBelow Vexp contDiff_Vexp (c := 0)
    fun x => by linarith [two_le_Vexp x]

/-- The `cosh` form of the potential is smooth. -/
theorem contDiff_twoCosh :
    ContDiff ℝ ((⊤ : ℕ∞) : WithTop ℕ∞) fun x : ℝ => 2 * Real.cosh x :=
  contDiff_const.mul Real.contDiff_cosh

/-- **`−d²/dx² + 2 cosh x` is essentially self-adjoint on the compactly supported
smooth core**, the same statement as `expPotential_esa` written with `cosh`. -/
theorem coshPotential_esa :
    EssentiallySelfAdjointOn (ccDomain ℝ)
      (wallHam (fun x : ℝ => 2 * Real.cosh x) contDiff_twoCosh) :=
  wallHam_essentiallySelfAdjoint_of_bddBelow _ contDiff_twoCosh (c := 0)
    fun x => by
      have h := Real.one_le_cosh x
      linarith

/-- **The quadratic form of `−d²/dx² + (eˣ + e⁻ˣ)` is non-negative** on the compactly
supported smooth core, since the potential is.  This is the semiboundedness the
shift-invert schemes work with. -/
theorem expPotential_semibounded :
    SemiboundedBelowOn (ccDomain ℝ) (wallHam Vexp contDiff_Vexp) 0 :=
  wallHam_nonneg_form Vexp contDiff_Vexp fun x => by linarith [two_le_Vexp x]

end

end BookProof.ExpPotentialEsa
