import BookProof.ChapterQgVielbeinScalaronGaugeFL.Part1
import BookProof.ChapterQgVielbeinScalaronGaugeFL.Part2

/-!
# Quantum gravity: vielbein **and** scalaron **and** 3D gauge fixing **and** the gauge
fixing of the derivative variables — essential self-adjointness by Faris–Lavine

This module assembles, in one Hamiltonian, every ingredient the strategy asks of the
gravity thread, and proves essential self-adjointness of the result on the outer Fock space
**only** through the commutator criterion of Faris–Lavine, with the Friedrichs extension of
a positive one-particle operator as comparison operator.

## The variables

The spatial slice is not discretized: the vielbein is expanded in its **exact Fourier
modes**, so a momentum runs over all of `ℤ³` and the spatial derivative is the exact symbol
`∂_μ ↦ i k_μ`.  There is no lattice and no truncation to finitely many modes.

At each momentum `k` the field-space components are

* the nine vielbein components `e_ν^i(k)` (`eIdx`), and
* the **twenty-seven derivative variables** `D_{μν}^i(k)` (`dIdx`), carried as *independent*
  coordinates, exactly as the coordinates representing spatial derivatives of the fields are
  carried in the `84`-coordinate formulation of the gravity Hamiltonian.

So `Comp` has `9 + 27 = 36` elements and a mode is a pair `(k, c)` (`GMode`).

## The quadratic form: three families of linear forms

`gCoef k F` is the coefficient vector of the linear form `F` at momentum `k`, and the
vielbein self-interaction is the Gram matrix `gGram` of the whole family:

* **torsion** `T_{μν}^i = D_{μν}^i − D_{νμ}^i` (`torsionF`) — written purely in the
  derivative variables, no derivative symbol anywhere;
* **the gauge fixing of the derivative variables** `G_{μν}^i = D_{μν}^i − i k_μ e_ν^i`
  (`dGaugeF`) — the condition that fixes an independent coordinate to the spatial derivative
  of a field;
* **the 3D gauge fixing** `C^i = Σ_μ i k_μ e_μ^i` (`gauge3dF`) — the transverse
  (divergence) condition on the spatial slice.

`formValue` evaluates a form on a field configuration, and

* `formValue_dGauge` — the derivative-gauge form is exactly `D_{μν}^i − i k_μ e_ν^i`;
* `torsion_eq_exact_of_gauge_fixed` — **on the gauge-fixing surface the torsion written in
  the independent derivative variables is the exact torsion** `i(k_μ e_ν^i − k_ν e_μ^i)` of
  the fields.  This is the precise sense in which the gauge fixing of the derivative
  variables does what it is meant to do.

## The scalaron

The scalaron is carried in position representation on the fibre `L²(ℝ_φ)` with the **full
exponential** Einstein-frame potential — `starobinskyWall`, no Taylor expansion, no
relative-boundedness hypothesis on the wall — and it couples to the trace of the vielbein at
arbitrary coupling constant `g` (`gCoupling`).

## What is proved

* `qgFullModes` — the mode data of the complete model, satisfying all five Faris–Lavine
  bounds uniformly in the momentum, with `κ = 855 + |g|` and band size `36`.
* **`qgFull_esa_farisLavine`** — essential self-adjointness on the domain of the lifted
  Friedrichs extension of the positive comparison operator.
* **`qgFull_esa_core_fl`** — the same on the finite-particle core, where the Hamiltonian is
  originally defined.
* **`starobinsky_qgFull_esa`**, **`starobinsky_qgFull_esa_core`** — the physical instance,
  with the full exponential Einstein-frame Starobinsky potential.
* **`qgFull_stone_flow`**, **`starobinsky_qgFull_stone_flow`** — the unitary time evolution
  generated by the unique self-adjoint realization (Stone), the finite-particle core being
  dense (`secCore_dense`).
* **`secHam_number_conserving`** — the outer Hamiltonian conserves the particle number: for
  any number function that is constant on the bands, every number sector is invariant.  For
  this model the bands are the momentum blocks, so `qgFull_momentum_conserving` and
  `qgFull_number_conserving` apply.
* Non-vacuity: each of the three families of linear forms, and the scalaron coupling, is
  really present (`gCoef_torsion_ne_zero`, `gCoef_dGauge_ne_zero`, `gCoef_gauge3d_ne_zero`,
  `gGram_diag_ne_zero`, `gCoupling_ne_zero`), and the mode set is infinite.

No spectral information, no mass gap and no continuum limit is claimed.

Everything is `sorry`-free and `axiom`-free.
-/
