import Mathlib
import BookProof.ChapterQgContinuumModeInstance
import BookProof.ChapterFarisLavineOnly

/-!
# Quantum gravity: vielbein **and** scalaron **and** 3D gauge fixing **and** the gauge
fixing of the derivative variables — essential self-adjointness by Faris–Lavine

This module assembles, in one Hamiltonian, every ingredient the strategy asks of the
gravity thread, and proves essential self-adjointness of the result on the outer Fock space
**only** through the commutator criterion of Faris–Lavine, with the Friedrichs extension of
a positive one-particle operator as comparison operator.

## The variables

The spatial slice is not discretized: the vielbein is expanded in its **exact Fourier
modes**, so a momentum runs over all of `ℤ³` and the spatial derivative is the exact symbol
`∂_μ ↦ i k_μ`.  There is no lattice and no truncation to finitely many modes.

At each momentum `k` the field-space components are

* the nine vielbein components `e_ν^i(k)` (`eIdx`), and
* the **twenty-seven derivative variables** `D_{μν}^i(k)` (`dIdx`), carried as *independent*
  coordinates, exactly as the coordinates representing spatial derivatives of the fields are
  carried in the `84`-coordinate formulation of the gravity Hamiltonian.

So `Comp` has `9 + 27 = 36` elements and a mode is a pair `(k, c)` (`GMode`).

## The quadratic form: three families of linear forms

`gCoef k F` is the coefficient vector of the linear form `F` at momentum `k`, and the
vielbein self-interaction is the Gram matrix `gGram` of the whole family:

* **torsion** `T_{μν}^i = D_{μν}^i − D_{νμ}^i` (`torsionF`) — written purely in the
  derivative variables, no derivative symbol anywhere;
* **the gauge fixing of the derivative variables** `G_{μν}^i = D_{μν}^i − i k_μ e_ν^i`
  (`dGaugeF`) — the condition that fixes an independent coordinate to the spatial derivative
  of a field;
* **the 3D gauge fixing** `C^i = Σ_μ i k_μ e_μ^i` (`gauge3dF`) — the transverse
  (divergence) condition on the spatial slice.

`formValue` evaluates a form on a field configuration, and

* `formValue_dGauge` — the derivative-gauge form is exactly `D_{μν}^i − i k_μ e_ν^i`;
* `torsion_eq_exact_of_gauge_fixed` — **on the gauge-fixing surface the torsion written in
  the independent derivative variables is the exact torsion** `i(k_μ e_ν^i − k_ν e_μ^i)` of
  the fields.  This is the precise sense in which the gauge fixing of the derivative
  variables does what it is meant to do.

## The scalaron

The scalaron is carried in position representation on the fibre `L²(ℝ_φ)` with the **full
exponential** Einstein-frame potential — `starobinskyWall`, no Taylor expansion, no
relative-boundedness hypothesis on the wall — and it couples to the trace of the vielbein at
arbitrary coupling constant `g` (`gCoupling`).

## What is proved

* `qgFullModes` — the mode data of the complete model, satisfying all five Faris–Lavine
  bounds uniformly in the momentum, with `κ = 855 + |g|` and band size `36`.
* **`qgFull_esa_farisLavine`** — essential self-adjointness on the domain of the lifted
  Friedrichs extension of the positive comparison operator.
* **`qgFull_esa_core_fl`** — the same on the finite-particle core, where the Hamiltonian is
  originally defined.
* **`starobinsky_qgFull_esa`**, **`starobinsky_qgFull_esa_core`** — the physical instance,
  with the full exponential Einstein-frame Starobinsky potential.
* **`qgFull_stone_flow`**, **`starobinsky_qgFull_stone_flow`** — the unitary time evolution
  generated by the unique self-adjoint realization (Stone), the finite-particle core being
  dense (`secCore_dense`).
* **`secHam_number_conserving`** — the outer Hamiltonian conserves the particle number: for
  any number function that is constant on the bands, every number sector is invariant.  For
  this model the bands are the momentum blocks, so `qgFull_momentum_conserving` and
  `qgFull_number_conserving` apply.
* Non-vacuity: each of the three families of linear forms, and the scalaron coupling, is
  really present (`gCoef_torsion_ne_zero`, `gCoef_dGauge_ne_zero`, `gCoef_gauge3d_ne_zero`,
  `gGram_diag_ne_zero`, `gCoupling_ne_zero`), and the mode set is infinite.

No spectral information, no mass gap and no continuum limit is claimed.

Everything is `sorry`-free and `axiom`-free.
-/

namespace BookProof.QgVielbeinScalaronGaugeFL

open BookProof.ScalaronFiberFL BookProof.ScalaronOuterFockFL
open BookProof.QgVielbeinModeInstance BookProof.QgContinuumModeInstance
open BookProof.FarisLavine BookProof.QgOuterFockCoreFL
open BookProof.StoneBridge BookProof.EsaClosure BookProof.ChapterStoneResolvent
open BookProof.DirectSumEsa BookProof.ScalaronEsa

noncomputable section

/-! ## 1. The extended field-space components and the modes -/

/-- The field-space components at one momentum: the nine vielbein components `e_ν^i`
(`Sum.inl`) and the twenty-seven **independent derivative variables** `D_{μν}^i`
(`Sum.inr`). -/
abbrev Comp := (Fin 3 × Fin 3) ⊕ (Fin 3 × Fin 3 × Fin 3)

/-- A mode of the extended (vielbein + derivative variables) field space: a momentum in
`ℤ³` together with a component.  There are infinitely many — no lattice, no truncation. -/
abbrev GMode := Mom × Comp

/-- The vielbein component `e_ν^i`. -/
def eIdx (nu i : Fin 3) : Comp := Sum.inl (nu, i)

/-- The independent derivative variable `D_{μν}^i`, the coordinate that represents the
spatial derivative `∂_μ e_ν^i`. -/
def dIdx (mu nu i : Fin 3) : Comp := Sum.inr (mu, nu, i)

theorem card_comp : Fintype.card Comp = 36 := by decide

/-- The energy of a mode: the exact free symbol `σ_k = 1 + |k|²`. -/
def gSig (x : GMode) : ℝ := 1 + momSq x.1

theorem one_le_gSig (x : GMode) : 1 ≤ gSig x := by
  have := momSq_nonneg x.1
  simp only [gSig]
  linarith

theorem gSig_nonneg (x : GMode) : 0 ≤ gSig x := le_trans zero_le_one (one_le_gSig x)

/-- The band of a mode: the thirty-six components at the same momentum.  Momentum
conservation is what makes all the mode matrices banded. -/
def gNbr (x : GMode) : Finset GMode :=
  ({x.1} : Finset Mom) ×ˢ (Finset.univ : Finset Comp)

theorem mem_gNbr {x y : GMode} : y ∈ gNbr x ↔ y.1 = x.1 := by
  constructor
  · intro h
    simp only [gNbr, Finset.mem_product, Finset.mem_singleton] at h
    exact h.1
  · intro h
    simp only [gNbr, Finset.mem_product, Finset.mem_singleton, Finset.mem_univ, and_true]
    exact h

theorem card_gNbr (x : GMode) : ((gNbr x).card : ℝ) = 36 := by
  simp [gNbr]

/-! ## 2. The three families of linear forms -/

/-- The linear forms of the gauge-fixed gravity Hamiltonian: the twenty-seven torsion forms,
the twenty-seven forms of the derivative-variable gauge fixing, and the three forms of the
3D (transverse) gauge fixing. -/
abbrev FormIdx := (Fin 3 × Fin 3 × Fin 3) ⊕ ((Fin 3 × Fin 3 × Fin 3) ⊕ Fin 3)

/-- The torsion form `T_{μν}^i`. -/
def torsionF (mu nu i : Fin 3) : FormIdx := Sum.inl (mu, nu, i)

/-- The gauge-fixing form `G_{μν}^i = D_{μν}^i − i k_μ e_ν^i` of the derivative variable
`D_{μν}^i`. -/
def dGaugeF (mu nu i : Fin 3) : FormIdx := Sum.inr (Sum.inl (mu, nu, i))

/-- The 3D gauge-fixing (transverse) form `C^i = Σ_μ i k_μ e_μ^i`. -/
def gauge3dF (i : Fin 3) : FormIdx := Sum.inr (Sum.inr i)

theorem card_formIdx : Fintype.card FormIdx = 57 := by decide

/-- The indicator of a component. -/
def ind (c d : Comp) : ℂ := if c = d then 1 else 0

theorem norm_ind_le (c d : Comp) : ‖ind c d‖ ≤ 1 := by
  simp only [ind]; split <;> simp

theorem sum_ind_mul (d : Comp) (z : Comp → ℂ) : ∑ c : Comp, ind c d * z c = z d := by
  classical
  rw [Finset.sum_eq_single d]
  · simp [ind]
  · intro c _ hc
    simp [ind, hc]
  · intro h
    exact absurd (Finset.mem_univ d) h

/-- **The coefficient vectors of the three families of linear forms** at momentum `k`. -/
def gCoef (k : Mom) : FormIdx → Comp → ℂ
  | Sum.inl (mu, nu, i), c => ind c (dIdx mu nu i) - ind c (dIdx nu mu i)
  | Sum.inr (Sum.inl (mu, nu, i)), c =>
      ind c (dIdx mu nu i) - Complex.I * ((k mu : ℤ) : ℂ) * ind c (eIdx nu i)
  | Sum.inr (Sum.inr i), c => ∑ mu : Fin 3, Complex.I * ((k mu : ℤ) : ℂ) * ind c (eIdx mu i)

@[simp] theorem gCoef_torsion (k : Mom) (mu nu i : Fin 3) (c : Comp) :
    gCoef k (torsionF mu nu i) c = ind c (dIdx mu nu i) - ind c (dIdx nu mu i) := rfl

@[simp] theorem gCoef_dGauge (k : Mom) (mu nu i : Fin 3) (c : Comp) :
    gCoef k (dGaugeF mu nu i) c
      = ind c (dIdx mu nu i) - Complex.I * ((k mu : ℤ) : ℂ) * ind c (eIdx nu i) := rfl

@[simp] theorem gCoef_gauge3d (k : Mom) (i : Fin 3) (c : Comp) :
    gCoef k (gauge3dF i) c = ∑ mu : Fin 3, Complex.I * ((k mu : ℤ) : ℂ) * ind c (eIdx mu i) :=
  rfl

/-! ### The size of the momentum -/

/-- `|k|`. -/
def mAbs (k : Mom) : ℝ := Real.sqrt (momSq k)

theorem mAbs_nonneg (k : Mom) : 0 ≤ mAbs k := Real.sqrt_nonneg _

theorem mAbs_sq (k : Mom) : mAbs k ^ 2 = momSq k := Real.sq_sqrt (momSq_nonneg k)

theorem abs_k_le_mAbs (k : Mom) (mu : Fin 3) : |((k mu : ℤ) : ℝ)| ≤ mAbs k := by
  have h : |((k mu : ℤ) : ℝ)| = Real.sqrt (((k mu : ℤ) : ℝ) ^ 2) :=
    (Real.sqrt_sq_eq_abs _).symm
  rw [h, mAbs]
  exact Real.sqrt_le_sqrt (sq_le_momSq k mu)

theorem norm_I_mul_k_mul_ind (k : Mom) (mu : Fin 3) (c d : Comp) :
    ‖Complex.I * ((k mu : ℤ) : ℂ) * ind c d‖ ≤ mAbs k := by
  have h1 : ‖Complex.I * ((k mu : ℤ) : ℂ) * ind c d‖
      = |((k mu : ℤ) : ℝ)| * ‖ind c d‖ := by
    rw [norm_mul, norm_mul, Complex.norm_I, one_mul]
    congr 1
    simp
  rw [h1]
  have h2 := norm_ind_le c d
  have h3 := abs_k_le_mAbs k mu
  have h4 : (0 : ℝ) ≤ |((k mu : ℤ) : ℝ)| := abs_nonneg _
  nlinarith [norm_nonneg (ind c d)]

/-- **The uniform bound on the coefficients**: every coefficient of every one of the three
families is bounded by `2 + 3|k|`. -/
theorem norm_gCoef_le (k : Mom) (F : FormIdx) (c : Comp) : ‖gCoef k F c‖ ≤ 2 + 3 * mAbs k := by
  have hM := mAbs_nonneg k
  rcases F with ⟨mu, nu, i⟩ | (⟨mu, nu, i⟩ | i)
  · have h : ‖gCoef k (torsionF mu nu i) c‖ ≤ 1 + 1 :=
      le_trans (norm_sub_le _ _) (add_le_add (norm_ind_le _ _) (norm_ind_le _ _))
    have : gCoef k (Sum.inl (mu, nu, i)) c = gCoef k (torsionF mu nu i) c := rfl
    rw [this]
    linarith
  · have h : ‖gCoef k (dGaugeF mu nu i) c‖ ≤ 1 + mAbs k :=
      le_trans (norm_sub_le _ _)
        (add_le_add (norm_ind_le _ _) (norm_I_mul_k_mul_ind k mu c (eIdx nu i)))
    have : gCoef k (Sum.inr (Sum.inl (mu, nu, i))) c = gCoef k (dGaugeF mu nu i) c := rfl
    rw [this]
    linarith
  · have h : ‖gCoef k (gauge3dF i) c‖ ≤ 3 * mAbs k := by
      rw [gCoef_gauge3d]
      refine le_trans (norm_sum_le _ _) ?_
      calc ∑ mu : Fin 3, ‖Complex.I * ((k mu : ℤ) : ℂ) * ind c (eIdx mu i)‖
          ≤ ∑ _mu : Fin 3, mAbs k :=
            Finset.sum_le_sum fun mu _ => norm_I_mul_k_mul_ind k mu c (eIdx mu i)
        _ = 3 * mAbs k := by
            rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
            norm_num
    have : gCoef k (Sum.inr (Sum.inr i)) c = gCoef k (gauge3dF i) c := rfl
    rw [this]
    linarith

theorem norm_gCoef_mul_le (k : Mom) (F : FormIdx) (c d : Comp) :
    ‖(starRingEnd ℂ) (gCoef k F c) * gCoef k F d‖ ≤ 15 * (1 + momSq k) := by
  rw [norm_mul, RCLike.norm_conj]
  have h1 := norm_gCoef_le k F c
  have h2 := norm_gCoef_le k F d
  have hM := mAbs_nonneg k
  have hsq := mAbs_sq k
  nlinarith [norm_nonneg (gCoef k F c), norm_nonneg (gCoef k F d), sq_nonneg (mAbs k - 1)]

/-! ### The forms evaluated on a field configuration -/

/-- The value of the linear form `F` at momentum `k` on a field configuration `z`. -/
def formValue (k : Mom) (F : FormIdx) (z : Comp → ℂ) : ℂ := ∑ c : Comp, gCoef k F c * z c

theorem formValue_torsion (k : Mom) (mu nu i : Fin 3) (z : Comp → ℂ) :
    formValue k (torsionF mu nu i) z = z (dIdx mu nu i) - z (dIdx nu mu i) := by
  simp only [formValue, gCoef_torsion, sub_mul, Finset.sum_sub_distrib, sum_ind_mul]

/-- **The gauge fixing of the derivative variables**: the form is `D_{μν}^i − i k_μ e_ν^i`,
so its vanishing says exactly that the independent coordinate `D_{μν}^i` is the spatial
derivative `∂_μ e_ν^i` of the field. -/
theorem formValue_dGauge (k : Mom) (mu nu i : Fin 3) (z : Comp → ℂ) :
    formValue k (dGaugeF mu nu i) z
      = z (dIdx mu nu i) - Complex.I * ((k mu : ℤ) : ℂ) * z (eIdx nu i) := by
  have h : ∀ c : Comp, gCoef k (dGaugeF mu nu i) c * z c
      = ind c (dIdx mu nu i) * z c
        - (Complex.I * ((k mu : ℤ) : ℂ)) * (ind c (eIdx nu i) * z c) := by
    intro c
    rw [gCoef_dGauge]
    ring
  rw [formValue, Finset.sum_congr rfl fun c _ => h c, Finset.sum_sub_distrib,
    ← Finset.mul_sum, sum_ind_mul, sum_ind_mul, mul_assoc]

/-- **The 3D gauge fixing**: the transverse condition `Σ_μ i k_μ e_μ^i = 0`. -/
theorem formValue_gauge3d (k : Mom) (i : Fin 3) (z : Comp → ℂ) :
    formValue k (gauge3dF i) z
      = ∑ mu : Fin 3, Complex.I * ((k mu : ℤ) : ℂ) * z (eIdx mu i) := by
  have h : ∀ c : Comp, gCoef k (gauge3dF i) c * z c
      = ∑ mu : Fin 3, (Complex.I * ((k mu : ℤ) : ℂ)) * (ind c (eIdx mu i) * z c) := by
    intro c
    rw [gCoef_gauge3d, Finset.sum_mul]
    exact Finset.sum_congr rfl fun mu _ => by ring
  rw [formValue, Finset.sum_congr rfl fun c _ => h c, Finset.sum_comm]
  refine Finset.sum_congr rfl fun mu _ => ?_
  rw [← Finset.mul_sum, sum_ind_mul, mul_assoc]

/-- **The gauge fixing does what it is meant to do**: on the surface where all the
derivative-gauge forms vanish, the torsion written in the *independent* derivative variables
is the exact torsion `i(k_μ e_ν^i − k_ν e_μ^i)` of the vielbein field. -/
theorem torsion_eq_exact_of_gauge_fixed (k : Mom) (z : Comp → ℂ)
    (h : ∀ mu nu i, formValue k (dGaugeF mu nu i) z = 0) (mu nu i : Fin 3) :
    formValue k (torsionF mu nu i) z
      = Complex.I * (((k mu : ℤ) : ℂ) * z (eIdx nu i) - ((k nu : ℤ) : ℂ) * z (eIdx mu i)) := by
  have h1 := h mu nu i
  have h2 := h nu mu i
  rw [formValue_dGauge] at h1 h2
  rw [formValue_torsion]
  have e1 : z (dIdx mu nu i) = Complex.I * ((k mu : ℤ) : ℂ) * z (eIdx nu i) := by
    linear_combination h1
  have e2 : z (dIdx nu mu i) = Complex.I * ((k nu : ℤ) : ℂ) * z (eIdx mu i) := by
    linear_combination h2
  rw [e1, e2]
  ring

/-! ## 3. The vielbein self-interaction: the Gram matrix of all three families -/

/-- **The complete quadratic form of the gauge-fixed gravity Hamiltonian in the extended
variables**: the Gram matrix of the torsion forms, the derivative-gauge forms and the 3D
gauge-fixing forms.  It is diagonal in the momentum and a full `36 × 36` matrix in the
components at each momentum. -/
def gGram (x y : GMode) : ℂ :=
  if x.1 = y.1 then
    ∑ F : FormIdx, (starRingEnd ℂ) (gCoef x.1 F x.2) * gCoef x.1 F y.2
  else 0

theorem gGram_herm (x y : GMode) : gGram y x = (starRingEnd ℂ) (gGram x y) := by
  by_cases h : x.1 = y.1
  · have hy : y.1 = x.1 := h.symm
    simp only [gGram]
    rw [if_pos hy, if_pos h, hy, map_sum]
    refine Finset.sum_congr rfl fun F _ => ?_
    simp only [map_mul, RingHomCompTriple.comp_apply, RingHom.id_apply]
    ring
  · simp only [gGram, if_neg h, if_neg (Ne.symm h), map_zero]

theorem gGram_off {x y : GMode} (h : y ∉ gNbr x) : gGram x y = 0 := by
  have hne : ¬ x.1 = y.1 := fun hh => h (mem_gNbr.mpr hh.symm)
  simp only [gGram, if_neg hne]

theorem norm_gGram_le (x y : GMode) : ‖gGram x y‖ ≤ 855 * gSig x := by
  by_cases h : x.1 = y.1
  · simp only [gGram, if_pos h]
    refine le_trans (norm_sum_le _ _) ?_
    calc ∑ F : FormIdx, ‖(starRingEnd ℂ) (gCoef x.1 F x.2) * gCoef x.1 F y.2‖
        ≤ ∑ _F : FormIdx, 15 * (1 + momSq x.1) :=
          Finset.sum_le_sum fun F _ => norm_gCoef_mul_le x.1 F x.2 y.2
      _ = 57 * (15 * (1 + momSq x.1)) := by
          rw [Finset.sum_const, Finset.card_univ, card_formIdx, nsmul_eq_mul]
          norm_num
      _ = 855 * gSig x := by simp only [gSig]; ring
  · have hnn := gSig_nonneg x
    simp only [gGram, if_neg h, norm_zero]
    linarith

end

end BookProof.QgVielbeinScalaronGaugeFL
