import Mathlib
import BookProof.ChapterQgContinuumModeInstance
import BookProof.ChapterFarisLavineOnly
import BookProof.ChapterQgVielbeinScalaronGaugeFL.Part1

/-!
# Quantum gravity: vielbein **and** scalaron **and** 3D gauge fixing **and** the gauge
fixing of the derivative variables — essential self-adjointness by Faris–Lavine

This module assembles, in one Hamiltonian, every ingredient the strategy asks of the
gravity thread, and proves essential self-adjointness of the result on the outer Fock space
**only** through the commutator criterion of Faris–Lavine, with the Friedrichs extension of
a positive one-particle operator as comparison operator.

## The variables

The spatial slice is not discretized: the vielbein is expanded in its **exact Fourier
modes**, so a momentum runs over all of `ℤ³` and the spatial derivative is the exact symbol
`∂_μ ↦ i k_μ`.  There is no lattice and no truncation to finitely many modes.

At each momentum `k` the field-space components are

* the nine vielbein components `e_ν^i(k)` (`eIdx`), and
* the **twenty-seven derivative variables** `D_{μν}^i(k)` (`dIdx`), carried as *independent*
  coordinates, exactly as the coordinates representing spatial derivatives of the fields are
  carried in the `84`-coordinate formulation of the gravity Hamiltonian.

So `Comp` has `9 + 27 = 36` elements and a mode is a pair `(k, c)` (`GMode`).

## The quadratic form: three families of linear forms

`gCoef k F` is the coefficient vector of the linear form `F` at momentum `k`, and the
vielbein self-interaction is the Gram matrix `gGram` of the whole family:

* **torsion** `T_{μν}^i = D_{μν}^i − D_{νμ}^i` (`torsionF`) — written purely in the
  derivative variables, no derivative symbol anywhere;
* **the gauge fixing of the derivative variables** `G_{μν}^i = D_{μν}^i − i k_μ e_ν^i`
  (`dGaugeF`) — the condition that fixes an independent coordinate to the spatial derivative
  of a field;
* **the 3D gauge fixing** `C^i = Σ_μ i k_μ e_μ^i` (`gauge3dF`) — the transverse
  (divergence) condition on the spatial slice.

`formValue` evaluates a form on a field configuration, and

* `formValue_dGauge` — the derivative-gauge form is exactly `D_{μν}^i − i k_μ e_ν^i`;
* `torsion_eq_exact_of_gauge_fixed` — **on the gauge-fixing surface the torsion written in
  the independent derivative variables is the exact torsion** `i(k_μ e_ν^i − k_ν e_μ^i)` of
  the fields.  This is the precise sense in which the gauge fixing of the derivative
  variables does what it is meant to do.

## The scalaron

The scalaron is carried in position representation on the fibre `L²(ℝ_φ)` with the **full
exponential** Einstein-frame potential — `starobinskyWall`, no Taylor expansion, no
relative-boundedness hypothesis on the wall — and it couples to the trace of the vielbein at
arbitrary coupling constant `g` (`gCoupling`).

## What is proved

* `qgFullModes` — the mode data of the complete model, satisfying all five Faris–Lavine
  bounds uniformly in the momentum, with `κ = 855 + |g|` and band size `36`.
* **`qgFull_esa_farisLavine`** — essential self-adjointness on the domain of the lifted
  Friedrichs extension of the positive comparison operator.
* **`qgFull_esa_core_fl`** — the same on the finite-particle core, where the Hamiltonian is
  originally defined.
* **`starobinsky_qgFull_esa`**, **`starobinsky_qgFull_esa_core`** — the physical instance,
  with the full exponential Einstein-frame Starobinsky potential.
* **`qgFull_stone_flow`**, **`starobinsky_qgFull_stone_flow`** — the unitary time evolution
  generated by the unique self-adjoint realization (Stone), the finite-particle core being
  dense (`secCore_dense`).
* **`secHam_number_conserving`** — the outer Hamiltonian conserves the particle number: for
  any number function that is constant on the bands, every number sector is invariant.  For
  this model the bands are the momentum blocks, so `qgFull_momentum_conserving` and
  `qgFull_number_conserving` apply.
* Non-vacuity: each of the three families of linear forms, and the scalaron coupling, is
  really present (`gCoef_torsion_ne_zero`, `gCoef_dGauge_ne_zero`, `gCoef_gauge3d_ne_zero`,
  `gGram_diag_ne_zero`, `gCoupling_ne_zero`), and the mode set is infinite.

No spectral information, no mass gap and no continuum limit is claimed.

Everything is `sorry`-free and `axiom`-free.
-/

namespace BookProof.QgVielbeinScalaronGaugeFL

open BookProof.ScalaronFiberFL BookProof.ScalaronOuterFockFL
open BookProof.QgVielbeinModeInstance BookProof.QgContinuumModeInstance
open BookProof.FarisLavine BookProof.QgOuterFockCoreFL
open BookProof.StoneBridge BookProof.EsaClosure BookProof.ChapterStoneResolvent
open BookProof.DirectSumEsa BookProof.ScalaronEsa

noncomputable section
/-! ## 4. The scalaron–vielbein coupling -/

/-- The trace part of the vielbein: the combination the scalaron couples to.  The derivative
variables do not carry it. -/
def gTrace (x : GMode) : ℝ :=
  match x.2 with
  | Sum.inl (nu, i) => if nu = i then 1 else 0
  | Sum.inr _ => 0

theorem abs_gTrace_le (x : GMode) : |gTrace x| ≤ 1 := by
  simp only [gTrace]
  rcases x with ⟨k, (⟨nu, i⟩ | ⟨mu, nu, i⟩)⟩
  · dsimp only; split <;> simp
  · simp

/-- **The scalaron–vielbein coupling** at coupling constant `g`: the scalaron field `φ`
multiplied by the trace of the vielbein, at equal momentum. -/
def gCoupling (g : ℝ) (x y : GMode) : ℂ :=
  if x.1 = y.1 then ((g * gTrace x * gTrace y : ℝ) : ℂ) else 0

theorem gCoupling_herm (g : ℝ) (x y : GMode) :
    gCoupling g y x = (starRingEnd ℂ) (gCoupling g x y) := by
  by_cases h : x.1 = y.1
  · have hy : y.1 = x.1 := h.symm
    simp only [gCoupling]
    rw [if_pos hy, if_pos h, Complex.conj_ofReal]
    norm_cast
    ring
  · simp only [gCoupling, if_neg h, if_neg (Ne.symm h), map_zero]

theorem gCoupling_off (g : ℝ) {x y : GMode} (h : y ∉ gNbr x) : gCoupling g x y = 0 := by
  have hne : ¬ x.1 = y.1 := fun hh => h (mem_gNbr.mpr hh.symm)
  simp only [gCoupling, if_neg hne]

theorem norm_gCoupling_le (g : ℝ) (x y : GMode) : ‖gCoupling g x y‖ ≤ |g| := by
  by_cases h : x.1 = y.1
  · simp only [gCoupling, if_pos h, Complex.norm_real, Real.norm_eq_abs, abs_mul]
    have h1 := abs_gTrace_le x
    have h2 := abs_gTrace_le y
    have hg := abs_nonneg g
    calc |g| * |gTrace x| * |gTrace y| ≤ |g| * 1 * 1 := by gcongr
      _ = |g| := by ring
  · simp only [gCoupling, if_neg h, norm_zero]
    exact abs_nonneg g

/-! ## 5. The mode data -/

/-- **The mode data of the complete gauge-fixed quantum-gravity model**: exact Fourier modes
of the vielbein together with the independent derivative variables, the torsion
self-interaction, the gauge fixing of the derivative variables, the 3D transverse gauge
fixing and the scalaron coupling.  All five Faris–Lavine bounds hold with the single
constant `κ = 855 + |g|` and band size `36`, uniformly in the momentum. -/
def qgFullModes (g : ℝ) : QgModeData GMode :=
  ofBounds gSig one_le_gSig gGram (gCoupling g) gNbr
    (fun a b => by rw [mem_gNbr, mem_gNbr, eq_comm])
    (fun _ _ hb => gGram_off hb) (fun _ _ hb => gCoupling_off g hb)
    gGram_herm (gCoupling_herm g)
    (855 + |g|) 36 (by positivity) (by norm_num)
    (fun a => le_of_eq (card_gNbr a))
    (fun a b => by
      by_cases h : a.1 = b.1
      · have hmin : min (gSig a) (gSig b) = gSig a := by
          simp only [gSig]
          rw [h]
          exact min_self _
        have hb := norm_gGram_le a b
        have hnn := gSig_nonneg a
        have hg := abs_nonneg g
        rw [hmin]
        nlinarith
      · have hz : gGram a b = 0 := by simp only [gGram, if_neg h]
        have h1 : (1 : ℝ) ≤ min (gSig a) (gSig b) := le_min (one_le_gSig a) (one_le_gSig b)
        have hg := abs_nonneg g
        rw [hz, norm_zero]
        nlinarith)
    (fun a b => le_trans (norm_gCoupling_le g a b) (by norm_num))
    (fun a b hb => by
      have h : b.1 = a.1 := mem_gNbr.mp hb
      have hcs : gSig a = gSig b := by simp only [gSig, h]
      have hg := abs_nonneg g
      rw [hcs, sub_self, abs_zero]
      linarith)

@[simp] theorem qgFullModes_sig (g : ℝ) : (qgFullModes g).sig = gSig := rfl

@[simp] theorem qgFullModes_A (g : ℝ) : (qgFullModes g).A = gGram := rfl

@[simp] theorem qgFullModes_B (g : ℝ) : (qgFullModes g).B = gCoupling g := rfl

@[simp] theorem qgFullModes_nbr (g : ℝ) : (qgFullModes g).nbr = gNbr := rfl

/-! ## 6. Essential self-adjointness, by Faris–Lavine -/

/-- **Essential self-adjointness of the complete gauge-fixed quantum-gravity Hamiltonian on
the outer Fock space, by Faris–Lavine.**

The Hamiltonian carries, at once: the vielbein in its exact Fourier modes (no lattice, no
truncation), the independent coordinates representing the spatial derivatives of the
vielbein, the torsion self-interaction written in those coordinates, the gauge fixing that
ties them to the derivatives of the fields, the 3D transverse gauge fixing, and the scalaron
in position representation with an arbitrary smooth non-negative wall and the coupling to
the trace of the vielbein at arbitrary coupling constant `g`.

The proof is Theorem 1 of Faris–Lavine against the `ℓ²`-lift of the Friedrichs extension of
the positive fibre operator `−∂²_φ + φ²/4 + V(φ) + σ_a`; no Carleman flux estimate, no Schur
weight and no Kato–Rellich perturbation is used. -/
theorem qgFull_esa_farisLavine (W : WallPot) (g : ℝ) :
    EssentiallySelfAdjointOn (secN W (qgFullModes g)).dom (secData W (qgFullModes g)).ext :=
  secHam_essentiallySelfAdjointOn W _

/-- The self-adjoint realization restricts to the Hamiltonian on the finite-particle
core. -/
theorem qgFull_ext_core (W : WallPot) (g : ℝ) (p : secCore (ι := GMode)) :
    (secData W (qgFullModes g)).ext ⟨(p : Sec GMode), (secData W (qgFullModes g)).gc.le p.2⟩
      = secHam W (qgFullModes g) p :=
  secData_ext_core W _ p

/-- **The same on the finite-particle core**, where the Hamiltonian is originally defined:
Faris–Lavine on the core itself, through
`BookProof.QgOuterFockCoreFL.CoreData.esa_on_core`. -/
theorem qgFull_esa_core_fl (W : WallPot) (g : ℝ) :
    EssentiallySelfAdjointOn (secCore (ι := GMode)) (secHam W (qgFullModes g)) := by
  refine (secData W (qgFullModes g)).esa_on_core (secHam_symmetricOn W _)
    (c := 6 * (qgFullModes g).K) (by have := (qgFullModes g).K_nonneg; linarith) ?_
  intro p
  have hc : commForm (secData W (qgFullModes g)).H₀ (secData W (qgFullModes g)).coreN p
      = commForm (secHam W (qgFullModes g)) (secDiag W (qgFullModes g)) p :=
    commForm_congr _ _ _ _ _ _ rfl (secData_coreN W (qgFullModes g) p)
  have hq : quadForm (secData W (qgFullModes g)).coreN p
      = quadForm (secDiag W (qgFullModes g)) p :=
    quadForm_congr _ _ _ _ rfl (secData_coreN W (qgFullModes g) p)
  rw [hc, hq]
  exact secHam_commForm_le W (qgFullModes g) p

/-- **The physical instance**: the full exponential Einstein-frame Starobinsky potential
`M⁴/(16α)(1 − e^{−√(2/3)φ/M})²`, with no Taylor expansion. -/
theorem starobinsky_qgFull_esa (M alpha : ℝ) (halpha : 0 < alpha) (g : ℝ) :
    EssentiallySelfAdjointOn (secN (starobinskyWall M alpha halpha) (qgFullModes g)).dom
      (secData (starobinskyWall M alpha halpha) (qgFullModes g)).ext :=
  qgFull_esa_farisLavine (starobinskyWall M alpha halpha) g

/-- The physical instance on the finite-particle core. -/
theorem starobinsky_qgFull_esa_core (M alpha : ℝ) (halpha : 0 < alpha) (g : ℝ) :
    EssentiallySelfAdjointOn (secCore (ι := GMode))
      (secHam (starobinskyWall M alpha halpha) (qgFullModes g)) :=
  qgFull_esa_core_fl (starobinskyWall M alpha halpha) g

/-! ## 6b. The unitary time evolution -/

/-- The finite-particle core is dense in the outer Fock space. -/
theorem secCore_dense :
    Dense ((secCore (ι := GMode) : Submodule ℂ (Sec GMode)) : Set (Sec GMode)) :=
  dsCore_dense fun _ => ccDomain_dense

/-- **The unitary flow of the complete gauge-fixed quantum-gravity Hamiltonian.**  Essential
self-adjointness on the dense finite-particle core gives a unique self-adjoint realization,
and Stone's theorem gives the time evolution it generates. -/
theorem qgFull_stone_flow (W : WallPot) (g : ℝ) :
    ∃ (T : UnboundedSelfAdjoint (Sec GMode))
      (U : ℝ → (Sec GMode →L[ℂ] Sec GMode)),
      IsSelfAdjointExtension (secHam W (qgFullModes g)) T.op ∧
        IsStoneFlow T U :=
  exists_stone_flow_of_esa _ secCore_dense (secHam_symmetricOn W _)
    (qgFull_esa_core_fl W g)

/-- The physical instance of the flow, with the full exponential Einstein-frame Starobinsky
potential. -/
theorem starobinsky_qgFull_stone_flow (M alpha : ℝ) (halpha : 0 < alpha) (g : ℝ) :
    ∃ (T : UnboundedSelfAdjoint (Sec GMode))
      (U : ℝ → (Sec GMode →L[ℂ] Sec GMode)),
      IsSelfAdjointExtension
          (secHam (starobinskyWall M alpha halpha) (qgFullModes g)) T.op ∧
        IsStoneFlow T U :=
  qgFull_stone_flow (starobinskyWall M alpha halpha) g

/-! ## 7. The outer Hamiltonian conserves the particle number -/

section Number

variable {ι : Type*}

/-- **The outer Hamiltonian conserves the particle number.**  For any assignment of a
particle number to the modes that is constant on the bands, the sector of a fixed particle
number is invariant: a core vector supported in the sector `num = n` is mapped by the
Hamiltonian to a vector supported in the same sector.  No lattice regularization is
involved: the number sectors, not a spatial cutoff, are what makes the outer Hamiltonian
block diagonal. -/
theorem secHam_number_conserving (W : WallPot) (Q : QgModeData ι) {num : ι → ℕ}
    (hnum : ∀ a b, b ∈ Q.nbr a → num b = num a) (x : secCore (ι := ι)) {n : ℕ}
    (hx : ∀ a, num a ≠ n → (x : Sec ι) a = 0) (a : ι) (ha : num a ≠ n) :
    (secHam W Q x : Sec ι) a = 0 := by
  have hb : ∀ b ∈ Q.nbr a, fibOf x b = 0 := by
    intro b hbm
    refine fibOf_eq_zero (hx b ?_)
    rw [hnum a b hbm]
    exact ha
  rw [secHam_apply, fibOf_eq_zero (hx a ha), map_zero,
    Finset.sum_eq_zero (fun b hbm => by rw [hb b hbm]; simp),
    Finset.sum_eq_zero (fun b hbm => by rw [hb b hbm, map_zero, smul_zero])]
  simp

end Number

/-- **Momentum conservation** for the complete model: the bands are the momentum blocks, so
every function of the momentum is conserved by the Hamiltonian. -/
theorem qgFull_momentum_conserving (W : WallPot) (g : ℝ) (num : Mom → ℕ)
    (x : secCore (ι := GMode)) {n : ℕ}
    (hx : ∀ a : GMode, num a.1 ≠ n → (x : Sec GMode) a = 0) (a : GMode) (ha : num a.1 ≠ n) :
    (secHam W (qgFullModes g) x : Sec GMode) a = 0 :=
  secHam_number_conserving W (qgFullModes g)
    (num := fun a => num a.1) (fun _ _ hb => congrArg num (mem_gNbr.mp hb)) x hx a ha

/-- **Particle-number conservation** for the complete model, in the form used by the nested
Fock-space construction: for any particle-number assignment that is constant on the momentum
blocks, every number sector is invariant. -/
theorem qgFull_number_conserving (W : WallPot) (g : ℝ) {num : GMode → ℕ}
    (hnum : ∀ a b : GMode, b.1 = a.1 → num b = num a) (x : secCore (ι := GMode)) {n : ℕ}
    (hx : ∀ a, num a ≠ n → (x : Sec GMode) a = 0) (a : GMode) (ha : num a ≠ n) :
    (secHam W (qgFullModes g) x : Sec GMode) a = 0 :=
  secHam_number_conserving W (qgFullModes g)
    (fun a b hb => hnum a b (mem_gNbr.mp hb)) x hx a ha

/-! ## 8. Non-vacuity -/

/-- The mode set is infinite: no lattice, no truncation to finitely many modes. -/
theorem infinite_gmode : Infinite GMode := inferInstance

/-- The torsion forms are really present. -/
theorem gCoef_torsion_ne_zero (k : Mom) :
    gCoef k (torsionF 0 1 0) (dIdx 0 1 0) ≠ 0 := by
  have hne : (dIdx 0 1 0 : Comp) ≠ dIdx 1 0 0 := by
    simp [dIdx]
  have h : gCoef k (torsionF 0 1 0) (dIdx 0 1 0) = 1 := by
    rw [gCoef_torsion]
    simp [ind, hne]
  rw [h]
  exact one_ne_zero

/-- The gauge fixing of the derivative variables really couples a derivative variable to a
vielbein component, whenever the momentum is non-zero in that direction. -/
theorem gCoef_dGauge_ne_zero (k : Mom) (hk : k 0 ≠ 0) :
    gCoef k (dGaugeF 0 1 0) (eIdx 1 0) ≠ 0 := by
  have hne : (eIdx 1 0 : Comp) ≠ dIdx 0 1 0 := by simp [eIdx, dIdx]
  have h : gCoef k (dGaugeF 0 1 0) (eIdx 1 0) = -(Complex.I * ((k 0 : ℤ) : ℂ)) := by
    rw [gCoef_dGauge]
    simp [ind, hne]
  rw [h]
  simp only [ne_eq, neg_eq_zero, mul_eq_zero, Complex.I_ne_zero, false_or]
  exact_mod_cast hk

/-- The 3D gauge fixing is really present, whenever the momentum is non-zero. -/
theorem gCoef_gauge3d_ne_zero (k : Mom) (hk : k 0 ≠ 0) :
    gCoef k (gauge3dF 0) (eIdx 0 0) ≠ 0 := by
  have h1 : (eIdx 0 0 : Comp) ≠ eIdx 1 0 := by simp [eIdx]
  have h2 : (eIdx 0 0 : Comp) ≠ eIdx 2 0 := by simp [eIdx, Fin.ext_iff]
  have h : gCoef k (gauge3dF 0) (eIdx 0 0) = Complex.I * ((k 0 : ℤ) : ℂ) := by
    rw [gCoef_gauge3d, Fin.sum_univ_three]
    simp [ind, h1, h2]
  rw [h]
  simp only [ne_eq, mul_eq_zero, Complex.I_ne_zero, false_or]
  exact_mod_cast hk

theorem conj_mul_self_ofReal (z : ℂ) : (starRingEnd ℂ) z * z = ((‖z‖ ^ 2 : ℝ) : ℂ) := by
  simpa using RCLike.conj_mul (K := ℂ) z

/-- The complete quadratic form of the gauge-fixed Hamiltonian is not the zero form: its
diagonal entry on a derivative variable is positive. -/
theorem gGram_diag_ne_zero (k : Mom) :
    gGram ((k, dIdx 0 1 0) : GMode) (k, dIdx 0 1 0) ≠ 0 := by
  have hsum : gGram ((k, dIdx 0 1 0) : GMode) (k, dIdx 0 1 0)
      = ((∑ F : FormIdx, ‖gCoef k F (dIdx 0 1 0)‖ ^ 2 : ℝ) : ℂ) := by
    simp only [gGram, if_true, Complex.ofReal_sum]
    exact Finset.sum_congr rfl fun F _ => conj_mul_self_ofReal _
  intro h0
  rw [hsum] at h0
  have hzero : (∑ F : FormIdx, ‖gCoef k F (dIdx 0 1 0)‖ ^ 2) = 0 := by exact_mod_cast h0
  have hterm : ‖gCoef k (torsionF 0 1 0) (dIdx 0 1 0)‖ ^ 2 = 0 :=
    (Finset.sum_eq_zero_iff_of_nonneg (fun F _ => by positivity)).mp hzero _
      (Finset.mem_univ _)
  refine gCoef_torsion_ne_zero k (norm_eq_zero.mp ?_)
  nlinarith [norm_nonneg (gCoef k (torsionF 0 1 0) (dIdx 0 1 0))]

/-- The scalaron–vielbein coupling is really present whenever the coupling constant is
non-zero. -/
theorem gCoupling_ne_zero (g : ℝ) (hg : g ≠ 0) (k : Mom) :
    gCoupling g ((k, eIdx 0 0) : GMode) (k, eIdx 0 0) ≠ 0 := by
  simp only [gCoupling, gTrace, eIdx]
  norm_num [hg]

end

end BookProof.QgVielbeinScalaronGaugeFL
