import Mathlib
import BookProof.ChapterHashimotoShiftInvert
import BookProof.ChapterComplexShiftCore
import BookProof.ChapterHashimotoComplexShifts.Part1

/-!
# The Hashimoto (SIRK) algorithm with **complex, non-real, and many different shifts**

`BookProof.ChapterHashimotoShiftInvert` develops the shift-invert trick for a
*single, real, positive* shift `γ`, where invertibility of `A + γ` comes from
positivity of `A`.  The Shift-invert Rational Krylov method of Hashimoto and
Nodera is however run with

* shifts `γ` that are **complex with non-zero imaginary part** — then
  `γ I − A` is invertible for *every* self-adjoint `A`, with no positivity
  assumption at all, purely because a non-real number is at distance
  `|Im γ| > 0` from the (real) numerical range; and
* **many different shifts** `γ₁, γ₂, …`, one per step, the rational Krylov
  subspace `Q_m({X_j}, v) = span{v, X₁v, X₂X₁v, …, X_{m-1}⋯X₁v}` being built
  out of the resolvents `X_j = (γ_j I − A)⁻¹`.

This module adapts the theory to that setting.  Everything is in the same
namespace `BookProof.HashimotoShiftInvert`.

## Part 1 — the non-real shift bound

`norm_cshiftMap_ge`: `‖(γ − A)x‖ ≥ |Im γ| ‖x‖` for a **symmetric** `A`, with no
positivity.  Hence `cshiftMap_injective`.

## Part 2 — bijectivity

`cshiftRange_isClosed`, `cshiftRange_orthogonal_eq_bot`, `cshiftMap_surjective`:
for a self-adjoint `A` (symmetry plus the adjoint criterion) and non-real `γ`,
`γ − A` is a bijection of `Dom` onto the whole space.

## Part 3 — the resolvent `X = (γ − A)⁻¹`

`IsShiftInvertC`, `exists_isShiftInvertC`, `IsShiftInvertC.opNorm_le`
(`‖X‖ ≤ 1/|Im γ|`), `IsShiftInvertC.adjoint_eq` (the adjoint of `X` is the
resolvent at the conjugate shift — `X` is no longer self-adjoint, it is normal),
`shiftInvertC_determines`, `isShiftInvertC_unique`, and
`isShiftInvertC_neg_of_isShiftInvert` relating the new theory to the real
positive-shift theory of the previous chapter.

## Part 4 — many shifts

`shiftInvertC_resolvent_identity` (`X_j − X_k = (γ_k − γ_j) X_j X_k`),
`shiftInvertC_commute`, `shiftInvertC_comp_one_sub` (the SIRK relation
`X_j (I − (γ_m − γ_j) X_m) = X_m`), the rational Krylov flag `rkVec`,
`rkSpan`, and `rkSpan_den_eq` — the cleared-denominator form of Hashimoto–Nodera
Eq. (11): `∏_{i<k} (I − (γ_m − γ_i)X_m)` maps the `k`-th rational Krylov vector
to `X_m^k v`, so the rational Krylov subspace built from many shifts is a space
of *rational* functions of the single resolvent `X_m`.  `rkCompression_tendsto`
gives strong convergence of the compressions along the flag.

## Part 5 — the headline

`hashimoto_multishift_selects_friedrichs`.

## Part 6 — a genuinely unbounded example with non-real shifts

The number operator `A eₙ = n eₙ` on `ℓ²(ℕ, ℂ)`, its resolvents at arbitrary
non-real shifts, and `hashimoto_multishift_unbounded_example`.
-/

namespace BookProof.HashimotoShiftInvert

open BookProof.FarisLavine BookProof.YangMillsFriedrichs BookProof.YangMillsFriedrichsLimit
open BookProof.HermiteGalerkin
open Filter Topology
/-! ## Part 4b — convergence of the compressions along the rational Krylov flag -/

section RkConvergence

variable {F : Type*} [NormedAddCommGroup F] [InnerProductSpace ℂ F] [CompleteSpace F]

/-- The **rational Krylov (Hashimoto/SIRK) compression** `P_m T P_m` of a bounded
operator along the flag of rational Krylov subspaces generated by the shifts. -/
noncomputable def rkCompression (T : F →L[ℂ] F) (X : ℕ → F →L[ℂ] F) (v : F) (m : ℕ) :
    F →L[ℂ] F :=
  (rkSpan X v m).starProjection ∘L T ∘L (rkSpan X v m).starProjection

omit [CompleteSpace F] in
/-- **The rational Krylov projections converge strongly to the identity** when
the flag is dense — the multi-shift analogue of `galerkinProj_tendsto`. -/
theorem rkProj_tendsto (X : ℕ → F →L[ℂ] F) (v : F)
    (hdense : Dense ((⨆ m : ℕ, rkSpan X v m : Submodule ℂ F) : Set F)) (u : F) :
    Tendsto (fun m : ℕ => (rkSpan X v m).starProjection u) atTop (nhds u) :=
  starProjection_tendsto_of_monotone_dense _ (fun _ _ h => rkSpan_mono X v h) hdense u

omit [CompleteSpace F] in
/-- **The multi-shift compressions converge strongly.**  For a dense rational
Krylov flag the compressions `P_m T P_m` of any bounded operator converge to `T`
in the strong operator topology; applied to `T = X_m` this is the convergence of
the SIRK approximation. -/
theorem rkCompression_tendsto (T : F →L[ℂ] F) (X : ℕ → F →L[ℂ] F) (v : F)
    (hdense : Dense ((⨆ m : ℕ, rkSpan X v m : Submodule ℂ F) : Set F)) (u : F) :
    Tendsto (fun m : ℕ => rkCompression T X v m u) atTop (nhds (T u)) :=
  compression_tendsto_of_starProjection_tendsto _ T (rkProj_tendsto X v hdense) u

end RkConvergence

/-! ## Part 5 — the headline theorem for complex, multiple shifts -/

section Headline

variable {F : Type*} [NormedAddCommGroup F] [InnerProductSpace ℂ F] [CompleteSpace F]

/-- **The Hashimoto/SIRK algorithm with non-real, step-dependent shifts.**

Let `H` be the matrix of a symmetric Hamiltonian in a complete orthonormal
basis, and let `A` be any positive self-adjoint extension of it — no
boundedness anywhere.  Let `γ : ℕ → ℂ` be an arbitrary sequence of shifts, each
with non-zero imaginary part (which is what makes `γ_j I − A` invertible: the
positivity of `A` is no longer needed).  Then there is a family of resolvents
`X_j = (γ_j I − A)⁻¹` such that

1. each `X_j` is everywhere defined and **bounded**, with `‖X_j‖ ≤ 1/|Im γ_j|`;
2. the `X_j` all have the same range, namely the domain of `A`, and each of them
   determines `A` completely;
3. they satisfy the first resolvent identity and commute pairwise;
4. the SIRK relation `X_j (I − (γ_m − γ_j) X_m) = X_m` holds, so the rational
   Krylov space built from all the shifts is a space of rational functions of the
   single resolvent `X_m` (`sirkDen_rkVec`);
5. the Galerkin truncations of each `X_j` converge to it strongly. -/
theorem hashimoto_multishift_selects_friedrichs (b : HilbertBasis ℕ ℂ F)
    (H : finiteModeDomain b →ₗ[ℂ] F) {Dom : Submodule ℂ F} (A : Dom →ₗ[ℂ] F)
    (hA : IsPositiveSelfAdjointExtension H A) (γ : ℕ → ℂ) (hγ : ∀ j, (γ j).im ≠ 0) :
    ∃ X : ℕ → F →L[ℂ] F,
      (∀ j, IsShiftInvertC A (γ j) (X j)) ∧
      (∀ j, ‖X j‖ ≤ |(γ j).im|⁻¹) ∧
      (∀ j, Dom = LinearMap.range ((X j : F →ₗ[ℂ] F))) ∧
      (∀ j k u, X j u - X k u = (γ k - γ j) • X j (X k u)) ∧
      (∀ j k, X j ∘L X k = X k ∘L X j) ∧
      (∀ j m, X j ∘L (ContinuousLinearMap.id ℂ F - (γ m - γ j) • X m) = X m) ∧
      (∀ m v k, sirkDen (X m) (fun i => γ m - γ i) k (rkVec X v k) = (X m ^ k) v) ∧
      (∀ j u, Tendsto (fun n : ℕ => galerkinCompression (X j) b n u) atTop (nhds (X j u))) ∧
      (∀ j (Dom' : Submodule ℂ F) (A' : Dom' →ₗ[ℂ] F), IsShiftInvertC A' (γ j) (X j) →
        Dom' = Dom ∧ ∀ (x : F) (hx : x ∈ Dom) (hx' : x ∈ Dom'), A' ⟨x, hx'⟩ = A ⟨x, hx⟩) := by
  obtain ⟨-, hsym, -, hsa⟩ := hA
  choose X hX using fun j : ℕ =>
    exists_isShiftInvertC hsym (hγ j) (cshiftMap_surjective hsym hsa (hγ j))
  refine ⟨X, hX, fun j => (hX j).opNorm_le hsym (hγ j), fun j => (hX j).dom_eq_range,
    fun j k u => shiftInvertC_resolvent_identity (hX j) (hX k) u,
    fun j k => shiftInvertC_commute (hX j) (hX k),
    fun j m => shiftInvertC_comp_one_sub (hX j) (hX m),
    fun m v k => sirkDen_rkVec m hX v k,
    fun j u => galerkinCompression_tendsto (X j) b u, ?_⟩
  intro j Dom' A' hA'
  obtain ⟨hdom, hval⟩ := shiftInvertC_determines hA' (hX j)
  exact ⟨hdom, fun x hx hx' => hval x hx' hx⟩

end Headline

/-! ## Part 6 — a genuinely unbounded example with non-real shifts

The number operator `A eₙ = n eₙ` on `ℓ²(ℕ, ℂ)` of
`BookProof.ChapterHashimotoShiftInvert`, whose resolvent at a shift `γ` off the
real axis is the bounded complex diagonal operator `eₙ ↦ eₙ/(γ − n)`.  Running
the algorithm with a whole sequence of such shifts is therefore not vacuous. -/

section UnboundedExample

open scoped InnerProductSpace ENNReal

/-! ### Complex diagonal operators on `ℓ²(ℕ, ℂ)` -/

theorem memlp_diagFunC {c : ℕ → ℂ} {M : ℝ} (hc : ∀ n, ‖c n‖ ≤ M) (x : ℓ²(ℕ, ℂ)) :
    Memℓp (fun n => c n * x n) 2 := by
  have hx : Summable fun n => ‖(x : ℕ → ℂ) n‖ ^ (2 : ℝ≥0∞).toReal :=
    (lp.memℓp x).summable (by norm_num)
  refine memℓp_gen (Summable.of_nonneg_of_le (fun n => by positivity) (fun n => ?_)
    (hx.mul_left (M ^ 2)))
  have ht : (2 : ℝ≥0∞).toReal = 2 := by norm_num
  rw [ht, Real.rpow_two, Real.rpow_two, norm_mul, mul_pow]
  gcongr
  exact hc n

/-- The diagonal (multiplication) operator on `ℓ²(ℕ, ℂ)` with **complex**
coefficients bounded by `M`, as a linear map. -/
noncomputable def diagLinC {c : ℕ → ℂ} {M : ℝ} (hc : ∀ n, ‖c n‖ ≤ M) :
    ℓ²(ℕ, ℂ) →ₗ[ℂ] ℓ²(ℕ, ℂ) where
  toFun x := ⟨fun n => c n * x n, memlp_diagFunC hc x⟩
  map_add' x y := by apply lp.ext; funext n; simp [mul_add]
  map_smul' a x := by apply lp.ext; funext n; simp; ring

@[simp] theorem diagLinC_apply {c : ℕ → ℂ} {M : ℝ} (hc : ∀ n, ‖c n‖ ≤ M) (x : ℓ²(ℕ, ℂ)) (n : ℕ) :
    ((diagLinC hc x : ℓ²(ℕ, ℂ)) : ℕ → ℂ) n = c n * x n := rfl

theorem diagLinC_norm_le {c : ℕ → ℂ} {M : ℝ} (hc : ∀ n, ‖c n‖ ≤ M) (x : ℓ²(ℕ, ℂ)) :
    ‖diagLinC hc x‖ ≤ M * ‖x‖ := by
  have hM : 0 ≤ M := le_trans (norm_nonneg (c 0)) (hc 0)
  refine lp.norm_le_of_tsum_le (by norm_num) (by positivity) ?_
  have hMx : Summable fun n => M ^ (2 : ℝ≥0∞).toReal * ‖(x : ℕ → ℂ) n‖ ^ (2 : ℝ≥0∞).toReal :=
    ((lp.memℓp x).summable (by norm_num)).mul_left _
  refine le_trans (Summable.tsum_le_tsum (fun n => ?_)
    ((memlp_diagFunC hc x).summable (by norm_num)) hMx) ?_
  · have ht : (2 : ℝ≥0∞).toReal = 2 := by norm_num
    change ‖c n * (x : ℕ → ℂ) n‖ ^ (2 : ℝ≥0∞).toReal ≤ _
    rw [ht, Real.rpow_two, Real.rpow_two, Real.rpow_two, norm_mul, mul_pow]
    gcongr
    exact hc n
  · rw [tsum_mul_left, ← lp.norm_rpow_eq_tsum (by norm_num : (0 : ℝ) < (2 : ℝ≥0∞).toReal) x]
    exact le_of_eq (Real.mul_rpow hM (norm_nonneg x)).symm

/-- The complex diagonal operator as a bounded operator, of norm at most `M`. -/
noncomputable def diagCLMC {c : ℕ → ℂ} {M : ℝ} (hc : ∀ n, ‖c n‖ ≤ M) :
    ℓ²(ℕ, ℂ) →L[ℂ] ℓ²(ℕ, ℂ) :=
  (diagLinC hc).mkContinuous M (diagLinC_norm_le hc)

@[simp] theorem diagCLMC_apply {c : ℕ → ℂ} {M : ℝ} (hc : ∀ n, ‖c n‖ ≤ M) (x : ℓ²(ℕ, ℂ)) (n : ℕ) :
    ((diagCLMC hc x : ℓ²(ℕ, ℂ)) : ℕ → ℂ) n = c n * x n := rfl

/-! ### The resolvents of the number operator at non-real shifts -/

/-- The coefficients `1/(γ − n)` of the resolvent of the number operator. -/
noncomputable def resCoeff (γ : ℂ) (n : ℕ) : ℂ := 1 / (γ - n)

/-- The coefficients `(n+1)/(γ − n)`: applying `R = (A+1)⁻¹` to this diagonal
gives the resolvent, which is how one sees that the resolvent lands in the
domain of `A`. -/
noncomputable def preCoeff (γ : ℂ) (n : ℕ) : ℂ := ((n : ℂ) + 1) / (γ - n)

theorem norm_sub_natCast_ge (γ : ℂ) (n : ℕ) : |γ.im| ≤ ‖γ - (n : ℂ)‖ := by
  have h := Complex.abs_im_le_norm (γ - (n : ℂ))
  simpa using h

theorem sub_natCast_ne_zero {γ : ℂ} (hγ : γ.im ≠ 0) (n : ℕ) : γ - (n : ℂ) ≠ 0 := by
  intro h
  have := norm_sub_natCast_ge γ n
  rw [h, norm_zero] at this
  exact hγ (abs_eq_zero.mp (le_antisymm this (abs_nonneg _)))

theorem resCoeff_norm_le {γ : ℂ} (hγ : γ.im ≠ 0) (n : ℕ) : ‖resCoeff γ n‖ ≤ |γ.im|⁻¹ := by
  have hd : 0 < |γ.im| := abs_pos.mpr hγ
  have hw : |γ.im| ≤ ‖γ - (n : ℂ)‖ := norm_sub_natCast_ge γ n
  have hwpos : 0 < ‖γ - (n : ℂ)‖ := lt_of_lt_of_le hd hw
  rw [resCoeff, norm_div, norm_one, div_le_iff₀ hwpos, inv_mul_eq_div, le_div_iff₀ hd]
  nlinarith

theorem preCoeff_norm_le {γ : ℂ} (hγ : γ.im ≠ 0) (n : ℕ) :
    ‖preCoeff γ n‖ ≤ 1 + (|γ.re| + 1) / |γ.im| := by
  have hd : 0 < |γ.im| := abs_pos.mpr hγ
  have hw : |γ.im| ≤ ‖γ - (n : ℂ)‖ := norm_sub_natCast_ge γ n
  have hwpos : 0 < ‖γ - (n : ℂ)‖ := lt_of_lt_of_le hd hw
  have hre : |γ.re - (n : ℝ)| ≤ ‖γ - (n : ℂ)‖ := by
    have h := Complex.abs_re_le_norm (γ - (n : ℂ))
    simpa using h
  have hnum : ((n : ℝ) + 1) ≤ ‖γ - (n : ℂ)‖ + (|γ.re| + 1) := by
    have h1 : (n : ℝ) - γ.re ≤ |γ.re - (n : ℝ)| := by
      rw [abs_sub_comm]; exact le_abs_self _
    have h2 : γ.re ≤ |γ.re| := le_abs_self _
    linarith
  have hnorm : ‖preCoeff γ n‖ = ((n : ℝ) + 1) / ‖γ - (n : ℂ)‖ := by
    rw [preCoeff, norm_div]
    congr 1
    rw [show ((n : ℂ) + 1) = (((n + 1 : ℕ) : ℂ)) by push_cast; ring, Complex.norm_natCast]
    push_cast
    ring
  rw [hnorm, div_le_iff₀ hwpos]
  have hkey : (|γ.re| + 1) ≤ (|γ.re| + 1) / |γ.im| * ‖γ - (n : ℂ)‖ := by
    rw [div_mul_eq_mul_div, le_div_iff₀ hd]
    nlinarith [abs_nonneg γ.re]
  nlinarith

/-- **The resolvent of the number operator at a non-real shift**: the bounded
complex diagonal operator `eₙ ↦ eₙ/(γ − n)`, of norm at most `1/|Im γ|`. -/
noncomputable def ell2Resolvent {γ : ℂ} (hγ : γ.im ≠ 0) : ℓ²(ℕ, ℂ) →L[ℂ] ℓ²(ℕ, ℂ) :=
  diagCLMC (resCoeff_norm_le hγ)

/-- The auxiliary diagonal `eₙ ↦ (n+1) eₙ/(γ − n)`, a preimage of the resolvent
under `R = (A+1)⁻¹`. -/
noncomputable def ell2ResolventPre {γ : ℂ} (hγ : γ.im ≠ 0) : ℓ²(ℕ, ℂ) →L[ℂ] ℓ²(ℕ, ℂ) :=
  diagCLMC (preCoeff_norm_le hγ)

theorem ell2Example_symmetricOn :
    SymmetricOn (LinearMap.range (ell2ShiftInvert : ℓ²(ℕ, ℂ) →ₗ[ℂ] ℓ²(ℕ, ℂ)))
      ell2UnboundedExample :=
  ell2Example_isPositiveSelfAdjointExtension.2.1

theorem ell2ShiftInvert_resolventPre {γ : ℂ} (hγ : γ.im ≠ 0) (u : ℓ²(ℕ, ℂ)) :
    ell2ShiftInvert (ell2ResolventPre hγ u) = ell2Resolvent hγ u := by
  apply lp.ext
  funext n
  have hne : γ - (n : ℂ) ≠ 0 := sub_natCast_ne_zero hγ n
  have hn1 : ((n : ℂ) + 1) ≠ 0 := by
    rw [show ((n : ℂ) + 1) = (((n + 1 : ℕ) : ℂ)) by push_cast; ring]
    exact_mod_cast Nat.succ_ne_zero n
  have hcoe : ((invCoeff n : ℝ) : ℂ) = ((n : ℂ) + 1)⁻¹ := by
    rw [invCoeff]
    push_cast
    rw [one_div]
  rw [ell2ShiftInvert, diagCLM_apply, ell2ResolventPre, diagCLMC_apply, ell2Resolvent,
    diagCLMC_apply, hcoe, preCoeff, resCoeff]
  field_simp

/-- **The diagonal operator `eₙ ↦ eₙ/(γ − n)` really is the resolvent** of the
unbounded number operator at the non-real shift `γ`. -/
theorem ell2Resolvent_isShiftInvertC {γ : ℂ} (hγ : γ.im ≠ 0) :
    IsShiftInvertC ell2UnboundedExample γ (ell2Resolvent hγ) := by
  refine isShiftInvertC_of_rightInverse ell2Example_symmetricOn hγ ?_
  intro u
  have hR : ell2ShiftInvert (ell2ResolventPre hγ u) = ell2Resolvent hγ u :=
    ell2ShiftInvert_resolventPre hγ u
  have hmem : ell2Resolvent hγ u
      ∈ LinearMap.range (ell2ShiftInvert : ℓ²(ℕ, ℂ) →ₗ[ℂ] ℓ²(ℕ, ℂ)) :=
    ⟨ell2ResolventPre hγ u, hR⟩
  refine ⟨hmem, ?_⟩
  have hpre : preim ell2ShiftInvert ⟨ell2Resolvent hγ u, hmem⟩ = ell2ResolventPre hγ u :=
    preim_eq _ ell2ShiftInvert_injective _ hR
  have hA : ell2UnboundedExample ⟨ell2Resolvent hγ u, hmem⟩
      = ell2ResolventPre hγ u - (1 : ℂ) • (ell2Resolvent hγ u) := by
    rw [ell2UnboundedExample, invShiftOperator_apply, hpre]
    norm_num
  rw [cshiftMap_apply]
  change γ • (ell2Resolvent hγ u) - ell2UnboundedExample ⟨ell2Resolvent hγ u, hmem⟩ = u
  rw [hA]
  apply lp.ext
  funext n
  have hne : γ - (n : ℂ) ≠ 0 := sub_natCast_ne_zero hγ n
  simp only [lp.coeFn_sub, lp.coeFn_smul, Pi.sub_apply, Pi.smul_apply, smul_eq_mul,
    ell2Resolvent, ell2ResolventPre, diagCLMC_apply, resCoeff, preCoeff]
  field_simp
  ring

/-- **The Hashimoto/SIRK algorithm with many non-real shifts, on a genuinely
unbounded Hamiltonian.**  For the number operator `A eₙ = n eₙ` on `ℓ²(ℕ, ℂ)`
— unbounded, by the last clause — and *any* sequence `γ : ℕ → ℂ` of shifts off
the real axis, the resolvents `X_j = (γ_j − A)⁻¹` are the bounded diagonal
operators `eₙ ↦ eₙ/(γ_j − n)`, they obey the resolvent identity, commute, obey
the SIRK relation and the rational-function identity of Eq. (11), their
Galerkin truncations converge to them, and each determines `A`. -/
theorem hashimoto_multishift_unbounded_example (γ : ℕ → ℂ) (hγ : ∀ j, (γ j).im ≠ 0) :
    ∃ X : ℕ → ℓ²(ℕ, ℂ) →L[ℂ] ℓ²(ℕ, ℂ),
      (∀ j u n, ((X j u : ℓ²(ℕ, ℂ)) : ℕ → ℂ) n = (u : ℕ → ℂ) n / (γ j - (n : ℂ))) ∧
      (∀ j, IsShiftInvertC ell2UnboundedExample (γ j) (X j)) ∧
      (∀ j, ‖X j‖ ≤ |(γ j).im|⁻¹) ∧
      (∀ j k u, X j u - X k u = (γ k - γ j) • X j (X k u)) ∧
      (∀ j k, X j ∘L X k = X k ∘L X j) ∧
      (∀ j m, X j ∘L (ContinuousLinearMap.id ℂ (ℓ²(ℕ, ℂ)) - (γ m - γ j) • X m) = X m) ∧
      (∀ m v k, sirkDen (X m) (fun i => γ m - γ i) k (rkVec X v k) = (X m ^ k) v) ∧
      (∀ j u, Tendsto (fun n : ℕ => galerkinCompression (X j) ell2Basis n u) atTop
        (nhds (X j u))) ∧
      (∀ j (Dom' : Submodule ℂ (ℓ²(ℕ, ℂ))) (A' : Dom' →ₗ[ℂ] ℓ²(ℕ, ℂ)),
        IsShiftInvertC A' (γ j) (X j) →
        Dom' = LinearMap.range (ell2ShiftInvert : ℓ²(ℕ, ℂ) →ₗ[ℂ] ℓ²(ℕ, ℂ))) ∧
      (∀ C : ℝ, ∃ x : finiteModeDomain ell2Basis,
        C * ‖(x : ℓ²(ℕ, ℂ))‖ < ‖ell2ExampleMatrix x‖) := by
  refine ⟨fun j => ell2Resolvent (hγ j), ?_, fun j => ell2Resolvent_isShiftInvertC (hγ j), ?_, ?_,
    ?_, ?_, ?_, fun j u => galerkinCompression_tendsto _ ell2Basis u, ?_,
    ell2ExampleMatrix_unbounded⟩
  · intro j u n
    have h1 : ((ell2Resolvent (hγ j) u : ℓ²(ℕ, ℂ)) : ℕ → ℂ) n
        = resCoeff (γ j) n * (u : ℕ → ℂ) n := diagCLMC_apply (resCoeff_norm_le (hγ j)) u n
    rw [h1, resCoeff, one_div, inv_mul_eq_div]
  · intro j
    exact (ell2Resolvent_isShiftInvertC (hγ j)).opNorm_le ell2Example_symmetricOn (hγ j)
  · intro j k u
    exact shiftInvertC_resolvent_identity (ell2Resolvent_isShiftInvertC (hγ j))
      (ell2Resolvent_isShiftInvertC (hγ k)) u
  · intro j k
    exact shiftInvertC_commute (ell2Resolvent_isShiftInvertC (hγ j))
      (ell2Resolvent_isShiftInvertC (hγ k))
  · intro j m
    exact shiftInvertC_comp_one_sub (ell2Resolvent_isShiftInvertC (hγ j))
      (ell2Resolvent_isShiftInvertC (hγ m))
  · intro m v k
    exact sirkDen_rkVec m (fun j => ell2Resolvent_isShiftInvertC (hγ j)) v k
  · intro j Dom' A' hA'
    obtain ⟨hdom, -⟩ := shiftInvertC_determines hA' (ell2Resolvent_isShiftInvertC (hγ j))
    exact hdom

end UnboundedExample

end BookProof.HashimotoShiftInvert
