import BookProof.Prelude
import BookProof.ChapterNonnegResolvent
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Analysis.Calculus.UniformLimitsDeriv
import Mathlib.Analysis.InnerProductSpace.Calculus

/-!
# The unitary group `e^{-itT}` of a non-negative self-adjoint linear relation

`BookProof.ChapterNonnegResolvent` produced, for a non-negative self-adjoint linear
relation `T` on a complex Hilbert space `F`, the resolvent family
`R a = (T + a)⁻¹` and the **Yosida approximation** `T_a = a (1 − a R a)`: bounded,
self-adjoint, non-negative operators with `T_a h → k` for `(h, k) ∈ T`.  This chapter
turns that approximation into the **one-parameter unitary group** `e^{-itT}` — the
Schrödinger dynamics generated by `T` — which is the object the Hashimoto–SIRK
shift-invert layer of this development consumes (a *unitary group*, not a semigroup:
the generator enters as `-iT`).

## The exponential of a bounded self-adjoint operator

`expU B t = e^{-itB}` for a bounded `B`.  For self-adjoint `B` it is unitary
(`expU_mem_unitary`) and isometric (`norm_expU_apply`); it satisfies `expU B 0 = 1`
(`expU_zero`), the group law `expU B (s + t) = expU B s * expU B t` (`expU_add`) and
the differential equation `d/dt e^{-itB} x = e^{-itB} (-iB) x`
(`hasDerivAt_expU_apply`).  The key quantitative statement is the **Duhamel estimate**
`‖(e^{-itB} − e^{-itC}) x‖ ≤ |t| ‖(B − C) x‖` for *commuting* bounded self-adjoint
`B, C` (`norm_expU_sub_apply_le`), with the special case
`‖e^{-itB} x − x‖ ≤ |t| ‖B x‖` (`norm_expU_sub_self_le`).

## The limit group

The Yosida approximations commute (`commute_yosidaCLM`, `commute_yosidaAt`) and
commute with every resolvent (`commute_yosidaCLM_invCLMAt`), so the approximating
groups `approxU hT n t = e^{-itT_{n+1}}` form a Cauchy sequence at every point of the
domain (`approxU_cauchy_of_mem`) and — the domain being dense for a single-valued `T`
(`BookProof.NonnegResolvent.dense_domain`) — at every vector (`approxU_cauchy`).  Its
limit is

* **`unitaryU hT hsv t = e^{-itT}`**, a bounded operator (`tendsto_unitaryU`) which is
  isometric (`norm_unitaryU_apply`) and unitary (`unitaryU_mem_unitary`,
  `unitaryU_surjective`), with `U 0 = 1` (`unitaryU_zero`) and the **group law**
  `U (s + t) = U s U t` (`unitaryU_add`, `unitaryU_apply_unitaryU`,
  `unitaryU_neg_eq_star`);
* **strongly continuous**: `‖U t h − h‖ ≤ |t| ‖k‖` on the domain
  (`norm_unitaryU_sub_of_mem`), whence `U t x → x` as `t → 0`
  (`tendsto_unitaryU_zero`) and `t ↦ U t x` is continuous
  (`continuous_unitaryU_apply`);
* approximated at the rate `‖U t h − e^{-itT_m} h‖ ≤ |t| ‖k − T_m h‖` on the domain
  (`norm_unitaryU_sub_approxU_le`) and **uniformly on bounded time intervals** at every
  vector (`tendstoUniformlyOn_approxU`).

## The dynamics

`e^{-itT}` commutes with every resolvent (`unitaryU_invCLMAt`), hence **leaves the
relation invariant**: `(h, k) ∈ T` implies `(U t h, U t k) ∈ T` (`mem_unitaryU`), so
the orbit of a point of the domain stays in the domain.  Along such an orbit the
**Schrödinger equation** holds globally in `t`,
`d/dt (e^{-itT} h) = -i e^{-itT} k` (`hasDerivAt_unitaryU`), and the inner products
— in particular the energy `⟪h, k⟫` — are conserved (`inner_unitaryU`,
`inner_unitaryU_of_mem`).  Conversely the orbits are the **only** solutions: a
differentiable curve staying in the relation and satisfying `u' = -i k` equals
`u s = e^{-isT} (u 0)` (`eq_unitaryU_of_hasDerivAt`), because the norm of a solution is
constant — the quadratic form of a symmetric relation being real
(`inner_mem_conj_eq`).

## Honest boundary

This is the abstract operator-theoretic statement for a *non-negative* self-adjoint
linear relation; nothing is claimed here about the project's physical Hamiltonians
beyond what follows once their hypotheses are checked.  The single-valuedness
hypothesis `hsv` is what makes the domain dense, and is the only place where the
relation is required to be an operator.  A functional calculus for unbounded
self-adjoint operators — and the spectral theorem behind it — is still not formalized
here; the group is built from the *bounded* Yosida approximants only.
-/

namespace BookProof.NonnegUnitaryGroup

open BookProof.ClosureUniqueness BookProof.PositiveSquareRoot BookProof.NonnegSquareRoot
open BookProof.NonnegResolvent
open Filter Topology NormedSpace
open scoped InnerProductSpace

variable {F : Type*} [NormedAddCommGroup F] [InnerProductSpace ℂ F] [CompleteSpace F]

noncomputable local instance ratNormedAlgebra : NormedAlgebra ℚ (F →L[ℂ] F) :=
  NormedAlgebra.restrictScalars ℚ ℂ (F →L[ℂ] F)

omit [CompleteSpace F] in
/-- Evaluating a differentiable curve of bounded operators at a fixed vector. -/
theorem hasDerivAt_apply {f : ℝ → (F →L[ℂ] F)} {f' : F →L[ℂ] F} {t : ℝ} (x : F)
    (h : HasDerivAt f f' t) : HasDerivAt (fun s => f s x) (f' x) t :=
  ((ContinuousLinearMap.apply ℂ F x).restrictScalars ℝ).hasFDerivAt.comp_hasDerivAt t h

/-! ## The exponential of a bounded self-adjoint operator -/

/-- The unitary `e^{-itB}` generated by a bounded self-adjoint operator `B`. -/
noncomputable def expU (B : F →L[ℂ] F) (t : ℝ) : F →L[ℂ] F := exp (t • ((-Complex.I) • B))

variable {B C : F →L[ℂ] F} {s t : ℝ}

theorem smul_neg_I_mem_skewAdjoint (hB : IsSelfAdjoint B) (t : ℝ) :
    t • ((-Complex.I) • B) ∈ skewAdjoint (F →L[ℂ] F) := by
  have hB' : star B = B := hB
  rw [skewAdjoint.mem_iff, star_smul, star_trivial, star_smul, hB']
  simp only [star_neg, Complex.star_def, Complex.conj_I, neg_neg]
  module

theorem expU_mem_unitary (hB : IsSelfAdjoint B) (t : ℝ) : expU B t ∈ unitary (F →L[ℂ] F) :=
  exp_mem_unitary_of_mem_skewAdjoint (smul_neg_I_mem_skewAdjoint hB t)

@[simp] theorem expU_zero (B : F →L[ℂ] F) : expU B 0 = 1 := by simp [expU]

theorem expU_add (B : F →L[ℂ] F) (s t : ℝ) : expU B (s + t) = expU B s * expU B t := by
  rw [expU, expU, expU, add_smul]
  exact exp_add_of_commute (((Commute.refl ((-Complex.I) • B)).smul_left s).smul_right t)

theorem norm_expU_apply (hB : IsSelfAdjoint B) (t : ℝ) (x : F) : ‖expU B t x‖ = ‖x‖ := by
  have hu : (star (expU B t)) * expU B t = 1 :=
    (Unitary.mem_iff.mp (expU_mem_unitary hB t)).1
  have hadj : ContinuousLinearMap.adjoint (expU B t) (expU B t x) = x := by
    have := congrArg (fun (S : F →L[ℂ] F) => S x) hu
    simpa [ContinuousLinearMap.star_eq_adjoint] using this
  have hinner : ⟪expU B t x, expU B t x⟫_ℂ = ⟪x, x⟫_ℂ := by
    rw [← ContinuousLinearMap.adjoint_inner_left, hadj]
  have h3 : (⟪expU B t x, expU B t x⟫_ℂ).re = (⟪x, x⟫_ℂ).re := by rw [hinner]
  simpa [inner_self_eq_norm_sq, ← Complex.ofReal_pow] using h3

theorem expU_zero_op (t : ℝ) : expU (0 : F →L[ℂ] F) t = 1 := by
  simp [expU]

theorem hasDerivAt_expU (B : F →L[ℂ] F) (t : ℝ) :
    HasDerivAt (fun s : ℝ => expU B s) (expU B t * ((-Complex.I) • B)) t :=
  hasDerivAt_exp_smul_const (𝕂 := ℝ) ((-Complex.I) • B) t

theorem hasDerivAt_expU_apply (B : F →L[ℂ] F) (t : ℝ) (x : F) :
    HasDerivAt (fun s : ℝ => expU B s x) ((expU B t) (((-Complex.I) • B) x)) t :=
  hasDerivAt_apply x (hasDerivAt_expU B t)

/-- **The fundamental estimate** `‖(e^{-itB} - e^{-itC}) x‖ ≤ |t| ‖(B - C) x‖` for commuting
bounded self-adjoint operators. -/
theorem norm_expU_sub_apply_le (hB : IsSelfAdjoint B) (hC : IsSelfAdjoint C)
    (hcomm : Commute B C) (t : ℝ) (x : F) :
    ‖expU B t x - expU C t x‖ ≤ |t| * ‖B x - C x‖ := by
  set gB : F →L[ℂ] F := (-Complex.I) • B with hgB
  set gC : F →L[ℂ] F := (-Complex.I) • C with hgC
  have hgcomm : Commute gB gC := (hcomm.smul_left _).smul_right _
  have hcommU : ∀ r : ℝ, gB * expU C r = expU C r * gB :=
    fun r => ((hgcomm.smul_right r).exp_right).eq
  set K : ℝ := ‖B x - C x‖ with hK
  set P : ℝ → (F →L[ℂ] F) := fun r => expU B (t - r) * expU C r with hP
  set D : ℝ → (F →L[ℂ] F) := fun r => (expU B (t - r) * expU C r) * (gC - gB) with hD
  have hderiv : ∀ r : ℝ, HasDerivAt (fun r => P r x) (D r x) r := by
    intro r
    have hc : HasDerivAt (fun r : ℝ => expU B (t - r)) (-(expU B (t - r) * gB)) r := by
      have h1 := hasDerivAt_expU B (t - r)
      have h2 : HasDerivAt (fun r : ℝ => t - r) (-1 : ℝ) r := by
        simpa using (hasDerivAt_id r).const_sub t
      have h3 := h1.scomp r h2
      have he : -(expU B (t - r) * gB) = Complex.I • (expU B (t - r) * B) := by
        rw [hgB, mul_smul_comm, neg_smul, neg_neg]
      rw [he]
      simpa using h3
    have hd : HasDerivAt (fun r : ℝ => expU C r) (expU C r * gC) r := hasDerivAt_expU C r
    have hmul := hc.mul hd
    have hEq : -(expU B (t - r) * gB) * expU C r + expU B (t - r) * (expU C r * gC) = D r := by
      calc -(expU B (t - r) * gB) * expU C r + expU B (t - r) * (expU C r * gC)
          = -(expU B (t - r) * (gB * expU C r)) + expU B (t - r) * (expU C r * gC) := by
            noncomm_ring
        _ = -(expU B (t - r) * (expU C r * gB)) + expU B (t - r) * (expU C r * gC) := by
            rw [hcommU r]
        _ = D r := by rw [hD]; noncomm_ring
    rw [hP]
    exact hasDerivAt_apply x (hEq ▸ hmul)
  have hnorm : ∀ r : ℝ, ‖D r x‖ = K := by
    intro r
    have h1 : D r x = expU B (t - r) (expU C r ((gC - gB) x)) := rfl
    rw [h1, norm_expU_apply hB, norm_expU_apply hC]
    have h2 : (gC - gB) x = (-Complex.I) • (C x - B x) := by
      simp [hgB, hgC, smul_sub]
    rw [h2, norm_smul, hK]
    simp [norm_sub_rev]
  have hmvt : ‖P t x - P 0 x‖ ≤ K * ‖t - 0‖ :=
    Convex.norm_image_sub_le_of_norm_hasDerivWithin_le
      (f := fun r => P r x) (f' := fun r => D r x) (C := K) (s := Set.univ)
      (fun r _ => (hderiv r).hasDerivWithinAt) (fun r _ => le_of_eq (hnorm r)) convex_univ
      (Set.mem_univ 0) (Set.mem_univ t)
  have hPt : P t x = expU C t x := by simp [hP]
  have hP0 : P 0 x = expU B t x := by simp [hP]
  rw [hPt, hP0] at hmvt
  calc ‖expU B t x - expU C t x‖
      = ‖expU C t x - expU B t x‖ := norm_sub_rev _ _
    _ ≤ K * ‖t - 0‖ := hmvt
    _ = |t| * K := by rw [sub_zero, Real.norm_eq_abs]; ring

/-- `‖e^{-itB} x - x‖ ≤ |t| ‖B x‖`. -/
theorem norm_expU_sub_self_le (hB : IsSelfAdjoint B) (t : ℝ) (x : F) :
    ‖expU B t x - x‖ ≤ |t| * ‖B x‖ := by
  have h := norm_expU_sub_apply_le hB (C := 0) (IsSelfAdjoint.zero _) (Commute.zero_right B) t x
  simpa [expU_zero_op] using h

omit [CompleteSpace F] in
/-- A sequence of isometric operators which converges pointwise on a dense set converges
pointwise everywhere (Cauchy version). -/
theorem cauchySeq_of_dense_of_isometry {G : ℕ → F →L[ℂ] F} (hiso : ∀ n y, ‖G n y‖ = ‖y‖)
    {D : Set F} (hD : Dense D) (hC : ∀ y ∈ D, CauchySeq (fun n => G n y)) (y : F) :
    CauchySeq (fun n => G n y) := by
  rw [Metric.cauchySeq_iff]
  intro ε hε
  obtain ⟨z, hz, hyz⟩ := hD.exists_dist_lt y (ε := ε / 3) (by linarith)
  obtain ⟨N, hN⟩ := Metric.cauchySeq_iff.mp (hC z hz) (ε / 3) (by linarith)
  refine ⟨N, fun k hk l hl => ?_⟩
  have hkz : dist (G k y) (G k z) = dist y z := by
    rw [dist_eq_norm, dist_eq_norm, ← map_sub, hiso]
  have hlz : dist (G l z) (G l y) = dist y z := by
    rw [dist_eq_norm, dist_eq_norm, ← map_sub, hiso, norm_sub_rev]
  calc dist (G k y) (G l y)
      ≤ dist (G k y) (G k z) + dist (G k z) (G l z) + dist (G l z) (G l y) :=
        dist_triangle4 _ _ _ _
    _ < ε / 3 + ε / 3 + ε / 3 := by
        rw [hkz, hlz]
        have := hN k hk l hl
        linarith
    _ = ε := by ring

/-! ## The approximating unitary groups `e^{-itT_a}` -/

variable {T : Submodule ℂ (F × F)} {a b : ℝ}

/-- The Yosida approximations of a non-negative self-adjoint relation commute. -/
theorem commute_invCLMAt (hT : IsNonnegSelfAdjoint T) (ha : 0 < a) (hb : 0 < b) :
    Commute (invCLMAt hT ha) (invCLMAt hT hb) := by
  change invCLMAt hT ha * invCLMAt hT hb = invCLMAt hT hb * invCLMAt hT ha
  ext x
  simpa using invCLMAt_comm hT ha hb x

theorem commute_yosidaCLM (hT : IsNonnegSelfAdjoint T) (ha : 0 < a) (hb : 0 < b) :
    Commute (yosidaCLM hT ha) (yosidaCLM hT hb) := by
  have hc := commute_invCLMAt hT ha hb
  have h1 : Commute ((a : ℂ) • invCLMAt hT ha) (1 - (b : ℂ) • invCLMAt hT hb) :=
    (Commute.one_right _).sub_right ((hc.smul_left (a : ℂ)).smul_right (b : ℂ))
  have h2 : Commute (1 - (a : ℂ) • invCLMAt hT ha) (1 - (b : ℂ) • invCLMAt hT hb) :=
    (Commute.one_left _).sub_left h1
  simpa only [yosidaCLM] using (h2.smul_left (a : ℂ)).smul_right (b : ℂ)

/-- The Yosida approximation commutes with every resolvent. -/
theorem commute_yosidaCLM_invCLMAt (hT : IsNonnegSelfAdjoint T) (ha : 0 < a) (hb : 0 < b) :
    Commute (yosidaCLM hT ha) (invCLMAt hT hb) := by
  have hc := commute_invCLMAt hT ha hb
  have h1 : Commute ((a : ℂ) • invCLMAt hT ha) (invCLMAt hT hb) := hc.smul_left (a : ℂ)
  have h2 : Commute (1 - (a : ℂ) • invCLMAt hT ha) (invCLMAt hT hb) :=
    (Commute.one_left _).sub_left h1
  simpa only [yosidaCLM] using h2.smul_left (a : ℂ)

theorem commute_yosidaAt (hT : IsNonnegSelfAdjoint T) (n m : ℕ) :
    Commute (yosidaAt hT n) (yosidaAt hT m) :=
  commute_yosidaCLM hT _ _

theorem isSelfAdjoint_yosidaAt (hT : IsNonnegSelfAdjoint T) (n : ℕ) :
    IsSelfAdjoint (yosidaAt hT n) :=
  isSelfAdjoint_yosidaCLM hT _

/-- The approximating unitary group `e^{-itT_n}` built from the Yosida approximation. -/
noncomputable def approxU (hT : IsNonnegSelfAdjoint T) (n : ℕ) (t : ℝ) : F →L[ℂ] F :=
  expU (yosidaAt hT n) t

@[simp] theorem approxU_zero (hT : IsNonnegSelfAdjoint T) (n : ℕ) : approxU hT n 0 = 1 :=
  expU_zero _

theorem approxU_add (hT : IsNonnegSelfAdjoint T) (n : ℕ) (s t : ℝ) :
    approxU hT n (s + t) = approxU hT n s * approxU hT n t :=
  expU_add _ s t

theorem norm_approxU_apply (hT : IsNonnegSelfAdjoint T) (n : ℕ) (t : ℝ) (x : F) :
    ‖approxU hT n t x‖ = ‖x‖ :=
  norm_expU_apply (isSelfAdjoint_yosidaAt hT n) t x

/-- The fundamental estimate `‖(e^{-itT_n} - e^{-itT_m}) x‖ ≤ |t| ‖(T_n - T_m) x‖`. -/
theorem norm_approxU_sub_apply_le (hT : IsNonnegSelfAdjoint T) (n m : ℕ) (t : ℝ) (x : F) :
    ‖approxU hT n t x - approxU hT m t x‖ ≤ |t| * ‖yosidaAt hT n x - yosidaAt hT m x‖ :=
  norm_expU_sub_apply_le (isSelfAdjoint_yosidaAt hT n) (isSelfAdjoint_yosidaAt hT m)
    (commute_yosidaAt hT n m) t x

/-! ## The limit group -/

theorem approxU_cauchy_of_mem (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) {h k : F} (hk : (h, k) ∈ T) (t : ℝ) :
    CauchySeq (fun n : ℕ => approxU hT n t h) := by
  have hy : CauchySeq (fun n : ℕ => yosidaAt hT n h) := (tendsto_yosidaAt hT hsv hk).cauchySeq
  rw [Metric.cauchySeq_iff]
  intro ε hε
  have hpos : (0 : ℝ) < ε / (|t| + 1) := by positivity
  obtain ⟨N, hN⟩ := Metric.cauchySeq_iff.mp hy _ hpos
  refine ⟨N, fun n hn m hm => ?_⟩
  have hnm := hN n hn m hm
  rw [dist_eq_norm] at hnm ⊢
  have habs : (0 : ℝ) ≤ |t| := abs_nonneg t
  calc ‖approxU hT n t h - approxU hT m t h‖
      ≤ |t| * ‖yosidaAt hT n h - yosidaAt hT m h‖ := norm_approxU_sub_apply_le hT n m t h
    _ ≤ |t| * (ε / (|t| + 1)) := by gcongr
    _ < ε := by
        rw [mul_div_assoc', div_lt_iff₀ (by positivity)]
        nlinarith

theorem approxU_cauchy (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) (x : F) :
    CauchySeq (fun n : ℕ => approxU hT n t x) := by
  refine cauchySeq_of_dense_of_isometry (G := fun n => approxU hT n t)
    (fun n y => norm_approxU_apply hT n t y) (dense_domain hT hsv) ?_ x
  intro y hy
  obtain ⟨p, hp, hp1⟩ := Submodule.mem_map.1 hy
  have hpy : (y, p.2) ∈ T := by
    have hpe : p = (y, p.2) := by
      rw [← hp1]
      simp
    rwa [← hpe]
  exact approxU_cauchy_of_mem hT hsv hpy t

/-- The unitary group `e^{-itT}` generated by a non-negative self-adjoint linear relation,
as a function. -/
noncomputable def unitaryFun (hT : IsNonnegSelfAdjoint T) (t : ℝ) (x : F) : F :=
  limUnder atTop (fun n : ℕ => approxU hT n t x)

theorem tendsto_unitaryFun (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) (x : F) :
    Tendsto (fun n : ℕ => approxU hT n t x) atTop (𝓝 (unitaryFun hT t x)) := by
  obtain ⟨z, hz⟩ := cauchySeq_tendsto_of_complete (approxU_cauchy hT hsv t x)
  rw [unitaryFun, hz.limUnder_eq]
  exact hz

theorem norm_unitaryFun (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) (x : F) :
    ‖unitaryFun hT t x‖ = ‖x‖ := by
  have h1 : Tendsto (fun n : ℕ => ‖approxU hT n t x‖) atTop (𝓝 ‖unitaryFun hT t x‖) :=
    (tendsto_unitaryFun hT hsv t x).norm
  have h2 : (fun n : ℕ => ‖approxU hT n t x‖) = fun _ : ℕ => ‖x‖ := by
    funext n; exact norm_approxU_apply hT n t x
  rw [h2] at h1
  exact tendsto_nhds_unique h1 tendsto_const_nhds

/-- `e^{-itT}` as a linear map. -/
noncomputable def unitaryLinear (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) : F →ₗ[ℂ] F where
  toFun x := unitaryFun hT t x
  map_add' x y := by
    refine tendsto_nhds_unique (tendsto_unitaryFun hT hsv t (x + y)) ?_
    have h : (fun n : ℕ => approxU hT n t (x + y))
        = fun n : ℕ => approxU hT n t x + approxU hT n t y := by
      funext n; rw [map_add]
    rw [h]
    exact (tendsto_unitaryFun hT hsv t x).add (tendsto_unitaryFun hT hsv t y)
  map_smul' c x := by
    refine tendsto_nhds_unique (tendsto_unitaryFun hT hsv t (c • x)) ?_
    have h : (fun n : ℕ => approxU hT n t (c • x))
        = fun n : ℕ => c • approxU hT n t x := by
      funext n; rw [map_smul]
    rw [h]
    exact (tendsto_unitaryFun hT hsv t x).const_smul c

/-- **The unitary group `e^{-itT}`** generated by a non-negative self-adjoint linear
relation. -/
noncomputable def unitaryU (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) : F →L[ℂ] F :=
  (unitaryLinear hT hsv t).mkContinuous 1 (fun x => by
    simp only [unitaryLinear, LinearMap.coe_mk, AddHom.coe_mk, one_mul]
    exact le_of_eq (norm_unitaryFun hT hsv t x))

@[simp] theorem unitaryU_apply (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) (x : F) :
    unitaryU hT hsv t x = unitaryFun hT t x := rfl

theorem tendsto_unitaryU (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) (x : F) :
    Tendsto (fun n : ℕ => approxU hT n t x) atTop (𝓝 (unitaryU hT hsv t x)) :=
  tendsto_unitaryFun hT hsv t x

theorem norm_unitaryU_apply (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) (x : F) :
    ‖unitaryU hT hsv t x‖ = ‖x‖ :=
  norm_unitaryFun hT hsv t x

@[simp] theorem unitaryU_zero (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) : unitaryU hT hsv 0 = 1 := by
  ext x
  refine tendsto_nhds_unique (tendsto_unitaryU hT hsv 0 x) ?_
  have h : (fun n : ℕ => approxU hT n 0 x) = fun _ : ℕ => x := by
    funext n; simp
  rw [h]
  simp

/-- **The one-parameter group law** `U (s + t) = U s U t`. -/
theorem unitaryU_add (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (s t : ℝ) :
    unitaryU hT hsv (s + t) = unitaryU hT hsv s * unitaryU hT hsv t := by
  ext x
  refine tendsto_nhds_unique (tendsto_unitaryU hT hsv (s + t) x) ?_
  have h : (fun n : ℕ => approxU hT n (s + t) x)
      = fun n : ℕ => approxU hT n s (approxU hT n t x) := by
    funext n
    rw [approxU_add]
    rfl
  rw [h]
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨N₁, hN₁⟩ := Metric.tendsto_atTop.mp (tendsto_unitaryU hT hsv t x) (ε / 2) (by linarith)
  obtain ⟨N₂, hN₂⟩ :=
    Metric.tendsto_atTop.mp (tendsto_unitaryU hT hsv s (unitaryU hT hsv t x)) (ε / 2)
      (by linarith)
  refine ⟨max N₁ N₂, fun n hn => ?_⟩
  have hn1 : N₁ ≤ n := le_trans (le_max_left _ _) hn
  have hn2 : N₂ ≤ n := le_trans (le_max_right _ _) hn
  have h1 : dist (approxU hT n s (approxU hT n t x)) (approxU hT n s (unitaryU hT hsv t x))
      < ε / 2 := by
    rw [dist_eq_norm, ← map_sub, norm_approxU_apply]
    have := hN₁ n hn1
    rwa [dist_eq_norm] at this
  have h2 : dist (approxU hT n s (unitaryU hT hsv t x))
      (unitaryU hT hsv s (unitaryU hT hsv t x)) < ε / 2 := hN₂ n hn2
  calc dist (approxU hT n s (approxU hT n t x)) (unitaryU hT hsv s (unitaryU hT hsv t x))
      ≤ dist (approxU hT n s (approxU hT n t x)) (approxU hT n s (unitaryU hT hsv t x))
        + dist (approxU hT n s (unitaryU hT hsv t x))
            (unitaryU hT hsv s (unitaryU hT hsv t x)) := dist_triangle _ _ _
    _ < ε := by linarith

theorem unitaryU_apply_unitaryU (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (s t : ℝ) (x : F) :
    unitaryU hT hsv s (unitaryU hT hsv t x) = unitaryU hT hsv (s + t) x := by
  rw [unitaryU_add hT hsv]; rfl

theorem unitaryU_surjective (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) :
    Function.Surjective (unitaryU hT hsv t) := by
  intro y
  refine ⟨unitaryU hT hsv (-t) y, ?_⟩
  rw [unitaryU_apply_unitaryU]
  simp

/-- **`e^{-itT}` is unitary.** -/
theorem unitaryU_mem_unitary (hT : IsNonnegSelfAdjoint T)
    (hsv : ∀ w : F, ((0 : F), w) ∈ T → w = 0) (t : ℝ) :
    unitaryU hT hsv t ∈ unitary (F →L[ℂ] F) := by
  have hiso : ∀ x y : F, ⟪unitaryU hT hsv t x, unitaryU hT hsv t y⟫_ℂ = ⟪x, y⟫_ℂ := by
    intro x y
    have hn : ∀ z : F, ‖(unitaryU hT hsv t : F →ₗ[ℂ] F) z‖ = ‖z‖ :=
      fun z => norm_unitaryU_apply hT hsv t z
    exact (LinearIsometry.mk (unitaryU hT hsv t : F →ₗ[ℂ] F) hn).inner_map_map x y
  have hstar : star (unitaryU hT hsv t) * unitaryU hT hsv t = 1 := by
    ext x
    have : ContinuousLinearMap.adjoint (unitaryU hT hsv t) (unitaryU hT hsv t x) = x := by
      refine ext_inner_right ℂ ?_
      intro y
      rw [ContinuousLinearMap.adjoint_inner_left, hiso]
    simpa [ContinuousLinearMap.star_eq_adjoint] using this
  refine Unitary.mem_iff.mpr ⟨hstar, ?_⟩
  ext y
  obtain ⟨x, hx⟩ := unitaryU_surjective hT hsv t y
  have hxx : (star (unitaryU hT hsv t)) (unitaryU hT hsv t x) = x := by
    have h := congrArg (fun (S : F →L[ℂ] F) => S x) hstar
    simpa using h
  rw [← hx]
  simp only [ContinuousLinearMap.mul_apply, ContinuousLinearMap.one_apply, hxx]

end BookProof.NonnegUnitaryGroup
