import Mathlib
import BookProof.ChapterQuantumGravityFock
import BookProof.ChapterBrstReducedTransfer
import BookProof.ChapterQgBrstCompleted.Part1

/-!
# The bounded BRST charge on the *completed* graded Hilbert space, and its reduced transfer

`CONSOLIDATED_PLAN.md` §10.6.2 item 4 is closed except for one join: the BRST charge of
`ChapterQuantumGravityBrstCharge` is built on the *algebraic* graded space
`ℂ[x₀,…,x₈₃] ⊗ Λ(ℂ¹⁹)`, whereas the reduced-transfer theorems of
`ChapterBrstReducedTransfer` need a **bounded** nilpotent charge on a *complete* space.
This module supplies exactly that missing object and performs the join.

## What is proved

* **A bounded weighted shift calculus on `ℓ²`** (`wshift`).  For a weight `w` with
  `‖w i‖ ≤ 1` and a reindexing `e` that is injective on the support of `w`, the map
  `f ↦ (i ↦ w i * f (e i))` is a bounded operator of norm `≤ 1` on `ℓ²(ι)`
  (`memlp_weighted`, `wshiftL_norm_le`).  This is the analytic content: the pullback of a
  square-summable family along a partially injective reindexing stays square-summable.
* **The ghost creation operators on the completed graded space.**  On
  `QGH = ℓ²(GradedIdx)` — the completion of the graded Fock space of
  `ChapterQuantumGravityFock`, `GradedIdx = BoseConf × FermConf` — the operator
  `brstTerm sym a` is `Ψ†_a` dressed with a bounded boson-sector constraint symbol
  `sym a : BoseConf → ℂ`.  It is bounded by `1` and satisfies the Jordan–Wigner
  anticommutation relations `brstTerm_comp_self` (`(Ψ†_a)² = 0`) and `brstTerm_anticomm`
  (`Ψ†_aΨ†_b + Ψ†_bΨ†_a = 0`).
* **The bounded nilpotent BRST charge** `qgBrstCharge sym = ∑_{a<19} sym_a Ψ†_a` over the
  book's `19` diffeomorphism ghosts: `qgBrstCharge_nilpotent` (`Ω² = 0`) and
  `qgBrstCharge_ne_zero` (it is not the zero operator, so the statement is not vacuous).
* **An explicit unitary group commuting with it**: `qgPhase omega t`, multiplication by
  `e^{-it·(boson energy)}`, with `qgPhase_zero`, `qgPhase_group`, `qgPhase_isometry` and
  `qgPhase_comm_brst`.  `qgPhase_single` identifies it on the occupation basis as the
  evolution generated by the graded Fock symbol `qgGradedSymbol omega 0` of
  `ChapterQuantumGravityFock` — the ghost-energy-free case, which is precisely the case in
  which the evolution commutes with the ghost ladder.
* **The join** (§10.6.2 item 4): `qgBrstTransfer` is the induced one-parameter group on the
  BRST cohomology `Cohomology (qgBrstCharge sym)` of the completed space, with
  `qgBrstTransfer_zero`, `qgBrstTransfer_comp`, `qgBrstTransfer_bijective`,
  `qgPhase_mem_physicalStates` (the §10.3 caveat: the evolution preserves the physical
  subspace) and `qgBrstTransfer_infDist` (the BRST quotient norm is preserved).

## Honest boundary

The charge is `Ω = ∑_a C_a Ψ†_a` with the constraint symbols `C_a` *diagonal* in the boson
occupation basis and bounded by one; the full gauge-fixed constraint algebra (whose
generators are unbounded) is not represented, and no claim is made that this `Ω` is the
BRST charge of the `R + αR²` theory.  What is claimed, and proved, is that the reduced
transfer of §10.6.2 item 4 now has a concrete bounded nilpotent charge on a complete
Hilbert space, together with a nontrivial commuting unitary group.  The Hamiltonian whose
group is used here has no ghost energy: a nonzero ghost energy does *not* commute with the
ghost ladder, so its evolution does not descend — that obstruction is recorded, not hidden.
-/

namespace BookProof.QgBrstCompleted

open scoped ENNReal
open BookProof BookProof.QuantumGravityFock BookProof.BrstReducedTransfer

noncomputable section
/-! ## The bounded nilpotent BRST charge -/

/-- **The bounded BRST charge** on the completed graded space: the sum of the dressed ghost
creations over the book's `19` diffeomorphism ghosts. -/
def qgBrstCharge (sym : ℕ → BoseConf → ℂ) (hsym : ∀ a n, ‖sym a n‖ ≤ 1) : QGH →L[ℂ] QGH :=
  ∑ a ∈ Finset.range qgGhostModes, brstTerm sym hsym a

theorem qgBrstCharge_apply_eq_sum {sym : ℕ → BoseConf → ℂ} (hsym : ∀ a n, ‖sym a n‖ ≤ 1)
    (f : QGH) :
    qgBrstCharge sym hsym f = ∑ a ∈ Finset.range qgGhostModes, brstTerm sym hsym a f := by
  rw [qgBrstCharge, ContinuousLinearMap.sum_apply]

/-- In a complex vector space an element equal to its own negative vanishes. -/
theorem eq_zero_of_eq_neg_self {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E] {x : E}
    (h : x = -x) : x = 0 := by
  have h2 : (2 : ℂ) • x = 0 := by
    rw [two_smul]
    nth_rewrite 2 [h]
    simp
  simpa using h2

/-- **Nilpotency of the BRST charge**, `Ω² = 0`, on the *completed* Hilbert space. -/
theorem qgBrstCharge_nilpotent {sym : ℕ → BoseConf → ℂ} (hsym : ∀ a n, ‖sym a n‖ ≤ 1)
    (f : QGH) : qgBrstCharge sym hsym (qgBrstCharge sym hsym f) = 0 := by
  classical
  have hanti : ∀ a b : ℕ, brstTerm sym hsym a (brstTerm sym hsym b f)
      + brstTerm sym hsym b (brstTerm sym hsym a f) = 0 := by
    intro a b
    by_cases hab : a = b
    · subst hab
      simp [brstTerm_comp_self hsym a f]
    · exact brstTerm_anticomm hsym hab f
  have hS : qgBrstCharge sym hsym (qgBrstCharge sym hsym f)
      = ∑ a ∈ Finset.range qgGhostModes, ∑ b ∈ Finset.range qgGhostModes,
          brstTerm sym hsym a (brstTerm sym hsym b f) := by
    rw [qgBrstCharge_apply_eq_sum, qgBrstCharge_apply_eq_sum]
    exact Finset.sum_congr rfl fun a _ => map_sum _ _ _
  rw [hS]
  refine eq_zero_of_eq_neg_self ?_
  calc ∑ a ∈ Finset.range qgGhostModes, ∑ b ∈ Finset.range qgGhostModes,
          brstTerm sym hsym a (brstTerm sym hsym b f)
      = ∑ a ∈ Finset.range qgGhostModes, ∑ b ∈ Finset.range qgGhostModes,
          -brstTerm sym hsym a (brstTerm sym hsym b f) := by
        rw [Finset.sum_comm]
        exact Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ =>
          eq_neg_of_add_eq_zero_left (hanti b a)
    _ = -∑ a ∈ Finset.range qgGhostModes, ∑ b ∈ Finset.range qgGhostModes,
          brstTerm sym hsym a (brstTerm sym hsym b f) := by
        simp

/-- The undressed (unit-symbol) BRST charge. -/
def oneSym : ℕ → BoseConf → ℂ := fun _ _ => 1

theorem oneSym_norm_le (a : ℕ) (n : BoseConf) : ‖oneSym a n‖ ≤ 1 := by simp [oneSym]

/-- The charge sends the ghost vacuum component to the one-ghost component of mode `0`. -/
theorem qgBrstCharge_one_ghost_zero (f : QGH) (n : BoseConf) :
    (qgBrstCharge oneSym oneSym_norm_le f) (n, ({0} : FermConf)) = f (n, (∅ : FermConf)) := by
  classical
  rw [qgBrstCharge_apply_eq_sum, lp.coeFn_sum, Finset.sum_apply, Finset.sum_eq_single 0]
  · rw [brstTerm_apply]
    have herase : ({0} : FermConf).erase 0 = ∅ := by simp
    rw [if_pos (by simp : (0 : ℕ) ∈ ({0} : FermConf))]
    simp only [herase, oneSym, jwSign, jwCount]
    norm_num
  · intro a _ hane
    rw [brstTerm_apply]
    have ha0 : a ∉ ({0} : FermConf) := by simpa using hane
    simp [ha0]
  · intro h
    exact absurd (Finset.mem_range.mpr (by norm_num [qgGhostModes])) h

/-- The BRST charge is **not** the zero operator: it moves the ghost vacuum over a boson
configuration into the one-ghost sector. -/
theorem qgBrstCharge_ne_zero : qgBrstCharge oneSym oneSym_norm_le ≠ 0 := by
  classical
  intro hzero
  have hval := qgBrstCharge_one_ghost_zero (lp.single 2 ((0 : BoseConf), (∅ : FermConf)) 1) 0
  rw [hzero] at hval
  simp at hval

/-! ## An explicit unitary group commuting with the charge -/

/-- The phase weight `e^{-it·E(n)}` of the boson-diagonal evolution. -/
def phaseWeight (omega : ℕ → ℝ) (t : ℝ) : GradedIdx → ℂ :=
  fun p => Complex.exp (-(t * BookProof.NavierStokesFlow.FockOfFock.confEnergy omega p.1) *
    Complex.I)

theorem phaseWeight_norm (omega : ℕ → ℝ) (t : ℝ) (p : GradedIdx) :
    ‖phaseWeight omega t p‖ = 1 := by
  rw [phaseWeight, mul_comm]
  rw [Complex.norm_exp]
  simp

theorem phaseWeight_norm_le (omega : ℕ → ℝ) (t : ℝ) (p : GradedIdx) :
    ‖phaseWeight omega t p‖ ≤ 1 := le_of_eq (phaseWeight_norm omega t p)

theorem id_injOn (omega : ℕ → ℝ) (t : ℝ) :
    Set.InjOn (id : GradedIdx → GradedIdx) {p | phaseWeight omega t p ≠ 0} :=
  fun _ _ _ _ h => h

/-- **The evolution group** on the completed graded space: multiplication by the phase
`e^{-it·E(n)}` of the boson energy.  This is the unitary group generated by the graded Fock
Hamiltonian of `ChapterQuantumGravityFock` with vanishing ghost energy. -/
def qgPhase (omega : ℕ → ℝ) (t : ℝ) : QGH →L[ℂ] QGH :=
  wshift (phaseWeight omega t) id (phaseWeight_norm_le omega t) (id_injOn omega t)

@[simp] theorem qgPhase_apply (omega : ℕ → ℝ) (t : ℝ) (f : QGH) (p : GradedIdx) :
    (qgPhase omega t f) p = phaseWeight omega t p * f p := rfl

theorem qgPhase_zero (omega : ℕ → ℝ) (f : QGH) : qgPhase omega 0 f = f := by
  ext p
  simp [phaseWeight]

theorem qgPhase_group (omega : ℕ → ℝ) (s t : ℝ) (f : QGH) :
    qgPhase omega s (qgPhase omega t f) = qgPhase omega (s + t) f := by
  ext p
  simp only [qgPhase_apply, phaseWeight, ← mul_assoc, ← Complex.exp_add]
  congr 2
  push_cast
  ring

theorem qgPhase_isometry (omega : ℕ → ℝ) (t : ℝ) (f : QGH) : ‖qgPhase omega t f‖ = ‖f‖ :=
  wshift_norm_eq _ _ _ _ (phaseWeight_norm omega t) rfl f

/-- On an occupation basis vector the group acts by the phase of the graded Fock symbol with
vanishing ghost energy — it *is* the second-quantized evolution of
`ChapterQuantumGravityFock`. -/
theorem qgPhase_single (omega : ℕ → ℝ) (t : ℝ) (p : GradedIdx) (c : ℂ) :
    qgPhase omega t (lp.single 2 p c)
      = Complex.exp (-(t * qgGradedSymbol omega (fun _ => 0) p) * Complex.I) •
          lp.single 2 p c := by
  classical
  ext q
  rw [qgPhase_apply, lp.coeFn_smul, Pi.smul_apply, smul_eq_mul]
  by_cases hq : q = p
  · subst hq
    rw [phaseWeight]
    congr 3
    rw [qgGradedSymbol]
    simp [ghostEnergy]
  · simp [lp.single_apply, hq]

/-- The evolution commutes with the BRST charge: the phase depends only on the boson
occupation, which the ghost ladder does not change. -/
theorem qgPhase_comm_brst {sym : ℕ → BoseConf → ℂ} (hsym : ∀ a n, ‖sym a n‖ ≤ 1)
    (omega : ℕ → ℝ) (t : ℝ) (f : QGH) :
    qgPhase omega t (qgBrstCharge sym hsym f) = qgBrstCharge sym hsym (qgPhase omega t f) := by
  classical
  have hterm : ∀ a : ℕ, qgPhase omega t (brstTerm sym hsym a f)
      = brstTerm sym hsym a (qgPhase omega t f) := by
    intro a
    ext p
    rw [qgPhase_apply, brstTerm_apply, brstTerm_apply, qgPhase_apply]
    rw [phaseWeight, phaseWeight]
    ring
  rw [qgBrstCharge_apply_eq_sum, qgBrstCharge_apply_eq_sum, map_sum]
  exact Finset.sum_congr rfl fun a _ => hterm a

/-! ## The ghost-energy obstruction -/

/-- The phase weight of the **full** graded Fock symbol, boson energy *plus* ghost energy. -/
def fullPhaseWeight (omega g : ℕ → ℝ) (t : ℝ) : GradedIdx → ℂ :=
  fun p => Complex.exp (-(t * qgGradedSymbol omega g p) * Complex.I)

theorem fullPhaseWeight_norm (omega g : ℕ → ℝ) (t : ℝ) (p : GradedIdx) :
    ‖fullPhaseWeight omega g t p‖ = 1 := by
  rw [fullPhaseWeight, mul_comm, Complex.norm_exp]
  simp

theorem fullPhaseWeight_norm_le (omega g : ℕ → ℝ) (t : ℝ) (p : GradedIdx) :
    ‖fullPhaseWeight omega g t p‖ ≤ 1 := le_of_eq (fullPhaseWeight_norm omega g t p)

theorem id_injOn_full (omega g : ℕ → ℝ) (t : ℝ) :
    Set.InjOn (id : GradedIdx → GradedIdx) {p | fullPhaseWeight omega g t p ≠ 0} :=
  fun _ _ _ _ h => h

/-- The evolution generated by the **full** graded Fock symbol: boson energy plus ghost
energy.  It is again a unitary group on the completed graded space. -/
def qgPhaseFull (omega g : ℕ → ℝ) (t : ℝ) : QGH →L[ℂ] QGH :=
  wshift (fullPhaseWeight omega g t) id (fullPhaseWeight_norm_le omega g t)
    (id_injOn_full omega g t)

@[simp] theorem qgPhaseFull_apply (omega g : ℕ → ℝ) (t : ℝ) (f : QGH) (p : GradedIdx) :
    (qgPhaseFull omega g t f) p = fullPhaseWeight omega g t p * f p := rfl

theorem qgPhaseFull_isometry (omega g : ℕ → ℝ) (t : ℝ) (f : QGH) :
    ‖qgPhaseFull omega g t f‖ = ‖f‖ :=
  wshift_norm_eq _ _ _ _ (fullPhaseWeight_norm omega g t) rfl f

/-- **The ghost-energy obstruction is real, not a stylistic restriction.**  If some ghost
energy is nonzero, the evolution it generates does *not* commute with the BRST charge, so
it does not descend to the BRST cohomology.  This is why the group used above carries no
ghost energy. -/
theorem qgPhaseFull_not_comm_brst (omega g : ℕ → ℝ) (hg : g 0 ≠ 0) :
    ¬ ∀ (t : ℝ) (y : QGH), qgPhaseFull omega g t (qgBrstCharge oneSym oneSym_norm_le y)
      = qgBrstCharge oneSym oneSym_norm_le (qgPhaseFull omega g t y) := by
  classical
  intro hcomm
  set t : ℝ := Real.pi / g 0 with ht
  set f : QGH := lp.single 2 ((0 : BoseConf), (∅ : FermConf)) 1 with hf
  have hfv : f ((0 : BoseConf), (∅ : FermConf)) = 1 := by
    rw [hf]; simp
  have h := congrArg (fun z : QGH => z ((0 : BoseConf), ({0} : FermConf))) (hcomm t f)
  simp only [qgPhaseFull_apply, qgBrstCharge_one_ghost_zero] at h
  rw [hfv, mul_one] at h
  -- the vacuum has zero energy, the one-ghost state has energy `g 0`
  have hg0 : ((g 0 : ℝ) : ℂ) ≠ 0 := by exact_mod_cast hg
  have hpi : ((t : ℂ) * ((g 0 : ℝ) : ℂ)) = ((Real.pi : ℝ) : ℂ) := by
    rw [ht]
    push_cast
    field_simp
  rw [fullPhaseWeight, fullPhaseWeight, qgGradedSymbol_oneGhost, qgGradedSymbol_vacuum,
    hpi] at h
  rw [show (-((Real.pi : ℝ) : ℂ)) * Complex.I = -(((Real.pi : ℝ) : ℂ) * Complex.I) by ring,
    Complex.exp_neg, Complex.exp_pi_mul_I] at h
  norm_num at h

/-! ## The join: the BRST-reduced transfer on the completed graded space -/

variable {sym : ℕ → BoseConf → ℂ} (hsym : ∀ a n, ‖sym a n‖ ≤ 1) (omega : ℕ → ℝ)

include hsym in
/-- The commutation hypothesis in the exact shape the reduction theorems consume. -/
theorem qgPhase_commutes :
    ∀ (t : ℝ) (y : QGH), qgPhase omega t (qgBrstCharge sym hsym y)
      = qgBrstCharge sym hsym (qgPhase omega t y) :=
  fun t y => qgPhase_comm_brst hsym omega t y

include hsym in
/-- The exact states are physical: the cohomology of the completed space is defined. -/
theorem qgExact_le_physical :
    exactStates (qgBrstCharge sym hsym) ≤ physicalStates (qgBrstCharge sym hsym) :=
  exactStates_le_physicalStates _ (qgBrstCharge_nilpotent hsym)

include hsym in
/-- **The §10.3 caveat, on the completed space**: the evolution maps physical (BRST-closed)
states to physical states. -/
theorem qgPhase_mem_physicalStates (t : ℝ) {x : QGH}
    (hx : x ∈ physicalStates (qgBrstCharge sym hsym)) :
    qgPhase omega t x ∈ physicalStates (qgBrstCharge sym hsym) :=
  physicalStates_invariant (Om := qgBrstCharge sym hsym) (qgPhase_commutes hsym omega t) x hx

include hsym in
/-- The evolution maps BRST-exact states to BRST-exact states. -/
theorem qgPhase_mem_exactStates (t : ℝ) {x : QGH}
    (hx : x ∈ exactStates (qgBrstCharge sym hsym)) :
    qgPhase omega t x ∈ exactStates (qgBrstCharge sym hsym) :=
  exactStates_invariant (Om := qgBrstCharge sym hsym) (qgPhase_commutes hsym omega t) x hx

/-- **The BRST-reduced transfer of §10.6.2 item 4**, now on the completed graded Hilbert
space with a genuinely bounded nilpotent charge. -/
def qgBrstTransfer (t : ℝ) :
    Cohomology (qgBrstCharge sym hsym) →ₗ[ℂ] Cohomology (qgBrstCharge sym hsym) :=
  transfer (qgBrstCharge sym hsym) (qgPhase omega) (qgPhase_commutes hsym omega) t

theorem qgBrstTransfer_zero : qgBrstTransfer hsym omega 0 = LinearMap.id :=
  transfer_zero (qgBrstCharge sym hsym) (qgPhase omega) (qgPhase_commutes hsym omega)
    (qgPhase_zero omega)

theorem qgBrstTransfer_comp (s t : ℝ) :
    (qgBrstTransfer hsym omega s).comp (qgBrstTransfer hsym omega t)
      = qgBrstTransfer hsym omega (s + t) :=
  transfer_comp (qgBrstCharge sym hsym) (qgPhase omega) (qgPhase_commutes hsym omega)
    (qgPhase_group omega) s t

theorem qgBrstTransfer_bijective (t : ℝ) : Function.Bijective (qgBrstTransfer hsym omega t) :=
  transfer_bijective (qgBrstCharge sym hsym) (qgPhase omega) (qgPhase_commutes hsym omega)
    (qgPhase_zero omega) (qgPhase_group omega) t

/-- **The BRST (quotient) norm is preserved** by the reduced transfer. -/
theorem qgBrstTransfer_infDist (t : ℝ) (x : QGH) :
    Metric.infDist (qgPhase omega t x) (exactStates (qgBrstCharge sym hsym))
      = Metric.infDist x (exactStates (qgBrstCharge sym hsym)) :=
  infDist_exactStates_eq (qgBrstCharge sym hsym) (qgPhase omega) (qgPhase_commutes hsym omega)
    (qgPhase_zero omega) (qgPhase_group omega) (qgPhase_isometry omega) t x

end

end BookProof.QgBrstCompleted
