import BookProof.ChapterStatisticalModelTheory
import BookProof.ChapterStatementOperator

#print axioms BookProof.ChapterStatisticalModelTheory.upward_lowenheim_skolem
#print axioms BookProof.ChapterStatisticalModelTheory.exists_uncountable_model
#print axioms BookProof.ChapterStatisticalModelTheory.monster_model_continuum
#print axioms BookProof.ChapterStatisticalModelTheory.exists_uncountable_model_of_countable_language
#print axioms BookProof.ChapterStatisticalModelTheory.countability_not_first_order_axiomatizable
#print axioms BookProof.ChapterStatisticalModelTheory.exists_nonisomorphic_models
#print axioms BookProof.ChapterStatisticalModelTheory.exists_nonstandard_model
#print axioms BookProof.ChapterStatisticalModelTheory.exists_countable_model
#print axioms BookProof.ChapterStatisticalModelTheory.exists_model_not_bijective_of_uncountable
#print axioms BookProof.ChapterStatisticalModelTheory.secondOrder_categoricity_real
#print axioms BookProof.ChapterStatementOperator.ModelStatement.truthValue_eq_norm_sq
#print axioms BookProof.ChapterStatementOperator.ModelStatement.truthValue_not
#print axioms BookProof.ChapterStatementOperator.ModelStatement.truthValue_and_le_left
#print axioms BookProof.ChapterStatementOperator.ModelStatement.truthValue_and_le_right
#print axioms BookProof.ChapterStatementOperator.ModelStatement.truthValue_eq_zero_iff
#print axioms BookProof.ChapterStatementOperator.ModelStatement.truthValue_eq_norm_sq_iff
#print axioms BookProof.ChapterStatementOperator.ModelStatement.undecidable_iff
#print axioms BookProof.ChapterStatementOperator.halfUncertain_not_idempotent
#print axioms BookProof.ChapterStatementOperator.approximate_proof_error
