import VersoManual

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

#doc (Manual) "Deterministic Transformations and the Origin of Complementarity" =>
%%%
tag := "deterministic-transformations"
%%%

# Symmetry Transformations Act on Events

A symmetry transformation is, at bottom, a unitary operator $`U` on the
wave-function. But the physical content of the transformation is not what it does to
$`\psi`; it is what it does to *events*. An event $`A` is represented by a
projection $`P_A`, and the transformed event is

$$`P_A \;\longmapsto\; U^\dagger P_A\, U.`

In the measurement basis $`\mathrm{Fin}\,n`, the algebra $`L^\infty(X,\mu)` of
events is just the algebra of *diagonal* matrices, and a single outcome $`a` is
the rank-one projection $`P_a = |e_a\rangle\langle e_a|`. The transformed
projection $`U^\dagger P_a U` has matrix entries

$$`(U^\dagger P_a U)_{ij} = \overline{U_{a i}}\, U_{a j}.`

The question that drives this chapter is: _when is the transformed event again a
diagonal event?_

# Deterministic Transformations

A transformation is *deterministic* when it sends every diagonal element of the
event algebra to another diagonal element — equivalently, when the conditional
probability it defines is a genuine function (the Radon–Nikodym derivative of one
measure with respect to another) rather than a genuinely random kernel. In the
finite-dimensional basis this means every column of $`U` has at most one non-zero
entry: each input outcome is sent to a single output outcome.

The manuscript's headline result is a clean commutation criterion:

:::paragraph
An automorphism $`U` is deterministic *if and only if* $`P_A` and
$`U P_B U^\dagger` commute, for all events $`A, B`.
:::

The verified statement (module `BookProof.ChapterDeterministic`):

```
#check @ChapterDeterministic.commute_proj_measOp_iff_isDeterministic
#check @ChapterDeterministic.commute_projSet_measOpSet_iff_isDeterministic
```

The second of these promotes the statement from single outcomes $`a, b` to
arbitrary events $`A, B \subseteq \mathrm{Fin}\,n`, by summing the rank-one
projections into the projection onto a subset. The same criterion appears, in the
language of off-diagonal parts, in module `BookProof.ChapterReconstruct`:

```
#check @ChapterReconstruct.offDiag_eq_zero_iff_isDeterministic
```

Reading it: the off-diagonal part of a column of $`U` vanishes for every column
exactly when $`U` is deterministic. The off-diagonal part is precisely the
interference that a deterministic map must destroy.

# Complementarity Is Randomness

Here is the conceptual payoff. Take two observables, say position and momentum.
Their projections $`P_X` and $`P_p` are diagonal in _different_ bases, related by a
Fourier transform $`U`; so $`P_X` and $`U P_p U^\dagger` do *not* commute. By the
criterion above, the symmetry transformation $`U` relating the two observables is
*non-deterministic*.

The manuscript reads this as the _definition_ of complementarity: two observables
are complementary precisely because the symmetry transformation relating them is
random. There is no mystery, and no failure of probability theory — probability
theory has no trouble with non-commuting observables, *as long as the wave-function
collapses* (the next chapter makes this precise). What the criterion shows is that
the non-commutativity is not an exotic addition to probability; it is the signature
of a non-deterministic symmetry.

# Quantum Mechanics Generalizes Statistical Mechanics, Not Probability

The deterministic transformations form the special case in which the symmetry
transformation is a mere change of variables. Classical statistical mechanics lives
entirely inside this case: its conditional probability measures are deterministic,
transforming a deterministic ensemble into a deterministic ensemble. Quantum
mechanics generalizes classical statistical mechanics by allowing the symmetry
transformations — in particular the time-evolution — to be *non-deterministic*.

This is the precise sense in which quantum mechanics is a generalization of
_classical statistical mechanics_ but *not* of probability theory itself. The
parametrization by a wave-function is available for any probability distribution;
what quantum mechanics adds is the freedom to act on it non-deterministically.

# Conservative Transformations

A transformation is *conservative* when it preserves the measure $`\mu` of the
event algebra. A continuous conservative transformation is a unitary time-evolution
$`U(t) = e^{iHt}` generated by a self-adjoint operator $`H`. The verified
construction (module `BookProof.ChapterConservative`):

```
#check @ChapterConservative.timeEvo_unitary
#check @ChapterConservative.timeEvo_add
```

The first says $`e^{iHt}` is unitary whenever $`H` is Hermitian (so total
probability is conserved); the second says these unitaries form a one-parameter
group, $`U(s)U(t) = U(s+t)`.

Which Hamiltonians generate *deterministic* conservative evolutions? Exactly the
diagonal ones. A Hamiltonian commutes with every event projection if and only if it
is itself diagonal in the measurement basis (module
`BookProof.ChapterConservativeDiagonal`):

```
#check @ConservativeDiagonal.commutes_all_events_iff_isDiag
#check @ConservativeDiagonal.conservative_iff_isDiag
```

So a conservative evolution is deterministic exactly when its Hamiltonian is
diagonal — when it merely re-phases the outcomes without mixing them. The moment
$`H` has off-diagonal entries, the evolution becomes non-deterministic, and we have
left classical statistical mechanics for quantum mechanics.

# Summary

 * A symmetry acts on events by $`P_A \mapsto U^\dagger P_A U`.
 * It is *deterministic* iff every transformed event stays diagonal, iff
   $`P_A` and $`U P_B U^\dagger` commute for all events $`A, B`, iff every column
   of $`U` has a single non-zero entry.
 * *Complementarity* is the non-commutativity that arises when the symmetry
   relating two observables is non-deterministic.
 * A *conservative* evolution $`e^{iHt}` is deterministic iff $`H` is diagonal.
 * Quantum mechanics = classical statistical mechanics + non-deterministic symmetry
   transformations. It generalizes statistical mechanics, not probability theory.
