import VersoManual

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

#doc (Manual) "Symmetries, Determinism, and Complementarity" =>
%%%
tag := "deterministic-transformations"
%%%

# Symmetries Are Unitary Representations

:::paragraph
A conditional probability measure that depends on a one-dimensional parameter — which
we may call time — "can be parametrized by a quantum process: a time-ordered product
integral of unitary operators, defined by a time-dependent Hamiltonian operator." The
manuscript's conclusion is that such parametrizations are "certainly natural and
common," and the reason is group-theoretic:
:::

:::paragraph
"When a subset of canonical transformations forms a group, such subset is always a
linear unitary representation of a group which is then called symmetry group and the
canonical transformations are then called symmetry transformations."
:::

:::paragraph
This chapter makes that sentence precise in the cleanest possible case: the
one-parameter group of time translations. We show that the time-evolution
$`U(t) = e^{iHt}` generated by a self-adjoint Hamiltonian is, literally, a group
homomorphism from the additive real line into the unitary group — that is, a
*unitary representation* of the symmetry group $`\mathbb{R}`.
:::

# Canonical Transformations Are Unitary

:::paragraph
For a Hermitian matrix $`H`, the time-evolution is the matrix exponential
$`U(t) = e^{iHt}`:
:::

```
#check @timeEvo
```

:::paragraph
Because $`H` is self-adjoint, $`U(t)` is unitary, and hence lives in the unitary
group:
:::

```
#check @timeEvo_unitary
#check @timeEvo_mem_unitaryGroup
```

:::paragraph
The measure-preserving (conservative) content of this — that conjugating a density
operator by $`U(t)` preserves its trace, so total probability is conserved — is taken
up in the section on conservative transformations below. Here we first record the
_group_ structure.
:::

# The One-Parameter Group Law

:::paragraph
The family $`U(t)` is a group action of $`(\mathbb{R}, +)`. It sends the identity
$`0` to the identity operator, it respects addition, and every element is invertible
with the time-reversed evolution as its inverse:
:::

$$`U(0) = 1, \qquad U(s)\,U(t) = U(s+t), \qquad U(t)^{-1} = U(-t).`

```
#check @timeEvoU_one
#check @timeEvoU_mul
#check @timeEvoU_inv
```

:::paragraph
This is precisely the structure the manuscript contrasts with Markov processes. A
Markov process is a *semigroup*: it has no inverses, and "one has not only to deal
with linear algebra but also with convex geometry at the infinitesimal level." A
unitary time-evolution is a *group*, and Lie theory "uses the group structure to
translate global geometric and analytic problems into local and infinitesimal ones,"
which are "essentially linear algebra." That is why quantum processes are not
intrinsically exotic — they are simply _more general_ than Markov processes, and far
easier to reduce to an infinitesimal generator (the Hamiltonian).
:::

# A Symmetry Group Is a Unitary Representation

:::paragraph
We now package the group law as a single object. Bundling each $`U(t)` with the proof
that it is unitary gives an element of the unitary group:
:::

```
#check @timeEvoU
```

:::paragraph
And the whole family is a *monoid homomorphism* from the additive reals (viewed
multiplicatively) into the unitary group — i.e. a unitary representation of the
one-parameter symmetry group $`\mathbb{R}`:
:::

```
#check @timeEvoRep
#check @timeEvoRep_apply
```

:::paragraph
This is the verified form of the manuscript's claim. A subset of canonical
transformations that forms a group — here the time translations — is a linear unitary
representation of that group, and the group is then called the symmetry group. The
representation is `sorry`-free: the homomorphism property is exactly the group law
$`U(s)U(t) = U(s+t)` proved above. Symmetry, in this book, is not an extra physical
postulate; it is the statement that the canonical transformations preserving a
conditional probability measure form a group, and that any such group acts by
unitaries. The spin-dependent representations that select bosonic versus fermionic
statistics ({ref "spin-statistics"}[the spin–statistics dichotomy]) are further
instances of the same principle.
:::

# Symmetry Transformations Act on Events

A symmetry transformation is, at bottom, a unitary operator $`U` on the
wave-function. But the physical content of the transformation is not what it does to
$`\psi`; it is what it does to *events*. An event $`A` is represented by a
projection $`P_A`, and the transformed event is

$$`P_A \;\longmapsto\; U^\dagger P_A\, U.`

In the measurement basis $`\mathrm{Fin}\,n`, the algebra $`L^\infty(X,\mu)` of
events is just the algebra of *diagonal* matrices, and a single outcome $`a` is
the rank-one projection $`P_a = |e_a\rangle\langle e_a|`. The transformed
projection $`U^\dagger P_a U` has matrix entries

$$`(U^\dagger P_a U)_{ij} = \overline{U_{a i}}\, U_{a j}.`

The question that drives the rest of this chapter is: _when is the transformed event
again a diagonal event?_

# Deterministic Transformations

A transformation is *deterministic* when it sends every diagonal element of the
event algebra to another diagonal element — equivalently, when the conditional
probability it defines is a genuine function (the Radon–Nikodym derivative of one
measure with respect to another) rather than a genuinely random kernel. In the
finite-dimensional basis this means every column of $`U` has at most one non-zero
entry: each input outcome is sent to a single output outcome.

The manuscript's headline result is a clean commutation criterion:

:::paragraph
An automorphism $`U` is deterministic *if and only if* $`P_A` and
$`U P_B U^\dagger` commute, for all events $`A, B`.
:::

The verified statement (module `BookProof.ChapterDeterministic`):

```
#check @ChapterDeterministic.commute_proj_measOp_iff_isDeterministic
#check @ChapterDeterministic.commute_projSet_measOpSet_iff_isDeterministic
```

The second of these promotes the statement from single outcomes $`a, b` to
arbitrary events $`A, B \subseteq \mathrm{Fin}\,n`, by summing the rank-one
projections into the projection onto a subset. The same criterion appears, in the
language of off-diagonal parts, in module `BookProof.ChapterReconstruct`:

```
#check @ChapterReconstruct.offDiag_eq_zero_iff_isDeterministic
```

Reading it: the off-diagonal part of a column of $`U` vanishes for every column
exactly when $`U` is deterministic. The off-diagonal part is precisely the
interference that a deterministic map must destroy.

# Complementarity Is Randomness

Here is the conceptual payoff. Take two observables, say position and momentum.
Their projections $`P_X` and $`P_p` are diagonal in _different_ bases, related by a
Fourier transform $`U`; so $`P_X` and $`U P_p U^\dagger` do *not* commute. By the
criterion above, the symmetry transformation $`U` relating the two observables is
*non-deterministic*.

The manuscript reads this as the _definition_ of complementarity: two observables
are complementary precisely because the symmetry transformation relating them is
random. There is no mystery, and no failure of probability theory — probability
theory has no trouble with non-commuting observables, *as long as the wave-function
collapses* ({ref "collapse-kolmogorov"}[the collapse chapter] makes this precise).
What the criterion shows is that the non-commutativity is not an exotic addition to
probability; it is the signature of a non-deterministic symmetry.

# Quantum Mechanics Generalizes Statistical Mechanics, Not Probability

The deterministic transformations form the special case in which the symmetry
transformation is a mere change of variables. Classical statistical mechanics lives
entirely inside this case: its conditional probability measures are deterministic,
transforming a deterministic ensemble into a deterministic ensemble. Quantum
mechanics generalizes classical statistical mechanics by allowing the symmetry
transformations — in particular the time-evolution — to be *non-deterministic*.

This is the precise sense in which quantum mechanics is a generalization of
_classical statistical mechanics_ but *not* of probability theory itself. The
parametrization by a wave-function is available for any probability distribution;
what quantum mechanics adds is the freedom to act on it non-deterministically.

# Time-Translation Is a Stochastic Process If and Only If It Is Deterministic

A *stochastic process* is a family of random events indexed by time: there is a
probability distribution for _each_ time, and the times are glued together by
conditional probabilities. Does the time-evolution of quantum mechanics define such
a process? The manuscript's answer is a precise and surprising one:

:::paragraph
There is a group action of a symmetry group on the *probability distribution* if
and only if the symmetry transforms *deterministic* distributions into
deterministic distributions. In particular, *time-translation in quantum mechanics
is a stochastic process if and only if it is deterministic.*
:::

This single fact is, the manuscript argues, overlooked by the assumptions of both
Bell's theorem and the EPR paradox.

Start with a probability distribution $`\mathrm{diag}(\rho_1)`. Acting on the
wave-function with a group element $`g` and then collapsing gives a new distribution
$`\mathrm{diag}(\rho_g)`. Wigner's theorem says the action of a symmetry on the
wave-function is linear and unitary. For the symmetry to act on the *probability
distribution* (and hence for a stochastic process to exist), the collapsed trace
$`\mathrm{tr}\bigl(\mathrm{diag}(\rho_g)\, U_h P_A U_h^\dagger\bigr)` and the
uncollapsed trace $`\mathrm{tr}\bigl(\rho_g\, U_h P_A U_h^\dagger\bigr)` must agree
for every pure $`\rho_g`, every event $`A`, and every group element $`h`.

The two traces differ exactly by the off-diagonal part of $`\rho_g`. The verified
accounting (module `BookProof.ChapterTimeTranslation`):

```
#check @ChapterTimeTranslation.trace_rho_measOp
#check @ChapterTimeTranslation.trace_diagPart_measOp
#check @ChapterTimeTranslation.trace_diff
```

The first two compute the two traces; the third isolates their difference. The
headline equivalence then falls out:

```
#check @ChapterTimeTranslation.trace_eq_iff_isDeterministic
#check @ChapterTimeTranslation.trace_eq_iff_isDeterministic_pure
```

Reading them: the two traces agree for every state and every event *if and only
if* $`U` is deterministic (the second states the same for pure states only). The
mechanism is concrete: if $`U` is deterministic, then
$`\overline{U_{ja}}\, U_{jl} = 0` whenever $`a \neq l`, so the off-diagonal
contribution vanishes; if $`U` is *not* deterministic, some
$`\overline{U_{ma}}\, U_{la} \neq 0` with $`l \neq m`, and the superposition
$`\Psi = (\delta_m + \delta_l)/\sqrt 2` isolates it. The same content, phrased
through the off-diagonal part (module `BookProof.ChapterReconstruct`):

```
#check @ChapterReconstruct.offDiag_eq_zero_iff_isDeterministic
```

If the time-evolution is non-deterministic, then there is *no* probability
distribution attached to each intermediate time — the symmetry does not descend to
the distributions, so no stochastic process is defined. This is the mathematical
core behind several of the manuscript's most provocative claims:

 * *EPR.* After the entangled particles separate and before the measurement
   transformation, there is no probability distribution for the state — because the
   (non-deterministic) time-evolution is not a stochastic process.
 * *Bell.* The Bell assumptions implicitly treat the time-evolution as a stochastic
   process; the theorem above shows that this is legitimate only in the
   deterministic case.
 * *The double-slit.* The product of two non-deterministic transformations is not
   the same as a stochastic process in which they are applied in sequence — which is
   exactly why the interference pattern appears (see
   {ref "double-slit"}[the double-slit chapter]).

# Conservative Transformations

A transformation is *conservative* when it preserves the measure $`\mu` of the
event algebra. A continuous conservative transformation is a unitary time-evolution
$`U(t) = e^{iHt}` generated by a self-adjoint operator $`H`. The verified
construction (module `BookProof.ChapterConservative`):

```
#check @ChapterConservative.timeEvo_unitary
#check @ChapterConservative.timeEvo_add
```

The first says $`e^{iHt}` is unitary whenever $`H` is Hermitian (so total
probability is conserved); the second says these unitaries form a one-parameter
group, $`U(s)U(t) = U(s+t)`.

Which Hamiltonians generate *deterministic* conservative evolutions? Exactly the
diagonal ones. A Hamiltonian commutes with every event projection if and only if it
is itself diagonal in the measurement basis (module
`BookProof.ChapterConservativeDiagonal`):

```
#check @ConservativeDiagonal.commutes_all_events_iff_isDiag
#check @ConservativeDiagonal.conservative_iff_isDiag
```

So a conservative evolution is deterministic exactly when its Hamiltonian is
diagonal — when it merely re-phases the outcomes without mixing them. The moment
$`H` has off-diagonal entries, the evolution becomes non-deterministic, and we have
left classical statistical mechanics for quantum mechanics.

# Summary

 * A symmetry group of canonical transformations is a *unitary representation*; the
   one-parameter time-translation group $`U(t) = e^{iHt}` satisfies the group law
   $`U(s)U(t) = U(s+t)`.
 * A symmetry acts on events by $`P_A \mapsto U^\dagger P_A U`. It is *deterministic*
   iff every transformed event stays diagonal, iff $`P_A` and $`U P_B U^\dagger`
   commute for all events $`A, B`, iff every column of $`U` has a single non-zero
   entry.
 * *Complementarity* is the non-commutativity that arises when the symmetry relating
   two observables is non-deterministic.
 * Time-translation is a *stochastic process* iff it is deterministic — the symmetry
   descends to the probability distributions exactly in the deterministic case.
 * A *conservative* evolution $`e^{iHt}` is deterministic iff $`H` is diagonal.
 * Quantum mechanics = classical statistical mechanics + non-deterministic symmetry
   transformations. It generalizes statistical mechanics, not probability theory.