import VersoManual

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

#doc (Manual) "Diffeomorphisms and Gravity" =>
%%%
tag := "diffeomorphisms-gravity"
%%%

# The Question

:::paragraph
The manuscript's chapter on diffeomorphisms and gravity argues that Quantum
Gravity should be treated as a special case of the (global) gauge/quantization
formalism in the continuum, rather than as Loop Quantum Gravity with
renormalization. Diffeomorphism is generated by constraints while time-evolution
is not a diffeomorphism, so the two are compatible. The strategy is to decompose
space-time into time and space (the $`3+1` split) and to study the induced spatial
metric as a degenerate object along the time direction. The verified content here
is the algebraic geometry of that $`3+1` split.
:::

# The 3+1 Split: Time and Space

:::paragraph
Fix a unit timelike vector $`v` (the time direction) in Minkowski space with
metric $`\eta` (here $`\eta = \operatorname{diag}(-1,1,1,1)`). The spatial
projector $`\chi^a{}_b = \delta^a{}_b + v^a v_b` is the orthogonal projection onto
the spatial hyperplane $`v^\perp`: it is idempotent, has kernel spanned by $`v`,
and has trace $`3` (it is a rank-3 projector). The temporal projector
$`\Pi^a{}_b = -v^a v_b = \delta - \chi` completes it:
:::

```
#check @BookProof.ChapterGravityProjector.metric
#check @BookProof.ChapterGravityProjector.spatialProj
#check @BookProof.ChapterGravityProjector.spatialProj_mulVec_self
#check @BookProof.ChapterGravityProjector.spatialProj_idempotent
#check @BookProof.ChapterGravityProjector.trace_spatialProj
#check @BookProof.ChapterGravityTimeProj.spatialProj_add_timeProj
#check @BookProof.ChapterGravityTimeProj.timeProj_idempotent
#check @BookProof.ChapterGravityTimeProj.trace_timeProj
```

:::paragraph
Every vector splits uniquely into a spatial part and a temporal part, and these
parts are Minkowski-orthogonal: $`\langle \chi x, \Pi x\rangle_\eta = 0`. This is
the geometric substance of the manuscript's "time-evolution is not a
diffeomorphism": the time and space components of a displacement are orthogonal
and independent:
:::

```
#check @BookProof.ChapterGravitySplit.spatialPart_add_timePart
#check @BookProof.ChapterGravitySplit.timePart_eq_smul
#check @BookProof.ChapterGravitySplit.parts_orthogonal
#check @BookProof.ChapterGravitySplit.split_unique
```

:::paragraph
Because the two projector endomorphisms $`\chi` and $`\Pi` sum to the identity and
annihilate each other ($`\chi\Pi = \Pi\chi = 0`), their ranges are *complementary
subspaces*: the whole of spacetime is their direct sum,
$`\mathbb{R}^{1,3} = \operatorname{im}\chi \oplus \operatorname{im}\Pi`, and the
image of the spatial projector is exactly the kernel of the temporal one. This is
the linear-algebra fact that turns the algebraic projector identities into the
manuscript's $`3+1` decomposition of spacetime itself:
:::

```
#check @BookProof.ChapterGravityProjDirectSum.isCompl_spatial_time_range
#check @BookProof.ChapterGravityProjDirectSum.range_spatial_eq_ker_time
#check @BookProof.ChapterGravityProjDirectSum.isCompl_range_of_add_eq_id
```

:::paragraph
The decomposition is moreover of the shape the manuscript asserts: the temporal
summand is precisely the line $`\mathbb{R}\cdot v` through the unit timelike
vector, so it is one-dimensional, and the spatial summand is a hyperplane. The
split is therefore literally $`4 = 3 + 1`:
:::

```
#check @BookProof.ChapterGravityRankSplit.timeRange_eq_span
#check @BookProof.ChapterGravityRankSplit.finrank_timeRange
#check @BookProof.ChapterGravityRankSplit.finrank_spatialRange
#check @BookProof.ChapterGravityRankSplit.gravity_split_three_plus_one
```

# The Induced Spatial Metric

:::paragraph
The $`3+1` split induces a spatial metric $`h_{ab} = \eta_{ab} + v_a v_b`, which
is symmetric, positive-semidefinite, and degenerate along the time direction
($`h v = 0`). Its relationship to the full metric is the tensor identity
$`h = \eta\cdot\chi`, and it satisfies the reverse Cauchy–Schwarz inequality for
the timelike unit vector:
:::

```
#check @BookProof.ChapterGravityMetric.spatialMetric
#check @BookProof.ChapterGravityMetric.spatialMetric_symm
#check @BookProof.ChapterGravityMetric.spatialMetric_eq_metric_mul_proj
#check @BookProof.ChapterGravityMetric.spatialMetric_mulVec_self
#check @BookProof.ChapterGravityMetric.spatialMetric_quadForm_nonneg
#check @BookProof.ChapterGravityMetric.spatialMetric_posSemidef
```

:::paragraph
The raised spatial metric $`h^{ab} = \eta^{ab} + v^a v^b` is the generalized
inverse of the induced metric on the degenerate spatial hyperplane: the pair
satisfies $`h\cdot h^\sharp\cdot h = h` and $`h^\sharp\cdot h = \chi`. This is
the "inverse metric" on the $`3`-dimensional slice, defined even though $`h` is
degenerate along time:
:::

```
#check @BookProof.ChapterGravityInvMetric.invSpatialMetric
#check @BookProof.ChapterGravityInvMetric.metric_mul_metric
#check @BookProof.ChapterGravityInvMetric.invSpatialMetric_mul_spatialMetric
#check @BookProof.ChapterGravityGenInverse.spatialMetric_genInverse
#check @BookProof.ChapterGravityGenInverse.invSpatialMetric_genInverse
```

# The Irreducible Decomposition of the Metric

:::paragraph
The manuscript analyzes the gravitational metric field into its irreducible parts
under the rotation group. Every matrix $`M` splits uniquely as
$`M = \tfrac12 S + \tfrac12 A + \tfrac13(\operatorname{tr} M)I`, where $`S` is
symmetric traceless (the $`2/3` factor), $`A` is antisymmetric, and the trace part
is the remainder. The three pieces are mutually Frobenius-orthogonal:
:::

```
#check @BookProof.ChapterGravityIrrep.antisymPart
#check @BookProof.ChapterGravityIrrep.symTracelessPart
#check @BookProof.ChapterGravityIrrep.trace_symTracelessPart
#check @BookProof.ChapterGravityIrrep.irrep_reconstruction
#check @BookProof.ChapterGravityIrrep.frob_symTraceless_antisym
#check @BookProof.ChapterGravityIrrep.frob_antisym_trace
```

# The Densitized Tetrad Variables and the Flat Principal Part

:::paragraph
The manuscript's final, 3D gauge-fixed gravity Hamiltonian carries the *singular*
kinetic terms $`\tfrac{1}{16e}S^{ab}S_{ab} - \tfrac{1}{24e}P^2`, whose
denominator $`e = \det e_i{}^a` vanishes where the tetrad degenerates. The
canonical repair is the change of variables to *densitized* tetrads
$`y = \sqrt e`, $`\tilde e_i{}^a = \sqrt e\, e_i{}^a`. Two facts make this
load-bearing rather than cosmetic: the singular coefficient is a square of a
derivative of the new coordinate, $`1/e = 4(\partial y/\partial e)^2`, so it is
absorbed into the field derivatives; and while $`1/e \to \infty` at a degenerate
tetrad, the new coordinate $`y = \sqrt e` extends continuously by $`0`:
:::

```
#check @BookProof.QuantumGravityDensitized.densY
#check @BookProof.QuantumGravityDensitized.inv_eq_four_mul_deriv_densY_sq
#check @BookProof.QuantumGravityDensitized.kinetic_absorption
#check @BookProof.QuantumGravityDensitized.conformal_absorption
#check @BookProof.QuantumGravityDensitized.densTetrad
#check @BookProof.QuantumGravityDensitized.densTetrad_det
#check @BookProof.QuantumGravityDensitized.densTetrad_recover
#check @BookProof.QuantumGravityDensitized.tendsto_inv_det_atTop
#check @BookProof.QuantumGravityDensitized.tendsto_densY_zero
```

:::paragraph
In the densitized variables the principal part of the kinetic operator has the
*constant* coefficients $`(1/16, -1/24)`: the field-space metric is flat, so all
its Christoffel symbols vanish and the point transformation produces no
connection ("quantum potential") corrections. The symbol is non-degenerate but
*indefinite* — the operator is a d'Alembertian (hyperbolic), not an elliptic
Laplacian, which is why the elliptic Sears route of the Navier–Stokes thread does
not apply to it:
:::

```
#check @BookProof.QuantumGravityDensitized.qgSymbol
#check @BookProof.QuantumGravityDensitized.qgSymbol_eq_metric_form
#check @BookProof.QuantumGravityDensitized.qgMetric_det_ne_zero
#check @BookProof.QuantumGravityDensitized.qgSymbol_indefinite
#check @BookProof.QuantumGravityDensitized.christoffel_eq_zero_of_const
#check @BookProof.QuantumGravityDensitized.qgMetric_christoffel_zero
#check @BookProof.QuantumGravityDensitized.qgFullSymbol_scaling
```

:::paragraph
The analytic conclusion for the *continuum* operator is *not* claimed. What is
proved is the discretized (Hermite-basis) realization, where the fiber operator is
multiplication by the mode symbol: it is genuinely unbounded, essentially
self-adjoint on its maximal domain, and its adjoint has trivial deficiency at
every non-real point — exactly the conclusion Strichartz's finite-speed argument
is supposed to supply in the continuum. Strichartz's theorem itself enters only as
an explicit *hypothesis* (never an axiom), and the transfer of essential
self-adjointness back to the physical variables is the unitary-equivalence step:
:::

```
#check @BookProof.QuantumGravityDensitized.qgModeHamiltonian
#check @BookProof.QuantumGravityDensitized.qgModeHamiltonian_essentiallySelfAdjoint
#check @BookProof.QuantumGravityDensitized.qgModeHamiltonian_deficiencyTrivialAt
#check @BookProof.QuantumGravityDensitized.qgModeHamiltonian_not_bounded
#check @BookProof.QuantumGravityDensitized.strichartz_esa_of_finiteSpeed
#check @BookProof.QuantumGravityDensitized.strichartz_finiteSpeed_satisfiable
#check @BookProof.QuantumGravityDensitized.qg_esa_of_farisLavine
#check @BookProof.QuantumGravityDensitized.densitized_hasZeroDeficiencyOn_transfer
```

:::paragraph
The transfer step needs an actual Hilbert-space unitary, and the raw point map
$`e \mapsto y = \sqrt e` is not one: the Jacobian $`de/dy = 2y` must be carried
along as the half-density factor $`\sqrt{2y}`. That unitary is *constructed*,
not assumed: composition with $`y \mapsto y^2` is measure preserving from the
weighted measure $`2y\,dy` to Lebesgue measure on $`(0,\infty)`, hence a unitary
$`L^2((0,\infty),de) \simeq L^2((0,\infty), 2y\,dy)`, and the transfer theorem
specializes to it:
:::

```
#check @BookProof.QuantumGravityHalfDensity.qgSrcMeasure_density_eq_halfDensity_sq
#check @BookProof.QuantumGravityHalfDensity.measurePreserving_qgSquare
#check @BookProof.QuantumGravityHalfDensity.measurePreserving_qgSqrt
#check @BookProof.QuantumGravityHalfDensity.halfDensityUnitary
#check @BookProof.QuantumGravityHalfDensity.halfDensityUnitary_apply
#check @BookProof.QuantumGravityHalfDensity.halfDensityUnitary_symm_apply
#check @BookProof.QuantumGravityHalfDensity.exists_halfDensity_unitary
#check @BookProof.QuantumGravityHalfDensity.qg_halfDensity_transfer
```

# Summary

The algebraic core of the manuscript's diffeomorphisms/gravity chapter:

 * the $`3+1` split into a rank-3 spatial projector and a rank-1 temporal projector, with orthogonal, unique spatial/temporal parts;
 * the induced spatial metric as a positive-semidefinite, time-degenerate object with a generalized inverse on the slice;
 * the irreducible $`S + A + \text{trace}` decomposition of the metric field;
 * the compatibility of diffeomorphism constraints with time-evolution;
 * the densitized change of variables $`y = \sqrt e`, $`\tilde e = \sqrt e\, e`, the absorption of the singular $`1/e`, the flat (hyperbolic) principal part, and the Hermite-basis realization on which essential self-adjointness is proved — with Strichartz's continuum theorem carried as a named hypothesis, never as a claimed result;
 * the half-density unitary $`L^2((0,\infty),de) \simeq L^2((0,\infty),2y\,dy)` of that change of variables, constructed rather than assumed, at which the unitary-transfer theorem is instantiated.