import VersoManual

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

#doc (Manual) "Diffeomorphisms and Gravity" =>
%%%
tag := "diffeomorphisms-gravity"
%%%

# The Question

:::paragraph
The manuscript's chapter on diffeomorphisms and gravity argues that Quantum
Gravity should be treated as a special case of the (global) gauge/quantization
formalism in the continuum, rather than as Loop Quantum Gravity with
renormalization. Diffeomorphism is generated by constraints while time-evolution
is not a diffeomorphism, so the two are compatible. The strategy is to decompose
space-time into time and space (the $`3+1` split) and to study the induced spatial
metric as a degenerate object along the time direction. The verified content here
is the algebraic geometry of that $`3+1` split.
:::

# The 3+1 Split: Time and Space

:::paragraph
Fix a unit timelike vector $`v` (the time direction) in Minkowski space with
metric $`\eta` (here $`\eta = \operatorname{diag}(-1,1,1,1)`). The spatial
projector $`\chi^a{}_b = \delta^a{}_b + v^a v_b` is the orthogonal projection onto
the spatial hyperplane $`v^\perp`: it is idempotent, has kernel spanned by $`v`,
and has trace $`3` (it is a rank-3 projector). The temporal projector
$`\Pi^a{}_b = -v^a v_b = \delta - \chi` completes it:
:::

```
#check @BookProof.ChapterGravityProjector.metric
#check @BookProof.ChapterGravityProjector.spatialProj
#check @BookProof.ChapterGravityProjector.spatialProj_mulVec_self
#check @BookProof.ChapterGravityProjector.spatialProj_idempotent
#check @BookProof.ChapterGravityProjector.trace_spatialProj
#check @BookProof.ChapterGravityTimeProj.spatialProj_add_timeProj
#check @BookProof.ChapterGravityTimeProj.timeProj_idempotent
#check @BookProof.ChapterGravityTimeProj.trace_timeProj
```

:::paragraph
Every vector splits uniquely into a spatial part and a temporal part, and these
parts are Minkowski-orthogonal: $`\langle \chi x, \Pi x\rangle_\eta = 0`. This is
the geometric substance of the manuscript's "time-evolution is not a
diffeomorphism": the time and space components of a displacement are orthogonal
and independent:
:::

```
#check @BookProof.ChapterGravitySplit.spatialPart_add_timePart
#check @BookProof.ChapterGravitySplit.timePart_eq_smul
#check @BookProof.ChapterGravitySplit.parts_orthogonal
#check @BookProof.ChapterGravitySplit.split_unique
```

:::paragraph
Because the two projector endomorphisms $`\chi` and $`\Pi` sum to the identity and
annihilate each other ($`\chi\Pi = \Pi\chi = 0`), their ranges are *complementary
subspaces*: the whole of spacetime is their direct sum,
$`\mathbb{R}^{1,3} = \operatorname{im}\chi \oplus \operatorname{im}\Pi`, and the
image of the spatial projector is exactly the kernel of the temporal one. This is
the linear-algebra fact that turns the algebraic projector identities into the
manuscript's $`3+1` decomposition of spacetime itself:
:::

```
#check @BookProof.ChapterGravityProjDirectSum.isCompl_spatial_time_range
#check @BookProof.ChapterGravityProjDirectSum.range_spatial_eq_ker_time
#check @BookProof.ChapterGravityProjDirectSum.isCompl_range_of_add_eq_id
```

# The Induced Spatial Metric

:::paragraph
The $`3+1` split induces a spatial metric $`h_{ab} = \eta_{ab} + v_a v_b`, which
is symmetric, positive-semidefinite, and degenerate along the time direction
($`h v = 0`). Its relationship to the full metric is the tensor identity
$`h = \eta\cdot\chi`, and it satisfies the reverse Cauchy–Schwarz inequality for
the timelike unit vector:
:::

```
#check @BookProof.ChapterGravityMetric.spatialMetric
#check @BookProof.ChapterGravityMetric.spatialMetric_symm
#check @BookProof.ChapterGravityMetric.spatialMetric_eq_metric_mul_proj
#check @BookProof.ChapterGravityMetric.spatialMetric_mulVec_self
#check @BookProof.ChapterGravityMetric.spatialMetric_quadForm_nonneg
#check @BookProof.ChapterGravityMetric.spatialMetric_posSemidef
```

:::paragraph
The raised spatial metric $`h^{ab} = \eta^{ab} + v^a v^b` is the generalized
inverse of the induced metric on the degenerate spatial hyperplane: the pair
satisfies $`h\cdot h^\sharp\cdot h = h` and $`h^\sharp\cdot h = \chi`. This is
the "inverse metric" on the $`3`-dimensional slice, defined even though $`h` is
degenerate along time:
:::

```
#check @BookProof.ChapterGravityInvMetric.invSpatialMetric
#check @BookProof.ChapterGravityInvMetric.metric_mul_metric
#check @BookProof.ChapterGravityInvMetric.invSpatialMetric_mul_spatialMetric
#check @BookProof.ChapterGravityGenInverse.spatialMetric_genInverse
#check @BookProof.ChapterGravityGenInverse.invSpatialMetric_genInverse
```

# The Irreducible Decomposition of the Metric

:::paragraph
The manuscript analyzes the gravitational metric field into its irreducible parts
under the rotation group. Every matrix $`M` splits uniquely as
$`M = \tfrac12 S + \tfrac12 A + \tfrac13(\operatorname{tr} M)I`, where $`S` is
symmetric traceless (the $`2/3` factor), $`A` is antisymmetric, and the trace part
is the remainder. The three pieces are mutually Frobenius-orthogonal:
:::

```
#check @BookProof.ChapterGravityIrrep.antisymPart
#check @BookProof.ChapterGravityIrrep.symTracelessPart
#check @BookProof.ChapterGravityIrrep.trace_symTracelessPart
#check @BookProof.ChapterGravityIrrep.irrep_reconstruction
#check @BookProof.ChapterGravityIrrep.frob_symTraceless_antisym
#check @BookProof.ChapterGravityIrrep.frob_antisym_trace
```

# Summary

The algebraic core of the manuscript's diffeomorphisms/gravity chapter:

 * the $`3+1` split into a rank-3 spatial projector and a rank-1 temporal projector, with orthogonal, unique spatial/temporal parts;
 * the induced spatial metric as a positive-semidefinite, time-degenerate object with a generalized inverse on the slice;
 * the irreducible $`S + A + \text{trace}` decomposition of the metric field;
 * the compatibility of diffeomorphism constraints with time-evolution.