import VersoManual

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

#doc (Manual) "Symmetries Are Unitary Representations" =>
%%%
tag := "symmetry-rep"
%%%

# The Question

:::paragraph
A conditional probability measure that depends on a one-dimensional parameter — which
we may call time — "can be parametrized by a quantum process: a time-ordered product
integral of unitary operators, defined by a time-dependent Hamiltonian operator." The
manuscript's conclusion is that such parametrizations are "certainly natural and
common," and the reason is group-theoretic:
:::

:::paragraph
"When a subset of canonical transformations forms a group, such subset is always a
linear unitary representation of a group which is then called symmetry group and the
canonical transformations are then called symmetry transformations."
:::

:::paragraph
This chapter makes that sentence precise in the cleanest possible case: the
one-parameter group of time translations. We show that the time-evolution
$`U(t) = e^{iHt}` generated by a self-adjoint Hamiltonian is, literally, a group
homomorphism from the additive real line into the unitary group — that is, a
*unitary representation* of the symmetry group $`\mathbb{R}`.
:::

# Canonical Transformations Are Unitary

:::paragraph
For a Hermitian matrix $`H`, the time-evolution is the matrix exponential
$`U(t) = e^{iHt}`:
:::

```
#check @timeEvo
```

:::paragraph
Because $`H` is self-adjoint, $`U(t)` is unitary, and hence lives in the unitary
group:
:::

```
#check @timeEvo_unitary
#check @timeEvo_mem_unitaryGroup
```

:::paragraph
The measure-preserving (conservative) content of this — that conjugating a density
operator by $`U(t)` preserves its trace, so total probability is conserved — is the
subject of {ref "deterministic-transformations"}[the next chapter]. Here we focus on
the _group_ structure.
:::

# The One-Parameter Group Law

:::paragraph
The family $`U(t)` is a group action of $`(\mathbb{R}, +)`. It sends the identity
$`0` to the identity operator, it respects addition, and every element is invertible
with the time-reversed evolution as its inverse:
:::

$$`U(0) = 1, \qquad U(s)\,U(t) = U(s+t), \qquad U(t)^{-1} = U(-t).`

```
#check @timeEvoU_one
#check @timeEvoU_mul
#check @timeEvo_inv
```

:::paragraph
This is precisely the structure the manuscript contrasts with Markov processes. A
Markov process is a *semigroup*: it has no inverses, and "one has not only to deal
with linear algebra but also with convex geometry at the infinitesimal level." A
unitary time-evolution is a *group*, and Lie theory "uses the group structure to
translate global geometric and analytic problems into local and infinitesimal ones,"
which are "essentially linear algebra." That is why quantum processes are not
intrinsically exotic — they are simply _more general_ than Markov processes, and far
easier to reduce to an infinitesimal generator (the Hamiltonian).
:::

# A Symmetry Group Is a Unitary Representation

:::paragraph
We now package the group law as a single object. Bundling each $`U(t)` with the proof
that it is unitary gives an element of the unitary group:
:::

```
#check @timeEvoU
```

:::paragraph
And the whole family is a *monoid homomorphism* from the additive reals (viewed
multiplicatively) into the unitary group — i.e. a unitary representation of the
one-parameter symmetry group $`\mathbb{R}`:
:::

```
#check @timeEvoRep
#check @timeEvoRep_apply
```

:::paragraph
This is the verified form of the manuscript's claim. A subset of canonical
transformations that forms a group — here the time translations — is a linear unitary
representation of that group, and the group is then called the symmetry group. The
representation is `sorry`-free: the homomorphism property is exactly the group law
$`U(s)U(t) = U(s+t)` proved above.
:::

# Why This Matters Here

:::paragraph
Symmetry, in this book, is not an extra physical postulate. It is the statement that
the canonical transformations preserving a conditional probability measure form a
group, and that any such group acts by unitaries — a unitary representation. The
time-translation representation built here is the prototype; the conservative and
deterministic transformations of
{ref "deterministic-transformations"}[the next chapter] are its measure-theoretic
consequences, and the spin-dependent representations that select bosonic versus
fermionic statistics ({ref "spin-statistics"}[the spin–statistics dichotomy]) are
further instances of the same principle.
:::
